import type { DialectCurriculum } from "@bangla-learn/types";

export const barisaliCurriculum: DialectCurriculum = {
  dialect: "barisali",
  units: [
    {
      id: "bar-unit-1",
      title: "Barisali Basics",
      description: "Learn Barisali — the dialect of Barisal Division, known for its musical rhythm",
      order: 1,
      color: "#FF4B4B",
      prep: {
        characters: [
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আইলা (came)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইলিশ (hilsa)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠা (to rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এহন (now)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওখানে (there)" },
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কই (where)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খাওয়া (eating)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলা (went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পানি (water)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বাপ (father)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালাই (quite well)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মায় (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাত (night)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হেই (he/she)" },
          { symbol: "চ", romanization: "ch",  type: "consonant" as const, exampleWord: "চাইর (four)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তারা (they)" },
          { symbol: "য", romanization: "j/y", type: "consonant" as const, exampleWord: "যাওয়া (to go)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সকাল (morning)" },
        ],
        flashcards: [
          { id: "fc-bar-1",  bangla: "হেই",         romanization: "Hei",        english: "He / She (Barisali)",       category: "pronouns"  },
          { id: "fc-bar-2",  bangla: "তাগো",        romanization: "Tago",       english: "Their / Them (Barisali)",   category: "pronouns"  },
          { id: "fc-bar-3",  bangla: "বাপ",         romanization: "Bap",        english: "Father (Barisali)",         category: "family"    },
          { id: "fc-bar-4",  bangla: "মায়",         romanization: "May",        english: "Mother (Barisali)",         category: "family"    },
          { id: "fc-bar-5",  bangla: "কই",          romanization: "Koi",        english: "Where (Barisali)",          category: "phrases"   },
          { id: "fc-bar-6",  bangla: "কেমুন",       romanization: "Kemun",      english: "How (Barisali for কেমন)",  category: "phrases"   },
          { id: "fc-bar-7",  bangla: "এহন",         romanization: "Ehon",       english: "Now (Barisali)",            category: "phrases"   },
          { id: "fc-bar-8",  bangla: "গেলা",        romanization: "Gela",       english: "Went (past tense)",         category: "verbs"     },
          { id: "fc-bar-9",  bangla: "আইলা",        romanization: "Aila",       english: "Came (past tense)",         category: "verbs"     },
          { id: "fc-bar-10", bangla: "ভালাই আছি",  romanization: "Bhalai achi",english: "I am quite fine",           category: "greetings" },
          { id: "fc-bar-11", bangla: "কই যাও?",    romanization: "Koi jao?",   english: "Where are you going?",      category: "greetings" },
          { id: "fc-bar-12", bangla: "কেমুন আছ?",  romanization: "Kemun ach?", english: "How are you?",              category: "greetings" },
          { id: "fc-bar-13", bangla: "চাইর",        romanization: "Chair",      english: "Four (Barisali for চার)",  category: "numbers"   },
          { id: "fc-bar-14", bangla: "জাই",         romanization: "Jai",        english: "Let's go",                  category: "phrases"   },
          { id: "fc-bar-15", bangla: "হের",         romanization: "Her",        english: "His / Her (Barisali)",      category: "pronouns"  },
        ],
        grammar: [
          {
            title: "Barisali Pronouns — হেই, তাগো",
            explanation: "Barisali uses 'হেই' (Hei) for he/she instead of Standard Bengali's 'সে'. The plural 'their/them' is 'তাগো' (Tago) instead of 'তাদের'.",
            examples: [
              { bangla: "হেই আসছে।",    romanization: "Hei ashche.",  english: "He/she has come." },
              { bangla: "তাগো বাড়ি।", romanization: "Tago bari.",    english: "Their home." },
            ],
          },
          {
            title: "Where & How — কই, কেমুন",
            explanation: "Barisali replaces 'কোথায়' (where) with 'কই' (Koi) and 'কেমন' (how) becomes 'কেমুন' (Kemun). These short words give Barisali its musical quality.",
            examples: [
              { bangla: "কই যাও?",    romanization: "Koi jao?",    english: "Where are you going?" },
              { bangla: "কেমুন আছ?", romanization: "Kemun ach?",  english: "How are you?" },
            ],
          },
          {
            title: "Musical Rhythm of Barisali",
            explanation: "Barisali is famous for its sing-song rhythm and drawn-out vowels. Words like 'ভালাই' add an extra '-ই' suffix for emphasis, a pattern unique to this dialect.",
            examples: [
              { bangla: "ভালাই আছি।",  romanization: "Bhalai achi.",  english: "I am quite well." },
              { bangla: "এহন যাই।",    romanization: "Ehon jai.",      english: "I'm going now." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "bar-1-0",
          title: "Write the Letters",
          description: "Trace Bengali vowels and consonants used in Barisali",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "bar-1-0-tr-1", character: "অ", romanization: "o/a", exampleWord: "অনেক — many", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-2", character: "আ", romanization: "aa", exampleWord: "আম — mango", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-3", character: "ক", romanization: "k", exampleWord: "কলা — banana", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-4", character: "ন", romanization: "n", exampleWord: "নাম — name", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-5", character: "ম", romanization: "m", exampleWord: "মা — mother", xp: 4 },
          ],
        },
        {
          id: "bar-1-1",
          title: "Greetings",
          description: "Greet and introduce yourself in Barisali-flavored Bangla",
          unit: 1,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-1-mp-1",
              pairs: [
                { bangla: "আসসালামু আলাইকুম", english: "Hello (Islamic greeting)", romanization: "assalamu alaikum" },
                { bangla: "ভালো",              english: "Good / Fine",              romanization: "bhalo"            },
                { bangla: "নাম",               english: "Name",                    romanization: "nam"              },
                { bangla: "তোমার নাম কী?",     english: "What is your name?",      romanization: "tomar nam ki?"    },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-1-1-tte-1",
              bangla: "তুমি কেমন আছো?",
              romanization: "tumi kemon acho?",
              answer: "How are you?",
              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "bar-1-1-ttb-1",
              english: "I am fine.",
              answer: "আমি ভালো আছি।",
              romanization: "ami bhalo achi.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "bar-1-1-mc-1",
              prompt: "Barisali Bangla is spoken in which region?",
              options: ["Sylhet", "Chittagong", "Barisal Division", "Rajshahi"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-2",
          title: "Introductions",
          description: "Say your name and where you are from in Barisali-flavored Bangla",
          unit: 1,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-1-2-tte-1",
              bangla: "আমার নাম ___।",
              romanization: "amar nam ___.",
              answer: "My name is ___.",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-1-2-tte-2",
              bangla: "আমি বাংলা শিখতাছি।",
              romanization: "ami bangla shikhtasi.",
              answer: "I am learning Bangla. (Barisali form)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-2-mc-1",
              prompt: "In Barisali, 'থেইকা' or 'থেকে' means:",
              options: ["name", "from", "going", "learning"],
              correct: 1,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "bar-1-2-fb-1",
              sentence: "আমি ___ থেইকা আইছি।",
              blank: "বরিশাল",
              romanization: "ami ___ theika aisi.",
              options: ["বরিশাল", "নাম", "আমার", "ভালো"],
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-3",
          title: "Polite Words",
          description: "Use polite expressions in Barisali-style speech",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-3-mp-1",
              pairs: [
                { bangla: "ধন্যবাদ",    english: "Thank you",           romanization: "dhonnobad"    },
                { bangla: "দয়া কইরা",  english: "Please (Barisali)",   romanization: "doya koira"  },
                { bangla: "মাফ কইরেন", english: "Excuse me (Barisali)", romanization: "maf koiren"  },
                { bangla: "ঠিক আছে",   english: "Okay",                romanization: "thik ase"     },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-1-3-tte-1",
              bangla: "দয়া কইরা বসেন।",
              romanization: "doya koira bosen.",
              answer: "Please sit. (Barisali polite form)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-3-mc-1",
              prompt: "The Barisali polite request pattern uses:",
              options: ["-করুন", "-কইরা", "-করবেন", "-করো"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-4",
          title: "Yes / No / Basic Replies",
          description: "Give simple replies in Barisali-style speech",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-4-mp-1",
              pairs: [
                { bangla: "হ",           english: "Yes (Barisali spoken)", romanization: "ho"        },
                { bangla: "না",          english: "No",                     romanization: "na"        },
                { bangla: "অইতে পারে", english: "Maybe (Barisali)",       romanization: "oite pare" },
                { bangla: "জানি না",   english: "I don't know",           romanization: "jani na"   },
              ],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-1-4-ttb-1",
              english: "Yes, I can. (Barisali)",
              answer: "হ, পারি।",
              romanization: "ho, pari.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-4-mc-1",
              prompt: "In Barisali, 'অইতে পারে' means:",
              options: ["yes", "no", "maybe", "okay"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-5",
          title: "Pronouns",
          description: "Use Barisali-style pronouns — including আপনে and progressive forms",
          unit: 1,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-5-mp-1",
              pairs: [
                { bangla: "আমি",   english: "I",                         romanization: "ami"  },
                { bangla: "তুমি",  english: "You (familiar)",             romanization: "tumi" },
                { bangla: "আপনে", english: "You (polite, Barisali form)", romanization: "apne" },
                { bangla: "ও",     english: "He / She",                   romanization: "o"    },
                { bangla: "ওরা",   english: "They",                       romanization: "ora"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-1-5-tte-1",
              bangla: "আপনে কেমন আসেন?",
              romanization: "apne kemon asen?",
              answer: "How are you? (Barisali polite form)",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-1-5-tte-2",
              bangla: "আমি আইতাছি।",
              romanization: "ami aitasi.",
              answer: "I am coming. (Barisali progressive)",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "bar-1-5-mc-1",
              prompt: "In Barisali, the polite 'you' is:",
              options: ["তুমি", "তুই", "আপনি", "আপনে"],
              correct: 3,
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-6",
          title: "Family",
          description: "Name your close family in Barisali-style speech — পোলা, মাইয়া, বইন",
          unit: 1,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-6-mp-1",
              pairs: [
                { bangla: "মা",      english: "Mother",           romanization: "ma"     },
                { bangla: "বাবা",    english: "Father",           romanization: "baba"   },
                { bangla: "ভাই",     english: "Brother",          romanization: "bhai"   },
                { bangla: "বইন",     english: "Sister (Barisali)", romanization: "boin"  },
                { bangla: "মাইয়া", english: "Daughter / Girl",  romanization: "maiya"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-1-6-tte-1",
              bangla: "এইডা আমার মা।",
              romanization: "eida amar ma.",
              answer: "This is my mother. (Barisali)",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-1-6-tte-2",
              bangla: "আমার এক বইন আছে।",
              romanization: "amar ek boin ase.",
              answer: "I have one sister. (Barisali: বইন for বোন)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-6-mc-1",
              prompt: "In Barisali, 'পোলা' means:",
              options: ["daughter", "son/boy", "sister", "mother"],
              correct: 1,
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-6-mc-2",
              prompt: "The Barisali word for sister is 'বইন'. In Standard Bangla it is:",
              options: ["ভাই", "মেয়ে", "বোন", "মা"],
              correct: 2,
              xp: 3,
            },
          ],
        },
      ],
    },
  ],
};
