import type { DialectCurriculum } from "@bangla-learn/types";

export const barisaliCurriculum: DialectCurriculum = {
  dialect: "barisali",
  units: [
    {
      id: "bar-unit-1",
      title: "Barisali Basics",
      description: "Learn Barisali — the dialect of Barisal Division, known for its musical rhythm",
      order: 1,
      color: "#FF4B4B",
      prep: {
        characters: [
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আইলা (came)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইলিশ (hilsa)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠা (to rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এহন (now)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওখানে (there)" },
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কই (where)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খাওয়া (eating)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলা (went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পানি (water)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বাপ (father)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালাই (quite well)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মায় (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাত (night)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হেই (he/she)" },
          { symbol: "চ", romanization: "ch",  type: "consonant" as const, exampleWord: "চাইর (four)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তারা (they)" },
          { symbol: "য", romanization: "j/y", type: "consonant" as const, exampleWord: "যাওয়া (to go)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সকাল (morning)" },
        ],
        flashcards: [
          { id: "fc-bar-1",  bangla: "হেই",         romanization: "Hei",        english: "He / She (Barisali)",       category: "pronouns"  },
          { id: "fc-bar-2",  bangla: "তাগো",        romanization: "Tago",       english: "Their / Them (Barisali)",   category: "pronouns"  },
          { id: "fc-bar-3",  bangla: "বাপ",         romanization: "Bap",        english: "Father (Barisali)",         category: "family"    },
          { id: "fc-bar-4",  bangla: "মায়",         romanization: "May",        english: "Mother (Barisali)",         category: "family"    },
          { id: "fc-bar-5",  bangla: "কই",          romanization: "Koi",        english: "Where (Barisali)",          category: "phrases"   },
          { id: "fc-bar-6",  bangla: "কেমুন",       romanization: "Kemun",      english: "How (Barisali for কেমন)",  category: "phrases"   },
          { id: "fc-bar-7",  bangla: "এহন",         romanization: "Ehon",       english: "Now (Barisali)",            category: "phrases"   },
          { id: "fc-bar-8",  bangla: "গেলা",        romanization: "Gela",       english: "Went (past tense)",         category: "verbs"     },
          { id: "fc-bar-9",  bangla: "আইলা",        romanization: "Aila",       english: "Came (past tense)",         category: "verbs"     },
          { id: "fc-bar-10", bangla: "ভালাই আছি",  romanization: "Bhalai achi",english: "I am quite fine",           category: "greetings" },
          { id: "fc-bar-11", bangla: "কই যাও?",    romanization: "Koi jao?",   english: "Where are you going?",      category: "greetings" },
          { id: "fc-bar-12", bangla: "কেমুন আছ?",  romanization: "Kemun ach?", english: "How are you?",              category: "greetings" },
          { id: "fc-bar-13", bangla: "চাইর",        romanization: "Chair",      english: "Four (Barisali for চার)",  category: "numbers"   },
          { id: "fc-bar-14", bangla: "জাই",         romanization: "Jai",        english: "Let's go",                  category: "phrases"   },
          { id: "fc-bar-15", bangla: "হের",         romanization: "Her",        english: "His / Her (Barisali)",      category: "pronouns"  },
        ],
        grammar: [
          {
            title: "Barisali Pronouns — হেই, তাগো",
            explanation: "Barisali uses 'হেই' (Hei) for he/she instead of Standard Bengali's 'সে'. The plural 'their/them' is 'তাগো' (Tago) instead of 'তাদের'.",
            examples: [
              { bangla: "হেই আসছে।",    romanization: "Hei ashche.",  english: "He/she has come." },
              { bangla: "তাগো বাড়ি।", romanization: "Tago bari.",    english: "Their home." },
            ],
          },
          {
            title: "Where & How — কই, কেমুন",
            explanation: "Barisali replaces 'কোথায়' (where) with 'কই' (Koi) and 'কেমন' (how) becomes 'কেমুন' (Kemun). These short words give Barisali its musical quality.",
            examples: [
              { bangla: "কই যাও?",    romanization: "Koi jao?",    english: "Where are you going?" },
              { bangla: "কেমুন আছ?", romanization: "Kemun ach?",  english: "How are you?" },
            ],
          },
          {
            title: "Musical Rhythm of Barisali",
            explanation: "Barisali is famous for its sing-song rhythm and drawn-out vowels. Words like 'ভালাই' add an extra '-ই' suffix for emphasis, a pattern unique to this dialect.",
            examples: [
              { bangla: "ভালাই আছি।",  romanization: "Bhalai achi.",  english: "I am quite well." },
              { bangla: "এহন যাই।",    romanization: "Ehon jai.",      english: "I'm going now." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "bar-1-0",
          title: "Write the Letters",
          description: "Trace Bengali vowels and consonants used in Barisali",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "bar-1-0-tr-1", character: "অ", romanization: "o/a", exampleWord: "অনেক — many", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-2", character: "আ", romanization: "aa", exampleWord: "আম — mango", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-3", character: "ক", romanization: "k", exampleWord: "কলা — banana", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-4", character: "ন", romanization: "n", exampleWord: "নাম — name", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-5", character: "ম", romanization: "m", exampleWord: "মা — mother", xp: 4 },
          ],
        },
        {
          id: "bar-1-1",
          title: "Greetings",
          description: "Greet and introduce yourself in Barisali-flavored Bangla",
          unit: 1,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-1-mp-1",
              pairs: [
                { bangla: "আসসালামু আলাইকুম", english: "Hello (Islamic greeting)", romanization: "assalamu alaikum" },
                { bangla: "ভালো",              english: "Good / Fine",              romanization: "bhalo"            },
                { bangla: "নাম",               english: "Name",                    romanization: "nam"              },
                { bangla: "তোমার নাম কী?",     english: "What is your name?",      romanization: "tomar nam ki?"    },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-1-1-tte-1",
              bangla: "তুমি কেমন আছো?",
              romanization: "tumi kemon acho?",
              answer: "How are you?",

              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "bar-1-1-ttb-1",
              english: "I am fine.",
              answer: "আমি ভালো আছি।",
              romanization: "ami bhalo achi.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "bar-1-1-mc-1",
              prompt: "Barisali Bangla is spoken in which region?",
              options: ["Sylhet", "Chittagong", "Barisal Division", "Rajshahi"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-2",
          title: "Introductions",
          description: "Say your name and where you are from in Barisali-flavored Bangla",
          unit: 1,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-1-2-tte-1",
              bangla: "আমার নাম ___।",
              romanization: "amar nam ___.",
              answer: "My name is ___.",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-1-2-tte-2",
              bangla: "আমি বাংলা শিখতাছি।",
              romanization: "ami bangla shikhtasi.",
              answer: "I am learning Bangla. (Barisali form)",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-2-mc-1",
              prompt: "In Barisali, 'থেইকা' or 'থেকে' means:",
              options: ["name", "from", "going", "learning"],
              correct: 1,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "bar-1-2-fb-1",
              sentence: "আমি ___ থেইকা আইছি।",
              blank: "বরিশাল",
              romanization: "ami ___ theika aisi.",
              options: ["বরিশাল", "নাম", "আমার", "ভালো"],
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-3",
          title: "Polite Words",
          description: "Use polite expressions in Barisali-style speech",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-3-mp-1",
              pairs: [
                { bangla: "ধন্যবাদ",    english: "Thank you",           romanization: "dhonnobad"    },
                { bangla: "দয়া কইরা",  english: "Please (Barisali)",   romanization: "doya koira"  },
                { bangla: "মাফ কইরেন", english: "Excuse me (Barisali)", romanization: "maf koiren"  },
                { bangla: "ঠিক আছে",   english: "Okay",                romanization: "thik ase"     },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-1-3-tte-1",
              bangla: "দয়া কইরা বসেন।",
              romanization: "doya koira bosen.",
              answer: "Please sit. (Barisali polite form)",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-3-mc-1",
              prompt: "The Barisali polite request pattern uses:",
              options: ["-করুন", "-কইরা", "-করবেন", "-করো"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-4",
          title: "Yes / No / Basic Replies",
          description: "Give simple replies in Barisali-style speech",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-4-mp-1",
              pairs: [
                { bangla: "হ",           english: "Yes (Barisali spoken)", romanization: "ho"        },
                { bangla: "না",          english: "No",                     romanization: "na"        },
                { bangla: "অইতে পারে", english: "Maybe (Barisali)",       romanization: "oite pare" },
                { bangla: "জানি না",   english: "I don't know",           romanization: "jani na"   },
              ],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-1-4-ttb-1",
              english: "Yes, I can. (Barisali)",
              answer: "হ, পারি।",
              romanization: "ho, pari.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-4-mc-1",
              prompt: "In Barisali, 'অইতে পারে' means:",
              options: ["yes", "no", "maybe", "okay"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-5",
          title: "Pronouns",
          description: "Use Barisali-style pronouns — including আপনে and progressive forms",
          unit: 1,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-5-mp-1",
              pairs: [
                { bangla: "আমি",   english: "I",                         romanization: "ami"  },
                { bangla: "তুমি",  english: "You (familiar)",             romanization: "tumi" },
                { bangla: "আপনে", english: "You (polite, Barisali form)", romanization: "apne" },
                { bangla: "ও",     english: "He / She",                   romanization: "o"    },
                { bangla: "ওরা",   english: "They",                       romanization: "ora"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-1-5-tte-1",
              bangla: "আপনে কেমন আসেন?",
              romanization: "apne kemon asen?",
              answer: "How are you? (Barisali polite form)",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-1-5-tte-2",
              bangla: "আমি আইতাছি।",
              romanization: "ami aitasi.",
              answer: "I am coming. (Barisali progressive)",

              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "bar-1-5-mc-1",
              prompt: "In Barisali, the polite 'you' is:",
              options: ["তুমি", "তুই", "আপনি", "আপনে"],
              correct: 3,
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-6",
          title: "Family",
          description: "Name your close family in Barisali-style speech — পোলা, মাইয়া, বইন",
          unit: 1,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-6-mp-1",
              pairs: [
                { bangla: "মা",      english: "Mother",           romanization: "ma"     },
                { bangla: "বাবা",    english: "Father",           romanization: "baba"   },
                { bangla: "ভাই",     english: "Brother",          romanization: "bhai"   },
                { bangla: "বইন",     english: "Sister (Barisali)", romanization: "boin"  },
                { bangla: "মাইয়া", english: "Daughter / Girl",  romanization: "maiya"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-1-6-tte-1",
              bangla: "এইডা আমার মা।",
              romanization: "eida amar ma.",
              answer: "This is my mother. (Barisali)",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-1-6-tte-2",
              bangla: "আমার এক বইন আছে।",
              romanization: "amar ek boin ase.",
              answer: "I have one sister. (Barisali: বইন for বোন)",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-6-mc-1",
              prompt: "In Barisali, 'পোলা' means:",
              options: ["daughter", "son/boy", "sister", "mother"],
              correct: 1,
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-6-mc-2",
              prompt: "The Barisali word for sister is 'বইন'. In Standard Bangla it is:",
              options: ["ভাই", "মেয়ে", "বোন", "মা"],
              correct: 2,
              xp: 3,
            },
          ],
        },
      ],
    },
    {
      id: "bar-unit-2",
      title: "Heart & Time",
      description: "Express affection, ask questions, count numbers, and talk about time in Barisali",
      order: 2,
      color: "#9333ea",
      prep: {
        characters: [],
        flashcards: [
          { id: "fc-bar-2-1",  bangla: "আপনে",       romanization: "apne",        english: "You (formal, Barisali)",    category: "pronouns"  },
          { id: "fc-bar-2-2",  bangla: "তোমারে",      romanization: "tomare",      english: "You / To you (object)",    category: "pronouns"  },
          { id: "fc-bar-2-3",  bangla: "আমাগো",       romanization: "amago",       english: "Our / Ours",               category: "pronouns"  },
          { id: "fc-bar-2-4",  bangla: "ভালোবাসি",   romanization: "bhalobashi",  english: "I love (you)",             category: "phrases"   },
          { id: "fc-bar-2-5",  bangla: "মায়া",        romanization: "maya",        english: "Affection / Love",         category: "phrases"   },
          { id: "fc-bar-2-6",  bangla: "কই",          romanization: "koi",         english: "Where (Barisali)",         category: "questions" },
          { id: "fc-bar-2-7",  bangla: "লাই",         romanization: "lai",         english: "For (Barisali: জন্য)",     category: "grammar"   },
          { id: "fc-bar-2-8",  bangla: "এহন",         romanization: "ehon",        english: "Now (Barisali: এখন)",      category: "time"      },
          { id: "fc-bar-2-9",  bangla: "রাইত",        romanization: "rait",        english: "Night (Barisali: রাত)",    category: "time"      },
          { id: "fc-bar-2-10", bangla: "সকাল",        romanization: "shokal",      english: "Morning",                  category: "time"      },
          { id: "fc-bar-2-11", bangla: "বিকাল",       romanization: "bikal",       english: "Afternoon / Evening",      category: "time"      },
          { id: "fc-bar-2-12", bangla: "আইজ",         romanization: "aij",         english: "Today (Barisali: আজ)",    category: "time"      },
          { id: "fc-bar-2-13", bangla: "গইকাল",       romanization: "goikal",      english: "Yesterday",                category: "time"      },
          { id: "fc-bar-2-14", bangla: "আগাইলকাল",   romanization: "agailkal",    english: "Tomorrow",                 category: "time"      },
          { id: "fc-bar-2-15", bangla: "দিমু",        romanization: "dimu",        english: "Will give (Barisali future)", category: "grammar" },
          { id: "fc-bar-2-16", bangla: "হইব",         romanization: "hoib",        english: "Will happen / Will be",    category: "grammar"   },
          { id: "fc-bar-2-17", bangla: "এক",          romanization: "ek",          english: "One",                      category: "numbers"   },
          { id: "fc-bar-2-18", bangla: "দুই",         romanization: "dui",         english: "Two",                      category: "numbers"   },
          { id: "fc-bar-2-19", bangla: "তিন",         romanization: "tin",         english: "Three",                    category: "numbers"   },
          { id: "fc-bar-2-20", bangla: "দশ",          romanization: "dosh",        english: "Ten",                      category: "numbers"   },
        ],
        grammar: [
          {
            title: "Barisali Object Pronoun: -রে",
            explanation: "Barisali uses '-রে' as the object marker. 'তোমাকে' in Standard Bangla becomes 'তোমারে'. Similarly 'আমাকে' → 'আমারে'.",
            examples: [
              { bangla: "আমি তোমারে ভালোবাসি।", romanization: "ami tomare bhalobashi.", english: "I love you." },
              { bangla: "আমারে ডাইকো।",          romanization: "amare daiko.",           english: "Call me." },
            ],
          },
          {
            title: "Barisali Future: দিমু / হইব",
            explanation: "Future tense in Barisali uses 'দিমু' (will give) and 'হইব' (will happen/be). These replace Standard Bangla's 'দেব' and 'হবে'.",
            examples: [
              { bangla: "আমি তোমারে দিমু।",  romanization: "ami tomare dimu.",  english: "I will give you." },
              { bangla: "এইডা হইব না।",      romanization: "eida hoib na.",     english: "This will not happen." },
            ],
          },
          {
            title: "Barisali Time Words",
            explanation: "Key time differences: এখন→এহন (now), রাত→রাইত (night), আজ→আইজ (today), গতকাল→গইকাল (yesterday), আগামীকাল→আগাইলকাল (tomorrow).",
            examples: [
              { bangla: "আইজ রাইত আমি যামু।", romanization: "aij rait ami jamu.", english: "Tonight I will go." },
              { bangla: "গইকাল কই আছিলা?",     romanization: "goikal koi ashila?", english: "Where were you yesterday?" },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "bar-2-0",
          title: "Respect & Affection",
          description: "Say 'I love you' and show respect in Barisali",
          unit: 2,
          order: 0,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-2-0-mp-1",
              pairs: [
                { bangla: "আপনে",             english: "You (formal)",   romanization: "apne"           },
                { bangla: "তোমারে ভালোবাসি", english: "I love you",     romanization: "tomare bhalobashi" },
                { bangla: "মায়া",             english: "Affection",      romanization: "maya"           },
                { bangla: "আমাগো",            english: "Our",            romanization: "amago"          },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-2-0-tte-1",
              bangla: "আমি তোমারে খুব মায়া করি।",
              romanization: "ami tomare khub maya kori.",
              answer: "I love / care for you a lot.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-2-0-mc-1",
              prompt: "In Barisali, the object 'you' (তোমাকে in Standard) is:",
              options: ["তোমায়", "তোমারে", "তোমার", "তুমি"],
              correct: 1,
              xp: 5,
            },
          ],
        },
        {
          id: "bar-2-1",
          title: "Sweet Questions",
          description: "Ask questions in Barisali — কেমন, কই, কেন",
          unit: 2,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-2-1-tte-1",
              bangla: "তুমি এহন কই আসো?",
              romanization: "tumi ehon koi aso?",
              answer: "Where are you now?",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-2-1-fb-1",
              sentence: "তোমার ___ পছন্দ?",
              blank: "কী",
              romanization: "tomar ___ pochondo?",
              options: ["কই", "কী", "কেন", "লাই"],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-2-1-mc-1",
              prompt: "In Barisali, 'where' is said as:",
              options: ["কোথায়", "কেলে", "কই", "কেন"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "bar-2-2",
          title: "Numbers 1–10",
          description: "Count from one to ten",
          unit: 2,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-2-2-mp-1",
              pairs: [
                { bangla: "এক",   english: "One",   romanization: "ek"    },
                { bangla: "দুই",  english: "Two",   romanization: "dui"   },
                { bangla: "তিন",  english: "Three", romanization: "tin"   },
                { bangla: "চার",  english: "Four",  romanization: "char"  },
              ],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-2-2-mp-2",
              pairs: [
                { bangla: "পাঁচ", english: "Five",  romanization: "pach"  },
                { bangla: "ছয়",  english: "Six",   romanization: "choy"  },
                { bangla: "সাত",  english: "Seven", romanization: "shat"  },
                { bangla: "আট",   english: "Eight", romanization: "at"    },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-2-2-mc-1",
              prompt: "What is 'দশ' in English?",
              options: ["Eight", "Nine", "Ten", "Seven"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "bar-2-3",
          title: "Numbers 11–20",
          description: "Count from eleven to twenty",
          unit: 2,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-2-3-mp-1",
              pairs: [
                { bangla: "এগারো",  english: "Eleven",   romanization: "egaro"   },
                { bangla: "বারো",   english: "Twelve",   romanization: "baro"    },
                { bangla: "তেরো",   english: "Thirteen", romanization: "tero"    },
                { bangla: "চৌদ্দ", english: "Fourteen", romanization: "chouddo" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-2-3-mc-1",
              prompt: "How do you say 'twenty' in Bangla?",
              options: ["পনেরো", "আঠারো", "বিশ", "উনিশ"],
              correct: 2,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-2-3-tte-1",
              bangla: "আমার বয়স পনেরো।",
              romanization: "amar boyosh ponero.",
              answer: "I am fifteen years old.",

              xp: 5,
            },
          ],
        },
        {
          id: "bar-2-4",
          title: "Time Words",
          description: "Morning, afternoon, night — in Barisali",
          unit: 2,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-2-4-mp-1",
              pairs: [
                { bangla: "সকাল",  english: "Morning",   romanization: "shokal" },
                { bangla: "বিকাল", english: "Afternoon", romanization: "bikal"  },
                { bangla: "রাইত",  english: "Night",     romanization: "rait"   },
                { bangla: "এহন",   english: "Now",       romanization: "ehon"   },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-2-4-tte-1",
              bangla: "আইজ রাইত ভালো।",
              romanization: "aij rait bhalo.",
              answer: "Tonight is good. / The night is good today.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-2-4-mc-1",
              prompt: "In Barisali, 'now' (এখন in Standard) is:",
              options: ["রাইত", "আইজ", "এহন", "লাই"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "bar-2-5",
          title: "Today / Yesterday / Tomorrow",
          description: "Talk about days in Barisali",
          unit: 2,
          order: 5,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-2-5-mc-1",
              prompt: "In Barisali, 'today' (আজ) becomes:",
              options: ["গইকাল", "আইজ", "আগাইলকাল", "এহন"],
              correct: 1,
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-2-5-mc-2",
              prompt: "In Barisali, 'yesterday' (গতকাল) is:",
              options: ["আইজ", "আগাইলকাল", "গইকাল", "কাইল"],
              correct: 2,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-2-5-tte-1",
              bangla: "আগাইলকাল আমি যামু।",
              romanization: "agailkal ami jamu.",
              answer: "Tomorrow I will go.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-2-5-ttb-1",
              english: "Where were you yesterday?",
              answer: "গইকাল তুমি কই আছিলা?",
              romanization: "goikal tumi koi ashila?",
              xp: 5,
            },
          ],
        },
      ],
    },
    // ─── Unit 3 ───────────────────────────────────────────────────────────────
    {
      id: "bar-unit-3",
      title: "Food & Daily Life",
      description: "Barisali kitchen talk, market haggling, and home routines.",
      color: "#ea580c",
      order: 3,
      prep: {
        flashcards: [
          { id: "fc-bar-3-1",  bangla: "ভাত",        romanization: "vhat",       english: "cooked rice",         emoji: "🍚", category: "food" },
          { id: "fc-bar-3-2",  bangla: "মাছ",         romanization: "mach",       english: "fish",                emoji: "🐟", category: "food" },
          { id: "fc-bar-3-3",  bangla: "ডাল",         romanization: "dal",        english: "lentils",             emoji: "🫘", category: "food" },
          { id: "fc-bar-3-4",  bangla: "সবজি",        romanization: "shobji",     english: "vegetables",          emoji: "🥦", category: "food" },
          { id: "fc-bar-3-5",  bangla: "পানি",        romanization: "pani",       english: "water",               emoji: "💧", category: "food" },
          { id: "fc-bar-3-6",  bangla: "চা",          romanization: "cha",        english: "tea",                 emoji: "🍵", category: "food" },
          { id: "fc-bar-3-7",  bangla: "দুধ",         romanization: "dudh",       english: "milk",                emoji: "🥛", category: "food" },
          { id: "fc-bar-3-8",  bangla: "রুটি",        romanization: "ruti",       english: "bread / roti",        emoji: "🫓", category: "food" },
          { id: "fc-bar-3-9",  bangla: "মাংস",        romanization: "mangsho",    english: "meat",                emoji: "🍖", category: "food" },
          { id: "fc-bar-3-10", bangla: "ফল",          romanization: "fol",        english: "fruit",               emoji: "🍎", category: "food" },
          { id: "fc-bar-3-11", bangla: "খাইতাছি",    romanization: "khaitashi",  english: "I am eating",         emoji: "😋", category: "verb" },
          { id: "fc-bar-3-12", bangla: "রানতাছি",    romanization: "rantashi",   english: "I am cooking",        emoji: "👨‍🍳", category: "verb" },
          { id: "fc-bar-3-13", bangla: "বাজার",       romanization: "bajar",      english: "market",              emoji: "🛒", category: "place" },
          { id: "fc-bar-3-14", bangla: "দোকান",       romanization: "dokan",      english: "shop",                emoji: "🏪", category: "place" },
          { id: "fc-bar-3-15", bangla: "বাড়ি",        romanization: "bari",       english: "home",                emoji: "🏠", category: "place" },
          { id: "fc-bar-3-16", bangla: "ঘর",          romanization: "ghor",       english: "room",                emoji: "🚪", category: "place" },
          { id: "fc-bar-3-17", bangla: "রান্নাঘর",    romanization: "rannaghor",  english: "kitchen",             emoji: "🍳", category: "place" },
          { id: "fc-bar-3-18", bangla: "বিছানা",      romanization: "bishana",    english: "bed",                 emoji: "🛏️", category: "home" },
          { id: "fc-bar-3-19", bangla: "খিদা",        romanization: "khida",      english: "hunger (Barisali)",   emoji: "😩", category: "feeling" },
          { id: "fc-bar-3-20", bangla: "পেট ভরা",     romanization: "pet vhora",  english: "stomach full",        emoji: "😌", category: "feeling" },
          { id: "fc-bar-3-21", bangla: "কিনমু",       romanization: "kinmu",      english: "I will buy",          emoji: "🛍️", category: "verb" },
          { id: "fc-bar-3-22", bangla: "দামটা",       romanization: "damta",      english: "the price",           emoji: "💰", category: "market" },
          { id: "fc-bar-3-23", bangla: "সস্তা",       romanization: "shoshta",    english: "cheap",               emoji: "🏷️", category: "market" },
          { id: "fc-bar-3-24", bangla: "দামী",        romanization: "dami",       english: "expensive",           emoji: "💎", category: "market" },
          { id: "fc-bar-3-25", bangla: "ঘুমাইতাছি",  romanization: "ghumaishi",  english: "I am sleeping",       emoji: "😴", category: "routine" },
          { id: "fc-bar-3-26", bangla: "উইঠা যাই",   romanization: "uitha jai",  english: "I get up / wake up",  emoji: "🌅", category: "routine" },
          { id: "fc-bar-3-27", bangla: "গোসল",        romanization: "ghoshol",    english: "bath",                emoji: "🚿", category: "routine" },
          { id: "fc-bar-3-28", bangla: "কামে যাই",   romanization: "kame jai",   english: "I go to work",        emoji: "💼", category: "routine" },
        ],
        characters: [],
        grammar: [
          {
            title: "-তাছি progressive in Barisali",
            explanation: "Barisali uses -তাছি for ongoing actions: খাইতাছি (am eating), রানতাছি (am cooking).",
            examples: [
              { bangla: "আমি ভাত খাইতাছি।",  romanization: "ami vhat khaitashi.",  english: "I am eating rice." },
              { bangla: "মা রান্না রানতাছে।",  romanization: "ma ranna rantashe.",   english: "Mother is cooking." },
            ],
          },
          {
            title: "কিনমু — Barisali future 'will buy'",
            explanation: "Barisali future: কিনমু (I will buy), দিমু (I will give), যামু (I will go) — all use -মু.",
            examples: [
              { bangla: "আমি বাজার থাইকা মাছ কিনমু।", romanization: "ami bajar thaika mach kinmu.", english: "I will buy fish from the market." },
              { bangla: "তোমারে চা দিমু।",             romanization: "tomare cha dimu.",             english: "I will give you tea." },
            ],
          },
          {
            title: "থাইকা = from",
            explanation: "Barisali থাইকা = standard Bengali থেকে (from). Used with places: বাজার থাইকা (from the market).",
            examples: [
              { bangla: "দোকান থাইকা কিনছি।", romanization: "dokan thaika kinshi.", english: "I bought from the shop." },
              { bangla: "বাড়ির কাছে বাজার।",   romanization: "barir kashe bajar.",   english: "The market is near home." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "bar-3-1",
          title: "Rice & Fish",
          description: "Food staples: rice, fish, and lentils in Barisali",
          unit: 3,
          order: 1,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-3-1-mc-1",
              prompt: "Barisali 'I am eating' is:",
              options: ["খাইতাছি", "খাচ্ছি", "খাইছিলাম", "খামু"],
              correct: 0,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-3-1-tte-1",
              bangla: "আমি ভাত আর মাছ খাইতাছি।",
              romanization: "ami vhat ar mach khaitashi.",
              answer: "I am eating rice and fish.",

              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-3-1-mp-1",
              pairs: [
                { bangla: "ভাত",  english: "rice", romanization: "bhat" },
                { bangla: "মাছ",  english: "fish", romanization: "mach" },
                { bangla: "ডাল",  english: "lentils", romanization: "dal" },
                { bangla: "পানি", english: "water", romanization: "pani" },
              ],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "bar-3-1-ttb-1",
              english: "I will eat fish and rice.",
              answer: "আমি মাছ আর ভাত খামু।",
              romanization: "ami mach ar vhat khamu.",
              xp: 5,
            },
          ],
        },
        {
          id: "bar-3-2",
          title: "At the Market",
          description: "Shopping at the market in Barisali dialect",
          unit: 3,
          order: 2,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-3-2-mc-1",
              prompt: "Barisali for 'I will buy' is:",
              options: ["কিনব", "কিনমু", "কিনছি", "কিনতাছি"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-3-2-tte-1",
              bangla: "বাজার থাইকা সবজি কিনমু।",
              romanization: "bajar thaika shobji kinmu.",
              answer: "I will buy vegetables from the market.",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-3-2-fb-1",
              sentence: "দামটা অনেক ___।",
              romanization: "damta onek ___.",
              blank: "দামী",

              options: ["দামী"],

              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-3-2-mp-1",
              pairs: [
                { bangla: "বাজার",  english: "market", romanization: "bajar" },
                { bangla: "দোকান",  english: "shop", romanization: "dokan" },
                { bangla: "সস্তা",  english: "cheap", romanization: "shoshta" },
                { bangla: "দামী",   english: "expensive", romanization: "dami" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "bar-3-3",
          title: "In the Kitchen",
          description: "Kitchen vocabulary and cooking in Barisali",
          unit: 3,
          order: 3,
          xpReward: 20,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-3-3-tte-1",
              bangla: "মা রান্নাঘরে রান্না রানতাছে।",
              romanization: "ma rannaghor-e ranna rantashe.",
              answer: "Mother is cooking in the kitchen.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-3-3-mc-1",
              prompt: "Barisali 'kitchen' is:",
              options: ["খাবার ঘর", "রান্নাঘর", "বিছানা ঘর", "বাজার ঘর"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "bar-3-3-mp-1",
              pairs: [
                { bangla: "রান্নাঘর", english: "kitchen", romanization: "rannaghor" },
                { bangla: "বিছানা",   english: "bed", romanization: "bishana" },
                { bangla: "ঘর",       english: "room", romanization: "ghor" },
                { bangla: "বাড়ি",    english: "home", romanization: "bari" },
              ],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "bar-3-3-ttb-1",
              english: "I will cook at home.",
              answer: "আমি বাড়িতে রান্না রানমু।",
              romanization: "ami barite ranna ranmu.",
              xp: 5,
            },
          ],
        },
        {
          id: "bar-3-4",
          title: "Daily Routine",
          description: "Daily routine and meal times in Barisali",
          unit: 3,
          order: 4,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-3-4-mc-1",
              prompt: "Barisali 'I am sleeping' is:",
              options: ["ঘুমাইছি", "ঘুমাইতাছি", "ঘুমামু", "ঘুমাইছিলাম"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-3-4-tte-1",
              bangla: "ভোরে উইঠা গোসল করছি।",
              romanization: "vhore uitha ghoshol korshi.",
              answer: "I woke up early and bathed.",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-3-4-fb-1",
              sentence: "সকালে উইঠা ___ করছি।",
              romanization: "shokale uitha ___ korshi.",
              blank: "গোসল",

              options: ["গোসল"],

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-3-4-ttb-1",
              english: "I go to work every day.",
              answer: "আমি প্রতিদিন কামে যাই।",
              romanization: "ami protidin kame jai.",
              xp: 5,
            },
          ],
        },
        {
          id: "bar-3-5",
          title: "Hunger & Fullness",
          description: "Expressing hunger and fullness in Barisali",
          unit: 3,
          order: 5,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-3-5-mc-1",
              prompt: "Barisali for 'hunger' (not standard ক্ষুধা) is:",
              options: ["পেট", "খিদা", "তৃষ্ণা", "ব্যথা"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-3-5-tte-1",
              bangla: "আমার অনেক খিদা লাগছে।",
              romanization: "amar onek khida lagse.",
              answer: "I am very hungry.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-3-5-ttb-1",
              english: "My stomach is full.",
              answer: "আমার পেট ভরা।",
              romanization: "amar pet vhora.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-3-5-mp-1",
              pairs: [
                { bangla: "খিদা",    english: "hunger", romanization: "khida" },
                { bangla: "পেট ভরা", english: "stomach full", romanization: "pet vhora" },
                { bangla: "পানি",    english: "water", romanization: "pani" },
                { bangla: "চা",      english: "tea", romanization: "cha" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "bar-3-6",
          title: "Food Quiz",
          description: "Food & Daily Life quiz — Barisali Unit 3",
          unit: 3,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-3-6-mc-1",
              prompt: "What does 'কিনমু' mean?",
              options: ["I bought", "I am buying", "I will buy", "Buy!"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-3-6-tte-1",
              bangla: "আমি বাজার থাইকা মাছ আর সবজি কিনমু।",
              romanization: "ami bajar thaika mach ar shobji kinmu.",
              answer: "I will buy fish and vegetables from the market.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-3-6-ttb-1",
              english: "Mother is cooking in the kitchen.",
              answer: "মা রান্নাঘরে রান্না রানতাছে।",
              romanization: "ma rannaghor-e ranna rantashe.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-3-6-fb-1",
              sentence: "আমার অনেক ___ লাগছে।",
              romanization: "amar onek ___ lagse.",
              blank: "খিদা",

              options: ["খিদা"],

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-3-6-mc-2",
              prompt: "Barisali progressive suffix is:",
              options: ["-ছি", "-তেছি", "-তাছি", "-ব"],
              correct: 2,
              xp: 4,
            },
          ],
        },
      ],
    },
    {
      id: "bar-4",
      title: "Numbers & Counting",
      description: "Count from 1 to 1000 in Barisali Bengali",
      order: 4,
      color: "#7c3aed",
      prep: {
        characters: [],
        grammar: [
          {
            title: "Classifier -টা / -টি",
            explanation: "When counting objects in Barisali, attach -টা (informal) or -টি (formal) after the number. এক-টা = one (of something), দুই-টা = two (of something). This mirrors standard Bengali usage.",
            examples: [
              { bangla: "একটা আম", romanization: "ekta am", english: "one mango" },
              { bangla: "তিনটা মাছ", romanization: "tinta mach", english: "three fish" },
              { bangla: "দুইটা কলা", romanization: "duita kola", english: "two bananas" },
            ],
          },
          {
            title: "Time question: কটা বাজে?",
            explanation: "In Barisali, 'What time is it?' is 'কটা বাজে?' (same as standard Bengali). The answer uses the number + টা + বাজে. E.g., দুইটা বাজে = It is two o'clock.",
            examples: [
              { bangla: "কটা বাজে?", romanization: "kota baje?", english: "What time is it?" },
              { bangla: "তিনটা বাজে।", romanization: "tinta baje.", english: "It is three o'clock." },
              { bangla: "দশটা বাজে।", romanization: "doshta baje.", english: "It is ten o'clock." },
            ],
          },
          {
            title: "Quantity question: কত? / কয়টা?",
            explanation: "'How many?' in Barisali is 'কত?' for general quantity and 'কয়টা?' when asking about countable objects. Both are common in everyday speech.",
            examples: [
              { bangla: "কয়টা আম আছে?", romanization: "koyta am ache?", english: "How many mangoes are there?" },
              { bangla: "কত টাকা?", romanization: "koto taka?", english: "How much money?" },
              { bangla: "কয়টা মানুষ?", romanization: "koyta manush?", english: "How many people?" },
            ],
          },
        ],
        flashcards: [
          { id: "bar-4-fc-1", bangla: "এক", romanization: "ek", english: "one", emoji: "1️⃣", category: "numbers" },
          { id: "bar-4-fc-2", bangla: "দুই", romanization: "dui", english: "two", emoji: "2️⃣", category: "numbers" },
          { id: "bar-4-fc-3", bangla: "তিন", romanization: "tin", english: "three", emoji: "3️⃣", category: "numbers" },
          { id: "bar-4-fc-4", bangla: "চার", romanization: "char", english: "four", emoji: "4️⃣", category: "numbers" },
          { id: "bar-4-fc-5", bangla: "পাঁচ", romanization: "panch", english: "five", emoji: "5️⃣", category: "numbers" },
          { id: "bar-4-fc-6", bangla: "ছয়", romanization: "chhoy", english: "six", emoji: "6️⃣", category: "numbers" },
          { id: "bar-4-fc-7", bangla: "সাত", romanization: "shat", english: "seven", emoji: "7️⃣", category: "numbers" },
          { id: "bar-4-fc-8", bangla: "আট", romanization: "at", english: "eight", emoji: "8️⃣", category: "numbers" },
          { id: "bar-4-fc-9", bangla: "নয়", romanization: "noy", english: "nine", emoji: "9️⃣", category: "numbers" },
          { id: "bar-4-fc-10", bangla: "দশ", romanization: "dosh", english: "ten", emoji: "🔟", category: "numbers" },
          { id: "bar-4-fc-11", bangla: "এগারো", romanization: "egaro", english: "eleven", emoji: "1️⃣1️⃣", category: "numbers" },
          { id: "bar-4-fc-12", bangla: "বারো", romanization: "baro", english: "twelve", emoji: "1️⃣2️⃣", category: "numbers" },
          { id: "bar-4-fc-13", bangla: "তেরো", romanization: "tero", english: "thirteen", emoji: "1️⃣3️⃣", category: "numbers" },
          { id: "bar-4-fc-14", bangla: "চৌদ্দ", romanization: "chouddo", english: "fourteen", emoji: "1️⃣4️⃣", category: "numbers" },
          { id: "bar-4-fc-15", bangla: "পনেরো", romanization: "ponero", english: "fifteen", emoji: "1️⃣5️⃣", category: "numbers" },
          { id: "bar-4-fc-16", bangla: "বিশ", romanization: "bish", english: "twenty", emoji: "2️⃣0️⃣", category: "numbers" },
          { id: "bar-4-fc-17", bangla: "ত্রিশ", romanization: "trish", english: "thirty", emoji: "3️⃣0️⃣", category: "numbers" },
          { id: "bar-4-fc-18", bangla: "চল্লিশ", romanization: "challish", english: "forty", emoji: "4️⃣0️⃣", category: "numbers" },
          { id: "bar-4-fc-19", bangla: "একশো", romanization: "ekshо", english: "one hundred", emoji: "💯", category: "numbers" },
          { id: "bar-4-fc-20", bangla: "এক হাজার", romanization: "ek hajar", english: "one thousand", emoji: "🔢", category: "numbers" },
          { id: "bar-4-fc-21", bangla: "কত?", romanization: "koto?", english: "how many / how much?", emoji: "❓", category: "question" },
          { id: "bar-4-fc-22", bangla: "কয়টা?", romanization: "koyta?", english: "how many (countable)?", emoji: "❓", category: "question" },
          { id: "bar-4-fc-23", bangla: "ঘণ্টা", romanization: "ghonta", english: "hour / o'clock", emoji: "🕐", category: "time" },
          { id: "bar-4-fc-24", bangla: "টাকা", romanization: "taka", english: "taka (money)", emoji: "💵", category: "money" },
          { id: "bar-4-fc-25", bangla: "দাম", romanization: "dam", english: "price", emoji: "🏷️", category: "money" },
        ],
      },
      lessons: [
        {
          id: "bar-4-1",
          title: "Numbers 1–10",
          description: "Learn to count from one to ten in Barisali",
          unit: 4,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-4-1-mc-1",
              prompt: "What is the Barisali word for 'five'?",
              options: ["চার", "পাঁচ", "ছয়", "সাত"],
              correct: 1,
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-4-1-mc-2",
              prompt: "Which number is 'আট'?",
              options: ["6", "7", "8", "9"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-4-1-tte-1",
              bangla: "তিন",
              romanization: "tin",
              answer: "three",
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-4-1-ttb-1",
              english: "seven",
              answer: "সাত",
              romanization: "shat",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-4-1-mp-1",
              pairs: [
                { bangla: "এক", english: "one", romanization: "ek" },
                { bangla: "দুই", english: "two", romanization: "dui" },
                { bangla: "নয়", english: "nine", romanization: "noy" },
                { bangla: "দশ", english: "ten", romanization: "dosh" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "bar-4-2",
          title: "Numbers 11–20",
          description: "Learn the teen numbers and twenty in Barisali",
          unit: 4,
          order: 2,
          xpReward: 10,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-4-2-mc-1",
              prompt: "What does 'এগারো' mean?",
              options: ["ten", "eleven", "twelve", "thirteen"],
              correct: 1,
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-4-2-mc-2",
              prompt: "Which is the Barisali word for 'fifteen'?",
              options: ["তেরো", "চৌদ্দ", "পনেরো", "বিশ"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-4-2-tte-1",
              bangla: "বারো",
              romanization: "baro",
              answer: "twelve",
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-4-2-ttb-1",
              english: "twenty",
              answer: "বিশ",
              romanization: "bish",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-4-2-mp-1",
              pairs: [
                { bangla: "তেরো", english: "thirteen", romanization: "tero" },
                { bangla: "চৌদ্দ", english: "fourteen", romanization: "chouddo" },
                { bangla: "ষোলো", english: "sixteen", romanization: "sholo" },
                { bangla: "বিশ", english: "twenty", romanization: "bish" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "bar-4-3",
          title: "Counting Objects",
          description: "Use classifiers to count objects in Barisali",
          unit: 4,
          order: 3,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-4-3-mp-1",
              pairs: [
                { bangla: "একটা আম", english: "one mango", romanization: "ekta am" },
                { bangla: "দুইটা মাছ", english: "two fish", romanization: "duita mach" },
                { bangla: "তিনটা কলা", english: "three bananas", romanization: "tinta kola" },
                { bangla: "পাঁচটা ডিম", english: "five eggs", romanization: "panchta dim" },
              ],
              xp: 6,
            },
            {
              type: "fill_blank",
              id: "bar-4-3-fb-1",
              sentence: "আমার ___ টা বই আছে।",
              romanization: "amar ___ ta boi ache.",
              blank: "চার",
              options: ["তিন", "চার", "পাঁচ", "ছয়"],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-4-3-tte-1",
              bangla: "সাতটা কমলা আছে।",
              romanization: "shatta komola ache.",
              answer: "There are seven oranges.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-4-3-fb-2",
              sentence: "দোকানে দশ___ জামা আছে।",
              romanization: "dokane dosh___ jama ache.",
              blank: "টা",
              options: ["টা", "টি", "জন", "খান"],
              xp: 5,
            },
          ],
        },
        {
          id: "bar-4-4",
          title: "Telling the Time",
          description: "Ask and tell the time in Barisali",
          unit: 4,
          order: 4,
          xpReward: 10,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-4-4-mc-1",
              prompt: "How do you ask 'What time is it?' in Barisali?",
              options: ["কত সময়?", "কটা বাজে?", "সময় কি?", "কয়টা বাজছে?"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-4-4-tte-1",
              bangla: "এখন পাঁচটা বাজে।",
              romanization: "ekhon panchta baje.",
              answer: "It is five o'clock now.",
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-4-4-ttb-1",
              english: "It is ten o'clock.",
              answer: "দশটা বাজে।",
              romanization: "doshta baje.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-4-4-mc-2",
              prompt: "'তিনটা বাজে' means:",
              options: ["three minutes", "three o'clock", "three days", "thirty"],
              correct: 1,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "bar-4-4-fb-1",
              sentence: "এখন ___ টা বাজে।",
              romanization: "ekhon ___ ta baje.",
              blank: "সাত",
              options: ["ছয়", "সাত", "আট", "নয়"],
              xp: 5,
            },
          ],
        },
        {
          id: "bar-4-5",
          title: "How Many? Shopping",
          description: "Use কত and কয়টা for shopping in Barisali",
          unit: 4,
          order: 5,
          xpReward: 10,
          exercises: [
            {
              type: "fill_blank",
              id: "bar-4-5-fb-1",
              sentence: "এই আমের ___ কত?",
              romanization: "ei amer ___ koto?",
              blank: "দাম",
              options: ["দাম", "টাকা", "সংখ্যা", "নাম"],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-4-5-tte-1",
              bangla: "কয়টা কলা লাগবে?",
              romanization: "koyta kola lagbe?",
              answer: "How many bananas do you need?",
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-4-5-ttb-1",
              english: "How much does this cost?",
              answer: "এইটার দাম কত?",
              romanization: "eitar dam koto?",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-4-5-fb-2",
              sentence: "আমার বিশ ___ আছে।",
              romanization: "amar bish ___ ache.",
              blank: "টাকা",
              options: ["টাকা", "ঘণ্টা", "দিন", "মাস"],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-4-5-mc-1",
              prompt: "To ask 'How many people?' in Barisali you say:",
              options: ["কত মানুষ?", "কয়টা মানুষ?", "কত জন?", "কয়জন?"],
              correct: 3,
              xp: 4,
            },
          ],
        },
        {
          id: "bar-4-6",
          title: "Numbers Quiz",
          description: "Numbers & Counting quiz — Barisali Unit 4",
          unit: 4,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-4-6-mc-1",
              prompt: "What is 'চৌদ্দ' in English?",
              options: ["thirteen", "fourteen", "fifteen", "sixteen"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-4-6-tte-1",
              bangla: "দোকানে একশো টাকার জিনিস আছে।",
              romanization: "dokane ekshо takar jinish ache.",
              answer: "There are hundred-taka items in the shop.",
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-4-6-ttb-1",
              english: "What time is it?",
              answer: "কটা বাজে?",
              romanization: "kota baje?",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-4-6-fb-1",
              sentence: "আমার কাছে ___ টাকা আছে।",
              romanization: "amar kache ___ taka ache.",
              blank: "পঞ্চাশ",
              options: ["চল্লিশ", "পঞ্চাশ", "বিশ", "ত্রিশ"],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-4-6-mc-2",
              prompt: "Barisali classifier for counting objects is:",
              options: ["-জন", "-টা", "-বার", "-দিন"],
              correct: 1,
              xp: 4,
            },
          ],
        },
      ],
    },
    {
      id: "bar-unit-5",
      title: "Getting Around",
      description: "Transport and directions in the Barisali delta",
      order: 5,
      prep: {
        characters: [],
        grammar: [
          {
            title: "Direction words in Barisali",
            rule: "Directions work the same as standard Bengali. হাতের বামে = to the left. হাতের ডানে = to the right. সামনে = ahead. পিছনে = behind.",
            examples: [
              { bangla: "বাম দিকে যাও।", romanization: "bam dike jao.", english: "Go left." },
              { bangla: "সামনে যাও।", romanization: "shamne jao.", english: "Go ahead." },
            ],
          },
          {
            title: "Barisali river transport",
            rule: "Barisali is delta country — নৌকা (boat) and লঞ্চ (launch/ferry) are central to life. লঞ্চে যামু = I will go by ferry (Barisali future -মু).",
            examples: [
              { bangla: "লঞ্চে যামু।", romanization: "launch-e jamu.", english: "I will go by ferry." },
              { bangla: "নৌকায় যাই।", romanization: "noukay jai.", english: "I go by boat." },
            ],
          },
          {
            title: "Asking distance — কতদূর?",
            rule: "কতদূর? = how far? হাঁটা দূরত্ব = walking distance. The structure is identical to standard Bengali.",
            examples: [
              { bangla: "ঘাট কতদূর?", romanization: "ghat kotodur?", english: "How far is the ferry terminal?" },
              { bangla: "কাছেই আছে।", romanization: "kachei ache.", english: "It's nearby." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "bar-5-1",
          title: "River Transport",
          description: "Boats, ferries, and the waterways of Barisali",
          unit: 5,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-5-1-mp-1",
              pairs: [
                { bangla: "নৌকা",  english: "boat",  romanization: "nouka"  },
                { bangla: "লঞ্চ",  english: "ferry", romanization: "launch" },
                { bangla: "ঘাট",   english: "dock",  romanization: "ghat"   },
                { bangla: "নদী",   english: "river", romanization: "nodi"   },
              ],
              xp: 8,
            },
            {
              type: "translate_to_english",
              id: "bar-5-1-tte-1",
              bangla: "লঞ্চে যামু।",
              romanization: "launch-e jamu.",
              answer: "I will go by ferry.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-5-1-mc-1",
              prompt: "Which transport is most important in Barisali's delta region?",
              options: ["ট্রেন", "রিকশা", "নৌকা", "বাইক"],
              correct: 2,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "bar-5-1-fb-1",
              sentence: "নৌকায় ___ পার হই।",
              romanization: "noukay ___ par hoi.",
              blank: "নদী",
              options: ["বাজার", "নদী", "ঘাট", "রাস্তা"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-5-1-ttb-1",
              english: "The ferry terminal is nearby.",
              answer: "ঘাট কাছেই আছে।",
              romanization: "ghat kachei ache.",
              xp: 6,
            },
          ],
        },
        {
          id: "bar-5-2",
          title: "Directions",
          description: "Left, right, and straight — navigate Barisali",
          unit: 5,
          order: 2,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-5-2-tte-1",
              bangla: "ডান দিকে যাও।",
              romanization: "dan dike jao.",
              answer: "Go right.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-5-2-mc-1",
              prompt: "What does 'সামনে' mean?",
              options: ["behind", "left", "right", "ahead"],
              correct: 3,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "bar-5-2-mp-1",
              pairs: [
                { bangla: "বাম",     english: "left",   romanization: "bam"    },
                { bangla: "ডান",     english: "right",  romanization: "dan"    },
                { bangla: "সামনে",  english: "ahead",  romanization: "shamne" },
                { bangla: "পিছনে",  english: "behind", romanization: "pichone"},
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "bar-5-2-fb-1",
              sentence: "বাজার ___ দিকে।",
              romanization: "bazar ___ dike.",
              blank: "বাম",
              options: ["ডান", "বাম", "সামনে", "পিছনে"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-5-2-ttb-1",
              english: "Go straight ahead.",
              answer: "সোজা সামনে যাও।",
              romanization: "shoja shamne jao.",
              xp: 6,
            },
          ],
        },
        {
          id: "bar-5-3",
          title: "How Far?",
          description: "Ask about distance in Barisali",
          unit: 5,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-5-3-mc-1",
              prompt: "How do you ask 'how far?' in Bengali?",
              options: ["কতদূর?", "কতক্ষণ?", "কতো দাম?", "কোথায়?"],
              correct: 0,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-5-3-tte-1",
              bangla: "ঘাট কতদূর?",
              romanization: "ghat kotodur?",
              answer: "How far is the dock?",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-5-3-fb-1",
              sentence: "বাজার ___ আছে।",
              romanization: "bazar ___ ache.",
              blank: "কাছেই",
              options: ["দূরে", "কাছেই", "সামনে", "পিছনে"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-5-3-ttb-1",
              english: "The hospital is far.",
              answer: "হাসপাতাল অনেক দূরে।",
              romanization: "hashpatal onek dure.",
              xp: 6,
            },
            {
              type: "multiple_choice",
              id: "bar-5-3-mc-2",
              prompt: "What does 'কাছেই আছে' mean?",
              options: ["It is far", "It is very expensive", "It is nearby", "It is to the left"],
              correct: 2,
              xp: 4,
            },
          ],
        },
        {
          id: "bar-5-4",
          title: "Buying Tickets",
          description: "Get on the ferry and buy your passage",
          unit: 5,
          order: 4,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-5-4-tte-1",
              bangla: "একটা টিকেট দেন।",
              romanization: "ekta tiket den.",
              answer: "Give me one ticket.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-5-4-mc-1",
              prompt: "How do you ask 'when does the ferry leave?'",
              options: ["লঞ্চ কতদূর?", "লঞ্চ কখন ছাড়ে?", "লঞ্চ কয়টা?", "লঞ্চ কোথায়?"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "bar-5-4-mp-1",
              pairs: [
                { bangla: "টিকেট",    english: "ticket",    romanization: "tiket"    },
                { bangla: "ঘাট",      english: "dock",      romanization: "ghat"     },
                { bangla: "ছাড়া",    english: "to leave",  romanization: "chara"    },
                { bangla: "পৌঁছানো", english: "to arrive", romanization: "pouchano" },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "bar-5-4-fb-1",
              sentence: "দুইটা টিকেট ___ দাম?",
              romanization: "duita tiket ___ dam?",
              blank: "কতো",
              options: ["কই", "কতো", "কখন", "কোথায়"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-5-4-ttb-1",
              english: "When does the boat arrive?",
              answer: "নৌকা কখন পৌঁছাবে?",
              romanization: "nouka kokhon pouchabe?",
              xp: 7,
            },
          ],
        },
        {
          id: "bar-5-5",
          title: "Transport Review",
          description: "Review all Barisali transport and direction vocabulary",
          unit: 5,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-5-5-tte-1",
              bangla: "আমি লঞ্চে ঘাটে যামু।",
              romanization: "ami launch-e ghate jamu.",
              answer: "I will go to the dock by ferry.",
              xp: 7,
            },
            {
              type: "multiple_choice",
              id: "bar-5-5-mc-1",
              prompt: "You need to go left. What do you say?",
              options: ["ডান দিকে যাও।", "সামনে যাও।", "বাম দিকে যাও।", "পিছনে যাও।"],
              correct: 2,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "bar-5-5-fb-1",
              sentence: "ঘাট ___ দূরে।",
              romanization: "ghat ___ dure.",
              blank: "অনেক",
              options: ["কাছে", "অনেক", "কম", "সামনে"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-5-5-mp-1",
              pairs: [
                { bangla: "কতদূর?",     english: "how far?",             romanization: "kotodur?"      },
                { bangla: "লঞ্চে যামু", english: "I will go by ferry",   romanization: "launch-e jamu" },
                { bangla: "ঘাট",        english: "dock / terminal",      romanization: "ghat"          },
                { bangla: "কাছেই",      english: "nearby",               romanization: "kachei"        },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "bar-5-5-ttb-1",
              english: "The market is ahead.",
              answer: "বাজার সামনে।",
              romanization: "bazar shamne.",
              xp: 6,
            },
          ],
        },
      ],
    },
    {
      id: "bar-unit-6",
      title: "Health & Body",
      description: "Body parts, illness, and medicine in the Barisali dialect",
      order: 6,
      prep: {
        characters: [],
        grammar: [
          {
            title: "Expressing pain — Barisali style",
            rule: "ব্যথা করতাছে (Barisali progressive: -তাছে) means 'is hurting'. Example: মাথা ব্যথা করতাছে = My head is hurting.",
            examples: [
              { bangla: "পেট ব্যথা করতাছে।", romanization: "pet betha kortache.", english: "My stomach is hurting." },
              { bangla: "হাত ব্যথা করতাছে।", romanization: "hat betha kortache.", english: "My hand is hurting." },
            ],
          },
          {
            title: "Feeling unwell in Barisali",
            rule: "আমি অসুস্থ (I am unwell). জ্বর আইছে = I have a fever (আইছে = Barisali 'has come'). ঠান্ডা লাগতাছে = I feel cold.",
            examples: [
              { bangla: "আমি অসুস্থ।", romanization: "ami oshustho.", english: "I am unwell." },
              { bangla: "জ্বর আইছে।", romanization: "jor aiche.", english: "I have a fever." },
            ],
          },
          {
            title: "Medicine and care",
            rule: "ওষুধ খাও = take medicine. ডাক্তার দেখাতে হইব = I need to see a doctor (Barisali: হইব = will be/must).",
            examples: [
              { bangla: "ডাক্তার দেখাতে হইব।", romanization: "daktar dekhate hoibo.", english: "I need to see a doctor." },
              { bangla: "ওষুধ খাও।", romanization: "oshud khao.", english: "Take the medicine." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "bar-6-1",
          title: "Body Parts",
          description: "Head to toe in Barisali Bengali",
          unit: 6,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-6-1-mp-1",
              pairs: [
                { bangla: "মাথা",  english: "head",    romanization: "matha" },
                { bangla: "হাত",   english: "hand",    romanization: "hat"   },
                { bangla: "পা",    english: "foot",    romanization: "pa"    },
                { bangla: "চোখ",   english: "eye",     romanization: "chokh" },
                { bangla: "পেট",   english: "stomach", romanization: "pet"   },
              ],
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "bar-6-1-mc-1",
              prompt: "What does 'কান' mean?",
              options: ["eye", "nose", "ear", "mouth"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-6-1-tte-1",
              bangla: "নাক আর মুখ।",
              romanization: "nak ar mukh.",
              answer: "Nose and mouth.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-6-1-fb-1",
              sentence: "___ দিয়া দেখি।",
              romanization: "___ diya dekhi.",
              blank: "চোখ",
              options: ["কান", "নাক", "চোখ", "মুখ"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-6-1-ttb-1",
              english: "My back is hurting. (Barisali)",
              answer: "পিঠ ব্যথা করতাছে।",
              romanization: "pith betha kortache.",
              xp: 6,
            },
          ],
        },
        {
          id: "bar-6-2",
          title: "Feeling Unwell",
          description: "Describe symptoms using Barisali progressives",
          unit: 6,
          order: 2,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-6-2-tte-1",
              bangla: "আমি অসুস্থ।",
              romanization: "ami oshustho.",
              answer: "I am unwell.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-6-2-mc-1",
              prompt: "The Barisali way to say 'I have a fever' is:",
              options: ["জ্বর আসছে।", "জ্বর আইছে।", "জ্বর হবে।", "জ্বর করি।"],
              correct: 1,
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-6-2-mp-1",
              pairs: [
                { bangla: "জ্বর",      english: "fever",   romanization: "jor"      },
                { bangla: "ব্যথা",     english: "pain",    romanization: "betha"    },
                { bangla: "ঠান্ডা",   english: "cold",    romanization: "thanda"   },
                { bangla: "অসুস্থ",   english: "unwell",  romanization: "oshustho" },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "bar-6-2-fb-1",
              sentence: "মাথা ব্যথা ___ ।",
              romanization: "matha betha ___ .",
              blank: "করতাছে",
              options: ["আইছে", "করতাছে", "হইব", "যাইব"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-6-2-ttb-1",
              english: "I feel cold. (Barisali progressive)",
              answer: "ঠান্ডা লাগতাছে।",
              romanization: "thanda lagtache.",
              xp: 6,
            },
          ],
        },
        {
          id: "bar-6-3",
          title: "At the Doctor",
          description: "Visit the doctor in Barisali Bengali",
          unit: 6,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-6-3-mc-1",
              prompt: "What does 'হাসপাতাল' mean?",
              options: ["clinic", "doctor", "hospital", "pharmacy"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "bar-6-3-tte-1",
              bangla: "ডাক্তার দেখাতে হইব।",
              romanization: "daktar dekhate hoibo.",
              answer: "I need to see a doctor.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-6-3-mp-1",
              pairs: [
                { bangla: "ডাক্তার",   english: "doctor",   romanization: "daktar"    },
                { bangla: "হাসপাতাল", english: "hospital", romanization: "hashpatal" },
                { bangla: "ওষুধ",      english: "medicine", romanization: "oshud"     },
                { bangla: "নার্স",     english: "nurse",    romanization: "nars"      },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "bar-6-3-fb-1",
              sentence: "ডাক্তারের কাছে ___ হইব।",
              romanization: "daktarer kache ___ hoibo.",
              blank: "যাইতে",
              options: ["আসতে", "যাইতে", "থাকতে", "খাইতে"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "bar-6-3-ttb-1",
              english: "Take the medicine.",
              answer: "ওষুধ খাও।",
              romanization: "oshud khao.",
              xp: 6,
            },
          ],
        },
        {
          id: "bar-6-4",
          title: "Medicine & Care",
          description: "Pharmacy visits and dosage in Barisali",
          unit: 6,
          order: 4,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-6-4-tte-1",
              bangla: "দিনে তিনবার ওষুধ খাও।",
              romanization: "dine tinbar oshud khao.",
              answer: "Take medicine three times a day.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-6-4-mc-1",
              prompt: "A pharmacist says 'খাওয়ার পরে খাইবেন' — when should you take it?",
              options: ["Before eating", "After eating", "On an empty stomach", "Before sleeping"],
              correct: 1,
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-6-4-fb-1",
              sentence: "দুইটা ট্যাবলেট ___ পরে খাও।",
              romanization: "duita tablet ___ pore khao.",
              blank: "খাওয়ার",
              options: ["ঘুমের", "খাওয়ার", "হাঁটার", "কাজের"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-6-4-mp-1",
              pairs: [
                { bangla: "ফার্মেসি",    english: "pharmacy",     romanization: "pharmeshi"   },
                { bangla: "ট্যাবলেট",   english: "tablet",       romanization: "tablet"      },
                { bangla: "দিনে",       english: "per day",      romanization: "dine"        },
                { bangla: "খাওয়ার পরে", english: "after eating", romanization: "khawar pore" },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "bar-6-4-ttb-1",
              english: "Give me two tablets.",
              answer: "দুইটা ট্যাবলেট দেন।",
              romanization: "duita tablet den.",
              xp: 6,
            },
          ],
        },
        {
          id: "bar-6-5",
          title: "Health Review",
          description: "Final review of health and body in Barisali",
          unit: 6,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-6-5-tte-1",
              bangla: "পেট ব্যথা করতাছে, ডাক্তারের কাছে যাইতে হইব।",
              romanization: "pet betha kortache, daktarer kache jaite hoibo.",
              answer: "My stomach is hurting, I need to go to the doctor.",
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "bar-6-5-mc-1",
              prompt: "The Barisali progressive suffix for 'is happening' is:",
              options: ["-ছে", "-তাছে", "-মু", "-ইছি"],
              correct: 1,
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "bar-6-5-fb-1",
              sentence: "আমি ___ আছি।",
              romanization: "ami ___ achi.",
              blank: "অসুস্থ",
              options: ["ভালো", "অসুস্থ", "সুস্থ", "খুশি"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "bar-6-5-mp-1",
              pairs: [
                { bangla: "মাথা ব্যথা",  english: "headache",               romanization: "matha betha" },
                { bangla: "জ্বর আইছে",   english: "have a fever (Barisali)", romanization: "jor aiche"   },
                { bangla: "ওষুধ",        english: "medicine",               romanization: "oshud"       },
                { bangla: "হাসপাতাল",   english: "hospital",               romanization: "hashpatal"   },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "bar-6-5-ttb-1",
              english: "My hand is hurting. (Barisali)",
              answer: "হাত ব্যথা করতাছে।",
              romanization: "hat betha kortache.",
              xp: 7,
            },
          ],
        },
      ],
    },
  ],
};
