import type { DialectCurriculum } from "@bangla-learn/types";

export const barisaliCurriculum: DialectCurriculum = {
  dialect: "barisali",
  units: [
    {
      id: "bar-unit-1",
      title: "Barisali Basics",
      description: "Learn Barisali — the dialect of Barisal Division, known for its musical rhythm",
      order: 1,
      color: "#FF4B4B",
      prep: {
        characters: [
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আইলা (came)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইলিশ (hilsa)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠা (to rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এহন (now)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওখানে (there)" },
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কই (where)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খাওয়া (eating)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলা (went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পানি (water)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বাপ (father)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালাই (quite well)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মায় (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাত (night)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হেই (he/she)" },
          { symbol: "চ", romanization: "ch",  type: "consonant" as const, exampleWord: "চাইর (four)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তারা (they)" },
          { symbol: "য", romanization: "j/y", type: "consonant" as const, exampleWord: "যাওয়া (to go)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সকাল (morning)" },
        ],
        flashcards: [
          { id: "fc-bar-1",  bangla: "হেই",         romanization: "Hei",        english: "He / She (Barisali)",       category: "pronouns"  },
          { id: "fc-bar-2",  bangla: "তাগো",        romanization: "Tago",       english: "Their / Them (Barisali)",   category: "pronouns"  },
          { id: "fc-bar-3",  bangla: "বাপ",         romanization: "Bap",        english: "Father (Barisali)",         category: "family"    },
          { id: "fc-bar-4",  bangla: "মায়",         romanization: "May",        english: "Mother (Barisali)",         category: "family"    },
          { id: "fc-bar-5",  bangla: "কই",          romanization: "Koi",        english: "Where (Barisali)",          category: "phrases"   },
          { id: "fc-bar-6",  bangla: "কেমুন",       romanization: "Kemun",      english: "How (Barisali for কেমন)",  category: "phrases"   },
          { id: "fc-bar-7",  bangla: "এহন",         romanization: "Ehon",       english: "Now (Barisali)",            category: "phrases"   },
          { id: "fc-bar-8",  bangla: "গেলা",        romanization: "Gela",       english: "Went (past tense)",         category: "verbs"     },
          { id: "fc-bar-9",  bangla: "আইলা",        romanization: "Aila",       english: "Came (past tense)",         category: "verbs"     },
          { id: "fc-bar-10", bangla: "ভালাই আছি",  romanization: "Bhalai achi",english: "I am quite fine",           category: "greetings" },
          { id: "fc-bar-11", bangla: "কই যাও?",    romanization: "Koi jao?",   english: "Where are you going?",      category: "greetings" },
          { id: "fc-bar-12", bangla: "কেমুন আছ?",  romanization: "Kemun ach?", english: "How are you?",              category: "greetings" },
          { id: "fc-bar-13", bangla: "চাইর",        romanization: "Chair",      english: "Four (Barisali for চার)",  category: "numbers"   },
          { id: "fc-bar-14", bangla: "জাই",         romanization: "Jai",        english: "Let's go",                  category: "phrases"   },
          { id: "fc-bar-15", bangla: "হের",         romanization: "Her",        english: "His / Her (Barisali)",      category: "pronouns"  },
        ],
        grammar: [
          {
            title: "Barisali Pronouns — হেই, তাগো",
            explanation: "Barisali uses 'হেই' (Hei) for he/she instead of Standard Bengali's 'সে'. The plural 'their/them' is 'তাগো' (Tago) instead of 'তাদের'.",
            examples: [
              { bangla: "হেই আসছে।",    romanization: "Hei ashche.",  english: "He/she has come." },
              { bangla: "তাগো বাড়ি।", romanization: "Tago bari.",    english: "Their home." },
            ],
          },
          {
            title: "Where & How — কই, কেমুন",
            explanation: "Barisali replaces 'কোথায়' (where) with 'কই' (Koi) and 'কেমন' (how) becomes 'কেমুন' (Kemun). These short words give Barisali its musical quality.",
            examples: [
              { bangla: "কই যাও?",    romanization: "Koi jao?",    english: "Where are you going?" },
              { bangla: "কেমুন আছ?", romanization: "Kemun ach?",  english: "How are you?" },
            ],
          },
          {
            title: "Musical Rhythm of Barisali",
            explanation: "Barisali is famous for its sing-song rhythm and drawn-out vowels. Words like 'ভালাই' add an extra '-ই' suffix for emphasis, a pattern unique to this dialect.",
            examples: [
              { bangla: "ভালাই আছি।",  romanization: "Bhalai achi.",  english: "I am quite well." },
              { bangla: "এহন যাই।",    romanization: "Ehon jai.",      english: "I'm going now." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "bar-1-0",
          title: "Write the Letters",
          description: "Trace Bengali vowels and consonants used in Barisali",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "bar-1-0-tr-1", character: "অ", romanization: "o/a", exampleWord: "অনেক — many", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-2", character: "আ", romanization: "aa", exampleWord: "আম — mango", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-3", character: "ক", romanization: "k", exampleWord: "কলা — banana", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-4", character: "ন", romanization: "n", exampleWord: "নাম — name", xp: 4 },
            { type: "letter_trace", id: "bar-1-0-tr-5", character: "ম", romanization: "m", exampleWord: "মা — mother", xp: 4 },
          ],
        },
        {
          id: "bar-1-1",
          title: "Barisali Greetings",
          description: "How Barisali speakers greet each other",
          unit: 1,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "multiple_choice",
              id: "bar-1-1-mc-1",
              prompt: "In Barisali, 'কেমুন আছ?' means:",
              options: ["Where are you going?", "How are you?", "What is your name?", "Did you eat?"],
              correct: 1,
              xp: 3,
            },
            {
              type: "translate_to_english",
              id: "bar-1-1-tte-1",
              bangla: "ভালাই আছি",
              romanization: "Bhalai achi",
              answer: "I am quite fine (Barisali)",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "bar-1-1-mc-2",
              prompt: "Barisali dialect is spoken mainly in which region?",
              options: ["Sylhet", "Chittagong", "Barisal Division", "Dhaka"],
              correct: 2,
              xp: 2,
            },
          ],
        },
        {
          id: "bar-1-2",
          title: "Barisali Pronouns",
          description: "Pronouns in Barisali differ slightly from Standard Bengali",
          unit: 1,
          order: 2,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-2-mp-1",
              pairs: [
                { bangla: "আমি (Ami)", english: "I", romanization: "Ami" },
                { bangla: "তুমি (Tumi)", english: "You (informal)", romanization: "Tumi" },
                { bangla: "হেই (Hei)", english: "He/She (Barisali)", romanization: "Hei" },
                { bangla: "আমরা (Amra)", english: "We", romanization: "Amra" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-1-2-mc-1",
              prompt: "In Barisali, 'হেই' refers to:",
              options: ["I", "You", "He or She", "We"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-3",
          title: "Numbers in Barisali",
          description: "Numbers in Barisali — mostly the same with some pronunciation differences",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-3-mp-1",
              pairs: [
                { bangla: "এক (Ek)", english: "One", romanization: "Ek" },
                { bangla: "দুই (Dui)", english: "Two", romanization: "Dui" },
                { bangla: "তিন (Tin)", english: "Three", romanization: "Tin" },
                { bangla: "চাইর (Chair)", english: "Four (Barisali)", romanization: "Chair" },
                { bangla: "পাঁচ (Panch)", english: "Five", romanization: "Panch" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "bar-1-3-mc-1",
              prompt: "In Barisali, 'চাইর' means the same as Standard Bengali:",
              options: ["তিন (Three)", "চার (Four)", "পাঁচ (Five)", "ছয় (Six)"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-4",
          title: "Barisali Family Words",
          description: "How Barisali speakers refer to family",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "bar-1-4-mp-1",
              pairs: [
                { bangla: "মা", english: "Mother", romanization: "Ma" },
                { bangla: "বাপ", english: "Father (Barisali)", romanization: "Bap" },
                { bangla: "দাদা", english: "Older brother / Grandfather", romanization: "Dada" },
                { bangla: "দিদি", english: "Older sister", romanization: "Didi" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "bar-1-4-tte-1",
              bangla: "বাপ",
              romanization: "Bap",
              answer: "Father (informal Barisali term)",
              xp: 3,
            },
          ],
        },
        {
          id: "bar-1-5",
          title: "Common Barisali Phrases",
          description: "Key phrases you will hear in Barisal",
          isQuiz: true,
          unit: 1,
          order: 5,
          xpReward: 20,
          exercises: [
            {
              type: "translate_to_english",
              id: "bar-1-5-tte-1",
              bangla: "কই যাও?",
              romanization: "Koi jao?",
              answer: "Where are you going? (Barisali)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "bar-1-5-mc-1",
              prompt: "In Barisali, 'কই' means:",
              options: ["What", "When", "Who", "Where"],
              correct: 3,
              xp: 3,
            },
            {
              type: "fill_blank",
              id: "bar-1-5-fb-1",
              sentence: "আমি বাড়ি ___ যাই।",
              blank: "তে",
              romanization: "Ami bari ___ jai. (I am going home.)",
              options: ["তে", "কে", "র", "য়"],
              xp: 3,
            },
          ],
        },
      ],
    },
  ],
};
