import type { DialectCurriculum } from "@bangla-learn/types";

export const chittagonianCurriculum: DialectCurriculum = {
  dialect: "chittagonian",
  units: [
    {
      id: "cgt-unit-1",
      title: "Chittagonian Basics",
      description: "Learn Chittagonian (চাটগাঁইয়া) — a distinct dialect of Chittagong Division",
      order: 1,
      color: "#CE82FF",
      lessons: [
        {
          id: "cgt-1-1",
          title: "Chittagonian Greetings",
          description: "Greetings unique to the Chittagong region",
          unit: 1,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "multiple_choice",
              id: "cgt-1-1-mc-1",
              prompt: "In Chittagonian, 'কেড্ডা আস?' means:",
              options: ["What is your name?", "How are you?", "Where are you going?", "Did you eat?"],
              correct: 1,
              xp: 3,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-1-tte-1",
              bangla: "ভালা আই",
              romanization: "Bhala ai",
              answer: "I am fine (Chittagonian)",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-1-mc-2",
              prompt: "Chittagonian is considered closest to which ancient language?",
              options: ["Sanskrit", "Pali", "Magadhi Prakrit", "Persian"],
              correct: 2,
              xp: 2,
            },
          ],
        },
        {
          id: "cgt-1-2",
          title: "Chittagonian Pronouns",
          description: "Pronouns are quite different in Chittagonian!",
          unit: 1,
          order: 2,
          xpReward: 12,
          exercises: [
            {
              type: "match_pairs",
              id: "cgt-1-2-mp-1",
              pairs: [
                { bangla: "আঁই (Ai)", english: "I (Chittagonian)", romanization: "Ai" },
                { bangla: "তুঁই (Tui)", english: "You (informal)", romanization: "Tui" },
                { bangla: "হে (He)", english: "He/She", romanization: "He" },
                { bangla: "আঁরা (Ara)", english: "We (Chittagonian)", romanization: "Ara" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-2-mc-1",
              prompt: "In Chittagonian, 'আঁই' means:",
              options: ["You", "I", "He", "We"],
              correct: 1,
              xp: 3,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-2-tte-1",
              bangla: "আঁই যাই",
              romanization: "Ai jai",
              answer: "I am going (Chittagonian)",
              xp: 4,
            },
          ],
        },
        {
          id: "cgt-1-3",
          title: "Numbers in Chittagonian",
          description: "Chittagonian numbers have some unique forms",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "cgt-1-3-mp-1",
              pairs: [
                { bangla: "এক (Ek)", english: "One", romanization: "Ek" },
                { bangla: "দুই (Dui)", english: "Two", romanization: "Dui" },
                { bangla: "তিন (Tin)", english: "Three", romanization: "Tin" },
                { bangla: "চাইর (Chair)", english: "Four", romanization: "Chair" },
                { bangla: "পাঁচ (Panch)", english: "Five", romanization: "Panch" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-3-mc-1",
              prompt: "In Chittagonian, 'আঁটা' means:",
              options: ["Seven", "Eight", "Nine", "Ten"],
              correct: 1,
              xp: 3,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-3-tte-1",
              bangla: "দশ",
              romanization: "Dosh",
              answer: "Ten (same as Standard Bengali)",
              xp: 2,
            },
          ],
        },
        {
          id: "cgt-1-4",
          title: "Chittagonian Family",
          description: "Family vocabulary in Chittagonian",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "cgt-1-4-mp-1",
              pairs: [
                { bangla: "মা (Ma)", english: "Mother", romanization: "Ma" },
                { bangla: "বাপ (Bap)", english: "Father", romanization: "Bap" },
                { bangla: "ভাই (Bhai)", english: "Brother", romanization: "Bhai" },
                { bangla: "বোইন (Boin)", english: "Sister (Chittagonian)", romanization: "Boin" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-4-mc-1",
              prompt: "The Chittagonian word for 'sister' is:",
              options: ["বোন", "আফা", "বোইন", "দিদি"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "cgt-1-5",
          title: "Common Chittagonian Phrases",
          description: "Everyday Chittagonian you will hear in Chittagong city",
          unit: 1,
          order: 5,
          xpReward: 20,
          exercises: [
            {
              type: "translate_to_english",
              id: "cgt-1-5-tte-1",
              bangla: "কিতা খাইলা?",
              romanization: "Kita khaila?",
              answer: "What did you eat? (shared with Sylheti)",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-5-tte-2",
              bangla: "গরম লাগে",
              romanization: "Gorom lage",
              answer: "It feels hot (common Chittagonian expression)",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-5-mc-1",
              prompt: "In Chittagonian, 'আঁই যাই' means:",
              options: ["I am eating", "I am going", "I am sleeping", "I am coming"],
              correct: 1,
              xp: 3,
            },
          ],
        },
      ],
    },
  ],
};
