import type { DialectCurriculum } from "@bangla-learn/types";

export const chittagonianCurriculum: DialectCurriculum = {
  dialect: "chittagonian",
  units: [
    {
      id: "cgt-unit-1",
      title: "Chittagonian Basics",
      description: "Learn Chittagonian (চাটগাঁইয়া) — a distinct dialect of Chittagong Division",
      order: 1,
      color: "#CE82FF",
      prep: {
        characters: [
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আঁই (I)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইলিশ (hilsa)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠুম (I will rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এক (one)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওহানে (there)" },
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কেড্ডা (how)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খাইয়ুম (I will eat)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলাম (I went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পানি (water)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বোইন (sister)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালা (good)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মা (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাইত (night)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হেইন (he/she)" },
          { symbol: "চ", romanization: "ch",  type: "consonant" as const, exampleWord: "চাটগাঁ (Chittagong)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তুঁই (you)" },
          { symbol: "য", romanization: "j/y", type: "consonant" as const, exampleWord: "যাইয়ুম (I will go)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সকাইল (morning)" },
        ],
        flashcards: [
          { id: "fc-cgt-1",  bangla: "আঁই",          romanization: "Ai",          english: "I (Chittagonian — not আমি!)", category: "pronouns"  },
          { id: "fc-cgt-2",  bangla: "তুঁই",          romanization: "Tui",         english: "You (informal)",              category: "pronouns"  },
          { id: "fc-cgt-3",  bangla: "হেইন",          romanization: "Hein",        english: "He / She / It",               category: "pronouns"  },
          { id: "fc-cgt-4",  bangla: "আঁরা",          romanization: "Ara",         english: "We (Chittagonian)",            category: "pronouns"  },
          { id: "fc-cgt-5",  bangla: "তুঁরা",          romanization: "Tura",        english: "You (plural)",                 category: "pronouns"  },
          { id: "fc-cgt-6",  bangla: "বোইন",          romanization: "Boin",        english: "Sister (Chittagonian)",        category: "family"    },
          { id: "fc-cgt-7",  bangla: "ভালা",          romanization: "Bhala",       english: "Good / Well",                  category: "adjectives"},
          { id: "fc-cgt-8",  bangla: "কেড্ডা",        romanization: "Kedda",       english: "How / What (Chittagonian)",    category: "phrases"   },
          { id: "fc-cgt-9",  bangla: "যাইয়ুম",       romanization: "Jaium",       english: "I will go",                    category: "verbs"     },
          { id: "fc-cgt-10", bangla: "আইয়ুম",        romanization: "Aium",        english: "I will come",                  category: "verbs"     },
          { id: "fc-cgt-11", bangla: "খাইয়ুম",       romanization: "Khaium",      english: "I will eat",                   category: "verbs"     },
          { id: "fc-cgt-12", bangla: "ফাইত্তা",       romanization: "Faitta",      english: "Morning (Chittagonian)",       category: "time"      },
          { id: "fc-cgt-13", bangla: "রাইত",          romanization: "Rait",        english: "Night",                        category: "time"      },
          { id: "fc-cgt-14", bangla: "আঁই যাই",       romanization: "Ai jai",      english: "I am going",                   category: "phrases"   },
          { id: "fc-cgt-15", bangla: "কেড্ডা আস?",   romanization: "Kedda as?",   english: "How are you?",                 category: "greetings" },
          { id: "fc-cgt-16", bangla: "ভালা আই",       romanization: "Bhala ai",    english: "I am fine",                    category: "greetings" },
        ],
        grammar: [
          {
            title: "Chittagonian Pronouns — আঁই, তুঁই",
            explanation: "The most striking feature of Chittagonian: 'I' is 'আঁই' (Ai) — not 'আমি'. 'You' (informal) is 'তুঁই' (Tui). 'We' is 'আঁরা' (Ara). This makes Chittagonian instantly recognisable.",
            examples: [
              { bangla: "আঁই বাড়ি যাই।",  romanization: "Ai bari jai.",    english: "I am going home." },
              { bangla: "তুঁই কি খাইলি?", romanization: "Tui ki khaili?", english: "Did you eat?" },
            ],
          },
          {
            title: "Future Tense — the -উম / -ইয়ুম ending",
            explanation: "Chittagonian forms the future tense by adding '-উম' or '-ইয়ুম' to the verb root. This is very different from Standard Bengali's '-ব' ending.",
            examples: [
              { bangla: "আঁই যাইয়ুম।",   romanization: "Ai jaium.",    english: "I will go." },
              { bangla: "আঁই খাইয়ুম।",   romanization: "Ai khaium.",   english: "I will eat." },
            ],
          },
          {
            title: "Arabic & Persian Influence",
            explanation: "Chittagong was a major sea port for centuries. Many Arabic and Persian words entered the dialect, especially around trade, time, and religion.",
            examples: [
              { bangla: "ফাইত্তা",  romanization: "Faitta", english: "Morning (from Arabic فجر Fajr)" },
              { bangla: "বোইন",     romanization: "Boin",   english: "Sister (older Arabic-influenced term)" },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "cgt-1-0",
          title: "Write the Letters",
          description: "Trace Bengali vowels and consonants used in Chittagonian",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "cgt-1-0-tr-1", character: "অ", romanization: "o/a", exampleWord: "অনেক — many", xp: 4 },
            { type: "letter_trace", id: "cgt-1-0-tr-2", character: "আ", romanization: "aa", exampleWord: "আম — mango", xp: 4 },
            { type: "letter_trace", id: "cgt-1-0-tr-3", character: "ক", romanization: "k", exampleWord: "কলা — banana", xp: 4 },
            { type: "letter_trace", id: "cgt-1-0-tr-4", character: "ন", romanization: "n", exampleWord: "নাম — name", xp: 4 },
            { type: "letter_trace", id: "cgt-1-0-tr-5", character: "ম", romanization: "m", exampleWord: "মা — mother", xp: 4 },
          ],
        },
        {
          id: "cgt-1-1",
          title: "Greetings",
          description: "Learn Chittagonian greetings — taught audio-first due to high divergence from Standard Bangla",
          unit: 1,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "cgt-1-1-mp-1",
              pairs: [
                { bangla: "আসসালামু আলাইকুম", english: "Hello (Islamic greeting)",     romanization: "assalamu alaikum" },
                { bangla: "ভাল / বাল",         english: "Good / Fine (Chittagonian)", romanization: "bhal / bala"       },
                { bangla: "নাম",               english: "Name",                        romanization: "nam"              },
                { bangla: "আঁই ভাল আছি।",     english: "I am fine. (Chittagonian I)", romanization: "ai bhal asi."     },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-1-tte-1",
              bangla: "তুঁই গইন অ?",
              romanization: "tui goin o?",
              answer: "How are you? (Chittagonian spoken form)",
              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "cgt-1-1-ttb-1",
              english: "I am fine. (Chittagonian — use আঁই)",
              answer: "আঁই ভাল আছি।",
              romanization: "ai bhal asi.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-1-mc-1",
              prompt: "In Chittagonian, 'আঁই' means:",
              options: ["You", "I", "He/She", "They"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "cgt-1-2",
          title: "Introductions",
          description: "Say who you are and ask someone's name in Chittagonian-style speech",
          unit: 1,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "cgt-1-2-tte-1",
              bangla: "আঁর নাম ___।",
              romanization: "ar nam ___.",
              answer: "My name is ___. (Chittagonian: আঁর for my)",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-2-tte-2",
              bangla: "আঁই বাংলা শিখতাসি।",
              romanization: "ai bangla shikhtasi.",
              answer: "I am learning Bangla. (Chittagonian form)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-2-mc-1",
              prompt: "In Chittagonian, 'আঁর' means:",
              options: ["your", "my", "his/her", "their"],
              correct: 1,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "cgt-1-2-fb-1",
              sentence: "তুঁয়ার নাম কী?",
              blank: "তুঁয়ার",
              romanization: "tuar nam ki?",
              options: ["তুঁয়ার", "আঁর", "নাম", "কী"],
              xp: 3,
            },
          ],
        },
        {
          id: "cgt-1-3",
          title: "Polite Words",
          description: "Use common polite replies in Chittagonian-style speech",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "cgt-1-3-mp-1",
              pairs: [
                { bangla: "ধন্যবাদ",           english: "Thank you",              romanization: "dhonnobad"     },
                { bangla: "মাফ গইরেন",         english: "Excuse me (Chittagonian)", romanization: "maf goiren"  },
                { bangla: "ঠিক আসে",           english: "Okay",                   romanization: "thik ase"      },
                { bangla: "সাহায্য গইরেন",     english: "Please help",            romanization: "shahajjo goiren" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-3-tte-1",
              bangla: "মাফ গইরেন।",
              romanization: "maf goiren.",
              answer: "Excuse me. (Chittagonian: গইরেন vs কইরেন in Sylheti)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-3-mc-1",
              prompt: "Chittagonian polite requests often use which ending?",
              options: ["-করুন", "-গইরেন", "-করবেন", "-করেন"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "cgt-1-4",
          title: "Yes / No / Basic Replies",
          description: "Give short replies in Chittagonian-style speech",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "cgt-1-4-mp-1",
              pairs: [
                { bangla: "অঁ / হ",       english: "Yes (Chittagonian nasal form)", romanization: "õ / ho"   },
                { bangla: "না",            english: "No",                             romanization: "na"       },
                { bangla: "অইত পারে",     english: "Maybe (Chittagonian)",           romanization: "oit pare" },
                { bangla: "পারুম / পারি", english: "Can (Chittagonian / Standard)",  romanization: "parum / pari" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "cgt-1-4-ttb-1",
              english: "Yes, I can. (Chittagonian)",
              answer: "হ, পারুম।",
              romanization: "ho, parum.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-4-mc-1",
              prompt: "The Chittagonian word 'পারুম' means:",
              options: ["I went", "I know", "I can", "I ate"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "cgt-1-5",
          title: "Pronouns",
          description: "Learn Chittagonian pronouns — very different from Standard Bangla!",
          unit: 1,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "cgt-1-5-mp-1",
              pairs: [
                { bangla: "আঁই",   english: "I (Chittagonian)",         romanization: "ai / ãi" },
                { bangla: "তুঁই",  english: "You (informal)",           romanization: "tui / tũi" },
                { bangla: "আপনে", english: "You (polite)",             romanization: "apne"      },
                { bangla: "হেই",   english: "He / She / That person",   romanization: "hei"       },
                { bangla: "আঁরা", english: "We (Chittagonian)",         romanization: "ara"       },
                { bangla: "হেরা", english: "They (Chittagonian)",       romanization: "hera"      },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-5-tte-1",
              bangla: "আপনে ভাল আসেন?",
              romanization: "apne bhal asen?",
              answer: "Are you well? (Chittagonian polite)",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-5-tte-2",
              bangla: "হেরা আইবো।",
              romanization: "hera aibo.",
              answer: "They will come. (Chittagonian: হেরা = they)",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-5-mc-1",
              prompt: "In Chittagonian, 'হেই' refers to:",
              options: ["I", "You", "He or She", "We"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "cgt-1-6",
          title: "Family",
          description: "Name close family members in Chittagonian — বাপ, বইন, পোলা, মাইয়া",
          unit: 1,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "cgt-1-6-mp-1",
              pairs: [
                { bangla: "মা",      english: "Mother",                  romanization: "ma"     },
                { bangla: "বাপ",     english: "Father (Chittagonian)",    romanization: "bap"    },
                { bangla: "ভাই",     english: "Brother",                  romanization: "bhai"   },
                { bangla: "বইন",     english: "Sister (Chittagonian)",    romanization: "boin"   },
                { bangla: "মাইয়া", english: "Daughter / Girl",          romanization: "maiya"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-6-tte-1",
              bangla: "এইডা আঁর মা।",
              romanization: "eida ar ma.",
              answer: "This is my mother. (Chittagonian: আঁর = my)",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "cgt-1-6-tte-2",
              bangla: "আঁর এক বইন আসে।",
              romanization: "ar ek boin ase.",
              answer: "I have one sister. (Chittagonian)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-6-mc-1",
              prompt: "The Chittagonian word for father is:",
              options: ["বাবা", "আব্বা", "বাপ", "ভাই"],
              correct: 2,
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "cgt-1-6-mc-2",
              prompt: "'পোলা' in Chittagonian means:",
              options: ["daughter", "son/boy", "brother", "friend"],
              correct: 1,
              xp: 3,
            },
          ],
        },
      ],
    },
  ],
};
