import type { DialectCurriculum } from "@bangla-learn/types";

export const khulnaCurriculum: DialectCurriculum = {
  dialect: "khulna",
  units: [
    {
      id: "khu-unit-1",
      title: "Khulna Bangla Basics",
      description: "Learn Khulna Bangla — the southwestern regional variety of Bangladesh",
      order: 1,
      color: "#059669",
      prep: {
        characters: [
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আমি (I)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইচ্ছা (wish)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠা (to rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এক (one)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওরা (they)" },
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কই (where)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খালা (aunt)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলাম (I went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালো (good)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মা (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাত (night)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তুমি (you)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পরিবার (family)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বাবা (father)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হ (yes)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সাহায্য (help)" },
          { symbol: "আপ", romanization: "ap", type: "consonant" as const, exampleWord: "আপনে (you, polite)" },
          { symbol: "ধ", romanization: "dh",  type: "consonant" as const, exampleWord: "ধন্যবাদ (thank you)" },
        ],
        flashcards: [
          { id: "fc-khu-1",  bangla: "আমি",          romanization: "ami",       english: "I",                            category: "pronouns"  },
          { id: "fc-khu-2",  bangla: "তুমি",          romanization: "tumi",      english: "You (familiar)",               category: "pronouns"  },
          { id: "fc-khu-3",  bangla: "আপনে",          romanization: "apne",      english: "You (polite, Khulna form)",    category: "pronouns"  },
          { id: "fc-khu-4",  bangla: "ও",              romanization: "o",         english: "He / She",                     category: "pronouns"  },
          { id: "fc-khu-5",  bangla: "আমরা",          romanization: "amra",      english: "We",                           category: "pronouns"  },
          { id: "fc-khu-6",  bangla: "ওরা",            romanization: "ora",       english: "They",                         category: "pronouns"  },
          { id: "fc-khu-7",  bangla: "ভালো",          romanization: "bhalo",     english: "Good / Fine",                  category: "adjectives"},
          { id: "fc-khu-8",  bangla: "হ",              romanization: "ho",        english: "Yes (Khulna spoken form)",     category: "phrases"   },
          { id: "fc-khu-9",  bangla: "না",              romanization: "na",        english: "No",                           category: "phrases"   },
          { id: "fc-khu-10", bangla: "ঠিক আসে",       romanization: "thik ase",  english: "Okay (Khulna form)",           category: "phrases"   },
          { id: "fc-khu-11", bangla: "হতে পারে",      romanization: "hote pare", english: "Maybe",                        category: "phrases"   },
          { id: "fc-khu-12", bangla: "বাবা / বাপ",    romanization: "baba / bap",english: "Father (both forms used)",     category: "family"    },
          { id: "fc-khu-13", bangla: "বইন / বোন",     romanization: "boin / bon",english: "Sister (both forms used)",     category: "family"    },
          { id: "fc-khu-14", bangla: "পোলা / ছেলে",  romanization: "pola / chele", english: "Son / Boy (both forms)",    category: "family"    },
          { id: "fc-khu-15", bangla: "মাইয়া / মেয়ে", romanization: "maiya / meye", english: "Daughter / Girl (both)",   category: "family"    },
          { id: "fc-khu-16", bangla: "শিখতেছি",       romanization: "shikhtesi", english: "Am learning (Khulna form)",   category: "phrases"   },
        ],
        grammar: [
          {
            title: "Khulna's paired forms",
            explanation: "Khulna Bangla teaches standard/regional pairs side by side. For example, বাবা/বাপ (father) or বোন/বইন (sister). Both forms are accepted, so learners hear both in everyday speech.",
            examples: [
              { bangla: "বাবা / বাপ",  romanization: "baba / bap",  english: "Father — both forms are used in Khulna" },
              { bangla: "বইন / বোন",   romanization: "boin / bon",   english: "Sister — regional/standard pair" },
            ],
          },
          {
            title: "Progressive: -তেছি / -তাছি",
            explanation: "In Khulna Bangla the progressive -ছি ending often appears as -তেছি or -তাছি. E.g. শিখতেছি = am learning; আইতেছি = am coming.",
            examples: [
              { bangla: "আমি আইতেছি।",       romanization: "ami aitesi.",       english: "I am coming." },
              { bangla: "আমি বাংলা শিখতেছি।", romanization: "ami bangla shikhtesi.", english: "I am learning Bangla." },
            ],
          },
          {
            title: "Polite 'you' — আপনে",
            explanation: "Khulna spoken Bangla favors আপনে (apne) as the polite form of 'you', alongside standard আপনি.",
            examples: [
              { bangla: "আপনে কেমন আছেন?", romanization: "apne kemon asen?", english: "How are you? (polite)" },
              { bangla: "ও আমার বন্ধু।",   romanization: "o amar bondhu.",   english: "He/She is my friend." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "khu-1-0",
          title: "Write the Letters",
          description: "Trace key letters used in Khulna Bangla",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "khu-1-0-tr-1", character: "আ", romanization: "aa",  exampleWord: "আমি — I",         xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-2", character: "ন", romanization: "n",   exampleWord: "নাম — name",      xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-3", character: "ম", romanization: "m",   exampleWord: "মা — mother",     xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-4", character: "ত", romanization: "t",   exampleWord: "তুমি — you",      xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-5", character: "ভ", romanization: "bh",  exampleWord: "ভালো — good",    xp: 4 },
          ],
        },
        {
          id: "khu-1-1",
          title: "Greetings",
          description: "Greet and exchange names in Khulna Bangla",
          unit: 1,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-1-mp-1",
              pairs: [
                { bangla: "আসসালামু আলাইকুম", english: "Hello (Islamic greeting)", romanization: "assalamu alaikum" },
                { bangla: "নমস্কার",            english: "Hello / Greetings",        romanization: "nomoshkar"        },
                { bangla: "ভালো",              english: "Good / Fine",              romanization: "bhalo"            },
                { bangla: "আমার নাম ___।",     english: "My name is ___.",          romanization: "amar nam ___."    },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-1-tte-1",
              bangla: "তুমি কেমন আছো?",
              romanization: "tumi kemon acho?",
              answer: "How are you?",
              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "khu-1-1-ttb-1",
              english: "I am fine.",
              answer: "আমি ভালো আছি।",
              romanization: "ami bhalo achi.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "khu-1-1-mc-1",
              prompt: "In Khulna Bangla, which is a common greeting?",
              options: [
                "ভালা আসেন? (Sylheti)",
                "তোমার নাম কী? (What is your name?)",
                "আমি ভালো আছি। (I am fine.)",
                "কিতা? (Chittagonian)",
              ],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-2",
          title: "Introductions",
          description: "Introduce yourself in Khulna Bangla using regional speech patterns",
          unit: 1,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-1-2-tte-1",
              bangla: "আমার নাম ___।",
              romanization: "amar nam ___.",
              answer: "My name is ___.",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-1-2-tte-2",
              bangla: "আমি বাংলা শিখতেছি।",
              romanization: "ami bangla shikhtesi.",
              answer: "I am learning Bangla. (Khulna form)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-2-mc-1",
              prompt: "'শিখতেছি' is a Khulna form meaning:",
              options: ["am eating", "am learning", "am going", "am sleeping"],
              correct: 1,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "khu-1-2-fb-1",
              sentence: "আমি ___ থেকে আইছি।",
              blank: "খুলনা",
              romanization: "ami ___ theke aisi.",
              options: ["খুলনা", "নাম", "আমার", "ভালো"],
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-3",
          title: "Polite Words",
          description: "Use polite expressions in Khulna Bangla",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-3-mp-1",
              pairs: [
                { bangla: "ধন্যবাদ",     english: "Thank you",  romanization: "dhonnobad"       },
                { bangla: "দয়া করে",    english: "Please",     romanization: "doya kore"       },
                { bangla: "মাফ করেন",   english: "Excuse me",  romanization: "maf koren"       },
                { bangla: "সাহায্য করেন", english: "Please help", romanization: "shahajjo koren" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-3-tte-1",
              bangla: "দয়া করে সাহায্য করেন।",
              romanization: "doya kore shahajjo koren.",
              answer: "Please help.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-3-mc-1",
              prompt: "In Khulna Bangla, 'ঠিক আসে' means:",
              options: ["thank you", "excuse me", "okay", "please"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-4",
          title: "Yes / No / Basic Replies",
          description: "Respond to simple questions in Khulna Bangla",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-4-mp-1",
              pairs: [
                { bangla: "হ",          english: "Yes (Khulna spoken)", romanization: "ho"        },
                { bangla: "না",         english: "No",                   romanization: "na"        },
                { bangla: "হতে পারে", english: "Maybe",                romanization: "hote pare" },
                { bangla: "জানি না",  english: "I don't know",         romanization: "jani na"   },
              ],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-1-4-ttb-1",
              english: "Yes, I can. (Khulna)",
              answer: "হ, পারি।",
              romanization: "ho, pari.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-4-mc-1",
              prompt: "In Khulna Bangla, 'হ' means:",
              options: ["No", "Maybe", "Yes", "Okay"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-5",
          title: "Pronouns",
          description: "Use Khulna Bangla pronouns including the regional form আপনে",
          unit: 1,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-5-mp-1",
              pairs: [
                { bangla: "আমি",   english: "I",                        romanization: "ami"  },
                { bangla: "তুমি",  english: "You (familiar)",            romanization: "tumi" },
                { bangla: "আপনে", english: "You (polite, Khulna form)", romanization: "apne" },
                { bangla: "ও",     english: "He / She",                  romanization: "o"    },
                { bangla: "ওরা",   english: "They",                      romanization: "ora"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-5-tte-1",
              bangla: "আপনে কেমন আছেন?",
              romanization: "apne kemon asen?",
              answer: "How are you? (polite, Khulna form)",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-1-5-tte-2",
              bangla: "আমি আইতেছি।",
              romanization: "ami aitesi.",
              answer: "I am coming. (Khulna progressive)",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "khu-1-5-mc-1",
              prompt: "In Khulna Bangla, 'ও' refers to:",
              options: ["I", "You", "He or She", "They"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-6",
          title: "Family",
          description: "Learn Khulna Bangla family words — with paired regional/standard forms",
          unit: 1,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-6-mp-1",
              pairs: [
                { bangla: "মা",              english: "Mother",            romanization: "ma"           },
                { bangla: "বাবা / বাপ",      english: "Father (both forms)", romanization: "baba / bap"  },
                { bangla: "ভাই",             english: "Brother",           romanization: "bhai"         },
                { bangla: "বইন / বোন",       english: "Sister (both forms)", romanization: "boin / bon"  },
                { bangla: "পোলা / ছেলে",    english: "Son / Boy",          romanization: "pola / chele" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-6-tte-1",
              bangla: "এইডা আমার মা।",
              romanization: "eida amar ma.",
              answer: "This is my mother.",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-1-6-tte-2",
              bangla: "আমার এক বইন আছে।",
              romanization: "amar ek boin ase.",
              answer: "I have one sister. (Khulna form)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-6-mc-1",
              prompt: "Khulna Bangla teaches family pairs. 'মাইয়া / মেয়ে' means:",
              options: ["son/boy", "daughter/girl", "sister", "mother"],
              correct: 1,
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-6-mc-2",
              prompt: "Which sentence is in Khulna Bangla style?",
              options: [
                "এইডা আমার মা।",
                "ইনি আমার মা।",
                "এই আমার মা।",
                "উনি আমার মা।",
              ],
              correct: 0,
              xp: 3,
            },
          ],
        },
      ],
    },
  ],
};
