import type { DialectCurriculum } from "@bangla-learn/types";

export const khulnaCurriculum: DialectCurriculum = {
  dialect: "khulna",
  units: [
    {
      id: "khu-unit-1",
      title: "Khulna Bangla Basics",
      description: "Learn Khulna Bangla — the southwestern regional variety of Bangladesh",
      order: 1,
      color: "#059669",
      prep: {
        characters: [
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আমি (I)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইচ্ছা (wish)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠা (to rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এক (one)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওরা (they)" },
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কই (where)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খালা (aunt)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলাম (I went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালো (good)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মা (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাত (night)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তুমি (you)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পরিবার (family)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বাবা (father)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হ (yes)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সাহায্য (help)" },
          { symbol: "আপ", romanization: "ap", type: "consonant" as const, exampleWord: "আপনে (you, polite)" },
          { symbol: "ধ", romanization: "dh",  type: "consonant" as const, exampleWord: "ধন্যবাদ (thank you)" },
        ],
        flashcards: [
          { id: "fc-khu-1",  bangla: "আমি",          romanization: "ami",       english: "I",                            category: "pronouns"  },
          { id: "fc-khu-2",  bangla: "তুমি",          romanization: "tumi",      english: "You (familiar)",               category: "pronouns"  },
          { id: "fc-khu-3",  bangla: "আপনে",          romanization: "apne",      english: "You (polite, Khulna form)",    category: "pronouns"  },
          { id: "fc-khu-4",  bangla: "ও",              romanization: "o",         english: "He / She",                     category: "pronouns"  },
          { id: "fc-khu-5",  bangla: "আমরা",          romanization: "amra",      english: "We",                           category: "pronouns"  },
          { id: "fc-khu-6",  bangla: "ওরা",            romanization: "ora",       english: "They",                         category: "pronouns"  },
          { id: "fc-khu-7",  bangla: "ভালো",          romanization: "bhalo",     english: "Good / Fine",                  category: "adjectives"},
          { id: "fc-khu-8",  bangla: "হ",              romanization: "ho",        english: "Yes (Khulna spoken form)",     category: "phrases"   },
          { id: "fc-khu-9",  bangla: "না",              romanization: "na",        english: "No",                           category: "phrases"   },
          { id: "fc-khu-10", bangla: "ঠিক আসে",       romanization: "thik ase",  english: "Okay (Khulna form)",           category: "phrases"   },
          { id: "fc-khu-11", bangla: "হতে পারে",      romanization: "hote pare", english: "Maybe",                        category: "phrases"   },
          { id: "fc-khu-12", bangla: "বাবা / বাপ",    romanization: "baba / bap",english: "Father (both forms used)",     category: "family"    },
          { id: "fc-khu-13", bangla: "বইন / বোন",     romanization: "boin / bon",english: "Sister (both forms used)",     category: "family"    },
          { id: "fc-khu-14", bangla: "পোলা / ছেলে",  romanization: "pola / chele", english: "Son / Boy (both forms)",    category: "family"    },
          { id: "fc-khu-15", bangla: "মাইয়া / মেয়ে", romanization: "maiya / meye", english: "Daughter / Girl (both)",   category: "family"    },
          { id: "fc-khu-16", bangla: "শিখতেছি",       romanization: "shikhtesi", english: "Am learning (Khulna form)",   category: "phrases"   },
        ],
        grammar: [
          {
            title: "Khulna's paired forms",
            explanation: "Khulna Bangla teaches standard/regional pairs side by side. For example, বাবা/বাপ (father) or বোন/বইন (sister). Both forms are accepted, so learners hear both in everyday speech.",
            examples: [
              { bangla: "বাবা / বাপ",  romanization: "baba / bap",  english: "Father — both forms are used in Khulna" },
              { bangla: "বইন / বোন",   romanization: "boin / bon",   english: "Sister — regional/standard pair" },
            ],
          },
          {
            title: "Progressive: -তেছি / -তাছি",
            explanation: "In Khulna Bangla the progressive -ছি ending often appears as -তেছি or -তাছি. E.g. শিখতেছি = am learning; আইতেছি = am coming.",
            examples: [
              { bangla: "আমি আইতেছি।",       romanization: "ami aitesi.",       english: "I am coming." },
              { bangla: "আমি বাংলা শিখতেছি।", romanization: "ami bangla shikhtesi.", english: "I am learning Bangla." },
            ],
          },
          {
            title: "Polite 'you' — আপনে",
            explanation: "Khulna spoken Bangla favors আপনে (apne) as the polite form of 'you', alongside standard আপনি.",
            examples: [
              { bangla: "আপনে কেমন আছেন?", romanization: "apne kemon asen?", english: "How are you? (polite)" },
              { bangla: "ও আমার বন্ধু।",   romanization: "o amar bondhu.",   english: "He/She is my friend." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "khu-1-0",
          title: "Write the Letters",
          description: "Trace key letters used in Khulna Bangla",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "khu-1-0-tr-1", character: "আ", romanization: "aa",  exampleWord: "আমি — I",         xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-2", character: "ন", romanization: "n",   exampleWord: "নাম — name",      xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-3", character: "ম", romanization: "m",   exampleWord: "মা — mother",     xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-4", character: "ত", romanization: "t",   exampleWord: "তুমি — you",      xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-5", character: "ভ", romanization: "bh",  exampleWord: "ভালো — good",    xp: 4 },
          ],
        },
        {
          id: "khu-1-1",
          title: "Greetings",
          description: "Greet and exchange names in Khulna Bangla",
          unit: 1,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-1-mp-1",
              pairs: [
                { bangla: "আসসালামু আলাইকুম", english: "Hello (Islamic greeting)", romanization: "assalamu alaikum" },
                { bangla: "নমস্কার",            english: "Hello / Greetings",        romanization: "nomoshkar"        },
                { bangla: "ভালো",              english: "Good / Fine",              romanization: "bhalo"            },
                { bangla: "আমার নাম ___।",     english: "My name is ___.",          romanization: "amar nam ___."    },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-1-tte-1",
              bangla: "তুমি কেমন আছো?",
              romanization: "tumi kemon acho?",
              answer: "How are you?",
              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "khu-1-1-ttb-1",
              english: "I am fine.",
              answer: "আমি ভালো আছি।",
              romanization: "ami bhalo achi.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "khu-1-1-mc-1",
              prompt: "In Khulna Bangla, which is a common greeting?",
              options: [
                "ভালা আসেন? (Sylheti)",
                "তোমার নাম কী? (What is your name?)",
                "আমি ভালো আছি। (I am fine.)",
                "কিতা? (Chittagonian)",
              ],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-2",
          title: "Introductions",
          description: "Introduce yourself in Khulna Bangla using regional speech patterns",
          unit: 1,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-1-2-tte-1",
              bangla: "আমার নাম ___।",
              romanization: "amar nam ___.",
              answer: "My name is ___.",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-1-2-tte-2",
              bangla: "আমি বাংলা শিখতেছি।",
              romanization: "ami bangla shikhtesi.",
              answer: "I am learning Bangla. (Khulna form)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-2-mc-1",
              prompt: "'শিখতেছি' is a Khulna form meaning:",
              options: ["am eating", "am learning", "am going", "am sleeping"],
              correct: 1,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "khu-1-2-fb-1",
              sentence: "আমি ___ থেকে আইছি।",
              blank: "খুলনা",
              romanization: "ami ___ theke aisi.",
              options: ["খুলনা", "নাম", "আমার", "ভালো"],
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-3",
          title: "Polite Words",
          description: "Use polite expressions in Khulna Bangla",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-3-mp-1",
              pairs: [
                { bangla: "ধন্যবাদ",     english: "Thank you",  romanization: "dhonnobad"       },
                { bangla: "দয়া করে",    english: "Please",     romanization: "doya kore"       },
                { bangla: "মাফ করেন",   english: "Excuse me",  romanization: "maf koren"       },
                { bangla: "সাহায্য করেন", english: "Please help", romanization: "shahajjo koren" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-3-tte-1",
              bangla: "দয়া করে সাহায্য করেন।",
              romanization: "doya kore shahajjo koren.",
              answer: "Please help.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-3-mc-1",
              prompt: "In Khulna Bangla, 'ঠিক আসে' means:",
              options: ["thank you", "excuse me", "okay", "please"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-4",
          title: "Yes / No / Basic Replies",
          description: "Respond to simple questions in Khulna Bangla",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-4-mp-1",
              pairs: [
                { bangla: "হ",          english: "Yes (Khulna spoken)", romanization: "ho"        },
                { bangla: "না",         english: "No",                   romanization: "na"        },
                { bangla: "হতে পারে", english: "Maybe",                romanization: "hote pare" },
                { bangla: "জানি না",  english: "I don't know",         romanization: "jani na"   },
              ],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-1-4-ttb-1",
              english: "Yes, I can. (Khulna)",
              answer: "হ, পারি।",
              romanization: "ho, pari.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-4-mc-1",
              prompt: "In Khulna Bangla, 'হ' means:",
              options: ["No", "Maybe", "Yes", "Okay"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-5",
          title: "Pronouns",
          description: "Use Khulna Bangla pronouns including the regional form আপনে",
          unit: 1,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-5-mp-1",
              pairs: [
                { bangla: "আমি",   english: "I",                        romanization: "ami"  },
                { bangla: "তুমি",  english: "You (familiar)",            romanization: "tumi" },
                { bangla: "আপনে", english: "You (polite, Khulna form)", romanization: "apne" },
                { bangla: "ও",     english: "He / She",                  romanization: "o"    },
                { bangla: "ওরা",   english: "They",                      romanization: "ora"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-5-tte-1",
              bangla: "আপনে কেমন আছেন?",
              romanization: "apne kemon asen?",
              answer: "How are you? (polite, Khulna form)",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-1-5-tte-2",
              bangla: "আমি আইতেছি।",
              romanization: "ami aitesi.",
              answer: "I am coming. (Khulna progressive)",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "khu-1-5-mc-1",
              prompt: "In Khulna Bangla, 'ও' refers to:",
              options: ["I", "You", "He or She", "They"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-6",
          title: "Family",
          description: "Learn Khulna Bangla family words — with paired regional/standard forms",
          unit: 1,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-6-mp-1",
              pairs: [
                { bangla: "মা",              english: "Mother",            romanization: "ma"           },
                { bangla: "বাবা / বাপ",      english: "Father (both forms)", romanization: "baba / bap"  },
                { bangla: "ভাই",             english: "Brother",           romanization: "bhai"         },
                { bangla: "বইন / বোন",       english: "Sister (both forms)", romanization: "boin / bon"  },
                { bangla: "পোলা / ছেলে",    english: "Son / Boy",          romanization: "pola / chele" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-6-tte-1",
              bangla: "এইডা আমার মা।",
              romanization: "eida amar ma.",
              answer: "This is my mother.",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-1-6-tte-2",
              bangla: "আমার এক বইন আছে।",
              romanization: "amar ek boin ase.",
              answer: "I have one sister. (Khulna form)",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-6-mc-1",
              prompt: "Khulna Bangla teaches family pairs. 'মাইয়া / মেয়ে' means:",
              options: ["son/boy", "daughter/girl", "sister", "mother"],
              correct: 1,
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-6-mc-2",
              prompt: "Which sentence is in Khulna Bangla style?",
              options: [
                "এইডা আমার মা।",
                "ইনি আমার মা।",
                "এই আমার মা।",
                "উনি আমার মা।",
              ],
              correct: 0,
              xp: 3,
            },
          ],
        },
      ],
    },
    {
      id: "khu-unit-2",
      title: "Heart & Time",
      description: "Express affection, count numbers, and talk about time in Khulna dialect",
      order: 2,
      color: "#0891b2",
      prep: {
        characters: [],
        flashcards: [
          { id: "fc-khu-2-1",  bangla: "আপনে",        romanization: "apne",        english: "You (formal, Khulna)",          category: "pronouns"  },
          { id: "fc-khu-2-2",  bangla: "তোমারে",       romanization: "tomare",      english: "You / To you (object, -রে)",   category: "pronouns"  },
          { id: "fc-khu-2-3",  bangla: "আমাগো",        romanization: "amago",       english: "Our / Ours",                    category: "pronouns"  },
          { id: "fc-khu-2-4",  bangla: "ভালোবাসি",   romanization: "bhalobashi",  english: "I love (you)",                  category: "phrases"   },
          { id: "fc-khu-2-5",  bangla: "মায়া",         romanization: "maya",        english: "Affection / Love",              category: "phrases"   },
          { id: "fc-khu-2-6",  bangla: "লাই",          romanization: "lai",         english: "For (Khulna: জন্য)",           category: "grammar"   },
          { id: "fc-khu-2-7",  bangla: "আইতেছি",      romanization: "aiteshi",     english: "Am coming (-তেছি progressive)", category: "grammar"   },
          { id: "fc-khu-2-8",  bangla: "দিমু",         romanization: "dimu",        english: "Will give (Khulna future)",    category: "grammar"   },
          { id: "fc-khu-2-9",  bangla: "হইব",          romanization: "hoib",        english: "Will happen / Will be",        category: "grammar"   },
          { id: "fc-khu-2-10", bangla: "এহন",          romanization: "ehon",        english: "Now (Khulna: এখন)",           category: "time"      },
          { id: "fc-khu-2-11", bangla: "রাইত",         romanization: "rait",        english: "Night (Khulna: রাত)",         category: "time"      },
          { id: "fc-khu-2-12", bangla: "সকাল",         romanization: "shokal",      english: "Morning",                     category: "time"      },
          { id: "fc-khu-2-13", bangla: "আইজ",          romanization: "aij",         english: "Today (Khulna: আজ)",          category: "time"      },
          { id: "fc-khu-2-14", bangla: "গইকাল",        romanization: "goikal",      english: "Yesterday",                   category: "time"      },
          { id: "fc-khu-2-15", bangla: "আগাইলকাল",    romanization: "agailkal",    english: "Tomorrow",                    category: "time"      },
          { id: "fc-khu-2-16", bangla: "এক",           romanization: "ek",          english: "One",                         category: "numbers"   },
          { id: "fc-khu-2-17", bangla: "দশ",           romanization: "dosh",        english: "Ten",                         category: "numbers"   },
          { id: "fc-khu-2-18", bangla: "বিশ",          romanization: "bish",        english: "Twenty",                      category: "numbers"   },
        ],
        grammar: [
          {
            title: "Khulna -তেছি Progressive",
            explanation: "Khulna uses '-তেছি' for present progressive (ongoing action). 'আসছি' (Standard) becomes 'আইতেছি' (Khulna). This is a distinctive Khulna feature.",
            examples: [
              { bangla: "আমি আইতেছি।",          romanization: "ami aiteshi.",          english: "I am coming." },
              { bangla: "সে খাইতেছে।",          romanization: "she khaiteshe.",        english: "He/she is eating." },
            ],
          },
          {
            title: "Khulna Object Marker: -রে",
            explanation: "Like Barisali, Khulna uses '-রে' as the object marker. 'তোমাকে' → 'তোমারে', 'আমাকে' → 'আমারে'. 'আমাগো' means 'our' (আমাদের in Standard).",
            examples: [
              { bangla: "আমি তোমারে মায়া করি।", romanization: "ami tomare maya kori.", english: "I care for / love you." },
              { bangla: "আমাগো বাড়ি এইখানে।",   romanization: "amago bari eikhane.",   english: "Our home is here." },
            ],
          },
          {
            title: "Khulna Future: দিমু / হইব",
            explanation: "Future tense: 'দেব' → 'দিমু' (will give), 'হবে' → 'হইব' (will happen). Time words: আজ→আইজ, গতকাল→গইকাল, আগামীকাল→আগাইলকাল.",
            examples: [
              { bangla: "আমি তোমারে দিমু।", romanization: "ami tomare dimu.", english: "I will give you." },
              { bangla: "এইডা হইব না।",     romanization: "eida hoib na.",    english: "This will not happen." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "khu-2-0",
          title: "Respect & Affection",
          description: "Say 'I love you' and express care in Khulna",
          unit: 2,
          order: 0,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-2-0-mp-1",
              pairs: [
                { bangla: "আপনে",            english: "You (formal)",   romanization: "apne"           },
                { bangla: "তোমারে মায়া করি", english: "I love / care for you", romanization: "tomare maya kori" },
                { bangla: "আমাগো",           english: "Our",            romanization: "amago"          },
                { bangla: "লাই",             english: "For",            romanization: "lai"            },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-2-0-tte-1",
              bangla: "আমি তোমারে ভালোবাসি।",
              romanization: "ami tomare bhalobashi.",
              answer: "I love you.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-0-mc-1",
              prompt: "Khulna uses '-রে' as an object marker. 'You' (object) becomes:",
              options: ["তোমায়", "তোমারে", "তোমার", "তুমি"],
              correct: 1,
              xp: 5,
            },
          ],
        },
        {
          id: "khu-2-1",
          title: "Sweet Questions",
          description: "Ask questions in Khulna dialect",
          unit: 2,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-2-1-tte-1",
              bangla: "তুমি এহন কই আসো?",
              romanization: "tumi ehon koi aso?",
              answer: "Where are you now?",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "khu-2-1-fb-1",
              sentence: "আমি তোমার ___ আইতেছি।",
              blank: "লাই",
              romanization: "ami tomar ___ aiteshi.",
              options: ["লাই", "এহন", "রাইত", "কই"],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-1-mc-1",
              prompt: "In Khulna, the progressive 'am coming' is:",
              options: ["আসছি", "আইলাম", "আইতেছি", "আইজ"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "khu-2-2",
          title: "Numbers 1–10",
          description: "Count from one to ten",
          unit: 2,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-2-2-mp-1",
              pairs: [
                { bangla: "এক",   english: "One",   romanization: "ek"    },
                { bangla: "দুই",  english: "Two",   romanization: "dui"   },
                { bangla: "তিন",  english: "Three", romanization: "tin"   },
                { bangla: "চার",  english: "Four",  romanization: "char"  },
              ],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-2-2-mp-2",
              pairs: [
                { bangla: "পাঁচ", english: "Five",  romanization: "pach" },
                { bangla: "সাত",  english: "Seven", romanization: "shat" },
                { bangla: "নয়",  english: "Nine",  romanization: "noy"  },
                { bangla: "দশ",   english: "Ten",   romanization: "dosh" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-2-mc-1",
              prompt: "How do you say 'six' in Bangla?",
              options: ["পাঁচ", "সাত", "ছয়", "আট"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "khu-2-3",
          title: "Numbers 11–20",
          description: "Count from eleven to twenty",
          unit: 2,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-2-3-mp-1",
              pairs: [
                { bangla: "এগারো",  english: "Eleven",   romanization: "egaro"   },
                { bangla: "পনেরো",  english: "Fifteen",  romanization: "ponero"  },
                { bangla: "আঠারো",  english: "Eighteen", romanization: "atharo"  },
                { bangla: "বিশ",    english: "Twenty",   romanization: "bish"    },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-3-mc-1",
              prompt: "How do you say 'nineteen'?",
              options: ["আঠারো", "উনিশ", "বিশ", "সতেরো"],
              correct: 1,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-2-3-tte-1",
              bangla: "আমার বয়স তেরো।",
              romanization: "amar boyosh tero.",
              answer: "I am thirteen years old.",
              xp: 5,
            },
          ],
        },
        {
          id: "khu-2-4",
          title: "Time Words",
          description: "Morning, night, now — Khulna style",
          unit: 2,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-2-4-mp-1",
              pairs: [
                { bangla: "সকাল",  english: "Morning",   romanization: "shokal" },
                { bangla: "রাইত",  english: "Night",     romanization: "rait"   },
                { bangla: "এহন",   english: "Now",       romanization: "ehon"   },
                { bangla: "আইতেছি", english: "Am coming", romanization: "aiteshi" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-2-4-tte-1",
              bangla: "আমি এহন আইতেছি।",
              romanization: "ami ehon aiteshi.",
              answer: "I am coming now.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-4-mc-1",
              prompt: "In Khulna, 'night' (রাত in Standard) becomes:",
              options: ["রাইত", "এহন", "আইজ", "লাই"],
              correct: 0,
              xp: 5,
            },
          ],
        },
        {
          id: "khu-2-5",
          title: "Today / Yesterday / Tomorrow",
          description: "Talk about days in Khulna — quiz time!",
          unit: 2,
          order: 5,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "khu-2-5-mc-1",
              prompt: "In Khulna, 'today' (আজ) is:",
              options: ["গইকাল", "আইজ", "আগাইলকাল", "এহন"],
              correct: 1,
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-5-mc-2",
              prompt: "In Khulna, 'yesterday' (গতকাল) is:",
              options: ["আইজ", "আগাইলকাল", "গইকাল", "কাইল"],
              correct: 2,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-2-5-tte-1",
              bangla: "আমি আগাইলকাল দিমু।",
              romanization: "ami agailkal dimu.",
              answer: "I will give (it) tomorrow.",
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-2-5-ttb-1",
              english: "I am coming for you.",
              answer: "আমি তোমার লাই আইতেছি।",
              romanization: "ami tomar lai aiteshi.",
              xp: 5,
            },
          ],
        },
      ],
    },
  ],
};
