import type { DialectCurriculum } from "@bangla-learn/types";

export const khulnaCurriculum: DialectCurriculum = {
  dialect: "khulna",
  units: [
    {
      id: "khu-unit-1",
      title: "Khulna Bangla Basics",
      description: "Learn Khulna Bangla — the southwestern regional variety of Bangladesh",
      order: 1,
      color: "#059669",
      prep: {
        characters: [
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আমি (I)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইচ্ছা (wish)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠা (to rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এক (one)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওরা (they)" },
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কই (where)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খালা (aunt)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলাম (I went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালো (good)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মা (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাত (night)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তুমি (you)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পরিবার (family)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বাবা (father)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হ (yes)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সাহায্য (help)" },
          { symbol: "আপ", romanization: "ap", type: "consonant" as const, exampleWord: "আপনে (you, polite)" },
          { symbol: "ধ", romanization: "dh",  type: "consonant" as const, exampleWord: "ধন্যবাদ (thank you)" },
        ],
        flashcards: [
          { id: "fc-khu-1",  bangla: "আমি",          romanization: "ami",       english: "I",                            category: "pronouns"  },
          { id: "fc-khu-2",  bangla: "তুমি",          romanization: "tumi",      english: "You (familiar)",               category: "pronouns"  },
          { id: "fc-khu-3",  bangla: "আপনে",          romanization: "apne",      english: "You (polite, Khulna form)",    category: "pronouns"  },
          { id: "fc-khu-4",  bangla: "ও",              romanization: "o",         english: "He / She",                     category: "pronouns"  },
          { id: "fc-khu-5",  bangla: "আমরা",          romanization: "amra",      english: "We",                           category: "pronouns"  },
          { id: "fc-khu-6",  bangla: "ওরা",            romanization: "ora",       english: "They",                         category: "pronouns"  },
          { id: "fc-khu-7",  bangla: "ভালো",          romanization: "bhalo",     english: "Good / Fine",                  category: "adjectives"},
          { id: "fc-khu-8",  bangla: "হ",              romanization: "ho",        english: "Yes (Khulna spoken form)",     category: "phrases"   },
          { id: "fc-khu-9",  bangla: "না",              romanization: "na",        english: "No",                           category: "phrases"   },
          { id: "fc-khu-10", bangla: "ঠিক আসে",       romanization: "thik ase",  english: "Okay (Khulna form)",           category: "phrases"   },
          { id: "fc-khu-11", bangla: "হতে পারে",      romanization: "hote pare", english: "Maybe",                        category: "phrases"   },
          { id: "fc-khu-12", bangla: "বাবা / বাপ",    romanization: "baba / bap",english: "Father (both forms used)",     category: "family"    },
          { id: "fc-khu-13", bangla: "বইন / বোন",     romanization: "boin / bon",english: "Sister (both forms used)",     category: "family"    },
          { id: "fc-khu-14", bangla: "পোলা / ছেলে",  romanization: "pola / chele", english: "Son / Boy (both forms)",    category: "family"    },
          { id: "fc-khu-15", bangla: "মাইয়া / মেয়ে", romanization: "maiya / meye", english: "Daughter / Girl (both)",   category: "family"    },
          { id: "fc-khu-16", bangla: "শিখতেছি",       romanization: "shikhtesi", english: "Am learning (Khulna form)",   category: "phrases"   },
        ],
        grammar: [
          {
            title: "Khulna's paired forms",
            explanation: "Khulna Bangla teaches standard/regional pairs side by side. For example, বাবা/বাপ (father) or বোন/বইন (sister). Both forms are accepted, so learners hear both in everyday speech.",
            examples: [
              { bangla: "বাবা / বাপ",  romanization: "baba / bap",  english: "Father — both forms are used in Khulna" },
              { bangla: "বইন / বোন",   romanization: "boin / bon",   english: "Sister — regional/standard pair" },
            ],
          },
          {
            title: "Progressive: -তেছি / -তাছি",
            explanation: "In Khulna Bangla the progressive -ছি ending often appears as -তেছি or -তাছি. E.g. শিখতেছি = am learning; আইতেছি = am coming.",
            examples: [
              { bangla: "আমি আইতেছি।",       romanization: "ami aitesi.",       english: "I am coming." },
              { bangla: "আমি বাংলা শিখতেছি।", romanization: "ami bangla shikhtesi.", english: "I am learning Bangla." },
            ],
          },
          {
            title: "Polite 'you' — আপনে",
            explanation: "Khulna spoken Bangla favors আপনে (apne) as the polite form of 'you', alongside standard আপনি.",
            examples: [
              { bangla: "আপনে কেমন আছেন?", romanization: "apne kemon asen?", english: "How are you? (polite)" },
              { bangla: "ও আমার বন্ধু।",   romanization: "o amar bondhu.",   english: "He/She is my friend." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "khu-1-0",
          title: "Write the Letters",
          description: "Trace key letters used in Khulna Bangla",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "khu-1-0-tr-1", character: "আ", romanization: "aa",  exampleWord: "আমি — I",         xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-2", character: "ন", romanization: "n",   exampleWord: "নাম — name",      xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-3", character: "ম", romanization: "m",   exampleWord: "মা — mother",     xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-4", character: "ত", romanization: "t",   exampleWord: "তুমি — you",      xp: 4 },
            { type: "letter_trace", id: "khu-1-0-tr-5", character: "ভ", romanization: "bh",  exampleWord: "ভালো — good",    xp: 4 },
          ],
        },
        {
          id: "khu-1-1",
          title: "Greetings",
          description: "Greet and exchange names in Khulna Bangla",
          unit: 1,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-1-mp-1",
              pairs: [
                { bangla: "আসসালামু আলাইকুম", english: "Hello (Islamic greeting)", romanization: "assalamu alaikum" },
                { bangla: "নমস্কার",            english: "Hello / Greetings",        romanization: "nomoshkar"        },
                { bangla: "ভালো",              english: "Good / Fine",              romanization: "bhalo"            },
                { bangla: "আমার নাম ___।",     english: "My name is ___.",          romanization: "amar nam ___."    },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-1-tte-1",
              bangla: "তুমি কেমন আছো?",
              romanization: "tumi kemon acho?",
              answer: "How are you?",

              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "khu-1-1-ttb-1",
              english: "I am fine.",
              answer: "আমি ভালো আছি।",
              romanization: "ami bhalo achi.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "khu-1-1-mc-1",
              prompt: "In Khulna Bangla, which is a common greeting?",
              options: [
                "ভালা আসেন? (Sylheti)",
                "তোমার নাম কী? (What is your name?)",
                "আমি ভালো আছি। (I am fine.)",
                "কিতা? (Chittagonian)",
              ],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-2",
          title: "Introductions",
          description: "Introduce yourself in Khulna Bangla using regional speech patterns",
          unit: 1,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-1-2-tte-1",
              bangla: "আমার নাম ___।",
              romanization: "amar nam ___.",
              answer: "My name is ___.",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-1-2-tte-2",
              bangla: "আমি বাংলা শিখতেছি।",
              romanization: "ami bangla shikhtesi.",
              answer: "I am learning Bangla. (Khulna form)",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-2-mc-1",
              prompt: "'শিখতেছি' is a Khulna form meaning:",
              options: ["am eating", "am learning", "am going", "am sleeping"],
              correct: 1,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "khu-1-2-fb-1",
              sentence: "আমি ___ থেকে আইছি।",
              blank: "খুলনা",
              romanization: "ami ___ theke aisi.",
              options: ["খুলনা", "নাম", "আমার", "ভালো"],
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-3",
          title: "Polite Words",
          description: "Use polite expressions in Khulna Bangla",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-3-mp-1",
              pairs: [
                { bangla: "ধন্যবাদ",     english: "Thank you",  romanization: "dhonnobad"       },
                { bangla: "দয়া করে",    english: "Please",     romanization: "doya kore"       },
                { bangla: "মাফ করেন",   english: "Excuse me",  romanization: "maf koren"       },
                { bangla: "সাহায্য করেন", english: "Please help", romanization: "shahajjo koren" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-3-tte-1",
              bangla: "দয়া করে সাহায্য করেন।",
              romanization: "doya kore shahajjo koren.",
              answer: "Please help.",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-3-mc-1",
              prompt: "In Khulna Bangla, 'ঠিক আসে' means:",
              options: ["thank you", "excuse me", "okay", "please"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-4",
          title: "Yes / No / Basic Replies",
          description: "Respond to simple questions in Khulna Bangla",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-4-mp-1",
              pairs: [
                { bangla: "হ",          english: "Yes (Khulna spoken)", romanization: "ho"        },
                { bangla: "না",         english: "No",                   romanization: "na"        },
                { bangla: "হতে পারে", english: "Maybe",                romanization: "hote pare" },
                { bangla: "জানি না",  english: "I don't know",         romanization: "jani na"   },
              ],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-1-4-ttb-1",
              english: "Yes, I can. (Khulna)",
              answer: "হ, পারি।",
              romanization: "ho, pari.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-4-mc-1",
              prompt: "In Khulna Bangla, 'হ' means:",
              options: ["No", "Maybe", "Yes", "Okay"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-5",
          title: "Pronouns",
          description: "Use Khulna Bangla pronouns including the regional form আপনে",
          unit: 1,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-5-mp-1",
              pairs: [
                { bangla: "আমি",   english: "I",                        romanization: "ami"  },
                { bangla: "তুমি",  english: "You (familiar)",            romanization: "tumi" },
                { bangla: "আপনে", english: "You (polite, Khulna form)", romanization: "apne" },
                { bangla: "ও",     english: "He / She",                  romanization: "o"    },
                { bangla: "ওরা",   english: "They",                      romanization: "ora"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-5-tte-1",
              bangla: "আপনে কেমন আছেন?",
              romanization: "apne kemon asen?",
              answer: "How are you? (polite, Khulna form)",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-1-5-tte-2",
              bangla: "আমি আইতেছি।",
              romanization: "ami aitesi.",
              answer: "I am coming. (Khulna progressive)",

              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "khu-1-5-mc-1",
              prompt: "In Khulna Bangla, 'ও' refers to:",
              options: ["I", "You", "He or She", "They"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "khu-1-6",
          title: "Family",
          description: "Learn Khulna Bangla family words — with paired regional/standard forms",
          unit: 1,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-1-6-mp-1",
              pairs: [
                { bangla: "মা",              english: "Mother",            romanization: "ma"           },
                { bangla: "বাবা / বাপ",      english: "Father (both forms)", romanization: "baba / bap"  },
                { bangla: "ভাই",             english: "Brother",           romanization: "bhai"         },
                { bangla: "বইন / বোন",       english: "Sister (both forms)", romanization: "boin / bon"  },
                { bangla: "পোলা / ছেলে",    english: "Son / Boy",          romanization: "pola / chele" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-1-6-tte-1",
              bangla: "এইডা আমার মা।",
              romanization: "eida amar ma.",
              answer: "This is my mother.",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-1-6-tte-2",
              bangla: "আমার এক বইন আছে।",
              romanization: "amar ek boin ase.",
              answer: "I have one sister. (Khulna form)",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-6-mc-1",
              prompt: "Khulna Bangla teaches family pairs. 'মাইয়া / মেয়ে' means:",
              options: ["son/boy", "daughter/girl", "sister", "mother"],
              correct: 1,
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "khu-1-6-mc-2",
              prompt: "Which sentence is in Khulna Bangla style?",
              options: [
                "এইডা আমার মা।",
                "ইনি আমার মা।",
                "এই আমার মা।",
                "উনি আমার মা।",
              ],
              correct: 0,
              xp: 3,
            },
          ],
        },
      ],
    },
    {
      id: "khu-unit-2",
      title: "Heart & Time",
      description: "Express affection, count numbers, and talk about time in Khulna dialect",
      order: 2,
      color: "#0891b2",
      prep: {
        characters: [],
        flashcards: [
          { id: "fc-khu-2-1",  bangla: "আপনে",        romanization: "apne",        english: "You (formal, Khulna)",          category: "pronouns"  },
          { id: "fc-khu-2-2",  bangla: "তোমারে",       romanization: "tomare",      english: "You / To you (object, -রে)",   category: "pronouns"  },
          { id: "fc-khu-2-3",  bangla: "আমাগো",        romanization: "amago",       english: "Our / Ours",                    category: "pronouns"  },
          { id: "fc-khu-2-4",  bangla: "ভালোবাসি",   romanization: "bhalobashi",  english: "I love (you)",                  category: "phrases"   },
          { id: "fc-khu-2-5",  bangla: "মায়া",         romanization: "maya",        english: "Affection / Love",              category: "phrases"   },
          { id: "fc-khu-2-6",  bangla: "লাই",          romanization: "lai",         english: "For (Khulna: জন্য)",           category: "grammar"   },
          { id: "fc-khu-2-7",  bangla: "আইতেছি",      romanization: "aiteshi",     english: "Am coming (-তেছি progressive)", category: "grammar"   },
          { id: "fc-khu-2-8",  bangla: "দিমু",         romanization: "dimu",        english: "Will give (Khulna future)",    category: "grammar"   },
          { id: "fc-khu-2-9",  bangla: "হইব",          romanization: "hoib",        english: "Will happen / Will be",        category: "grammar"   },
          { id: "fc-khu-2-10", bangla: "এহন",          romanization: "ehon",        english: "Now (Khulna: এখন)",           category: "time"      },
          { id: "fc-khu-2-11", bangla: "রাইত",         romanization: "rait",        english: "Night (Khulna: রাত)",         category: "time"      },
          { id: "fc-khu-2-12", bangla: "সকাল",         romanization: "shokal",      english: "Morning",                     category: "time"      },
          { id: "fc-khu-2-13", bangla: "আইজ",          romanization: "aij",         english: "Today (Khulna: আজ)",          category: "time"      },
          { id: "fc-khu-2-14", bangla: "গইকাল",        romanization: "goikal",      english: "Yesterday",                   category: "time"      },
          { id: "fc-khu-2-15", bangla: "আগাইলকাল",    romanization: "agailkal",    english: "Tomorrow",                    category: "time"      },
          { id: "fc-khu-2-16", bangla: "এক",           romanization: "ek",          english: "One",                         category: "numbers"   },
          { id: "fc-khu-2-17", bangla: "দশ",           romanization: "dosh",        english: "Ten",                         category: "numbers"   },
          { id: "fc-khu-2-18", bangla: "বিশ",          romanization: "bish",        english: "Twenty",                      category: "numbers"   },
        ],
        grammar: [
          {
            title: "Khulna -তেছি Progressive",
            explanation: "Khulna uses '-তেছি' for present progressive (ongoing action). 'আসছি' (Standard) becomes 'আইতেছি' (Khulna). This is a distinctive Khulna feature.",
            examples: [
              { bangla: "আমি আইতেছি।",          romanization: "ami aiteshi.",          english: "I am coming." },
              { bangla: "সে খাইতেছে।",          romanization: "she khaiteshe.",        english: "He/she is eating." },
            ],
          },
          {
            title: "Khulna Object Marker: -রে",
            explanation: "Like Barisali, Khulna uses '-রে' as the object marker. 'তোমাকে' → 'তোমারে', 'আমাকে' → 'আমারে'. 'আমাগো' means 'our' (আমাদের in Standard).",
            examples: [
              { bangla: "আমি তোমারে মায়া করি।", romanization: "ami tomare maya kori.", english: "I care for / love you." },
              { bangla: "আমাগো বাড়ি এইখানে।",   romanization: "amago bari eikhane.",   english: "Our home is here." },
            ],
          },
          {
            title: "Khulna Future: দিমু / হইব",
            explanation: "Future tense: 'দেব' → 'দিমু' (will give), 'হবে' → 'হইব' (will happen). Time words: আজ→আইজ, গতকাল→গইকাল, আগামীকাল→আগাইলকাল.",
            examples: [
              { bangla: "আমি তোমারে দিমু।", romanization: "ami tomare dimu.", english: "I will give you." },
              { bangla: "এইডা হইব না।",     romanization: "eida hoib na.",    english: "This will not happen." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "khu-2-0",
          title: "Respect & Affection",
          description: "Say 'I love you' and express care in Khulna",
          unit: 2,
          order: 0,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-2-0-mp-1",
              pairs: [
                { bangla: "আপনে",            english: "You (formal)",   romanization: "apne"           },
                { bangla: "তোমারে মায়া করি", english: "I love / care for you", romanization: "tomare maya kori" },
                { bangla: "আমাগো",           english: "Our",            romanization: "amago"          },
                { bangla: "লাই",             english: "For",            romanization: "lai"            },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-2-0-tte-1",
              bangla: "আমি তোমারে ভালোবাসি।",
              romanization: "ami tomare bhalobashi.",
              answer: "I love you.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-0-mc-1",
              prompt: "Khulna uses '-রে' as an object marker. 'You' (object) becomes:",
              options: ["তোমায়", "তোমারে", "তোমার", "তুমি"],
              correct: 1,
              xp: 5,
            },
          ],
        },
        {
          id: "khu-2-1",
          title: "Sweet Questions",
          description: "Ask questions in Khulna dialect",
          unit: 2,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-2-1-tte-1",
              bangla: "তুমি এহন কই আসো?",
              romanization: "tumi ehon koi aso?",
              answer: "Where are you now?",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "khu-2-1-fb-1",
              sentence: "আমি তোমার ___ আইতেছি।",
              blank: "লাই",
              romanization: "ami tomar ___ aiteshi.",
              options: ["লাই", "এহন", "রাইত", "কই"],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-1-mc-1",
              prompt: "In Khulna, the progressive 'am coming' is:",
              options: ["আসছি", "আইলাম", "আইতেছি", "আইজ"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "khu-2-2",
          title: "Numbers 1–10",
          description: "Count from one to ten",
          unit: 2,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-2-2-mp-1",
              pairs: [
                { bangla: "এক",   english: "One",   romanization: "ek"    },
                { bangla: "দুই",  english: "Two",   romanization: "dui"   },
                { bangla: "তিন",  english: "Three", romanization: "tin"   },
                { bangla: "চার",  english: "Four",  romanization: "char"  },
              ],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-2-2-mp-2",
              pairs: [
                { bangla: "পাঁচ", english: "Five",  romanization: "pach" },
                { bangla: "সাত",  english: "Seven", romanization: "shat" },
                { bangla: "নয়",  english: "Nine",  romanization: "noy"  },
                { bangla: "দশ",   english: "Ten",   romanization: "dosh" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-2-mc-1",
              prompt: "How do you say 'six' in Bangla?",
              options: ["পাঁচ", "সাত", "ছয়", "আট"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "khu-2-3",
          title: "Numbers 11–20",
          description: "Count from eleven to twenty",
          unit: 2,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-2-3-mp-1",
              pairs: [
                { bangla: "এগারো",  english: "Eleven",   romanization: "egaro"   },
                { bangla: "পনেরো",  english: "Fifteen",  romanization: "ponero"  },
                { bangla: "আঠারো",  english: "Eighteen", romanization: "atharo"  },
                { bangla: "বিশ",    english: "Twenty",   romanization: "bish"    },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-3-mc-1",
              prompt: "How do you say 'nineteen'?",
              options: ["আঠারো", "উনিশ", "বিশ", "সতেরো"],
              correct: 1,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-2-3-tte-1",
              bangla: "আমার বয়স তেরো।",
              romanization: "amar boyosh tero.",
              answer: "I am thirteen years old.",

              xp: 5,
            },
          ],
        },
        {
          id: "khu-2-4",
          title: "Time Words",
          description: "Morning, night, now — Khulna style",
          unit: 2,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-2-4-mp-1",
              pairs: [
                { bangla: "সকাল",  english: "Morning",   romanization: "shokal" },
                { bangla: "রাইত",  english: "Night",     romanization: "rait"   },
                { bangla: "এহন",   english: "Now",       romanization: "ehon"   },
                { bangla: "আইতেছি", english: "Am coming", romanization: "aiteshi" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-2-4-tte-1",
              bangla: "আমি এহন আইতেছি।",
              romanization: "ami ehon aiteshi.",
              answer: "I am coming now.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-4-mc-1",
              prompt: "In Khulna, 'night' (রাত in Standard) becomes:",
              options: ["রাইত", "এহন", "আইজ", "লাই"],
              correct: 0,
              xp: 5,
            },
          ],
        },
        {
          id: "khu-2-5",
          title: "Today / Yesterday / Tomorrow",
          description: "Talk about days in Khulna — quiz time!",
          unit: 2,
          order: 5,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "khu-2-5-mc-1",
              prompt: "In Khulna, 'today' (আজ) is:",
              options: ["গইকাল", "আইজ", "আগাইলকাল", "এহন"],
              correct: 1,
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-2-5-mc-2",
              prompt: "In Khulna, 'yesterday' (গতকাল) is:",
              options: ["আইজ", "আগাইলকাল", "গইকাল", "কাইল"],
              correct: 2,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "khu-2-5-tte-1",
              bangla: "আমি আগাইলকাল দিমু।",
              romanization: "ami agailkal dimu.",
              answer: "I will give (it) tomorrow.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-2-5-ttb-1",
              english: "I am coming for you.",
              answer: "আমি তোমার লাই আইতেছি।",
              romanization: "ami tomar lai aiteshi.",
              xp: 5,
            },
          ],
        },
      ],
    },
    // ─── Unit 3 ───────────────────────────────────────────────────────────────
    {
      id: "khu-unit-3",
      title: "Food & Daily Life",
      description: "Khulna kitchen talk with -তেছি progressive and market haggling.",
      color: "#0e7490",
      order: 3,
      prep: {
        flashcards: [
          { id: "fc-khu-3-1",  bangla: "ভাত",         romanization: "vhat",       english: "cooked rice",      emoji: "🍚", category: "food" },
          { id: "fc-khu-3-2",  bangla: "মাছ",          romanization: "mach",       english: "fish",             emoji: "🐟", category: "food" },
          { id: "fc-khu-3-3",  bangla: "ডাল",          romanization: "dal",        english: "lentils",          emoji: "🫘", category: "food" },
          { id: "fc-khu-3-4",  bangla: "সবজি",         romanization: "shobji",     english: "vegetables",       emoji: "🥦", category: "food" },
          { id: "fc-khu-3-5",  bangla: "পানি",         romanization: "pani",       english: "water",            emoji: "💧", category: "food" },
          { id: "fc-khu-3-6",  bangla: "চা",           romanization: "cha",        english: "tea",              emoji: "🍵", category: "food" },
          { id: "fc-khu-3-7",  bangla: "দুধ",          romanization: "dudh",       english: "milk",             emoji: "🥛", category: "food" },
          { id: "fc-khu-3-8",  bangla: "রুটি",         romanization: "ruti",       english: "bread / roti",     emoji: "🫓", category: "food" },
          { id: "fc-khu-3-9",  bangla: "মাংস",         romanization: "mangsho",    english: "meat",             emoji: "🍖", category: "food" },
          { id: "fc-khu-3-10", bangla: "ফল",           romanization: "fol",        english: "fruit",            emoji: "🍎", category: "food" },
          { id: "fc-khu-3-11", bangla: "খাইতেছি",     romanization: "khaiteshi",  english: "I am eating",      emoji: "😋", category: "verb" },
          { id: "fc-khu-3-12", bangla: "রানতেছি",     romanization: "ranteshi",   english: "I am cooking",     emoji: "👨‍🍳", category: "verb" },
          { id: "fc-khu-3-13", bangla: "বাজার",        romanization: "bajar",      english: "market",           emoji: "🛒", category: "place" },
          { id: "fc-khu-3-14", bangla: "দোকান",        romanization: "dokan",      english: "shop",             emoji: "🏪", category: "place" },
          { id: "fc-khu-3-15", bangla: "বাড়ি",         romanization: "bari",       english: "home",             emoji: "🏠", category: "place" },
          { id: "fc-khu-3-16", bangla: "ঘর",           romanization: "ghor",       english: "room",             emoji: "🚪", category: "place" },
          { id: "fc-khu-3-17", bangla: "রান্নাঘর",     romanization: "rannaghor",  english: "kitchen",          emoji: "🍳", category: "place" },
          { id: "fc-khu-3-18", bangla: "বিছানা",       romanization: "bishana",    english: "bed",              emoji: "🛏️", category: "home" },
          { id: "fc-khu-3-19", bangla: "খিদা",         romanization: "khida",      english: "hunger",           emoji: "😩", category: "feeling" },
          { id: "fc-khu-3-20", bangla: "পেট ভরা",      romanization: "pet vhora",  english: "stomach full",     emoji: "😌", category: "feeling" },
          { id: "fc-khu-3-21", bangla: "কিনমু",        romanization: "kinmu",      english: "I will buy",       emoji: "🛍️", category: "verb" },
          { id: "fc-khu-3-22", bangla: "দামটা",        romanization: "damta",      english: "the price",        emoji: "💰", category: "market" },
          { id: "fc-khu-3-23", bangla: "সস্তা",        romanization: "shoshta",    english: "cheap",            emoji: "🏷️", category: "market" },
          { id: "fc-khu-3-24", bangla: "দামী",         romanization: "dami",       english: "expensive",        emoji: "💎", category: "market" },
          { id: "fc-khu-3-25", bangla: "ঘুমাইতেছি",   romanization: "ghumaiteshi",english: "I am sleeping",    emoji: "😴", category: "routine" },
          { id: "fc-khu-3-26", bangla: "উইঠা যাই",    romanization: "uitha jai",  english: "I get up",         emoji: "🌅", category: "routine" },
          { id: "fc-khu-3-27", bangla: "গোসল",         romanization: "ghoshol",    english: "bath",             emoji: "🚿", category: "routine" },
          { id: "fc-khu-3-28", bangla: "কামে যাই",    romanization: "kame jai",   english: "I go to work",     emoji: "💼", category: "routine" },
        ],
        characters: [],
        grammar: [
          {
            title: "-তেছি progressive in Khulna",
            explanation: "Khulna uses -তেছি for ongoing actions: খাইতেছি (am eating), আইতেছি (am coming), রানতেছি (am cooking).",
            examples: [
              { bangla: "আমি ভাত খাইতেছি।",  romanization: "ami vhat khaiteshi.",  english: "I am eating rice." },
              { bangla: "মা রান্না রানতেছে।",  romanization: "ma ranna ranteshe.",   english: "Mother is cooking." },
            ],
          },
          {
            title: "কিনমু — Khulna future",
            explanation: "Khulna future: কিনমু (I will buy), দিমু (I will give), যামু (I will go) — same -মু suffix as Barisali.",
            examples: [
              { bangla: "আমি বাজার থাইকা মাছ কিনমু।", romanization: "ami bajar thaika mach kinmu.", english: "I will buy fish from the market." },
              { bangla: "তোমারে চা দিমু।",             romanization: "tomare cha dimu.",             english: "I will give you tea." },
            ],
          },
          {
            title: "তোমারে — object marker in Khulna",
            explanation: "Khulna uses -রে as the object suffix: তোমারে (to you), আমারে (to me) — not standard তোমাকে.",
            examples: [
              { bangla: "তোমারে মাছ দিমু।",  romanization: "tomare mach dimu.",   english: "I will give you fish." },
              { bangla: "আমারে চা দাও।",      romanization: "amare cha dao.",       english: "Give me tea." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "khu-3-1",
          title: "Rice & Fish",
          description: "Food staples: rice, fish, and lentils in Khulna dialect",
          unit: 3,
          order: 1,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "khu-3-1-mc-1",
              prompt: "Khulna 'I am eating' uses:",
              options: ["খাইতাছি", "খাইতেছি", "খাচ্ছি", "খাইছি"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-3-1-tte-1",
              bangla: "আমি ভাত আর মাছ খাইতেছি।",
              romanization: "ami vhat ar mach khaiteshi.",
              answer: "I am eating rice and fish.",

              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-3-1-mp-1",
              pairs: [
                { bangla: "ভাত",  english: "rice", romanization: "bhat" },
                { bangla: "মাছ",  english: "fish", romanization: "mach" },
                { bangla: "ডাল",  english: "lentils", romanization: "dal" },
                { bangla: "পানি", english: "water", romanization: "pani" },
              ],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "khu-3-1-ttb-1",
              english: "I will eat fish and rice.",
              answer: "আমি মাছ আর ভাত খামু।",
              romanization: "ami mach ar vhat khamu.",
              xp: 5,
            },
          ],
        },
        {
          id: "khu-3-2",
          title: "At the Market",
          description: "Shopping at the market in Khulna dialect",
          unit: 3,
          order: 2,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "khu-3-2-mc-1",
              prompt: "Khulna 'I will buy' is:",
              options: ["কিনব", "কিনমু", "কিনুম", "কিনতেছি"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-3-2-tte-1",
              bangla: "বাজার থাইকা সবজি কিনমু।",
              romanization: "bajar thaika shobji kinmu.",
              answer: "I will buy vegetables from the market.",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "khu-3-2-fb-1",
              sentence: "দামটা অনেক ___।",
              romanization: "damta onek ___.",
              blank: "দামী",

              options: ["দামী"],

              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-3-2-mp-1",
              pairs: [
                { bangla: "বাজার",  english: "market", romanization: "bajar" },
                { bangla: "দোকান",  english: "shop", romanization: "dokan" },
                { bangla: "সস্তা",  english: "cheap", romanization: "shoshta" },
                { bangla: "দামী",   english: "expensive", romanization: "dami" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "khu-3-3",
          title: "In the Kitchen",
          description: "Kitchen vocabulary and cooking in Khulna",
          unit: 3,
          order: 3,
          xpReward: 20,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-3-3-tte-1",
              bangla: "মা রান্নাঘরে রান্না রানতেছে।",
              romanization: "ma rannaghor-e ranna ranteshe.",
              answer: "Mother is cooking in the kitchen.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-3-3-mc-1",
              prompt: "Khulna 'kitchen' is:",
              options: ["খাবার ঘর", "রান্নাঘর", "বিছানা ঘর", "কামের ঘর"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "khu-3-3-mp-1",
              pairs: [
                { bangla: "রান্নাঘর", english: "kitchen", romanization: "rannaghor" },
                { bangla: "বিছানা",   english: "bed", romanization: "bishana" },
                { bangla: "ঘর",       english: "room", romanization: "ghor" },
                { bangla: "বাড়ি",    english: "home", romanization: "bari" },
              ],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "khu-3-3-ttb-1",
              english: "I will cook at home.",
              answer: "আমি বাড়িতে রান্না রানমু।",
              romanization: "ami barite ranna ranmu.",
              xp: 5,
            },
          ],
        },
        {
          id: "khu-3-4",
          title: "Daily Routine",
          description: "Daily routine and meal times in Khulna",
          unit: 3,
          order: 4,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "khu-3-4-mc-1",
              prompt: "Khulna 'I am sleeping' uses -তেছি form:",
              options: ["ঘুমাইতাছি", "ঘুমাইতেছি", "ঘুমাচ্ছি", "ঘুমামু"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-3-4-tte-1",
              bangla: "ভোরে উইঠা গোসল করছি।",
              romanization: "vhore uitha ghoshol korshi.",
              answer: "I woke up early and bathed.",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "khu-3-4-fb-1",
              sentence: "সকালে উইঠা ___ করছি।",
              romanization: "shokale uitha ___ korshi.",
              blank: "গোসল",

              options: ["গোসল"],

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-3-4-ttb-1",
              english: "I go to work every day.",
              answer: "আমি প্রতিদিন কামে যাই।",
              romanization: "ami protidin kame jai.",
              xp: 5,
            },
          ],
        },
        {
          id: "khu-3-5",
          title: "Hunger & Fullness",
          description: "Expressing hunger and fullness in Khulna",
          unit: 3,
          order: 5,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "khu-3-5-mc-1",
              prompt: "Khulna word for 'hunger' is:",
              options: ["ক্ষুধা", "খিদা", "পেট", "তৃষ্ণা"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-3-5-tte-1",
              bangla: "আমার অনেক খিদা লাগছে।",
              romanization: "amar onek khida lagse.",
              answer: "I am very hungry.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-3-5-ttb-1",
              english: "Give me tea.",
              answer: "আমারে চা দাও।",
              romanization: "amare cha dao.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-3-5-mp-1",
              pairs: [
                { bangla: "খিদা",    english: "hunger", romanization: "khida" },
                { bangla: "পেট ভরা", english: "stomach full", romanization: "pet vhora" },
                { bangla: "পানি",    english: "water", romanization: "pani" },
                { bangla: "চা",      english: "tea", romanization: "cha" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "khu-3-6",
          title: "Food Quiz",
          description: "Food & Daily Life quiz — Khulna Unit 3",
          unit: 3,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "khu-3-6-mc-1",
              prompt: "Khulna progressive suffix is:",
              options: ["-তাছি", "-তেছি", "-ছি", "-ব"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-3-6-tte-1",
              bangla: "আমি বাজার থাইকা মাছ আর সবজি কিনমু।",
              romanization: "ami bajar thaika mach ar shobji kinmu.",
              answer: "I will buy fish and vegetables from the market.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-3-6-ttb-1",
              english: "Mother is cooking in the kitchen.",
              answer: "মা রান্নাঘরে রান্না রানতেছে।",
              romanization: "ma rannaghor-e ranna ranteshe.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "khu-3-6-fb-1",
              sentence: "আমার অনেক ___ লাগছে।",
              romanization: "amar onek ___ lagse.",
              blank: "খিদা",

              options: ["খিদা"],

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-3-6-mc-2",
              prompt: "Khulna 'Give me tea' uses which object marker?",
              options: ["আমাকে", "আমারে", "আমার", "আমাগো"],
              correct: 1,
              xp: 4,
            },
          ],
        },
      ],
    },
    {
      id: "khu-unit-4",
      title: "Numbers & Counting",
      description: "Count, ask prices, and tell the time in Khulna Bangla",
      order: 4,
      prep: {
        characters: [],
        grammar: [
          {
            title: "Khulna numbers",
            rule: "Numbers are the same as standard Bengali. The classifier -টা/-টি is used for objects. কয়টা? = how many? কত টাকা? = how much money?",
            examples: [
              { bangla: "কয়টা আম চাই?", romanization: "koyta am chai?", english: "How many mangoes do you want?" },
              { bangla: "পাঁচটা দেন।", romanization: "pachta den.", english: "Give me five." },
            ],
          },
          {
            title: "Telling the time in Khulna",
            rule: "কটা বাজে? = what time is it? (Khulna uses কটা, same as Barisali). The answer follows the pattern: [number]টা বাজে = it is [n] o'clock.",
            examples: [
              { bangla: "কটা বাজে?", romanization: "kota baje?", english: "What time is it?" },
              { bangla: "আটটা বাজে।", romanization: "atta baje.", english: "It is eight o'clock." },
            ],
          },
          {
            title: "Khulna market arithmetic",
            rule: "দাম কতো? = how much is the price? মোট কতো? = total how much? Khulna speakers often drop the final vowel: বিশ for 20, তিরিশ for 30.",
            examples: [
              { bangla: "মোট বিশ টাকা।", romanization: "mot bish taka.", english: "Total twenty taka." },
              { bangla: "দাম কতো?", romanization: "dam koto?", english: "What is the price?" },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "khu-4-1",
          title: "Numbers 1–10",
          description: "Core counting in Khulna Bangla",
          unit: 4,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-4-1-mp-1",
              pairs: [
                { bangla: "এক",   english: "one",   romanization: "ek"    },
                { bangla: "দুই",  english: "two",   romanization: "dui"   },
                { bangla: "তিন",  english: "three", romanization: "tin"   },
                { bangla: "চার",  english: "four",  romanization: "char"  },
                { bangla: "পাঁচ", english: "five",  romanization: "panch" },
              ],
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "khu-4-1-mc-1",
              prompt: "What is 'সাত' in English?",
              options: ["six", "seven", "eight", "nine"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "khu-4-1-mp-2",
              pairs: [
                { bangla: "ছয়",  english: "six",   romanization: "chhoy" },
                { bangla: "সাত", english: "seven", romanization: "shat"  },
                { bangla: "আট",  english: "eight", romanization: "at"    },
                { bangla: "নয়", english: "nine",  romanization: "noy"   },
                { bangla: "দশ",  english: "ten",   romanization: "dosh"  },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "khu-4-1-ttb-1",
              english: "Give me five mangoes.",
              answer: "পাঁচটা আম দেন।",
              romanization: "pachta am den.",
              xp: 6,
            },
            {
              type: "multiple_choice",
              id: "khu-4-1-mc-2",
              prompt: "Khulna classifier for counting objects is:",
              options: ["-খান", "-টা / -টি", "-বার", "-জন"],
              correct: 1,
              xp: 4,
            },
          ],
        },
        {
          id: "khu-4-2",
          title: "Numbers 11–20",
          description: "Teens and twenties in Khulna Bangla",
          unit: 4,
          order: 2,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-4-2-mp-1",
              pairs: [
                { bangla: "এগারো",  english: "eleven",  romanization: "egaro"  },
                { bangla: "বারো",   english: "twelve",  romanization: "baro"   },
                { bangla: "তেরো",   english: "thirteen", romanization: "tero"   },
                { bangla: "চোদ্দো", english: "fourteen", romanization: "chodo"  },
                { bangla: "পনেরো",  english: "fifteen", romanization: "ponero" },
              ],
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "khu-4-2-mc-1",
              prompt: "What is 'বিশ'?",
              options: ["fifteen", "sixteen", "twenty", "thirty"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-4-2-tte-1",
              bangla: "সতেরোটা মাছ।",
              romanization: "shaterta mach.",
              answer: "Seventeen fish.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "khu-4-2-fb-1",
              sentence: "আঠারো আর দুই = ___।",
              romanization: "atharo ar dui = ___.",
              blank: "বিশ",
              options: ["উনিশ", "বিশ", "একুশ", "বাইশ"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-4-2-ttb-1",
              english: "I want twenty takas.",
              answer: "বিশ টাকা চাই।",
              romanization: "bish taka chai.",
              xp: 6,
            },
          ],
        },
        {
          id: "khu-4-3",
          title: "Tens & Hundreds",
          description: "Bigger numbers for the Khulna market",
          unit: 4,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-4-3-mp-1",
              pairs: [
                { bangla: "বিশ",    english: "twenty",   romanization: "bish"   },
                { bangla: "ত্রিশ",  english: "thirty",   romanization: "trish"  },
                { bangla: "চল্লিশ", english: "forty",    romanization: "challish" },
                { bangla: "পঞ্চাশ", english: "fifty",    romanization: "ponchash" },
                { bangla: "একশো",  english: "hundred",  romanization: "ekshо"  },
              ],
              xp: 8,
            },
            {
              type: "translate_to_english",
              id: "khu-4-3-tte-1",
              bangla: "মোট একশো টাকা।",
              romanization: "mot ekshо taka.",
              answer: "Total one hundred taka.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-4-3-mc-1",
              prompt: "A seller says 'পঞ্চাশ টাকা' — how much?",
              options: ["30 taka", "40 taka", "50 taka", "60 taka"],
              correct: 2,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "khu-4-3-fb-1",
              sentence: "পঞ্চাশ আর পঞ্চাশ = ___ টাকা।",
              romanization: "ponchash ar ponchash = ___ taka.",
              blank: "একশো",
              options: ["নব্বই", "একশো", "আশি", "ষাট"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-4-3-ttb-1",
              english: "How much is the price?",
              answer: "দাম কতো?",
              romanization: "dam koto?",
              xp: 5,
            },
          ],
        },
        {
          id: "khu-4-4",
          title: "Telling the Time",
          description: "Ask and say the time in Khulna Bangla",
          unit: 4,
          order: 4,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "khu-4-4-mc-1",
              prompt: "How do you ask 'What time is it?' in Khulna?",
              options: ["কত বাজে?", "কটা বাজে?", "কতদূর?", "কয়খান?"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-4-4-tte-1",
              bangla: "আটটা বাজে।",
              romanization: "atta baje.",
              answer: "It is eight o'clock.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-4-4-mp-1",
              pairs: [
                { bangla: "একটা বাজে",   english: "it is one o'clock",   romanization: "ekta baje"   },
                { bangla: "তিনটা বাজে",  english: "it is three o'clock", romanization: "tinta baje"  },
                { bangla: "ছয়টা বাজে",  english: "it is six o'clock",   romanization: "chhoyta baje" },
                { bangla: "দশটা বাজে",   english: "it is ten o'clock",   romanization: "doshta baje" },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "khu-4-4-fb-1",
              sentence: "___ বাজে। (It is five o'clock)",
              romanization: "___ baje.",
              blank: "পাঁচটা",
              options: ["চারটা", "পাঁচটা", "ছয়টা", "সাতটা"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-4-4-ttb-1",
              english: "What time is it?",
              answer: "কটা বাজে?",
              romanization: "kota baje?",
              xp: 5,
            },
          ],
        },
        {
          id: "khu-4-5",
          title: "Numbers Review",
          description: "Numbers, prices, and time — full Khulna review",
          unit: 4,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-4-5-tte-1",
              bangla: "কয়টা বাজে? — সাতটা বাজে।",
              romanization: "koyta baje? — shatta baje.",
              answer: "What time is it? — It is seven o'clock.",
              xp: 6,
            },
            {
              type: "multiple_choice",
              id: "khu-4-5-mc-1",
              prompt: "A vendor says 'তিরিশ টাকা' — how much?",
              options: ["20 taka", "25 taka", "30 taka", "35 taka"],
              correct: 2,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "khu-4-5-fb-1",
              sentence: "দশটা মাছ ___ টাকা।",
              romanization: "doshta mach ___ taka.",
              blank: "একশো",
              options: ["দশ", "পঞ্চাশ", "একশো", "বিশ"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-4-5-mp-1",
              pairs: [
                { bangla: "কটা বাজে?",   english: "what time is it?",    romanization: "kota baje?"    },
                { bangla: "দাম কতো?",    english: "how much?",           romanization: "dam koto?"     },
                { bangla: "কয়টা?",      english: "how many?",           romanization: "koyta?"        },
                { bangla: "মোট",         english: "total",               romanization: "mot"           },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "khu-4-5-ttb-1",
              english: "Give me ten fish for fifty taka.",
              answer: "পঞ্চাশ টাকায় দশটা মাছ দেন।",
              romanization: "ponchash takay doshta mach den.",
              xp: 8,
            },
          ],
        },
      ],
    },
    {
      id: "khu-unit-5",
      title: "Getting Around",
      description: "Transport and directions through the Khulna Sundarbans gateway",
      order: 5,
      prep: {
        characters: [],
        grammar: [
          {
            title: "Khulna transport — river and road",
            rule: "Khulna sits at the Sundarbans delta. নৌকা (boat) and লঞ্চ (ferry) alongside রিকশা (rickshaw) and বাস (bus). Khulna future: যামু = I will go (-মু ending).",
            examples: [
              { bangla: "লঞ্চে যামু।", romanization: "launch-e jamu.", english: "I will go by ferry." },
              { bangla: "রিকশায় যাই।", romanization: "rikshay jai.", english: "I go by rickshaw." },
            ],
          },
          {
            title: "Direction words in Khulna",
            rule: "বামে = to the left, ডানে = to the right, সামনে = ahead, পিছনে = behind. Khulna uses the same direction words as standard Bengali.",
            examples: [
              { bangla: "বামে যাও।", romanization: "bame jao.", english: "Go left." },
              { bangla: "ডানে যাও।", romanization: "dane jao.", english: "Go right." },
            ],
          },
          {
            title: "Asking how far — কতদূর?",
            rule: "কতদূর? = how far? নিকটে = nearby (Khulna literary form). কাছেই = nearby (colloquial).",
            examples: [
              { bangla: "সুন্দরবন কতদূর?", romanization: "shundorbon kotodur?", english: "How far is the Sundarbans?" },
              { bangla: "কাছেই আছে।", romanization: "kachei ache.", english: "It's nearby." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "khu-5-1",
          title: "River & Road",
          description: "Transport through Khulna's waterways and streets",
          unit: 5,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-5-1-mp-1",
              pairs: [
                { bangla: "নৌকা",  english: "boat",     romanization: "nouka"  },
                { bangla: "লঞ্চ",  english: "ferry",    romanization: "launch" },
                { bangla: "রিকশা", english: "rickshaw", romanization: "riksha" },
                { bangla: "বাস",   english: "bus",      romanization: "bas"    },
              ],
              xp: 8,
            },
            {
              type: "translate_to_english",
              id: "khu-5-1-tte-1",
              bangla: "লঞ্চে যামু।",
              romanization: "launch-e jamu.",
              answer: "I will go by ferry.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-5-1-mc-1",
              prompt: "Khulna is the gateway to which famous forest?",
              options: ["Haor wetlands", "Sundarbans", "Chittagong hills", "Madhupur forest"],
              correct: 1,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "khu-5-1-fb-1",
              sentence: "নৌকায় ___ পার হই।",
              romanization: "noukay ___ par hoi.",
              blank: "নদী",
              options: ["বাজার", "নদী", "রাস্তা", "ঘাট"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-5-1-ttb-1",
              english: "I go by bus.",
              answer: "আমি বাসে যাই।",
              romanization: "ami base jai.",
              xp: 6,
            },
          ],
        },
        {
          id: "khu-5-2",
          title: "Directions",
          description: "Find your way around Khulna city",
          unit: 5,
          order: 2,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-5-2-tte-1",
              bangla: "ডানে যাও।",
              romanization: "dane jao.",
              answer: "Go right.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-5-2-mc-1",
              prompt: "What does 'সামনে' mean?",
              options: ["behind", "left", "right", "ahead"],
              correct: 3,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "khu-5-2-mp-1",
              pairs: [
                { bangla: "বামে",    english: "left",   romanization: "bame"   },
                { bangla: "ডানে",    english: "right",  romanization: "dane"   },
                { bangla: "সামনে",  english: "ahead",  romanization: "shamne" },
                { bangla: "পিছনে",  english: "behind", romanization: "pichone"},
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "khu-5-2-fb-1",
              sentence: "বাজার ___ দিকে।",
              romanization: "bazar ___ dike.",
              blank: "বামে",
              options: ["ডানে", "বামে", "সামনে", "পিছনে"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-5-2-ttb-1",
              english: "The Sundarbans is ahead.",
              answer: "সুন্দরবন সামনে।",
              romanization: "shundorbon shamne.",
              xp: 6,
            },
          ],
        },
        {
          id: "khu-5-3",
          title: "How Far?",
          description: "Ask about distance in Khulna",
          unit: 5,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "khu-5-3-mc-1",
              prompt: "How do you ask 'how far?' in Khulna Bangla?",
              options: ["কতদূর?", "কতক্ষণ?", "কতো দাম?", "কোথায়?"],
              correct: 0,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-5-3-tte-1",
              bangla: "সুন্দরবন কতদূর?",
              romanization: "shundorbon kotodur?",
              answer: "How far is the Sundarbans?",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "khu-5-3-fb-1",
              sentence: "স্টেশন ___ দূরে।",
              romanization: "steshan ___ dure.",
              blank: "অনেক",
              options: ["কাছে", "অনেক", "কম", "এখানে"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-5-3-ttb-1",
              english: "The market is nearby.",
              answer: "বাজার কাছেই আছে।",
              romanization: "bazar kachei ache.",
              xp: 6,
            },
            {
              type: "multiple_choice",
              id: "khu-5-3-mc-2",
              prompt: "What does 'কাছেই আছে' mean?",
              options: ["It is far", "Very expensive", "It is nearby", "To the right"],
              correct: 2,
              xp: 4,
            },
          ],
        },
        {
          id: "khu-5-4",
          title: "Tickets & Schedules",
          description: "Buy tickets and navigate Khulna transport",
          unit: 5,
          order: 4,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-5-4-tte-1",
              bangla: "দুইটা টিকেট দেন।",
              romanization: "duita tiket den.",
              answer: "Give me two tickets.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-5-4-mc-1",
              prompt: "How do you ask 'when does the ferry leave?'",
              options: ["লঞ্চ কতদূর?", "লঞ্চ কখন ছাড়ে?", "লঞ্চ কয়টা?", "লঞ্চ কোথায়?"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "khu-5-4-mp-1",
              pairs: [
                { bangla: "টিকেট",    english: "ticket",    romanization: "tiket"    },
                { bangla: "ঘাট",      english: "dock",      romanization: "ghat"     },
                { bangla: "ছাড়া",    english: "to leave",  romanization: "chara"    },
                { bangla: "পৌঁছানো", english: "to arrive", romanization: "pouchano" },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "khu-5-4-fb-1",
              sentence: "লঞ্চ কখন ___ ?",
              romanization: "launch kokhon ___ ?",
              blank: "ছাড়ে",
              options: ["আসে", "ছাড়ে", "থামে", "যায়"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-5-4-ttb-1",
              english: "When does the boat arrive?",
              answer: "নৌকা কখন পৌঁছাবে?",
              romanization: "nouka kokhon pouchabe?",
              xp: 7,
            },
          ],
        },
        {
          id: "khu-5-5",
          title: "Transport Review",
          description: "Full review of Khulna transport and directions",
          unit: 5,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-5-5-tte-1",
              bangla: "আমি লঞ্চে সুন্দরবনে যামু।",
              romanization: "ami launch-e shundorbane jamu.",
              answer: "I will go to the Sundarbans by ferry.",
              xp: 7,
            },
            {
              type: "multiple_choice",
              id: "khu-5-5-mc-1",
              prompt: "You want to go left. What do you say in Khulna Bangla?",
              options: ["ডানে যাও।", "সামনে যাও।", "বামে যাও।", "পিছনে যাও।"],
              correct: 2,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "khu-5-5-fb-1",
              sentence: "ঘাট ___ দূরে।",
              romanization: "ghat ___ dure.",
              blank: "অনেক",
              options: ["কাছে", "অনেক", "কম", "সামনে"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-5-5-mp-1",
              pairs: [
                { bangla: "কতদূর?",     english: "how far?",           romanization: "kotodur?"      },
                { bangla: "লঞ্চে যামু", english: "I will go by ferry", romanization: "launch-e jamu" },
                { bangla: "ঘাট",        english: "dock",               romanization: "ghat"          },
                { bangla: "কাছেই",      english: "nearby",             romanization: "kachei"        },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "khu-5-5-ttb-1",
              english: "The market is to the right.",
              answer: "বাজার ডানে।",
              romanization: "bazar dane.",
              xp: 6,
            },
          ],
        },
      ],
    },
    {
      id: "khu-unit-6",
      title: "Health & Body",
      description: "Body parts, illness, and medicine in Khulna Bangla",
      order: 6,
      prep: {
        characters: [],
        grammar: [
          {
            title: "Expressing pain — Khulna style",
            rule: "ব্যথা করতেছি (Khulna -তেছি progressive) = 'is hurting me'. Example: মাথা ব্যথা করতেছে = My head is hurting.",
            examples: [
              { bangla: "পেট ব্যথা করতেছে।", romanization: "pet betha kortechhe.", english: "My stomach is hurting." },
              { bangla: "হাত ব্যথা করতেছে।", romanization: "hat betha kortechhe.", english: "My hand is hurting." },
            ],
          },
          {
            title: "Feeling unwell in Khulna",
            rule: "আমি অসুস্থ (I am unwell). জ্বর আইছে = I have a fever (আইছে = Khulna 'has come'). ঠান্ডা লাগতেছে = I feel cold (-তেছে progressive).",
            examples: [
              { bangla: "আমি অসুস্থ।", romanization: "ami oshustho.", english: "I am unwell." },
              { bangla: "জ্বর আইছে।", romanization: "jor aiche.", english: "I have a fever." },
            ],
          },
          {
            title: "Medicine — ওষুধ",
            rule: "ডাক্তার দেখাতে হইব = I need to see a doctor (Khulna: হইব). ওষুধ খাওয়া = taking medicine.",
            examples: [
              { bangla: "ডাক্তার দেখাতে হইব।", romanization: "daktar dekhate hoibo.", english: "I need to see a doctor." },
              { bangla: "ওষুধ খাও।", romanization: "oshud khao.", english: "Take the medicine." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "khu-6-1",
          title: "Body Parts",
          description: "Head to toe in Khulna Bangla",
          unit: 6,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "khu-6-1-mp-1",
              pairs: [
                { bangla: "মাথা",  english: "head",    romanization: "matha" },
                { bangla: "হাত",   english: "hand",    romanization: "hat"   },
                { bangla: "পা",    english: "foot",    romanization: "pa"    },
                { bangla: "চোখ",   english: "eye",     romanization: "chokh" },
                { bangla: "পেট",   english: "stomach", romanization: "pet"   },
              ],
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "khu-6-1-mc-1",
              prompt: "What does 'কান' mean?",
              options: ["eye", "nose", "ear", "mouth"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-6-1-tte-1",
              bangla: "নাক আর মুখ।",
              romanization: "nak ar mukh.",
              answer: "Nose and mouth.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "khu-6-1-fb-1",
              sentence: "___ দিয়া শুনি।",
              romanization: "___ diya shuni.",
              blank: "কান",
              options: ["মাথা", "কান", "চোখ", "নাক"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-6-1-ttb-1",
              english: "My back is hurting. (Khulna -তেছে)",
              answer: "পিঠ ব্যথা করতেছে।",
              romanization: "pith betha kortechhe.",
              xp: 6,
            },
          ],
        },
        {
          id: "khu-6-2",
          title: "Feeling Unwell",
          description: "Describe symptoms using the Khulna -তেছে progressive",
          unit: 6,
          order: 2,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-6-2-tte-1",
              bangla: "আমি অসুস্থ।",
              romanization: "ami oshustho.",
              answer: "I am unwell.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-6-2-mc-1",
              prompt: "Khulna way to say 'I have a fever' is:",
              options: ["জ্বর আসছে।", "জ্বর আইছে।", "জ্বর হবে।", "জ্বর করি।"],
              correct: 1,
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-6-2-mp-1",
              pairs: [
                { bangla: "জ্বর",     english: "fever",   romanization: "jor"      },
                { bangla: "ব্যথা",    english: "pain",    romanization: "betha"    },
                { bangla: "ঠান্ডা",  english: "cold",    romanization: "thanda"   },
                { bangla: "অসুস্থ",  english: "unwell",  romanization: "oshustho" },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "khu-6-2-fb-1",
              sentence: "মাথা ব্যথা ___ ।",
              romanization: "matha betha ___ .",
              blank: "করতেছে",
              options: ["আইছে", "করতেছে", "হইব", "যাইব"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-6-2-ttb-1",
              english: "I feel cold. (Khulna progressive)",
              answer: "ঠান্ডা লাগতেছে।",
              romanization: "thanda lagtechhe.",
              xp: 6,
            },
          ],
        },
        {
          id: "khu-6-3",
          title: "At the Doctor",
          description: "Visit the doctor in Khulna Bangla",
          unit: 6,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "khu-6-3-mc-1",
              prompt: "What does 'হাসপাতাল' mean?",
              options: ["clinic", "doctor", "hospital", "pharmacy"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "khu-6-3-tte-1",
              bangla: "ডাক্তার দেখাতে হইব।",
              romanization: "daktar dekhate hoibo.",
              answer: "I need to see a doctor.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-6-3-mp-1",
              pairs: [
                { bangla: "ডাক্তার",   english: "doctor",   romanization: "daktar"    },
                { bangla: "হাসপাতাল", english: "hospital", romanization: "hashpatal" },
                { bangla: "ওষুধ",      english: "medicine", romanization: "oshud"     },
                { bangla: "নার্স",     english: "nurse",    romanization: "nars"      },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "khu-6-3-fb-1",
              sentence: "ডাক্তারের কাছে যাইতে ___ ।",
              romanization: "daktarer kache jaite ___ .",
              blank: "হইব",
              options: ["লাগব", "হইব", "পারব", "যাইব"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "khu-6-3-ttb-1",
              english: "Take the medicine.",
              answer: "ওষুধ খাও।",
              romanization: "oshud khao.",
              xp: 6,
            },
          ],
        },
        {
          id: "khu-6-4",
          title: "Medicine & Care",
          description: "Pharmacy visits and dosage in Khulna",
          unit: 6,
          order: 4,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-6-4-tte-1",
              bangla: "দিনে তিনবার ওষুধ খাও।",
              romanization: "dine tinbar oshud khao.",
              answer: "Take medicine three times a day.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "khu-6-4-mc-1",
              prompt: "A pharmacist says 'খাওয়ার পরে খাইবেন' — when should you take it?",
              options: ["Before eating", "After eating", "On an empty stomach", "Before sleeping"],
              correct: 1,
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "khu-6-4-fb-1",
              sentence: "দুইটা ট্যাবলেট ___ পরে খাও।",
              romanization: "duita tablet ___ pore khao.",
              blank: "খাওয়ার",
              options: ["ঘুমের", "খাওয়ার", "হাঁটার", "কাজের"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-6-4-mp-1",
              pairs: [
                { bangla: "ফার্মেসি",    english: "pharmacy",     romanization: "pharmeshi"   },
                { bangla: "ট্যাবলেট",   english: "tablet",       romanization: "tablet"      },
                { bangla: "দিনে",       english: "per day",      romanization: "dine"        },
                { bangla: "খাওয়ার পরে", english: "after eating", romanization: "khawar pore" },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "khu-6-4-ttb-1",
              english: "Give me two tablets.",
              answer: "দুইটা ট্যাবলেট দেন।",
              romanization: "duita tablet den.",
              xp: 6,
            },
          ],
        },
        {
          id: "khu-6-5",
          title: "Health Review",
          description: "Full review of health and body in Khulna Bangla",
          unit: 6,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "khu-6-5-tte-1",
              bangla: "পেট ব্যথা করতেছে, ডাক্তারের কাছে যাইতে হইব।",
              romanization: "pet betha kortechhe, daktarer kache jaite hoibo.",
              answer: "My stomach is hurting, I need to go to the doctor.",
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "khu-6-5-mc-1",
              prompt: "The Khulna progressive suffix is:",
              options: ["-ছে", "-তেছে", "-মু", "-ইছি"],
              correct: 1,
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "khu-6-5-fb-1",
              sentence: "আমি ___ আছি।",
              romanization: "ami ___ achi.",
              blank: "অসুস্থ",
              options: ["ভালো", "অসুস্থ", "সুস্থ", "খুশি"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "khu-6-5-mp-1",
              pairs: [
                { bangla: "মাথা ব্যথা",  english: "headache",             romanization: "matha betha"  },
                { bangla: "জ্বর আইছে",   english: "have a fever (Khulna)", romanization: "jor aiche"    },
                { bangla: "ওষুধ",        english: "medicine",             romanization: "oshud"        },
                { bangla: "হাসপাতাল",   english: "hospital",             romanization: "hashpatal"    },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "khu-6-5-ttb-1",
              english: "My hand is hurting. (Khulna)",
              answer: "হাত ব্যথা করতেছে।",
              romanization: "hat betha kortechhe.",
              xp: 7,
            },
          ],
        },
      ],
    },
  ],
};
