import type { DialectCurriculum } from "@bangla-learn/types";

export const rajshahiCurriculum: DialectCurriculum = {
  dialect: "rajshahi",
  units: [
    {
      id: "raj-unit-1",
      title: "Rajshahi Bangla Basics",
      description: "Learn Rajshahi Bangla — the regional variety of Bangladesh's northwestern division",
      order: 1,
      color: "#16a34a",
      prep: {
        characters: [
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আমি (I)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইচ্ছা (wish)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠা (to rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এক (one)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওরা (they)" },
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কেমন (how)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খাওয়া (eating)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলাম (I went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালো (good)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মা (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাত (night)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সে (he/she)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হ্যাঁ (yes)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তোমার (your)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পরিবার (family)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বাবা (father)" },
          { symbol: "জ", romanization: "j",   type: "consonant" as const, exampleWord: "জানি (I know)" },
          { symbol: "ধ", romanization: "dh",  type: "consonant" as const, exampleWord: "ধন্যবাদ (thank you)" },
        ],
        flashcards: [
          { id: "fc-raj-1",  bangla: "আমি",       romanization: "ami",       english: "I",                   category: "pronouns"  },
          { id: "fc-raj-2",  bangla: "তুমি",       romanization: "tumi",      english: "You (familiar)",      category: "pronouns"  },
          { id: "fc-raj-3",  bangla: "আপনি",       romanization: "apni",      english: "You (polite)",        category: "pronouns"  },
          { id: "fc-raj-4",  bangla: "সে",          romanization: "shey",      english: "He / She",            category: "pronouns"  },
          { id: "fc-raj-5",  bangla: "আমরা",       romanization: "amra",      english: "We",                  category: "pronouns"  },
          { id: "fc-raj-6",  bangla: "তারা",       romanization: "tara",      english: "They",                category: "pronouns"  },
          { id: "fc-raj-7",  bangla: "ভালো",       romanization: "bhalo",     english: "Good / Fine",         category: "adjectives"},
          { id: "fc-raj-8",  bangla: "হ্যাঁ",      romanization: "hya",       english: "Yes",                 category: "phrases"   },
          { id: "fc-raj-9",  bangla: "না",          romanization: "na",        english: "No",                  category: "phrases"   },
          { id: "fc-raj-10", bangla: "ঠিক আছে",    romanization: "thik ache", english: "Okay",                category: "phrases"   },
          { id: "fc-raj-11", bangla: "ধন্যবাদ",    romanization: "dhonnobad", english: "Thank you",           category: "phrases"   },
          { id: "fc-raj-12", bangla: "মাফ করবেন", romanization: "maf korben",english: "Excuse me",           category: "phrases"   },
          { id: "fc-raj-13", bangla: "মা",          romanization: "ma",        english: "Mother",              category: "family"    },
          { id: "fc-raj-14", bangla: "বাবা",        romanization: "baba",      english: "Father",              category: "family"    },
          { id: "fc-raj-15", bangla: "বোন",         romanization: "bon",       english: "Sister",              category: "family"    },
          { id: "fc-raj-16", bangla: "ভাই",         romanization: "bhai",      english: "Brother",             category: "family"    },
        ],
        grammar: [
          {
            title: "Standard-compatible grammar",
            explanation: "Rajshahi Bangla is close to Standard Bangla in grammar, making it a natural transition track. Use standard verb endings early; regional pronunciation differences appear mainly in audio.",
            examples: [
              { bangla: "আমি ভালো আছি।",       romanization: "ami bhalo achi.",       english: "I am fine." },
              { bangla: "তুমি কেমন আছো?",       romanization: "tumi kemon acho?",      english: "How are you?" },
            ],
          },
          {
            title: "Familiar vs polite 'you'",
            explanation: "Like Standard Bangla, Rajshahi uses তুমি for familiar and আপনি for polite. সে means he/she and তারা means they.",
            examples: [
              { bangla: "আপনি কেমন আছেন?",     romanization: "apni kemon achen?",    english: "How are you? (polite)" },
              { bangla: "সে আমার বন্ধু।",       romanization: "shey amar bondhu.",     english: "He/She is my friend." },
            ],
          },
          {
            title: "Possession with আমার / তোমার",
            explanation: "Use আমার for 'my' and তোমার for 'your' (familiar). আমার নাম means 'my name.'",
            examples: [
              { bangla: "আমার নাম ___।",        romanization: "amar nam ___.",         english: "My name is ___." },
              { bangla: "তোমার নাম কী?",         romanization: "tomar nam ki?",         english: "What is your name?" },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "raj-1-0",
          title: "Write the Letters",
          description: "Trace key Bengali letters used in Rajshahi Bangla",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "raj-1-0-tr-1", character: "আ", romanization: "aa",  exampleWord: "আমি — I",          xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-2", character: "ন", romanization: "n",   exampleWord: "নাম — name",       xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-3", character: "ম", romanization: "m",   exampleWord: "মা — mother",      xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-4", character: "ভ", romanization: "bh",  exampleWord: "ভালো — good",     xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-5", character: "স", romanization: "s",   exampleWord: "সে — he/she",      xp: 4 },
          ],
        },
        {
          id: "raj-1-1",
          title: "Greetings",
          description: "Greet, ask a name, and give a basic reply in Rajshahi-based Bangla",
          unit: 1,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-1-mp-1",
              pairs: [
                { bangla: "আসসালামু আলাইকুম", english: "Hello (Islamic greeting)", romanization: "assalamu alaikum" },
                { bangla: "নমস্কার",            english: "Hello / Greetings",        romanization: "nomoshkar"        },
                { bangla: "ভালো",              english: "Good / Fine",              romanization: "bhalo"            },
                { bangla: "আমার নাম ___।",     english: "My name is ___.",          romanization: "amar nam ___."    },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-1-tte-1",
              bangla: "তুমি কেমন আছো?",
              romanization: "tumi kemon acho?",
              answer: "How are you?",

              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "raj-1-1-ttb-1",
              english: "I am fine.",
              answer: "আমি ভালো আছি।",
              romanization: "ami bhalo achi.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "raj-1-1-mc-1",
              prompt: "How do you say 'What is your name?' in Rajshahi Bangla?",
              options: [
                "তোমার নাম কী?",
                "কিতা তোমার নাম?",
                "তুঁয়ার নাম কী?",
                "আপনার নামডা কী?",
              ],
              correct: 0,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-2",
          title: "Introductions",
          description: "Say your name and where you are from in Rajshahi Bangla",
          unit: 1,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-1-2-tte-1",
              bangla: "আমার নাম ___।",
              romanization: "amar nam ___.",
              answer: "My name is ___.",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-1-2-tte-2",
              bangla: "আমি বাংলা শিখছি।",
              romanization: "ami bangla shikhchi.",
              answer: "I am learning Bangla.",

              xp: 4,
            },
            {
              type: "fill_blank",
              id: "raj-1-2-fb-1",
              sentence: "আমি ___ থেকে এসেছি।",
              blank: "ঢাকা",
              romanization: "ami ___ theke eshechi.",
              options: ["ঢাকা", "খাওয়া", "নাম", "আমার"],
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-2-mc-1",
              prompt: "What does 'শিখছি' mean?",
              options: ["am eating", "am learning", "am going", "am sleeping"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-3",
          title: "Polite Words",
          description: "Use polite expressions in Rajshahi Bangla",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-3-mp-1",
              pairs: [
                { bangla: "ধন্যবাদ",    english: "Thank you",  romanization: "dhonnobad" },
                { bangla: "দয়া করে",   english: "Please",     romanization: "doya kore" },
                { bangla: "মাফ করবেন", english: "Excuse me",  romanization: "maf korben" },
                { bangla: "ঠিক আছে",   english: "Okay",       romanization: "thik ache" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-3-tte-1",
              bangla: "দয়া করে বসুন।",
              romanization: "doya kore bosun.",
              answer: "Please sit.",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-3-mc-1",
              prompt: "Which phrase means 'Excuse me' in Rajshahi Bangla?",
              options: ["ধন্যবাদ", "দয়া করে", "মাফ করবেন", "বসুন"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-4",
          title: "Yes / No / Basic Replies",
          description: "Answer simple questions in Rajshahi Bangla",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-4-mp-1",
              pairs: [
                { bangla: "হ্যাঁ",     english: "Yes",         romanization: "hya"    },
                { bangla: "না",        english: "No",          romanization: "na"     },
                { bangla: "হয়তো",    english: "Maybe",       romanization: "hoyto"  },
                { bangla: "জানি না", english: "I don't know", romanization: "jani na" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-1-4-ttb-1",
              english: "Yes, I can.",
              answer: "হ্যাঁ, পারি।",
              romanization: "hya, pari.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-4-mc-1",
              prompt: "How do you say 'Maybe' in Rajshahi Bangla?",
              options: ["হ্যাঁ", "না", "হয়তো", "জানি"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-5",
          title: "Pronouns",
          description: "Use Rajshahi Bangla pronouns in everyday phrases",
          unit: 1,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-5-mp-1",
              pairs: [
                { bangla: "আমি",   english: "I",             romanization: "ami"  },
                { bangla: "তুমি",  english: "You (familiar)", romanization: "tumi" },
                { bangla: "আপনি", english: "You (polite)",   romanization: "apni" },
                { bangla: "সে",    english: "He / She",       romanization: "shey" },
                { bangla: "তারা", english: "They",            romanization: "tara" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-5-tte-1",
              bangla: "আপনি কেমন আছেন?",
              romanization: "apni kemon achen?",
              answer: "How are you? (polite)",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-1-5-tte-2",
              bangla: "তারা আসবে।",
              romanization: "tara ashbe.",
              answer: "They will come.",

              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "raj-1-5-mc-1",
              prompt: "In Rajshahi Bangla, 'সে' refers to:",
              options: ["I", "You", "He or She", "They"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-6",
          title: "Family",
          description: "Talk about your family in Rajshahi Bangla",
          unit: 1,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-6-mp-1",
              pairs: [
                { bangla: "মা",      english: "Mother",        romanization: "ma"      },
                { bangla: "বাবা",    english: "Father",        romanization: "baba"    },
                { bangla: "ভাই",     english: "Brother",       romanization: "bhai"    },
                { bangla: "বোন",     english: "Sister",        romanization: "bon"     },
                { bangla: "পরিবার", english: "Family",        romanization: "poribar" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-6-tte-1",
              bangla: "এ আমার মা।",
              romanization: "e amar ma.",
              answer: "This is my mother.",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-1-6-tte-2",
              bangla: "আমার এক ভাই আছে।",
              romanization: "amar ek bhai ache.",
              answer: "I have one brother.",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-6-mc-1",
              prompt: "In Rajshahi Bangla, 'মেয়ে' means:",
              options: ["son", "daughter/girl", "sister", "mother"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "raj-1-6-ttb-1",
              english: "My family is big.",
              answer: "আমার পরিবার বড়।",
              romanization: "amar poribar boro.",
              xp: 3,
            },
          ],
        },
      ],
    },
    {
      id: "raj-unit-2",
      title: "Heart & Time",
      description: "Express affection, count numbers, and talk about time in Rajshahi dialect",
      order: 2,
      color: "#16a34a",
      prep: {
        characters: [],
        flashcards: [
          { id: "fc-raj-2-1",  bangla: "আপনি",         romanization: "apni",        english: "You (formal, Rajshahi — same as Standard)", category: "pronouns"  },
          { id: "fc-raj-2-2",  bangla: "তুমি",          romanization: "tumi",        english: "You (informal)",                           category: "pronouns"  },
          { id: "fc-raj-2-3",  bangla: "ভালোবাসি",    romanization: "bhalobashi",  english: "I love (you)",                             category: "phrases"   },
          { id: "fc-raj-2-4",  bangla: "যত্ন",          romanization: "jotno",       english: "Care / Attention",                         category: "phrases"   },
          { id: "fc-raj-2-5",  bangla: "কী",            romanization: "ki",          english: "What",                                     category: "questions" },
          { id: "fc-raj-2-6",  bangla: "কোথায়",        romanization: "kothay",      english: "Where",                                    category: "questions" },
          { id: "fc-raj-2-7",  bangla: "কেন",           romanization: "keno",        english: "Why",                                      category: "questions" },
          { id: "fc-raj-2-8",  bangla: "সকাল",          romanization: "shokal",      english: "Morning",                                  category: "time"      },
          { id: "fc-raj-2-9",  bangla: "বিকেল",         romanization: "bikel",       english: "Afternoon",                                category: "time"      },
          { id: "fc-raj-2-10", bangla: "সন্ধ্যা",       romanization: "shondhya",    english: "Evening",                                  category: "time"      },
          { id: "fc-raj-2-11", bangla: "রাত",           romanization: "rat",         english: "Night",                                    category: "time"      },
          { id: "fc-raj-2-12", bangla: "এখন",           romanization: "ekhon",       english: "Now",                                      category: "time"      },
          { id: "fc-raj-2-13", bangla: "আজ",            romanization: "aj",          english: "Today",                                    category: "time"      },
          { id: "fc-raj-2-14", bangla: "গতকাল",         romanization: "gotokal",     english: "Yesterday",                                category: "time"      },
          { id: "fc-raj-2-15", bangla: "আগামীকাল",     romanization: "agamikal",    english: "Tomorrow",                                 category: "time"      },
          { id: "fc-raj-2-16", bangla: "আসব",           romanization: "ashbo",       english: "Will come (future)",                       category: "grammar"   },
          { id: "fc-raj-2-17", bangla: "করবে",          romanization: "korbe",       english: "Will do (future, 2nd person)",             category: "grammar"   },
          { id: "fc-raj-2-18", bangla: "এগারো",         romanization: "egaro",       english: "Eleven",                                   category: "numbers"   },
          { id: "fc-raj-2-19", bangla: "পনেরো",         romanization: "ponero",      english: "Fifteen",                                  category: "numbers"   },
          { id: "fc-raj-2-20", bangla: "বিশ",           romanization: "bish",        english: "Twenty",                                   category: "numbers"   },
        ],
        grammar: [
          {
            title: "Rajshahi — Close to Standard",
            explanation: "Rajshahi dialect stays very close to Standard Bangla in vocabulary. Key differences: slight vowel shifts in fast speech, and a rural cadence. The grammar rules are essentially identical to Standard.",
            examples: [
              { bangla: "তুমি কেমন আছ?",       romanization: "tumi kemon achho?",    english: "How are you? (informal)" },
              { bangla: "আমি ভালো আছি।",        romanization: "ami bhalo achi.",       english: "I am fine." },
            ],
          },
          {
            title: "Rajshahi Future Tense",
            explanation: "Future tense in Rajshahi matches Standard Bangla: '-ব' suffix. 'আসব' (will come), 'করবে' (you will do), 'দেব' (will give). No dialect-specific transformations.",
            examples: [
              { bangla: "আমি আগামীকাল আসব।", romanization: "ami agamikal ashbo.",  english: "I will come tomorrow." },
              { bangla: "তুমি কী করবে?",       romanization: "tumi ki korbe?",       english: "What will you do?" },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "raj-2-0",
          title: "Respect & Affection",
          description: "Express love and respect — Rajshahi style",
          unit: 2,
          order: 0,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-2-0-mp-1",
              pairs: [
                { bangla: "ভালোবাসি",  english: "I love (you)",   romanization: "bhalobashi" },
                { bangla: "যত্ন নাও",  english: "Take care",       romanization: "jotno nao" },
                { bangla: "আপনি",      english: "You (formal)",    romanization: "apni"       },
                { bangla: "প্রিয়",    english: "Dear / Beloved",  romanization: "priyo"      },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-2-0-tte-1",
              bangla: "তুমি আমার খুব প্রিয়।",
              romanization: "tumi amar khub priyo.",
              answer: "You are very dear to me.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-0-mc-1",
              prompt: "In Rajshahi, the formal 'you' is (same as Standard):",
              options: ["আপনে", "হে", "আপনি", "তুঁই"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "raj-2-1",
          title: "Sweet Questions",
          description: "Ask questions — কী, কোথায়, কেন",
          unit: 2,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-2-1-tte-1",
              bangla: "তুমি কোথায় যাচ্ছ?",
              romanization: "tumi kothay jaccho?",
              answer: "Where are you going?",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-2-1-fb-1",
              sentence: "তোমার ___ পছন্দ?",
              blank: "কী",
              romanization: "tomar ___ pochondo?",
              options: ["কেন", "কী", "কোথায়", "কেমন"],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-1-mc-1",
              prompt: "Rajshahi uses the same word as Standard for 'where':",
              options: ["কেলে", "কই", "কোথায়", "কিতা"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "raj-2-2",
          title: "Numbers 1–10",
          description: "Count from one to ten",
          unit: 2,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-2-2-mp-1",
              pairs: [
                { bangla: "এক",   english: "One",   romanization: "ek"    },
                { bangla: "দুই",  english: "Two",   romanization: "dui"   },
                { bangla: "তিন",  english: "Three", romanization: "tin"   },
                { bangla: "পাঁচ", english: "Five",  romanization: "pach"  },
              ],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-2-2-mp-2",
              pairs: [
                { bangla: "ছয়",  english: "Six",   romanization: "choy"  },
                { bangla: "সাত",  english: "Seven", romanization: "shat"  },
                { bangla: "আট",   english: "Eight", romanization: "at"    },
                { bangla: "দশ",   english: "Ten",   romanization: "dosh"  },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-2-mc-1",
              prompt: "What is 'নয়' in English?",
              options: ["Seven", "Eight", "Nine", "Ten"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "raj-2-3",
          title: "Numbers 11–20",
          description: "Count from eleven to twenty",
          unit: 2,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-2-3-mp-1",
              pairs: [
                { bangla: "এগারো", english: "Eleven",   romanization: "egaro"    },
                { bangla: "বারো",  english: "Twelve",   romanization: "baro"     },
                { bangla: "তেরো",  english: "Thirteen", romanization: "tero"     },
                { bangla: "বিশ",   english: "Twenty",   romanization: "bish"     },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-3-mc-1",
              prompt: "How do you say 'sixteen' in Bangla?",
              options: ["পনেরো", "ষোলো", "সতেরো", "আঠারো"],
              correct: 1,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-2-3-tte-1",
              bangla: "আমার বয়স আঠারো।",
              romanization: "amar boyosh atharo.",
              answer: "I am eighteen years old.",

              xp: 5,
            },
          ],
        },
        {
          id: "raj-2-4",
          title: "Time Words",
          description: "Morning, evening, night, now",
          unit: 2,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-2-4-mp-1",
              pairs: [
                { bangla: "সকাল",   english: "Morning",  romanization: "shokal"   },
                { bangla: "বিকেল",  english: "Afternoon", romanization: "bikel"   },
                { bangla: "সন্ধ্যা", english: "Evening", romanization: "shondhya" },
                { bangla: "রাত",    english: "Night",    romanization: "rat"      },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-2-4-tte-1",
              bangla: "এখন সন্ধ্যা।",
              romanization: "ekhon shondhya.",
              answer: "It is evening now.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-4-mc-1",
              prompt: "In Rajshahi (same as Standard), 'now' is:",
              options: ["এহন", "এখন", "আইজ", "রাইত"],
              correct: 1,
              xp: 5,
            },
          ],
        },
        {
          id: "raj-2-5",
          title: "Today / Yesterday / Tomorrow",
          description: "Talk about days — quiz time!",
          unit: 2,
          order: 5,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-2-5-mc-1",
              prompt: "In Rajshahi (same as Standard), 'yesterday' is:",
              options: ["আজ", "গতকাল", "আগামীকাল", "এখন"],
              correct: 1,
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-5-mc-2",
              prompt: "How do you say 'tomorrow'?",
              options: ["গতকাল", "আজ", "আগামীকাল", "পরশু"],
              correct: 2,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-2-5-tte-1",
              bangla: "আমি আগামীকাল আসব।",
              romanization: "ami agamikal ashbo.",
              answer: "I will come tomorrow.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-2-5-ttb-1",
              english: "What did you do yesterday?",
              answer: "তুমি গতকাল কী করলে?",
              romanization: "tumi gotokal ki korle?",
              xp: 5,
            },
          ],
        },
      ],
    },
    // ─── Unit 3 ───────────────────────────────────────────────────────────────
    {
      id: "raj-unit-3",
      title: "Food & Daily Life",
      description: "Rajshahi-flavoured food talk, market visits, and home routines.",
      color: "#15803d",
      order: 3,
      prep: {
        flashcards: [
          { id: "fc-raj-3-1",  bangla: "ভাত",        romanization: "vhat",      english: "cooked rice",     emoji: "🍚", category: "food" },
          { id: "fc-raj-3-2",  bangla: "মাছ",         romanization: "mach",      english: "fish",            emoji: "🐟", category: "food" },
          { id: "fc-raj-3-3",  bangla: "ডাল",         romanization: "dal",       english: "lentils",         emoji: "🫘", category: "food" },
          { id: "fc-raj-3-4",  bangla: "সবজি",        romanization: "shobji",    english: "vegetables",      emoji: "🥦", category: "food" },
          { id: "fc-raj-3-5",  bangla: "পানি",        romanization: "pani",      english: "water",           emoji: "💧", category: "food" },
          { id: "fc-raj-3-6",  bangla: "চা",          romanization: "cha",       english: "tea",             emoji: "🍵", category: "food" },
          { id: "fc-raj-3-7",  bangla: "দুধ",         romanization: "dudh",      english: "milk",            emoji: "🥛", category: "food" },
          { id: "fc-raj-3-8",  bangla: "রুটি",        romanization: "ruti",      english: "bread / roti",    emoji: "🫓", category: "food" },
          { id: "fc-raj-3-9",  bangla: "মাংস",        romanization: "mangsho",   english: "meat",            emoji: "🍖", category: "food" },
          { id: "fc-raj-3-10", bangla: "ফল",          romanization: "fol",       english: "fruit",           emoji: "🍎", category: "food" },
          { id: "fc-raj-3-11", bangla: "খাচ্ছি",     romanization: "khashshi",  english: "I am eating",     emoji: "😋", category: "verb" },
          { id: "fc-raj-3-12", bangla: "রান্না করছি", romanization: "ranna korshi", english: "I am cooking", emoji: "👨‍🍳", category: "verb" },
          { id: "fc-raj-3-13", bangla: "বাজার",       romanization: "bajar",     english: "market",          emoji: "🛒", category: "place" },
          { id: "fc-raj-3-14", bangla: "দোকান",       romanization: "dokan",     english: "shop",            emoji: "🏪", category: "place" },
          { id: "fc-raj-3-15", bangla: "বাড়ি",        romanization: "bari",      english: "home",            emoji: "🏠", category: "place" },
          { id: "fc-raj-3-16", bangla: "ঘর",          romanization: "ghor",      english: "room",            emoji: "🚪", category: "place" },
          { id: "fc-raj-3-17", bangla: "রান্নাঘর",    romanization: "rannaghor", english: "kitchen",         emoji: "🍳", category: "place" },
          { id: "fc-raj-3-18", bangla: "বিছানা",      romanization: "bishana",   english: "bed",             emoji: "🛏️", category: "home" },
          { id: "fc-raj-3-19", bangla: "ক্ষুধা",      romanization: "khudha",    english: "hunger",          emoji: "😩", category: "feeling" },
          { id: "fc-raj-3-20", bangla: "পেট ভরা",     romanization: "pet vhora", english: "stomach full",    emoji: "😌", category: "feeling" },
          { id: "fc-raj-3-21", bangla: "কিনব",        romanization: "kinbo",     english: "I will buy",      emoji: "🛍️", category: "verb" },
          { id: "fc-raj-3-22", bangla: "দাম",         romanization: "dam",       english: "price",           emoji: "💰", category: "market" },
          { id: "fc-raj-3-23", bangla: "সস্তা",       romanization: "shoshta",   english: "cheap",           emoji: "🏷️", category: "market" },
          { id: "fc-raj-3-24", bangla: "দামি",        romanization: "dami",      english: "expensive",       emoji: "💎", category: "market" },
          { id: "fc-raj-3-25", bangla: "ঘুমাচ্ছি",   romanization: "ghumashshi",english: "I am sleeping",   emoji: "😴", category: "routine" },
          { id: "fc-raj-3-26", bangla: "উঠছি",       romanization: "uthshi",    english: "I am getting up", emoji: "🌅", category: "routine" },
          { id: "fc-raj-3-27", bangla: "গোসল",        romanization: "ghoshol",   english: "bath",            emoji: "🚿", category: "routine" },
          { id: "fc-raj-3-28", bangla: "কাজে যাই",   romanization: "kaje jai",  english: "I go to work",    emoji: "💼", category: "routine" },
        ],
        characters: [],
        grammar: [
          {
            title: "Standard -ছি progressive in Rajshahi",
            explanation: "Rajshahi uses standard Bengali -ছি progressive: খাচ্ছি (am eating), রান্না করছি (am cooking). This matches Standard Bengali closely.",
            examples: [
              { bangla: "আমি ভাত খাচ্ছি।",      romanization: "ami vhat khashshi.",    english: "I am eating rice." },
              { bangla: "মা রান্না করছেন।",      romanization: "ma ranna korshhen.",    english: "Mother is cooking." },
            ],
          },
          {
            title: "কিনব — future in Rajshahi",
            explanation: "Rajshahi future uses standard -ব: কিনব (will buy), খাব (will eat), যাব (will go).",
            examples: [
              { bangla: "আমি বাজার থেকে মাছ কিনব।", romanization: "ami bajar theke mach kinbo.", english: "I will buy fish from the market." },
              { bangla: "তোমাকে চা দেব।",            romanization: "tomake cha debo.",             english: "I will give you tea." },
            ],
          },
          {
            title: "থেকে = from (Rajshahi standard form)",
            explanation: "Rajshahi uses থেকে (standard Bengali) for 'from', unlike Barisali থাইকা or Chittagonian থাকি.",
            examples: [
              { bangla: "দোকান থেকে কিনেছি।", romanization: "dokan theke kineshi.", english: "I bought from the shop." },
              { bangla: "বাড়ির কাছে বাজার।",  romanization: "barir kashe bajar.",   english: "The market is near home." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "raj-3-1",
          title: "Rice & Fish",
          description: "Food staples: rice, fish, and lentils in Rajshahi dialect",
          unit: 3,
          order: 1,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-3-1-mc-1",
              prompt: "Rajshahi 'I am eating' (standard form) is:",
              options: ["খাইতাছি", "খাচ্ছি", "খাইছি", "খামু"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-3-1-tte-1",
              bangla: "আমি ভাত আর মাছ খাচ্ছি।",
              romanization: "ami vhat ar mach khashshi.",
              answer: "I am eating rice and fish.",

              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-3-1-mp-1",
              pairs: [
                { bangla: "ভাত",  english: "rice", romanization: "bhat" },
                { bangla: "মাছ",  english: "fish", romanization: "mach" },
                { bangla: "ডাল",  english: "lentils", romanization: "dal" },
                { bangla: "পানি", english: "water", romanization: "pani" },
              ],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "raj-3-1-ttb-1",
              english: "I will eat fish and rice.",
              answer: "আমি মাছ আর ভাত খাব।",
              romanization: "ami mach ar vhat khabo.",
              xp: 5,
            },
          ],
        },
        {
          id: "raj-3-2",
          title: "At the Market",
          description: "Shopping at the market in Rajshahi dialect",
          unit: 3,
          order: 2,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-3-2-mc-1",
              prompt: "Rajshahi 'I will buy' is:",
              options: ["কিনব", "কিনমু", "কিনুম", "কিনছি"],
              correct: 0,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-3-2-tte-1",
              bangla: "বাজার থেকে সবজি কিনব।",
              romanization: "bajar theke shobji kinbo.",
              answer: "I will buy vegetables from the market.",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-3-2-fb-1",
              sentence: "মাংসটা অনেক ___।",
              romanization: "mangsota onek ___.",
              blank: "দামি",

              options: ["দামি"],

              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-3-2-mp-1",
              pairs: [
                { bangla: "বাজার",  english: "market", romanization: "bajar" },
                { bangla: "দোকান",  english: "shop", romanization: "dokan" },
                { bangla: "সস্তা",  english: "cheap", romanization: "shoshta" },
                { bangla: "দামি",   english: "expensive", romanization: "dami" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "raj-3-3",
          title: "In the Kitchen",
          description: "Kitchen vocabulary and cooking in Rajshahi",
          unit: 3,
          order: 3,
          xpReward: 20,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-3-3-tte-1",
              bangla: "মা রান্নাঘরে রান্না করছেন।",
              romanization: "ma rannaghor-e ranna korshhen.",
              answer: "Mother is cooking in the kitchen.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-3-3-mc-1",
              prompt: "Rajshahi 'kitchen' is:",
              options: ["খাবার ঘর", "রান্নাঘর", "বিছানা ঘর", "কাজের ঘর"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "raj-3-3-mp-1",
              pairs: [
                { bangla: "রান্নাঘর", english: "kitchen", romanization: "rannaghor" },
                { bangla: "বিছানা",   english: "bed", romanization: "bishana" },
                { bangla: "ঘর",       english: "room", romanization: "ghor" },
                { bangla: "বাড়ি",    english: "home", romanization: "bari" },
              ],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "raj-3-3-ttb-1",
              english: "I will cook at home.",
              answer: "আমি বাড়িতে রান্না করব।",
              romanization: "ami barite ranna korbo.",
              xp: 5,
            },
          ],
        },
        {
          id: "raj-3-4",
          title: "Daily Routine",
          description: "Daily routine and meal times in Rajshahi",
          unit: 3,
          order: 4,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-3-4-mc-1",
              prompt: "Rajshahi 'I am sleeping' is:",
              options: ["ঘুমাইতাছি", "ঘুমাচ্ছি", "ঘুমামু", "ঘুমাইছি"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-3-4-tte-1",
              bangla: "ভোরে উঠে গোসল করেছি।",
              romanization: "vhore uthe ghoshol korechi.",
              answer: "I woke up early and bathed.",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-3-4-fb-1",
              sentence: "সকালে উঠে ___ করেছি।",
              romanization: "shokale uthe ___ korechi.",
              blank: "গোসল",

              options: ["গোসল"],

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-3-4-ttb-1",
              english: "I go to work every day.",
              answer: "আমি প্রতিদিন কাজে যাই।",
              romanization: "ami protidin kaje jai.",
              xp: 5,
            },
          ],
        },
        {
          id: "raj-3-5",
          title: "Hunger & Fullness",
          description: "Expressing hunger and fullness in Rajshahi",
          unit: 3,
          order: 5,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-3-5-mc-1",
              prompt: "Rajshahi standard word for 'hunger' is:",
              options: ["খিদা", "ক্ষুধা", "পেট", "তৃষ্ণা"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-3-5-tte-1",
              bangla: "আমার অনেক ক্ষুধা পেয়েছে।",
              romanization: "amar onek khudha peyeche.",
              answer: "I am very hungry.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-3-5-ttb-1",
              english: "My stomach is full.",
              answer: "আমার পেট ভরা।",
              romanization: "amar pet vhora.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-3-5-mp-1",
              pairs: [
                { bangla: "ক্ষুধা",  english: "hunger", romanization: "khudha" },
                { bangla: "পেট ভরা", english: "stomach full", romanization: "pet vhora" },
                { bangla: "পানি",    english: "water", romanization: "pani" },
                { bangla: "চা",      english: "tea", romanization: "cha" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "raj-3-6",
          title: "Food Quiz",
          description: "Food & Daily Life quiz — Rajshahi Unit 3",
          unit: 3,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-3-6-mc-1",
              prompt: "Rajshahi future 'I will buy' is:",
              options: ["কিনমু", "কিনব", "কিনুম", "কিনতেছি"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-3-6-tte-1",
              bangla: "আমি বাজার থেকে মাছ আর সবজি কিনব।",
              romanization: "ami bajar theke mach ar shobji kinbo.",
              answer: "I will buy fish and vegetables from the market.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-3-6-ttb-1",
              english: "Mother is cooking in the kitchen.",
              answer: "মা রান্নাঘরে রান্না করছেন।",
              romanization: "ma rannaghor-e ranna korshhen.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-3-6-fb-1",
              sentence: "আমার অনেক ___ পেয়েছে।",
              romanization: "amar onek ___ peyeche.",
              blank: "ক্ষুধা",

              options: ["ক্ষুধা"],

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-3-6-mc-2",
              prompt: "Rajshahi 'from the market' is:",
              options: ["বাজার থাইকা", "বাজার থাকি", "বাজার থেকে", "বাজার লাই"],
              correct: 2,
              xp: 4,
            },
          ],
        },
      ],
    },
    {
      id: "raj-unit-4",
      title: "Numbers & Counting",
      description: "Count, bargain, and tell the time in Rajshahi Bangla",
      order: 4,
      prep: {
        characters: [],
        grammar: [
          {
            title: "Numbers in Rajshahi",
            rule: "Rajshahi uses standard Bengali numbers. The classifier -টা/-টি counts objects. কয়টা? = how many? The regional accent softens some consonants.",
            examples: [
              { bangla: "কয়টা আম চাও?", romanization: "koyta am chao?", english: "How many mangoes do you want?" },
              { bangla: "পাঁচটা দাও।", romanization: "pachta dao.", english: "Give me five." },
            ],
          },
          {
            title: "Telling the time — Rajshahi",
            rule: "কটা বাজে? = what time is it? Rajshahi is very close to standard: [number]টা বাজে = it is [n] o'clock. দুপুর = noon, সন্ধ্যা = evening.",
            examples: [
              { bangla: "কটা বাজে?", romanization: "kota baje?", english: "What time is it?" },
              { bangla: "নয়টা বাজে।", romanization: "noyta baje.", english: "It is nine o'clock." },
            ],
          },
          {
            title: "Market prices — দাম",
            rule: "দাম কত? = how much is the price? (Rajshahi uses কত, same as standard). মোট = total. শ' = hundred (colloquial shortening of একশো).",
            examples: [
              { bangla: "দাম কত?", romanization: "dam koto?", english: "What is the price?" },
              { bangla: "পঞ্চাশ টাকা।", romanization: "ponchash taka.", english: "Fifty taka." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "raj-4-1",
          title: "Numbers 1–10",
          description: "Core counting in Rajshahi Bangla",
          unit: 4,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-4-1-mp-1",
              pairs: [
                { bangla: "এক",   english: "one",   romanization: "ek"    },
                { bangla: "দুই",  english: "two",   romanization: "dui"   },
                { bangla: "তিন",  english: "three", romanization: "tin"   },
                { bangla: "চার",  english: "four",  romanization: "char"  },
                { bangla: "পাঁচ", english: "five",  romanization: "panch" },
              ],
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "raj-4-1-mc-1",
              prompt: "What is 'আট' in English?",
              options: ["six", "seven", "eight", "nine"],
              correct: 2,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "raj-4-1-mp-2",
              pairs: [
                { bangla: "ছয়",  english: "six",   romanization: "chhoy" },
                { bangla: "সাত", english: "seven", romanization: "shat"  },
                { bangla: "আট",  english: "eight", romanization: "at"    },
                { bangla: "নয়", english: "nine",  romanization: "noy"   },
                { bangla: "দশ",  english: "ten",   romanization: "dosh"  },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "raj-4-1-ttb-1",
              english: "Give me three mangoes.",
              answer: "তিনটা আম দাও।",
              romanization: "tinta am dao.",
              xp: 6,
            },
            {
              type: "multiple_choice",
              id: "raj-4-1-mc-2",
              prompt: "Rajshahi Bangla is closest in vocabulary to:",
              options: ["Sylheti", "Standard Bengali", "Chittagonian", "Barisali"],
              correct: 1,
              xp: 4,
            },
          ],
        },
        {
          id: "raj-4-2",
          title: "Numbers 11–30",
          description: "Teens, twenties, and thirties in Rajshahi Bangla",
          unit: 4,
          order: 2,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-4-2-mp-1",
              pairs: [
                { bangla: "এগারো",  english: "eleven",   romanization: "egaro"   },
                { bangla: "বারো",   english: "twelve",   romanization: "baro"    },
                { bangla: "পনেরো",  english: "fifteen",  romanization: "ponero"  },
                { bangla: "বিশ",    english: "twenty",   romanization: "bish"    },
                { bangla: "ত্রিশ",  english: "thirty",   romanization: "trish"   },
              ],
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "raj-4-2-mc-1",
              prompt: "What is 'পঁচিশ'?",
              options: ["twenty", "twenty-two", "twenty-five", "thirty"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-4-2-tte-1",
              bangla: "পনেরোটা মাছ।",
              romanization: "poneрota mach.",
              answer: "Fifteen fish.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-4-2-fb-1",
              sentence: "দশ আর দশ = ___।",
              romanization: "dosh ar dosh = ___.",
              blank: "বিশ",
              options: ["পনেরো", "বিশ", "পঁচিশ", "ত্রিশ"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-4-2-ttb-1",
              english: "I want twenty mangoes.",
              answer: "বিশটা আম চাই।",
              romanization: "bishta am chai.",
              xp: 6,
            },
          ],
        },
        {
          id: "raj-4-3",
          title: "Bigger Numbers",
          description: "Tens and hundreds for the Rajshahi silk market",
          unit: 4,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-4-3-mp-1",
              pairs: [
                { bangla: "চল্লিশ", english: "forty",    romanization: "challish"  },
                { bangla: "পঞ্চাশ", english: "fifty",    romanization: "ponchash"  },
                { bangla: "ষাট",    english: "sixty",    romanization: "shat"      },
                { bangla: "একশো",  english: "hundred",  romanization: "ekshо"     },
              ],
              xp: 8,
            },
            {
              type: "translate_to_english",
              id: "raj-4-3-tte-1",
              bangla: "মোট একশো টাকা।",
              romanization: "mot ekshо taka.",
              answer: "Total one hundred taka.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-4-3-mc-1",
              prompt: "Rajshahi is famous for its silk — রেশম কাপড়। 'কাপড়' means:",
              options: ["silk", "cloth / fabric", "market", "price"],
              correct: 1,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "raj-4-3-fb-1",
              sentence: "রেশম কাপড়ের দাম ___ টাকা।",
              romanization: "resham kaporer dam ___ taka.",
              blank: "পঞ্চাশ",
              options: ["দশ", "পঁচিশ", "পঞ্চাশ", "হাজার"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-4-3-ttb-1",
              english: "How much is the price?",
              answer: "দাম কত?",
              romanization: "dam koto?",
              xp: 5,
            },
          ],
        },
        {
          id: "raj-4-4",
          title: "Telling the Time",
          description: "Ask and say the time in Rajshahi Bangla",
          unit: 4,
          order: 4,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-4-4-mc-1",
              prompt: "How do you ask 'what time is it?' in Rajshahi Bangla?",
              options: ["কত বাজে?", "কটা বাজে?", "কতদূর?", "কয়টা বাজে?"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-4-4-tte-1",
              bangla: "নয়টা বাজে।",
              romanization: "noyta baje.",
              answer: "It is nine o'clock.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-4-4-mp-1",
              pairs: [
                { bangla: "দুইটা বাজে",   english: "it is two o'clock",   romanization: "duita baje"   },
                { bangla: "চারটা বাজে",   english: "it is four o'clock",  romanization: "charta baje"  },
                { bangla: "সাতটা বাজে",   english: "it is seven o'clock", romanization: "shatta baje"  },
                { bangla: "বারোটা বাজে",  english: "it is twelve o'clock", romanization: "barota baje" },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "raj-4-4-fb-1",
              sentence: "___ বাজে। (It is six o'clock)",
              romanization: "___ baje.",
              blank: "ছয়টা",
              options: ["পাঁচটা", "ছয়টা", "সাতটা", "আটটা"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-4-4-ttb-1",
              english: "It is twelve o'clock.",
              answer: "বারোটা বাজে।",
              romanization: "barota baje.",
              xp: 5,
            },
          ],
        },
        {
          id: "raj-4-5",
          title: "Numbers Review",
          description: "Numbers, prices, and time — full Rajshahi review",
          unit: 4,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-4-5-tte-1",
              bangla: "কটা বাজে? — নয়টা বাজে।",
              romanization: "kota baje? — noyta baje.",
              answer: "What time is it? — It is nine o'clock.",
              xp: 6,
            },
            {
              type: "multiple_choice",
              id: "raj-4-5-mc-1",
              prompt: "A vendor says 'ষাট টাকা' — how much?",
              options: ["40 taka", "50 taka", "60 taka", "70 taka"],
              correct: 2,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "raj-4-5-fb-1",
              sentence: "পাঁচটা কাপড় ___ টাকা।",
              romanization: "pachta kapor ___ taka.",
              blank: "একশো",
              options: ["দশ", "পঞ্চাশ", "একশো", "বিশ"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-4-5-mp-1",
              pairs: [
                { bangla: "কটা বাজে?",  english: "what time is it?",  romanization: "kota baje?"  },
                { bangla: "দাম কত?",    english: "how much?",         romanization: "dam koto?"   },
                { bangla: "কয়টা?",     english: "how many?",         romanization: "koyta?"      },
                { bangla: "মোট",        english: "total",             romanization: "mot"         },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "raj-4-5-ttb-1",
              english: "Give me five metres of silk cloth for one hundred taka.",
              answer: "একশো টাকায় পাঁচ মিটার রেশম কাপড় দাও।",
              romanization: "ekshо takay panch miтar resham kapor dao.",
              xp: 8,
            },
          ],
        },
      ],
    },
    {
      id: "raj-unit-5",
      title: "Getting Around",
      description: "Transport and directions across the Rajshahi plains",
      order: 5,
      prep: {
        characters: [],
        grammar: [
          {
            title: "Rajshahi transport",
            rule: "Rajshahi is an inland city — রিকশা (rickshaw) and বাস (bus) dominate. ভ্যান (van/cycle van) is also common on rural roads. যাব = I will go (standard Bengali future).",
            examples: [
              { bangla: "রিকশায় যাব।", romanization: "rikshay jabo.", english: "I will go by rickshaw." },
              { bangla: "বাসে যাই।", romanization: "base jai.", english: "I go by bus." },
            ],
          },
          {
            title: "Direction words — Rajshahi",
            rule: "Rajshahi uses near-standard direction words: বামে = left, ডানে = right, সামনে = ahead, পেছনে = behind. Rajshahi speakers pronounce these close to standard Bengali.",
            examples: [
              { bangla: "বামে যান।", romanization: "bame jan.", english: "Go left." },
              { bangla: "ডানে যান।", romanization: "dane jan.", english: "Go right." },
            ],
          },
          {
            title: "Distances — কতদূর?",
            rule: "কতদূর? = how far? হাঁটা দূরত্ব = walking distance. কাছে = nearby. Rajshahi is flat, so 'walking distance' is common.",
            examples: [
              { bangla: "বাজার কতদূর?", romanization: "bazar kotodur?", english: "How far is the market?" },
              { bangla: "হাঁটা দূরত্বে।", romanization: "hata durotte.", english: "Within walking distance." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "raj-5-1",
          title: "Rickshaw & Bus",
          description: "Transport across the Rajshahi plains",
          unit: 5,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-5-1-mp-1",
              pairs: [
                { bangla: "রিকশা", english: "rickshaw",  romanization: "riksha" },
                { bangla: "বাস",   english: "bus",        romanization: "bas"    },
                { bangla: "ভ্যান", english: "cycle van",  romanization: "van"    },
                { bangla: "ট্রেন", english: "train",      romanization: "tren"   },
              ],
              xp: 8,
            },
            {
              type: "translate_to_english",
              id: "raj-5-1-tte-1",
              bangla: "রিকশায় যাব।",
              romanization: "rikshay jabo.",
              answer: "I will go by rickshaw.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-5-1-mc-1",
              prompt: "Rajshahi is famous for:",
              options: ["tea gardens", "mangrove forests", "silk and mangoes", "port trade"],
              correct: 2,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "raj-5-1-fb-1",
              sentence: "বাসে ___ যাই।",
              romanization: "base ___ jai.",
              blank: "বাজারে",
              options: ["বন্দরে", "বাজারে", "ঘাটে", "সমুদ্রে"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-5-1-ttb-1",
              english: "I go by bus.",
              answer: "বাসে যাই।",
              romanization: "base jai.",
              xp: 6,
            },
          ],
        },
        {
          id: "raj-5-2",
          title: "Directions",
          description: "Standard-close directions in Rajshahi",
          unit: 5,
          order: 2,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-5-2-tte-1",
              bangla: "ডানে যান।",
              romanization: "dane jan.",
              answer: "Go right.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-5-2-mc-1",
              prompt: "What does 'পেছনে' mean?",
              options: ["ahead", "left", "right", "behind"],
              correct: 3,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "raj-5-2-mp-1",
              pairs: [
                { bangla: "বামে",    english: "left",   romanization: "bame"    },
                { bangla: "ডানে",    english: "right",  romanization: "dane"    },
                { bangla: "সামনে",  english: "ahead",  romanization: "shamne"  },
                { bangla: "পেছনে",  english: "behind", romanization: "pechone" },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "raj-5-2-fb-1",
              sentence: "বাজার ___ দিকে।",
              romanization: "bazar ___ dike.",
              blank: "ডানে",
              options: ["বামে", "ডানে", "সামনে", "পেছনে"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-5-2-ttb-1",
              english: "Go straight ahead.",
              answer: "সোজা সামনে যান।",
              romanization: "shoja shamne jan.",
              xp: 6,
            },
          ],
        },
        {
          id: "raj-5-3",
          title: "How Far?",
          description: "Ask about distance in Rajshahi",
          unit: 5,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-5-3-mc-1",
              prompt: "How do you ask 'how far?' in Rajshahi Bangla?",
              options: ["কতদূর?", "কতক্ষণ?", "কতো দাম?", "কোথায়?"],
              correct: 0,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-5-3-tte-1",
              bangla: "বিশ্ববিদ্যালয় কতদূর?",
              romanization: "bishwabidyalay kotodur?",
              answer: "How far is the university?",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-5-3-fb-1",
              sentence: "বাজার হাঁটা ___ ।",
              romanization: "bazar hata ___ .",
              blank: "দূরত্বে",
              options: ["দূরে", "দূরত্বে", "কাছে", "সামনে"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-5-3-ttb-1",
              english: "The hospital is far.",
              answer: "হাসপাতাল অনেক দূরে।",
              romanization: "hashpatal onek dure.",
              xp: 6,
            },
            {
              type: "multiple_choice",
              id: "raj-5-3-mc-2",
              prompt: "Rajshahi is home to which major university?",
              options: ["BUET", "BRAC University", "Rajshahi University", "Dhaka University"],
              correct: 2,
              xp: 4,
            },
          ],
        },
        {
          id: "raj-5-4",
          title: "Tickets & Travel",
          description: "Buy tickets and plan your journey from Rajshahi",
          unit: 5,
          order: 4,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-5-4-tte-1",
              bangla: "একটা টিকেট দিন।",
              romanization: "ekta tiket din.",
              answer: "Give me one ticket.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-5-4-mc-1",
              prompt: "How do you ask 'when does the bus leave?' in Rajshahi?",
              options: ["বাস কতদূর?", "বাস কখন ছাড়ে?", "বাস কয়টা?", "বাস কোথায়?"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "raj-5-4-mp-1",
              pairs: [
                { bangla: "টিকেট",    english: "ticket",    romanization: "tiket"    },
                { bangla: "স্টেশন",   english: "station",   romanization: "steshan"  },
                { bangla: "ছাড়া",    english: "to leave",  romanization: "chara"    },
                { bangla: "পৌঁছানো", english: "to arrive", romanization: "pouchano" },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "raj-5-4-fb-1",
              sentence: "ট্রেন কখন ___ ?",
              romanization: "tren kokhon ___ ?",
              blank: "ছাড়ে",
              options: ["আসে", "ছাড়ে", "থামে", "যায়"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-5-4-ttb-1",
              english: "When does the train arrive?",
              answer: "ট্রেন কখন পৌঁছাবে?",
              romanization: "tren kokhon pouchabe?",
              xp: 7,
            },
          ],
        },
        {
          id: "raj-5-5",
          title: "Transport Review",
          description: "Full review of Rajshahi transport and directions",
          unit: 5,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-5-5-tte-1",
              bangla: "আমি রিকশায় বিশ্ববিদ্যালয়ে যাব।",
              romanization: "ami rikshay bishwabidyalay-e jabo.",
              answer: "I will go to the university by rickshaw.",
              xp: 7,
            },
            {
              type: "multiple_choice",
              id: "raj-5-5-mc-1",
              prompt: "You need to go left in Rajshahi Bangla. What do you say?",
              options: ["ডানে যান।", "সামনে যান।", "বামে যান।", "পেছনে যান।"],
              correct: 2,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "raj-5-5-fb-1",
              sentence: "স্টেশন অনেক ___ ।",
              romanization: "steshan onek ___ .",
              blank: "দূরে",
              options: ["কাছে", "দূরে", "সামনে", "বামে"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-5-5-mp-1",
              pairs: [
                { bangla: "কতদূর?",     english: "how far?",             romanization: "kotodur?"    },
                { bangla: "রিকশায় যাব", english: "I will go by rickshaw", romanization: "rikshay jabo" },
                { bangla: "স্টেশন",    english: "station",              romanization: "steshan"     },
                { bangla: "হাঁটা দূরত্ব", english: "walking distance",  romanization: "hata durotto" },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "raj-5-5-ttb-1",
              english: "The market is ahead.",
              answer: "বাজার সামনে।",
              romanization: "bazar shamne.",
              xp: 6,
            },
          ],
        },
      ],
    },
    {
      id: "raj-unit-6",
      title: "Health & Body",
      description: "Body parts, illness, and medicine in Rajshahi Bangla",
      order: 6,
      prep: {
        characters: [],
        grammar: [
          {
            title: "Expressing pain — Rajshahi style",
            rule: "ব্যথা করছে (standard -ছে progressive) = 'is hurting'. Rajshahi is closest to standard Bengali here. মাথা ব্যথা করছে = My head is hurting.",
            examples: [
              { bangla: "পেট ব্যথা করছে।", romanization: "pet betha korchhe.", english: "My stomach is hurting." },
              { bangla: "হাত ব্যথা করছে।", romanization: "hat betha korchhe.", english: "My hand is hurting." },
            ],
          },
          {
            title: "Feeling unwell — Rajshahi",
            rule: "আমি অসুস্থ (I am unwell). জ্বর হয়েছে = I have a fever (standard past). Rajshahi uses near-standard verb forms.",
            examples: [
              { bangla: "আমি অসুস্থ।", romanization: "ami oshustho.", english: "I am unwell." },
              { bangla: "জ্বর হয়েছে।", romanization: "jor hoyechhe.", english: "I have a fever." },
            ],
          },
          {
            title: "Medicine — Rajshahi",
            rule: "ডাক্তার দেখাতে হবে = I need to see a doctor (standard হবে). ওষুধ খান = take medicine (polite). Rajshahi uses হবে, not হইব.",
            examples: [
              { bangla: "ডাক্তার দেখাতে হবে।", romanization: "daktar dekhate hobe.", english: "I need to see a doctor." },
              { bangla: "ওষুধ খান।", romanization: "oshud khan.", english: "Take the medicine." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "raj-6-1",
          title: "Body Parts",
          description: "Head to toe in Rajshahi Bangla",
          unit: 6,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-6-1-mp-1",
              pairs: [
                { bangla: "মাথা",  english: "head",    romanization: "matha" },
                { bangla: "হাত",   english: "hand",    romanization: "hat"   },
                { bangla: "পা",    english: "foot",    romanization: "pa"    },
                { bangla: "চোখ",   english: "eye",     romanization: "chokh" },
                { bangla: "পেট",   english: "stomach", romanization: "pet"   },
              ],
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "raj-6-1-mc-1",
              prompt: "What does 'কান' mean?",
              options: ["eye", "nose", "ear", "mouth"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-6-1-tte-1",
              bangla: "নাক আর মুখ।",
              romanization: "nak ar mukh.",
              answer: "Nose and mouth.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-6-1-fb-1",
              sentence: "___ দিয়ে শুনি।",
              romanization: "___ diye shuni.",
              blank: "কান",
              options: ["মাথা", "কান", "চোখ", "নাক"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-6-1-ttb-1",
              english: "My back is hurting.",
              answer: "পিঠ ব্যথা করছে।",
              romanization: "pith betha korchhe.",
              xp: 6,
            },
          ],
        },
        {
          id: "raj-6-2",
          title: "Feeling Unwell",
          description: "Describe symptoms in near-standard Rajshahi Bangla",
          unit: 6,
          order: 2,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-6-2-tte-1",
              bangla: "আমি অসুস্থ।",
              romanization: "ami oshustho.",
              answer: "I am unwell.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-6-2-mc-1",
              prompt: "Rajshahi (near-standard) way to say 'I have a fever' is:",
              options: ["জ্বর আইছে।", "জ্বর হইছে।", "জ্বর হয়েছে।", "জ্বর আসছে।"],
              correct: 2,
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-6-2-mp-1",
              pairs: [
                { bangla: "জ্বর",     english: "fever",   romanization: "jor"      },
                { bangla: "ব্যথা",    english: "pain",    romanization: "betha"    },
                { bangla: "ঠান্ডা",  english: "cold",    romanization: "thanda"   },
                { bangla: "অসুস্থ",  english: "unwell",  romanization: "oshustho" },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "raj-6-2-fb-1",
              sentence: "মাথা ব্যথা ___ ।",
              romanization: "matha betha ___ .",
              blank: "করছে",
              options: ["হয়েছে", "করছে", "হবে", "যাবে"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-6-2-ttb-1",
              english: "I feel cold.",
              answer: "ঠান্ডা লাগছে।",
              romanization: "thanda lagchhe.",
              xp: 6,
            },
          ],
        },
        {
          id: "raj-6-3",
          title: "At the Doctor",
          description: "Visit the doctor in Rajshahi Bangla",
          unit: 6,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-6-3-mc-1",
              prompt: "What does 'হাসপাতাল' mean?",
              options: ["clinic", "doctor", "hospital", "pharmacy"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-6-3-tte-1",
              bangla: "ডাক্তার দেখাতে হবে।",
              romanization: "daktar dekhate hobe.",
              answer: "I need to see a doctor.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-6-3-mp-1",
              pairs: [
                { bangla: "ডাক্তার",   english: "doctor",   romanization: "daktar"    },
                { bangla: "হাসপাতাল", english: "hospital", romanization: "hashpatal" },
                { bangla: "ওষুধ",      english: "medicine", romanization: "oshud"     },
                { bangla: "নার্স",     english: "nurse",    romanization: "nars"      },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "raj-6-3-fb-1",
              sentence: "ডাক্তারের কাছে যেতে ___ ।",
              romanization: "daktarer kache jete ___ .",
              blank: "হবে",
              options: ["লাগবে", "হবে", "পারব", "যাব"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-6-3-ttb-1",
              english: "Take the medicine.",
              answer: "ওষুধ খান।",
              romanization: "oshud khan.",
              xp: 6,
            },
          ],
        },
        {
          id: "raj-6-4",
          title: "Medicine & Care",
          description: "Pharmacy visits and dosage in Rajshahi",
          unit: 6,
          order: 4,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-6-4-tte-1",
              bangla: "দিনে তিনবার ওষুধ খান।",
              romanization: "dine tinbar oshud khan.",
              answer: "Take medicine three times a day.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-6-4-mc-1",
              prompt: "A pharmacist says 'খাওয়ার পরে খাবেন' — when should you take it?",
              options: ["Before eating", "After eating", "On an empty stomach", "Before sleeping"],
              correct: 1,
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-6-4-fb-1",
              sentence: "দুটো ট্যাবলেট ___ পরে খান।",
              romanization: "duto tablet ___ pore khan.",
              blank: "খাওয়ার",
              options: ["ঘুমের", "খাওয়ার", "হাঁটার", "কাজের"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-6-4-mp-1",
              pairs: [
                { bangla: "ফার্মেসি",    english: "pharmacy",     romanization: "pharmeshi"   },
                { bangla: "ট্যাবলেট",   english: "tablet",       romanization: "tablet"      },
                { bangla: "দিনে",       english: "per day",      romanization: "dine"        },
                { bangla: "খাওয়ার পরে", english: "after eating", romanization: "khawar pore" },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "raj-6-4-ttb-1",
              english: "Give me two tablets.",
              answer: "দুটো ট্যাবলেট দিন।",
              romanization: "duto tablet din.",
              xp: 6,
            },
          ],
        },
        {
          id: "raj-6-5",
          title: "Health Review",
          description: "Full review of health and body in Rajshahi Bangla",
          unit: 6,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-6-5-tte-1",
              bangla: "পেট ব্যথা করছে, ডাক্তারের কাছে যেতে হবে।",
              romanization: "pet betha korchhe, daktarer kache jete hobe.",
              answer: "My stomach is hurting, I need to go to the doctor.",
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "raj-6-5-mc-1",
              prompt: "Rajshahi uses which future form (closest to standard)?",
              options: ["হইব", "অইব", "হবে", "যামু"],
              correct: 2,
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-6-5-fb-1",
              sentence: "আমি ___ আছি।",
              romanization: "ami ___ achi.",
              blank: "অসুস্থ",
              options: ["ভালো", "অসুস্থ", "সুস্থ", "খুশি"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-6-5-mp-1",
              pairs: [
                { bangla: "মাথা ব্যথা",   english: "headache",                    romanization: "matha betha"   },
                { bangla: "জ্বর হয়েছে",  english: "have a fever (Rajshahi/std)", romanization: "jor hoyechhe"  },
                { bangla: "ওষুধ",         english: "medicine",                    romanization: "oshud"         },
                { bangla: "হাসপাতাল",    english: "hospital",                    romanization: "hashpatal"     },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "raj-6-5-ttb-1",
              english: "My hand is hurting.",
              answer: "হাত ব্যথা করছে।",
              romanization: "hat betha korchhe.",
              xp: 7,
            },
          ],
        },
      ],
    },
  ],
};
