import type { DialectCurriculum } from "@bangla-learn/types";

export const rajshahiCurriculum: DialectCurriculum = {
  dialect: "rajshahi",
  units: [
    {
      id: "raj-unit-1",
      title: "Rajshahi Bangla Basics",
      description: "Learn Rajshahi Bangla — the regional variety of Bangladesh's northwestern division",
      order: 1,
      color: "#16a34a",
      prep: {
        characters: [
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আমি (I)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইচ্ছা (wish)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠা (to rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এক (one)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওরা (they)" },
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কেমন (how)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খাওয়া (eating)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলাম (I went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালো (good)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মা (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাত (night)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সে (he/she)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হ্যাঁ (yes)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তোমার (your)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পরিবার (family)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বাবা (father)" },
          { symbol: "জ", romanization: "j",   type: "consonant" as const, exampleWord: "জানি (I know)" },
          { symbol: "ধ", romanization: "dh",  type: "consonant" as const, exampleWord: "ধন্যবাদ (thank you)" },
        ],
        flashcards: [
          { id: "fc-raj-1",  bangla: "আমি",       romanization: "ami",       english: "I",                   category: "pronouns"  },
          { id: "fc-raj-2",  bangla: "তুমি",       romanization: "tumi",      english: "You (familiar)",      category: "pronouns"  },
          { id: "fc-raj-3",  bangla: "আপনি",       romanization: "apni",      english: "You (polite)",        category: "pronouns"  },
          { id: "fc-raj-4",  bangla: "সে",          romanization: "shey",      english: "He / She",            category: "pronouns"  },
          { id: "fc-raj-5",  bangla: "আমরা",       romanization: "amra",      english: "We",                  category: "pronouns"  },
          { id: "fc-raj-6",  bangla: "তারা",       romanization: "tara",      english: "They",                category: "pronouns"  },
          { id: "fc-raj-7",  bangla: "ভালো",       romanization: "bhalo",     english: "Good / Fine",         category: "adjectives"},
          { id: "fc-raj-8",  bangla: "হ্যাঁ",      romanization: "hya",       english: "Yes",                 category: "phrases"   },
          { id: "fc-raj-9",  bangla: "না",          romanization: "na",        english: "No",                  category: "phrases"   },
          { id: "fc-raj-10", bangla: "ঠিক আছে",    romanization: "thik ache", english: "Okay",                category: "phrases"   },
          { id: "fc-raj-11", bangla: "ধন্যবাদ",    romanization: "dhonnobad", english: "Thank you",           category: "phrases"   },
          { id: "fc-raj-12", bangla: "মাফ করবেন", romanization: "maf korben",english: "Excuse me",           category: "phrases"   },
          { id: "fc-raj-13", bangla: "মা",          romanization: "ma",        english: "Mother",              category: "family"    },
          { id: "fc-raj-14", bangla: "বাবা",        romanization: "baba",      english: "Father",              category: "family"    },
          { id: "fc-raj-15", bangla: "বোন",         romanization: "bon",       english: "Sister",              category: "family"    },
          { id: "fc-raj-16", bangla: "ভাই",         romanization: "bhai",      english: "Brother",             category: "family"    },
        ],
        grammar: [
          {
            title: "Standard-compatible grammar",
            explanation: "Rajshahi Bangla is close to Standard Bangla in grammar, making it a natural transition track. Use standard verb endings early; regional pronunciation differences appear mainly in audio.",
            examples: [
              { bangla: "আমি ভালো আছি।",       romanization: "ami bhalo achi.",       english: "I am fine." },
              { bangla: "তুমি কেমন আছো?",       romanization: "tumi kemon acho?",      english: "How are you?" },
            ],
          },
          {
            title: "Familiar vs polite 'you'",
            explanation: "Like Standard Bangla, Rajshahi uses তুমি for familiar and আপনি for polite. সে means he/she and তারা means they.",
            examples: [
              { bangla: "আপনি কেমন আছেন?",     romanization: "apni kemon achen?",    english: "How are you? (polite)" },
              { bangla: "সে আমার বন্ধু।",       romanization: "shey amar bondhu.",     english: "He/She is my friend." },
            ],
          },
          {
            title: "Possession with আমার / তোমার",
            explanation: "Use আমার for 'my' and তোমার for 'your' (familiar). আমার নাম means 'my name.'",
            examples: [
              { bangla: "আমার নাম ___।",        romanization: "amar nam ___.",         english: "My name is ___." },
              { bangla: "তোমার নাম কী?",         romanization: "tomar nam ki?",         english: "What is your name?" },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "raj-1-0",
          title: "Write the Letters",
          description: "Trace key Bengali letters used in Rajshahi Bangla",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "raj-1-0-tr-1", character: "আ", romanization: "aa",  exampleWord: "আমি — I",          xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-2", character: "ন", romanization: "n",   exampleWord: "নাম — name",       xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-3", character: "ম", romanization: "m",   exampleWord: "মা — mother",      xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-4", character: "ভ", romanization: "bh",  exampleWord: "ভালো — good",     xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-5", character: "স", romanization: "s",   exampleWord: "সে — he/she",      xp: 4 },
          ],
        },
        {
          id: "raj-1-1",
          title: "Greetings",
          description: "Greet, ask a name, and give a basic reply in Rajshahi-based Bangla",
          unit: 1,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-1-mp-1",
              pairs: [
                { bangla: "আসসালামু আলাইকুম", english: "Hello (Islamic greeting)", romanization: "assalamu alaikum" },
                { bangla: "নমস্কার",            english: "Hello / Greetings",        romanization: "nomoshkar"        },
                { bangla: "ভালো",              english: "Good / Fine",              romanization: "bhalo"            },
                { bangla: "আমার নাম ___।",     english: "My name is ___.",          romanization: "amar nam ___."    },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-1-tte-1",
              bangla: "তুমি কেমন আছো?",
              romanization: "tumi kemon acho?",
              answer: "How are you?",
              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "raj-1-1-ttb-1",
              english: "I am fine.",
              answer: "আমি ভালো আছি।",
              romanization: "ami bhalo achi.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "raj-1-1-mc-1",
              prompt: "How do you say 'What is your name?' in Rajshahi Bangla?",
              options: [
                "তোমার নাম কী?",
                "কিতা তোমার নাম?",
                "তুঁয়ার নাম কী?",
                "আপনার নামডা কী?",
              ],
              correct: 0,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-2",
          title: "Introductions",
          description: "Say your name and where you are from in Rajshahi Bangla",
          unit: 1,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-1-2-tte-1",
              bangla: "আমার নাম ___।",
              romanization: "amar nam ___.",
              answer: "My name is ___.",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-1-2-tte-2",
              bangla: "আমি বাংলা শিখছি।",
              romanization: "ami bangla shikhchi.",
              answer: "I am learning Bangla.",
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "raj-1-2-fb-1",
              sentence: "আমি ___ থেকে এসেছি।",
              blank: "ঢাকা",
              romanization: "ami ___ theke eshechi.",
              options: ["ঢাকা", "খাওয়া", "নাম", "আমার"],
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-2-mc-1",
              prompt: "What does 'শিখছি' mean?",
              options: ["am eating", "am learning", "am going", "am sleeping"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-3",
          title: "Polite Words",
          description: "Use polite expressions in Rajshahi Bangla",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-3-mp-1",
              pairs: [
                { bangla: "ধন্যবাদ",    english: "Thank you",  romanization: "dhonnobad" },
                { bangla: "দয়া করে",   english: "Please",     romanization: "doya kore" },
                { bangla: "মাফ করবেন", english: "Excuse me",  romanization: "maf korben" },
                { bangla: "ঠিক আছে",   english: "Okay",       romanization: "thik ache" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-3-tte-1",
              bangla: "দয়া করে বসুন।",
              romanization: "doya kore bosun.",
              answer: "Please sit.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-3-mc-1",
              prompt: "Which phrase means 'Excuse me' in Rajshahi Bangla?",
              options: ["ধন্যবাদ", "দয়া করে", "মাফ করবেন", "বসুন"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-4",
          title: "Yes / No / Basic Replies",
          description: "Answer simple questions in Rajshahi Bangla",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-4-mp-1",
              pairs: [
                { bangla: "হ্যাঁ",     english: "Yes",         romanization: "hya"    },
                { bangla: "না",        english: "No",          romanization: "na"     },
                { bangla: "হয়তো",    english: "Maybe",       romanization: "hoyto"  },
                { bangla: "জানি না", english: "I don't know", romanization: "jani na" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-1-4-ttb-1",
              english: "Yes, I can.",
              answer: "হ্যাঁ, পারি।",
              romanization: "hya, pari.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-4-mc-1",
              prompt: "How do you say 'Maybe' in Rajshahi Bangla?",
              options: ["হ্যাঁ", "না", "হয়তো", "জানি"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-5",
          title: "Pronouns",
          description: "Use Rajshahi Bangla pronouns in everyday phrases",
          unit: 1,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-5-mp-1",
              pairs: [
                { bangla: "আমি",   english: "I",             romanization: "ami"  },
                { bangla: "তুমি",  english: "You (familiar)", romanization: "tumi" },
                { bangla: "আপনি", english: "You (polite)",   romanization: "apni" },
                { bangla: "সে",    english: "He / She",       romanization: "shey" },
                { bangla: "তারা", english: "They",            romanization: "tara" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-5-tte-1",
              bangla: "আপনি কেমন আছেন?",
              romanization: "apni kemon achen?",
              answer: "How are you? (polite)",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-1-5-tte-2",
              bangla: "তারা আসবে।",
              romanization: "tara ashbe.",
              answer: "They will come.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "raj-1-5-mc-1",
              prompt: "In Rajshahi Bangla, 'সে' refers to:",
              options: ["I", "You", "He or She", "They"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-6",
          title: "Family",
          description: "Talk about your family in Rajshahi Bangla",
          unit: 1,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-6-mp-1",
              pairs: [
                { bangla: "মা",      english: "Mother",        romanization: "ma"      },
                { bangla: "বাবা",    english: "Father",        romanization: "baba"    },
                { bangla: "ভাই",     english: "Brother",       romanization: "bhai"    },
                { bangla: "বোন",     english: "Sister",        romanization: "bon"     },
                { bangla: "পরিবার", english: "Family",        romanization: "poribar" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-6-tte-1",
              bangla: "এ আমার মা।",
              romanization: "e amar ma.",
              answer: "This is my mother.",
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-1-6-tte-2",
              bangla: "আমার এক ভাই আছে।",
              romanization: "amar ek bhai ache.",
              answer: "I have one brother.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-6-mc-1",
              prompt: "In Rajshahi Bangla, 'মেয়ে' means:",
              options: ["son", "daughter/girl", "sister", "mother"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "raj-1-6-ttb-1",
              english: "My family is big.",
              answer: "আমার পরিবার বড়।",
              romanization: "amar poribar boro.",
              xp: 3,
            },
          ],
        },
      ],
    },
  ],
};
