import type { DialectCurriculum } from "@bangla-learn/types";

export const rajshahiCurriculum: DialectCurriculum = {
  dialect: "rajshahi",
  units: [
    {
      id: "raj-unit-1",
      title: "Rajshahi Bangla Basics",
      description: "Learn Rajshahi Bangla — the regional variety of Bangladesh's northwestern division",
      order: 1,
      color: "#16a34a",
      prep: {
        characters: [
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আমি (I)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইচ্ছা (wish)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠা (to rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এক (one)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওরা (they)" },
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কেমন (how)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খাওয়া (eating)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলাম (I went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালো (good)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মা (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাত (night)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সে (he/she)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হ্যাঁ (yes)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তোমার (your)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পরিবার (family)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বাবা (father)" },
          { symbol: "জ", romanization: "j",   type: "consonant" as const, exampleWord: "জানি (I know)" },
          { symbol: "ধ", romanization: "dh",  type: "consonant" as const, exampleWord: "ধন্যবাদ (thank you)" },
        ],
        flashcards: [
          { id: "fc-raj-1",  bangla: "আমি",       romanization: "ami",       english: "I",                   category: "pronouns"  },
          { id: "fc-raj-2",  bangla: "তুমি",       romanization: "tumi",      english: "You (familiar)",      category: "pronouns"  },
          { id: "fc-raj-3",  bangla: "আপনি",       romanization: "apni",      english: "You (polite)",        category: "pronouns"  },
          { id: "fc-raj-4",  bangla: "সে",          romanization: "shey",      english: "He / She",            category: "pronouns"  },
          { id: "fc-raj-5",  bangla: "আমরা",       romanization: "amra",      english: "We",                  category: "pronouns"  },
          { id: "fc-raj-6",  bangla: "তারা",       romanization: "tara",      english: "They",                category: "pronouns"  },
          { id: "fc-raj-7",  bangla: "ভালো",       romanization: "bhalo",     english: "Good / Fine",         category: "adjectives"},
          { id: "fc-raj-8",  bangla: "হ্যাঁ",      romanization: "hya",       english: "Yes",                 category: "phrases"   },
          { id: "fc-raj-9",  bangla: "না",          romanization: "na",        english: "No",                  category: "phrases"   },
          { id: "fc-raj-10", bangla: "ঠিক আছে",    romanization: "thik ache", english: "Okay",                category: "phrases"   },
          { id: "fc-raj-11", bangla: "ধন্যবাদ",    romanization: "dhonnobad", english: "Thank you",           category: "phrases"   },
          { id: "fc-raj-12", bangla: "মাফ করবেন", romanization: "maf korben",english: "Excuse me",           category: "phrases"   },
          { id: "fc-raj-13", bangla: "মা",          romanization: "ma",        english: "Mother",              category: "family"    },
          { id: "fc-raj-14", bangla: "বাবা",        romanization: "baba",      english: "Father",              category: "family"    },
          { id: "fc-raj-15", bangla: "বোন",         romanization: "bon",       english: "Sister",              category: "family"    },
          { id: "fc-raj-16", bangla: "ভাই",         romanization: "bhai",      english: "Brother",             category: "family"    },
        ],
        grammar: [
          {
            title: "Standard-compatible grammar",
            explanation: "Rajshahi Bangla is close to Standard Bangla in grammar, making it a natural transition track. Use standard verb endings early; regional pronunciation differences appear mainly in audio.",
            examples: [
              { bangla: "আমি ভালো আছি।",       romanization: "ami bhalo achi.",       english: "I am fine." },
              { bangla: "তুমি কেমন আছো?",       romanization: "tumi kemon acho?",      english: "How are you?" },
            ],
          },
          {
            title: "Familiar vs polite 'you'",
            explanation: "Like Standard Bangla, Rajshahi uses তুমি for familiar and আপনি for polite. সে means he/she and তারা means they.",
            examples: [
              { bangla: "আপনি কেমন আছেন?",     romanization: "apni kemon achen?",    english: "How are you? (polite)" },
              { bangla: "সে আমার বন্ধু।",       romanization: "shey amar bondhu.",     english: "He/She is my friend." },
            ],
          },
          {
            title: "Possession with আমার / তোমার",
            explanation: "Use আমার for 'my' and তোমার for 'your' (familiar). আমার নাম means 'my name.'",
            examples: [
              { bangla: "আমার নাম ___।",        romanization: "amar nam ___.",         english: "My name is ___." },
              { bangla: "তোমার নাম কী?",         romanization: "tomar nam ki?",         english: "What is your name?" },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "raj-1-0",
          title: "Write the Letters",
          description: "Trace key Bengali letters used in Rajshahi Bangla",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "raj-1-0-tr-1", character: "আ", romanization: "aa",  exampleWord: "আমি — I",          xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-2", character: "ন", romanization: "n",   exampleWord: "নাম — name",       xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-3", character: "ম", romanization: "m",   exampleWord: "মা — mother",      xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-4", character: "ভ", romanization: "bh",  exampleWord: "ভালো — good",     xp: 4 },
            { type: "letter_trace", id: "raj-1-0-tr-5", character: "স", romanization: "s",   exampleWord: "সে — he/she",      xp: 4 },
          ],
        },
        {
          id: "raj-1-1",
          title: "Greetings",
          description: "Greet, ask a name, and give a basic reply in Rajshahi-based Bangla",
          unit: 1,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-1-mp-1",
              pairs: [
                { bangla: "আসসালামু আলাইকুম", english: "Hello (Islamic greeting)", romanization: "assalamu alaikum" },
                { bangla: "নমস্কার",            english: "Hello / Greetings",        romanization: "nomoshkar"        },
                { bangla: "ভালো",              english: "Good / Fine",              romanization: "bhalo"            },
                { bangla: "আমার নাম ___।",     english: "My name is ___.",          romanization: "amar nam ___."    },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-1-tte-1",
              bangla: "তুমি কেমন আছো?",
              romanization: "tumi kemon acho?",
              answer: "How are you?",

              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "raj-1-1-ttb-1",
              english: "I am fine.",
              answer: "আমি ভালো আছি।",
              romanization: "ami bhalo achi.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "raj-1-1-mc-1",
              prompt: "How do you say 'What is your name?' in Rajshahi Bangla?",
              options: [
                "তোমার নাম কী?",
                "কিতা তোমার নাম?",
                "তুঁয়ার নাম কী?",
                "আপনার নামডা কী?",
              ],
              correct: 0,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-2",
          title: "Introductions",
          description: "Say your name and where you are from in Rajshahi Bangla",
          unit: 1,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-1-2-tte-1",
              bangla: "আমার নাম ___।",
              romanization: "amar nam ___.",
              answer: "My name is ___.",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-1-2-tte-2",
              bangla: "আমি বাংলা শিখছি।",
              romanization: "ami bangla shikhchi.",
              answer: "I am learning Bangla.",

              xp: 4,
            },
            {
              type: "fill_blank",
              id: "raj-1-2-fb-1",
              sentence: "আমি ___ থেকে এসেছি।",
              blank: "ঢাকা",
              romanization: "ami ___ theke eshechi.",
              options: ["ঢাকা", "খাওয়া", "নাম", "আমার"],
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-2-mc-1",
              prompt: "What does 'শিখছি' mean?",
              options: ["am eating", "am learning", "am going", "am sleeping"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-3",
          title: "Polite Words",
          description: "Use polite expressions in Rajshahi Bangla",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-3-mp-1",
              pairs: [
                { bangla: "ধন্যবাদ",    english: "Thank you",  romanization: "dhonnobad" },
                { bangla: "দয়া করে",   english: "Please",     romanization: "doya kore" },
                { bangla: "মাফ করবেন", english: "Excuse me",  romanization: "maf korben" },
                { bangla: "ঠিক আছে",   english: "Okay",       romanization: "thik ache" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-3-tte-1",
              bangla: "দয়া করে বসুন।",
              romanization: "doya kore bosun.",
              answer: "Please sit.",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-3-mc-1",
              prompt: "Which phrase means 'Excuse me' in Rajshahi Bangla?",
              options: ["ধন্যবাদ", "দয়া করে", "মাফ করবেন", "বসুন"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-4",
          title: "Yes / No / Basic Replies",
          description: "Answer simple questions in Rajshahi Bangla",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-4-mp-1",
              pairs: [
                { bangla: "হ্যাঁ",     english: "Yes",         romanization: "hya"    },
                { bangla: "না",        english: "No",          romanization: "na"     },
                { bangla: "হয়তো",    english: "Maybe",       romanization: "hoyto"  },
                { bangla: "জানি না", english: "I don't know", romanization: "jani na" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-1-4-ttb-1",
              english: "Yes, I can.",
              answer: "হ্যাঁ, পারি।",
              romanization: "hya, pari.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-4-mc-1",
              prompt: "How do you say 'Maybe' in Rajshahi Bangla?",
              options: ["হ্যাঁ", "না", "হয়তো", "জানি"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-5",
          title: "Pronouns",
          description: "Use Rajshahi Bangla pronouns in everyday phrases",
          unit: 1,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-5-mp-1",
              pairs: [
                { bangla: "আমি",   english: "I",             romanization: "ami"  },
                { bangla: "তুমি",  english: "You (familiar)", romanization: "tumi" },
                { bangla: "আপনি", english: "You (polite)",   romanization: "apni" },
                { bangla: "সে",    english: "He / She",       romanization: "shey" },
                { bangla: "তারা", english: "They",            romanization: "tara" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-5-tte-1",
              bangla: "আপনি কেমন আছেন?",
              romanization: "apni kemon achen?",
              answer: "How are you? (polite)",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-1-5-tte-2",
              bangla: "তারা আসবে।",
              romanization: "tara ashbe.",
              answer: "They will come.",

              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "raj-1-5-mc-1",
              prompt: "In Rajshahi Bangla, 'সে' refers to:",
              options: ["I", "You", "He or She", "They"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "raj-1-6",
          title: "Family",
          description: "Talk about your family in Rajshahi Bangla",
          unit: 1,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-1-6-mp-1",
              pairs: [
                { bangla: "মা",      english: "Mother",        romanization: "ma"      },
                { bangla: "বাবা",    english: "Father",        romanization: "baba"    },
                { bangla: "ভাই",     english: "Brother",       romanization: "bhai"    },
                { bangla: "বোন",     english: "Sister",        romanization: "bon"     },
                { bangla: "পরিবার", english: "Family",        romanization: "poribar" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-1-6-tte-1",
              bangla: "এ আমার মা।",
              romanization: "e amar ma.",
              answer: "This is my mother.",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-1-6-tte-2",
              bangla: "আমার এক ভাই আছে।",
              romanization: "amar ek bhai ache.",
              answer: "I have one brother.",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "raj-1-6-mc-1",
              prompt: "In Rajshahi Bangla, 'মেয়ে' means:",
              options: ["son", "daughter/girl", "sister", "mother"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "raj-1-6-ttb-1",
              english: "My family is big.",
              answer: "আমার পরিবার বড়।",
              romanization: "amar poribar boro.",
              xp: 3,
            },
          ],
        },
      ],
    },
    {
      id: "raj-unit-2",
      title: "Heart & Time",
      description: "Express affection, count numbers, and talk about time in Rajshahi dialect",
      order: 2,
      color: "#16a34a",
      prep: {
        characters: [],
        flashcards: [
          { id: "fc-raj-2-1",  bangla: "আপনি",         romanization: "apni",        english: "You (formal, Rajshahi — same as Standard)", category: "pronouns"  },
          { id: "fc-raj-2-2",  bangla: "তুমি",          romanization: "tumi",        english: "You (informal)",                           category: "pronouns"  },
          { id: "fc-raj-2-3",  bangla: "ভালোবাসি",    romanization: "bhalobashi",  english: "I love (you)",                             category: "phrases"   },
          { id: "fc-raj-2-4",  bangla: "যত্ন",          romanization: "jotno",       english: "Care / Attention",                         category: "phrases"   },
          { id: "fc-raj-2-5",  bangla: "কী",            romanization: "ki",          english: "What",                                     category: "questions" },
          { id: "fc-raj-2-6",  bangla: "কোথায়",        romanization: "kothay",      english: "Where",                                    category: "questions" },
          { id: "fc-raj-2-7",  bangla: "কেন",           romanization: "keno",        english: "Why",                                      category: "questions" },
          { id: "fc-raj-2-8",  bangla: "সকাল",          romanization: "shokal",      english: "Morning",                                  category: "time"      },
          { id: "fc-raj-2-9",  bangla: "বিকেল",         romanization: "bikel",       english: "Afternoon",                                category: "time"      },
          { id: "fc-raj-2-10", bangla: "সন্ধ্যা",       romanization: "shondhya",    english: "Evening",                                  category: "time"      },
          { id: "fc-raj-2-11", bangla: "রাত",           romanization: "rat",         english: "Night",                                    category: "time"      },
          { id: "fc-raj-2-12", bangla: "এখন",           romanization: "ekhon",       english: "Now",                                      category: "time"      },
          { id: "fc-raj-2-13", bangla: "আজ",            romanization: "aj",          english: "Today",                                    category: "time"      },
          { id: "fc-raj-2-14", bangla: "গতকাল",         romanization: "gotokal",     english: "Yesterday",                                category: "time"      },
          { id: "fc-raj-2-15", bangla: "আগামীকাল",     romanization: "agamikal",    english: "Tomorrow",                                 category: "time"      },
          { id: "fc-raj-2-16", bangla: "আসব",           romanization: "ashbo",       english: "Will come (future)",                       category: "grammar"   },
          { id: "fc-raj-2-17", bangla: "করবে",          romanization: "korbe",       english: "Will do (future, 2nd person)",             category: "grammar"   },
          { id: "fc-raj-2-18", bangla: "এগারো",         romanization: "egaro",       english: "Eleven",                                   category: "numbers"   },
          { id: "fc-raj-2-19", bangla: "পনেরো",         romanization: "ponero",      english: "Fifteen",                                  category: "numbers"   },
          { id: "fc-raj-2-20", bangla: "বিশ",           romanization: "bish",        english: "Twenty",                                   category: "numbers"   },
        ],
        grammar: [
          {
            title: "Rajshahi — Close to Standard",
            explanation: "Rajshahi dialect stays very close to Standard Bangla in vocabulary. Key differences: slight vowel shifts in fast speech, and a rural cadence. The grammar rules are essentially identical to Standard.",
            examples: [
              { bangla: "তুমি কেমন আছ?",       romanization: "tumi kemon achho?",    english: "How are you? (informal)" },
              { bangla: "আমি ভালো আছি।",        romanization: "ami bhalo achi.",       english: "I am fine." },
            ],
          },
          {
            title: "Rajshahi Future Tense",
            explanation: "Future tense in Rajshahi matches Standard Bangla: '-ব' suffix. 'আসব' (will come), 'করবে' (you will do), 'দেব' (will give). No dialect-specific transformations.",
            examples: [
              { bangla: "আমি আগামীকাল আসব।", romanization: "ami agamikal ashbo.",  english: "I will come tomorrow." },
              { bangla: "তুমি কী করবে?",       romanization: "tumi ki korbe?",       english: "What will you do?" },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "raj-2-0",
          title: "Respect & Affection",
          description: "Express love and respect — Rajshahi style",
          unit: 2,
          order: 0,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-2-0-mp-1",
              pairs: [
                { bangla: "ভালোবাসি",  english: "I love (you)",   romanization: "bhalobashi" },
                { bangla: "যত্ন নাও",  english: "Take care",       romanization: "jotno nao" },
                { bangla: "আপনি",      english: "You (formal)",    romanization: "apni"       },
                { bangla: "প্রিয়",    english: "Dear / Beloved",  romanization: "priyo"      },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-2-0-tte-1",
              bangla: "তুমি আমার খুব প্রিয়।",
              romanization: "tumi amar khub priyo.",
              answer: "You are very dear to me.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-0-mc-1",
              prompt: "In Rajshahi, the formal 'you' is (same as Standard):",
              options: ["আপনে", "হে", "আপনি", "তুঁই"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "raj-2-1",
          title: "Sweet Questions",
          description: "Ask questions — কী, কোথায়, কেন",
          unit: 2,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-2-1-tte-1",
              bangla: "তুমি কোথায় যাচ্ছ?",
              romanization: "tumi kothay jaccho?",
              answer: "Where are you going?",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-2-1-fb-1",
              sentence: "তোমার ___ পছন্দ?",
              blank: "কী",
              romanization: "tomar ___ pochondo?",
              options: ["কেন", "কী", "কোথায়", "কেমন"],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-1-mc-1",
              prompt: "Rajshahi uses the same word as Standard for 'where':",
              options: ["কেলে", "কই", "কোথায়", "কিতা"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "raj-2-2",
          title: "Numbers 1–10",
          description: "Count from one to ten",
          unit: 2,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-2-2-mp-1",
              pairs: [
                { bangla: "এক",   english: "One",   romanization: "ek"    },
                { bangla: "দুই",  english: "Two",   romanization: "dui"   },
                { bangla: "তিন",  english: "Three", romanization: "tin"   },
                { bangla: "পাঁচ", english: "Five",  romanization: "pach"  },
              ],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-2-2-mp-2",
              pairs: [
                { bangla: "ছয়",  english: "Six",   romanization: "choy"  },
                { bangla: "সাত",  english: "Seven", romanization: "shat"  },
                { bangla: "আট",   english: "Eight", romanization: "at"    },
                { bangla: "দশ",   english: "Ten",   romanization: "dosh"  },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-2-mc-1",
              prompt: "What is 'নয়' in English?",
              options: ["Seven", "Eight", "Nine", "Ten"],
              correct: 2,
              xp: 5,
            },
          ],
        },
        {
          id: "raj-2-3",
          title: "Numbers 11–20",
          description: "Count from eleven to twenty",
          unit: 2,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-2-3-mp-1",
              pairs: [
                { bangla: "এগারো", english: "Eleven",   romanization: "egaro"    },
                { bangla: "বারো",  english: "Twelve",   romanization: "baro"     },
                { bangla: "তেরো",  english: "Thirteen", romanization: "tero"     },
                { bangla: "বিশ",   english: "Twenty",   romanization: "bish"     },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-3-mc-1",
              prompt: "How do you say 'sixteen' in Bangla?",
              options: ["পনেরো", "ষোলো", "সতেরো", "আঠারো"],
              correct: 1,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-2-3-tte-1",
              bangla: "আমার বয়স আঠারো।",
              romanization: "amar boyosh atharo.",
              answer: "I am eighteen years old.",

              xp: 5,
            },
          ],
        },
        {
          id: "raj-2-4",
          title: "Time Words",
          description: "Morning, evening, night, now",
          unit: 2,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "raj-2-4-mp-1",
              pairs: [
                { bangla: "সকাল",   english: "Morning",  romanization: "shokal"   },
                { bangla: "বিকেল",  english: "Afternoon", romanization: "bikel"   },
                { bangla: "সন্ধ্যা", english: "Evening", romanization: "shondhya" },
                { bangla: "রাত",    english: "Night",    romanization: "rat"      },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-2-4-tte-1",
              bangla: "এখন সন্ধ্যা।",
              romanization: "ekhon shondhya.",
              answer: "It is evening now.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-4-mc-1",
              prompt: "In Rajshahi (same as Standard), 'now' is:",
              options: ["এহন", "এখন", "আইজ", "রাইত"],
              correct: 1,
              xp: 5,
            },
          ],
        },
        {
          id: "raj-2-5",
          title: "Today / Yesterday / Tomorrow",
          description: "Talk about days — quiz time!",
          unit: 2,
          order: 5,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-2-5-mc-1",
              prompt: "In Rajshahi (same as Standard), 'yesterday' is:",
              options: ["আজ", "গতকাল", "আগামীকাল", "এখন"],
              correct: 1,
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-2-5-mc-2",
              prompt: "How do you say 'tomorrow'?",
              options: ["গতকাল", "আজ", "আগামীকাল", "পরশু"],
              correct: 2,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "raj-2-5-tte-1",
              bangla: "আমি আগামীকাল আসব।",
              romanization: "ami agamikal ashbo.",
              answer: "I will come tomorrow.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-2-5-ttb-1",
              english: "What did you do yesterday?",
              answer: "তুমি গতকাল কী করলে?",
              romanization: "tumi gotokal ki korle?",
              xp: 5,
            },
          ],
        },
      ],
    },
    // ─── Unit 3 ───────────────────────────────────────────────────────────────
    {
      id: "raj-unit-3",
      title: "Food & Daily Life",
      description: "Rajshahi-flavoured food talk, market visits, and home routines.",
      color: "#15803d",
      order: 3,
      prep: {
        flashcards: [
          { id: "fc-raj-3-1",  bangla: "ভাত",        romanization: "vhat",      english: "cooked rice",     emoji: "🍚", category: "food" },
          { id: "fc-raj-3-2",  bangla: "মাছ",         romanization: "mach",      english: "fish",            emoji: "🐟", category: "food" },
          { id: "fc-raj-3-3",  bangla: "ডাল",         romanization: "dal",       english: "lentils",         emoji: "🫘", category: "food" },
          { id: "fc-raj-3-4",  bangla: "সবজি",        romanization: "shobji",    english: "vegetables",      emoji: "🥦", category: "food" },
          { id: "fc-raj-3-5",  bangla: "পানি",        romanization: "pani",      english: "water",           emoji: "💧", category: "food" },
          { id: "fc-raj-3-6",  bangla: "চা",          romanization: "cha",       english: "tea",             emoji: "🍵", category: "food" },
          { id: "fc-raj-3-7",  bangla: "দুধ",         romanization: "dudh",      english: "milk",            emoji: "🥛", category: "food" },
          { id: "fc-raj-3-8",  bangla: "রুটি",        romanization: "ruti",      english: "bread / roti",    emoji: "🫓", category: "food" },
          { id: "fc-raj-3-9",  bangla: "মাংস",        romanization: "mangsho",   english: "meat",            emoji: "🍖", category: "food" },
          { id: "fc-raj-3-10", bangla: "ফল",          romanization: "fol",       english: "fruit",           emoji: "🍎", category: "food" },
          { id: "fc-raj-3-11", bangla: "খাচ্ছি",     romanization: "khashshi",  english: "I am eating",     emoji: "😋", category: "verb" },
          { id: "fc-raj-3-12", bangla: "রান্না করছি", romanization: "ranna korshi", english: "I am cooking", emoji: "👨‍🍳", category: "verb" },
          { id: "fc-raj-3-13", bangla: "বাজার",       romanization: "bajar",     english: "market",          emoji: "🛒", category: "place" },
          { id: "fc-raj-3-14", bangla: "দোকান",       romanization: "dokan",     english: "shop",            emoji: "🏪", category: "place" },
          { id: "fc-raj-3-15", bangla: "বাড়ি",        romanization: "bari",      english: "home",            emoji: "🏠", category: "place" },
          { id: "fc-raj-3-16", bangla: "ঘর",          romanization: "ghor",      english: "room",            emoji: "🚪", category: "place" },
          { id: "fc-raj-3-17", bangla: "রান্নাঘর",    romanization: "rannaghor", english: "kitchen",         emoji: "🍳", category: "place" },
          { id: "fc-raj-3-18", bangla: "বিছানা",      romanization: "bishana",   english: "bed",             emoji: "🛏️", category: "home" },
          { id: "fc-raj-3-19", bangla: "ক্ষুধা",      romanization: "khudha",    english: "hunger",          emoji: "😩", category: "feeling" },
          { id: "fc-raj-3-20", bangla: "পেট ভরা",     romanization: "pet vhora", english: "stomach full",    emoji: "😌", category: "feeling" },
          { id: "fc-raj-3-21", bangla: "কিনব",        romanization: "kinbo",     english: "I will buy",      emoji: "🛍️", category: "verb" },
          { id: "fc-raj-3-22", bangla: "দাম",         romanization: "dam",       english: "price",           emoji: "💰", category: "market" },
          { id: "fc-raj-3-23", bangla: "সস্তা",       romanization: "shoshta",   english: "cheap",           emoji: "🏷️", category: "market" },
          { id: "fc-raj-3-24", bangla: "দামি",        romanization: "dami",      english: "expensive",       emoji: "💎", category: "market" },
          { id: "fc-raj-3-25", bangla: "ঘুমাচ্ছি",   romanization: "ghumashshi",english: "I am sleeping",   emoji: "😴", category: "routine" },
          { id: "fc-raj-3-26", bangla: "উঠছি",       romanization: "uthshi",    english: "I am getting up", emoji: "🌅", category: "routine" },
          { id: "fc-raj-3-27", bangla: "গোসল",        romanization: "ghoshol",   english: "bath",            emoji: "🚿", category: "routine" },
          { id: "fc-raj-3-28", bangla: "কাজে যাই",   romanization: "kaje jai",  english: "I go to work",    emoji: "💼", category: "routine" },
        ],
        characters: [],
        grammar: [
          {
            title: "Standard -ছি progressive in Rajshahi",
            explanation: "Rajshahi uses standard Bengali -ছি progressive: খাচ্ছি (am eating), রান্না করছি (am cooking). This matches Standard Bengali closely.",
            examples: [
              { bangla: "আমি ভাত খাচ্ছি।",      romanization: "ami vhat khashshi.",    english: "I am eating rice." },
              { bangla: "মা রান্না করছেন।",      romanization: "ma ranna korshhen.",    english: "Mother is cooking." },
            ],
          },
          {
            title: "কিনব — future in Rajshahi",
            explanation: "Rajshahi future uses standard -ব: কিনব (will buy), খাব (will eat), যাব (will go).",
            examples: [
              { bangla: "আমি বাজার থেকে মাছ কিনব।", romanization: "ami bajar theke mach kinbo.", english: "I will buy fish from the market." },
              { bangla: "তোমাকে চা দেব।",            romanization: "tomake cha debo.",             english: "I will give you tea." },
            ],
          },
          {
            title: "থেকে = from (Rajshahi standard form)",
            explanation: "Rajshahi uses থেকে (standard Bengali) for 'from', unlike Barisali থাইকা or Chittagonian থাকি.",
            examples: [
              { bangla: "দোকান থেকে কিনেছি।", romanization: "dokan theke kineshi.", english: "I bought from the shop." },
              { bangla: "বাড়ির কাছে বাজার।",  romanization: "barir kashe bajar.",   english: "The market is near home." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "raj-3-1",
          title: "Rice & Fish",
          description: "Food staples: rice, fish, and lentils in Rajshahi dialect",
          unit: 3,
          order: 1,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-3-1-mc-1",
              prompt: "Rajshahi 'I am eating' (standard form) is:",
              options: ["খাইতাছি", "খাচ্ছি", "খাইছি", "খামু"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-3-1-tte-1",
              bangla: "আমি ভাত আর মাছ খাচ্ছি।",
              romanization: "ami vhat ar mach khashshi.",
              answer: "I am eating rice and fish.",

              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-3-1-mp-1",
              pairs: [
                { bangla: "ভাত",  english: "rice", romanization: "bhat" },
                { bangla: "মাছ",  english: "fish", romanization: "mach" },
                { bangla: "ডাল",  english: "lentils", romanization: "dal" },
                { bangla: "পানি", english: "water", romanization: "pani" },
              ],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "raj-3-1-ttb-1",
              english: "I will eat fish and rice.",
              answer: "আমি মাছ আর ভাত খাব।",
              romanization: "ami mach ar vhat khabo.",
              xp: 5,
            },
          ],
        },
        {
          id: "raj-3-2",
          title: "At the Market",
          description: "Shopping at the market in Rajshahi dialect",
          unit: 3,
          order: 2,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-3-2-mc-1",
              prompt: "Rajshahi 'I will buy' is:",
              options: ["কিনব", "কিনমু", "কিনুম", "কিনছি"],
              correct: 0,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-3-2-tte-1",
              bangla: "বাজার থেকে সবজি কিনব।",
              romanization: "bajar theke shobji kinbo.",
              answer: "I will buy vegetables from the market.",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-3-2-fb-1",
              sentence: "মাংসটা অনেক ___।",
              romanization: "mangsota onek ___.",
              blank: "দামি",

              options: ["দামি"],

              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-3-2-mp-1",
              pairs: [
                { bangla: "বাজার",  english: "market", romanization: "bajar" },
                { bangla: "দোকান",  english: "shop", romanization: "dokan" },
                { bangla: "সস্তা",  english: "cheap", romanization: "shoshta" },
                { bangla: "দামি",   english: "expensive", romanization: "dami" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "raj-3-3",
          title: "In the Kitchen",
          description: "Kitchen vocabulary and cooking in Rajshahi",
          unit: 3,
          order: 3,
          xpReward: 20,
          exercises: [
            {
              type: "translate_to_english",
              id: "raj-3-3-tte-1",
              bangla: "মা রান্নাঘরে রান্না করছেন।",
              romanization: "ma rannaghor-e ranna korshhen.",
              answer: "Mother is cooking in the kitchen.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-3-3-mc-1",
              prompt: "Rajshahi 'kitchen' is:",
              options: ["খাবার ঘর", "রান্নাঘর", "বিছানা ঘর", "কাজের ঘর"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "raj-3-3-mp-1",
              pairs: [
                { bangla: "রান্নাঘর", english: "kitchen", romanization: "rannaghor" },
                { bangla: "বিছানা",   english: "bed", romanization: "bishana" },
                { bangla: "ঘর",       english: "room", romanization: "ghor" },
                { bangla: "বাড়ি",    english: "home", romanization: "bari" },
              ],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "raj-3-3-ttb-1",
              english: "I will cook at home.",
              answer: "আমি বাড়িতে রান্না করব।",
              romanization: "ami barite ranna korbo.",
              xp: 5,
            },
          ],
        },
        {
          id: "raj-3-4",
          title: "Daily Routine",
          description: "Daily routine and meal times in Rajshahi",
          unit: 3,
          order: 4,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-3-4-mc-1",
              prompt: "Rajshahi 'I am sleeping' is:",
              options: ["ঘুমাইতাছি", "ঘুমাচ্ছি", "ঘুমামু", "ঘুমাইছি"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-3-4-tte-1",
              bangla: "ভোরে উঠে গোসল করেছি।",
              romanization: "vhore uthe ghoshol korechi.",
              answer: "I woke up early and bathed.",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-3-4-fb-1",
              sentence: "সকালে উঠে ___ করেছি।",
              romanization: "shokale uthe ___ korechi.",
              blank: "গোসল",

              options: ["গোসল"],

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-3-4-ttb-1",
              english: "I go to work every day.",
              answer: "আমি প্রতিদিন কাজে যাই।",
              romanization: "ami protidin kaje jai.",
              xp: 5,
            },
          ],
        },
        {
          id: "raj-3-5",
          title: "Hunger & Fullness",
          description: "Expressing hunger and fullness in Rajshahi",
          unit: 3,
          order: 5,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-3-5-mc-1",
              prompt: "Rajshahi standard word for 'hunger' is:",
              options: ["খিদা", "ক্ষুধা", "পেট", "তৃষ্ণা"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-3-5-tte-1",
              bangla: "আমার অনেক ক্ষুধা পেয়েছে।",
              romanization: "amar onek khudha peyeche.",
              answer: "I am very hungry.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-3-5-ttb-1",
              english: "My stomach is full.",
              answer: "আমার পেট ভরা।",
              romanization: "amar pet vhora.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "raj-3-5-mp-1",
              pairs: [
                { bangla: "ক্ষুধা",  english: "hunger", romanization: "khudha" },
                { bangla: "পেট ভরা", english: "stomach full", romanization: "pet vhora" },
                { bangla: "পানি",    english: "water", romanization: "pani" },
                { bangla: "চা",      english: "tea", romanization: "cha" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "raj-3-6",
          title: "Food Quiz",
          description: "Food & Daily Life quiz — Rajshahi Unit 3",
          unit: 3,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "raj-3-6-mc-1",
              prompt: "Rajshahi future 'I will buy' is:",
              options: ["কিনমু", "কিনব", "কিনুম", "কিনতেছি"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "raj-3-6-tte-1",
              bangla: "আমি বাজার থেকে মাছ আর সবজি কিনব।",
              romanization: "ami bajar theke mach ar shobji kinbo.",
              answer: "I will buy fish and vegetables from the market.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "raj-3-6-ttb-1",
              english: "Mother is cooking in the kitchen.",
              answer: "মা রান্নাঘরে রান্না করছেন।",
              romanization: "ma rannaghor-e ranna korshhen.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "raj-3-6-fb-1",
              sentence: "আমার অনেক ___ পেয়েছে।",
              romanization: "amar onek ___ peyeche.",
              blank: "ক্ষুধা",

              options: ["ক্ষুধা"],

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "raj-3-6-mc-2",
              prompt: "Rajshahi 'from the market' is:",
              options: ["বাজার থাইকা", "বাজার থাকি", "বাজার থেকে", "বাজার লাই"],
              correct: 2,
              xp: 4,
            },
          ],
        },
      ],
    },
  ],
};
