import type { DialectCurriculum } from "@bangla-learn/types";

export const standardCurriculum: DialectCurriculum = {
  dialect: "standard",
  units: [
    {
      id: "std-unit-1",
      title: "Greetings & Basics",
      description: "Learn how to say hello, goodbye, and introduce yourself",
      order: 1,
      color: "#58CC02",
      lessons: [
        {
          id: "std-1-1",
          title: "Hello & Goodbye",
          description: "Your first Bengali words",
          unit: 1,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "multiple_choice",
              id: "std-1-1-mc-1",
              prompt: "How do you say 'Hello' in Standard Bengali?",
              options: ["নমস্কার (Nomoshkar)", "আল্লাহ হাফেজ (Allah Hafez)", "ধন্যবাদ (Dhonnobad)", "হ্যাঁ (Hæ)"],
              correct: 0,
              xp: 2,
            },
            {
              type: "translate_to_english",
              id: "std-1-1-tte-1",
              bangla: "আসসালামু আলাইকুম",
              romanization: "Assalamu Alaikum",
              answer: "Peace be upon you (Islamic greeting / Hello)",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "std-1-1-mc-2",
              prompt: "What does 'আল্লাহ হাফেজ' mean?",
              options: ["Hello", "Thank you", "Goodbye", "How are you?"],
              correct: 2,
              xp: 2,
            },
            {
              type: "translate_to_bangla",
              id: "std-1-1-ttb-1",
              english: "Hello",
              answer: "নমস্কার",
              romanization: "Nomoshkar",
              xp: 3,
            },
          ],
        },
        {
          id: "std-1-2",
          title: "How Are You?",
          description: "Asking and answering 'how are you'",
          unit: 1,
          order: 2,
          xpReward: 10,
          exercises: [
            {
              type: "multiple_choice",
              id: "std-1-2-mc-1",
              prompt: "How do you say 'How are you?' in Bengali?",
              options: [
                "আপনি কেমন আছেন? (Apni kemon achen?)",
                "আপনার নাম কী? (Apnar nam ki?)",
                "ধন্যবাদ (Dhonnobad)",
                "আমি ভালো আছি (Ami bhalo achi)",
              ],
              correct: 0,
              xp: 2,
            },
            {
              type: "translate_to_english",
              id: "std-1-2-tte-1",
              bangla: "আমি ভালো আছি",
              romanization: "Ami bhalo achi",
              answer: "I am fine / I am good",
              xp: 3,
            },
            {
              type: "fill_blank",
              id: "std-1-2-fb-1",
              sentence: "আপনি ___ আছেন?",
              blank: "কেমন",
              romanization: "Apni ___ achen?",
              options: ["কেমন", "ভালো", "নাম", "কী"],
              xp: 3,
            },
            {
              type: "translate_to_bangla",
              id: "std-1-2-ttb-1",
              english: "I am fine",
              answer: "আমি ভালো আছি",
              romanization: "Ami bhalo achi",
              xp: 2,
            },
          ],
        },
        {
          id: "std-1-3",
          title: "Numbers 1–5",
          description: "Count from one to five in Bengali",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "std-1-3-mp-1",
              pairs: [
                { bangla: "এক", english: "One", romanization: "Ek" },
                { bangla: "দুই", english: "Two", romanization: "Dui" },
                { bangla: "তিন", english: "Three", romanization: "Tin" },
                { bangla: "চার", english: "Four", romanization: "Char" },
                { bangla: "পাঁচ", english: "Five", romanization: "Pach" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "std-1-3-mc-1",
              prompt: "What is 'তিন' in English?",
              options: ["One", "Two", "Three", "Four"],
              correct: 2,
              xp: 2,
            },
            {
              type: "translate_to_bangla",
              id: "std-1-3-ttb-1",
              english: "Four",
              answer: "চার",
              romanization: "Char",
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-3-mc-2",
              prompt: "Which Bengali word means 'Five'?",
              options: ["এক", "দুই", "তিন", "পাঁচ"],
              correct: 3,
              xp: 2,
            },
          ],
        },
        {
          id: "std-1-4",
          title: "Numbers 6–10",
          description: "Continue counting in Bengali",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "std-1-4-mp-1",
              pairs: [
                { bangla: "ছয়", english: "Six", romanization: "Choy" },
                { bangla: "সাত", english: "Seven", romanization: "Shaat" },
                { bangla: "আট", english: "Eight", romanization: "Aat" },
                { bangla: "নয়", english: "Nine", romanization: "Noy" },
                { bangla: "দশ", english: "Ten", romanization: "Dosh" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "std-1-4-mc-1",
              prompt: "How do you say '7' in Bengali?",
              options: ["ছয়", "সাত", "আট", "নয়"],
              correct: 1,
              xp: 2,
            },
            {
              type: "translate_to_english",
              id: "std-1-4-tte-1",
              bangla: "দশ",
              romanization: "Dosh",
              answer: "Ten",
              xp: 3,
            },
          ],
        },
        {
          id: "std-1-5",
          title: "Family",
          description: "Learn words for family members",
          unit: 1,
          order: 5,
          xpReward: 20,
          exercises: [
            {
              type: "match_pairs",
              id: "std-1-5-mp-1",
              pairs: [
                { bangla: "মা", english: "Mother", romanization: "Ma" },
                { bangla: "বাবা", english: "Father", romanization: "Baba" },
                { bangla: "ভাই", english: "Brother", romanization: "Bhai" },
                { bangla: "বোন", english: "Sister", romanization: "Bon" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "std-1-5-mc-1",
              prompt: "What does 'দাদা' mean?",
              options: ["Father", "Uncle", "Grandfather (paternal)", "Brother"],
              correct: 2,
              xp: 3,
            },
            {
              type: "translate_to_bangla",
              id: "std-1-5-ttb-1",
              english: "Mother",
              answer: "মা",
              romanization: "Ma",
              xp: 2,
            },
            {
              type: "fill_blank",
              id: "std-1-5-fb-1",
              sentence: "আমার ___ আছে।",
              blank: "ভাই",
              romanization: "Amar ___ ache. (I have a brother.)",
              options: ["ভাই", "মা", "দশ", "ভালো"],
              xp: 3,
            },
          ],
        },
      ],
    },
    {
      id: "std-unit-2",
      title: "Colors & Objects",
      description: "Describe the world around you",
      order: 2,
      color: "#1CB0F6",
      lessons: [
        {
          id: "std-2-1",
          title: "Basic Colors",
          description: "Learn colors in Bengali",
          unit: 2,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "std-2-1-mp-1",
              pairs: [
                { bangla: "লাল", english: "Red", romanization: "Laal" },
                { bangla: "নীল", english: "Blue", romanization: "Neel" },
                { bangla: "সবুজ", english: "Green", romanization: "Shobuj" },
                { bangla: "হলুদ", english: "Yellow", romanization: "Holud" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "std-2-1-mc-1",
              prompt: "What color is 'কালো'?",
              options: ["White", "Black", "Orange", "Purple"],
              correct: 1,
              xp: 2,
            },
            {
              type: "translate_to_bangla",
              id: "std-2-1-ttb-1",
              english: "Green",
              answer: "সবুজ",
              romanization: "Shobuj",
              xp: 3,
            },
          ],
        },
      ],
    },
  ],
};
