import type { DialectCurriculum } from "@bangla-learn/types";

export const standardCurriculum: DialectCurriculum = {
  dialect: "standard",
  units: [
    {
      id: "std-unit-1",
      title: "Greetings & Basics",
      description: "Learn how to say hello, goodbye, and introduce yourself",
      order: 1,
      color: "#58CC02",
      prep: {
        characters: [
          // ── All 11 Bengali vowels (স্বরবর্ণ) ──────────────────────────────
          { symbol: "অ",  romanization: "o/a",  type: "vowel", exampleWord: "অনেক",   exampleMeaning: "many" },
          { symbol: "আ",  romanization: "aa",   type: "vowel", exampleWord: "আম",     exampleMeaning: "mango" },
          { symbol: "ই",  romanization: "i",    type: "vowel", exampleWord: "ইলিশ",   exampleMeaning: "hilsa fish" },
          { symbol: "ঈ",  romanization: "ii",   type: "vowel", exampleWord: "ঈদ",     exampleMeaning: "Eid" },
          { symbol: "উ",  romanization: "u",    type: "vowel", exampleWord: "উট",     exampleMeaning: "camel" },
          { symbol: "ঊ",  romanization: "uu",   type: "vowel", exampleWord: "ঊনত্রিশ", exampleMeaning: "twenty-nine" },
          { symbol: "ঋ",  romanization: "ri",   type: "vowel", exampleWord: "ঋতু",    exampleMeaning: "season" },
          { symbol: "এ",  romanization: "e",    type: "vowel", exampleWord: "এক",     exampleMeaning: "one" },
          { symbol: "ঐ",  romanization: "oi",   type: "vowel", exampleWord: "ঐক্য",   exampleMeaning: "unity" },
          { symbol: "ও",  romanization: "o",    type: "vowel", exampleWord: "ওষুধ",   exampleMeaning: "medicine" },
          { symbol: "ঔ",  romanization: "ou",   type: "vowel", exampleWord: "ঔষধ",    exampleMeaning: "drug/medicine" },
          // ── 39 Bengali consonants (ব্যঞ্জনবর্ণ) ────────────────────────────
          { symbol: "ক",  romanization: "k",    type: "consonant", exampleWord: "কলা",     exampleMeaning: "banana" },
          { symbol: "খ",  romanization: "kh",   type: "consonant", exampleWord: "খাবার",   exampleMeaning: "food" },
          { symbol: "গ",  romanization: "g",    type: "consonant", exampleWord: "গরু",     exampleMeaning: "cow" },
          { symbol: "ঘ",  romanization: "gh",   type: "consonant", exampleWord: "ঘর",     exampleMeaning: "house" },
          { symbol: "ঙ",  romanization: "ng",   type: "consonant", exampleWord: "বাংলা",   exampleMeaning: "Bangla" },
          { symbol: "চ",  romanization: "ch",   type: "consonant", exampleWord: "চাঁদ",   exampleMeaning: "moon" },
          { symbol: "ছ",  romanization: "chh",  type: "consonant", exampleWord: "ছাতা",   exampleMeaning: "umbrella" },
          { symbol: "জ",  romanization: "j",    type: "consonant", exampleWord: "জল",     exampleMeaning: "water" },
          { symbol: "ঝ",  romanization: "jh",   type: "consonant", exampleWord: "ঝড়",    exampleMeaning: "storm" },
          { symbol: "ঞ",  romanization: "ny",   type: "consonant", exampleWord: "জ্ঞান",  exampleMeaning: "knowledge" },
          { symbol: "ট",  romanization: "T",    type: "consonant", exampleWord: "টাকা",   exampleMeaning: "taka/money" },
          { symbol: "ঠ",  romanization: "Th",   type: "consonant", exampleWord: "ঠান্ডা", exampleMeaning: "cold" },
          { symbol: "ড",  romanization: "D",    type: "consonant", exampleWord: "ডাল",    exampleMeaning: "lentils" },
          { symbol: "ঢ",  romanization: "Dh",   type: "consonant", exampleWord: "ঢাকা",   exampleMeaning: "Dhaka" },
          { symbol: "ণ",  romanization: "N",    type: "consonant", exampleWord: "বর্ণ",   exampleMeaning: "letter" },
          { symbol: "ত",  romanization: "t",    type: "consonant", exampleWord: "তারা",   exampleMeaning: "star" },
          { symbol: "থ",  romanization: "th",   type: "consonant", exampleWord: "থালা",   exampleMeaning: "plate" },
          { symbol: "দ",  romanization: "d",    type: "consonant", exampleWord: "দুধ",    exampleMeaning: "milk" },
          { symbol: "ধ",  romanization: "dh",   type: "consonant", exampleWord: "ধান",    exampleMeaning: "paddy rice" },
          { symbol: "ন",  romanization: "n",    type: "consonant", exampleWord: "নাম",    exampleMeaning: "name" },
          { symbol: "প",  romanization: "p",    type: "consonant", exampleWord: "পাখি",   exampleMeaning: "bird" },
          { symbol: "ফ",  romanization: "ph/f", type: "consonant", exampleWord: "ফুল",    exampleMeaning: "flower" },
          { symbol: "ব",  romanization: "b",    type: "consonant", exampleWord: "বই",     exampleMeaning: "book" },
          { symbol: "ভ",  romanization: "bh",   type: "consonant", exampleWord: "ভালো",   exampleMeaning: "good" },
          { symbol: "ম",  romanization: "m",    type: "consonant", exampleWord: "মা",     exampleMeaning: "mother" },
          { symbol: "য",  romanization: "y/j",  type: "consonant", exampleWord: "যাও",    exampleMeaning: "go" },
          { symbol: "র",  romanization: "r",    type: "consonant", exampleWord: "রাত",    exampleMeaning: "night" },
          { symbol: "ল",  romanization: "l",    type: "consonant", exampleWord: "লাল",    exampleMeaning: "red" },
          { symbol: "শ",  romanization: "sh",   type: "consonant", exampleWord: "শুভ",    exampleMeaning: "auspicious" },
          { symbol: "ষ",  romanization: "Sh",   type: "consonant", exampleWord: "ষোল",    exampleMeaning: "sixteen" },
          { symbol: "স",  romanization: "s",    type: "consonant", exampleWord: "সব",     exampleMeaning: "all" },
          { symbol: "হ",  romanization: "h",    type: "consonant", exampleWord: "হাত",    exampleMeaning: "hand" },
          { symbol: "ড়", romanization: "r",    type: "consonant", exampleWord: "গাড়ি",  exampleMeaning: "car" },
          { symbol: "ঢ়", romanization: "rh",   type: "consonant", exampleWord: "ঢেঁড়স", exampleMeaning: "okra" },
          { symbol: "য়", romanization: "y",    type: "consonant", exampleWord: "দায়",   exampleMeaning: "responsibility" },
          { symbol: "ৎ",  romanization: "t",    type: "consonant", exampleWord: "মিষ্টি", exampleMeaning: "sweet" },
          { symbol: "ং",  romanization: "ng",   type: "consonant", exampleWord: "রং",     exampleMeaning: "color" },
          { symbol: "ঃ",  romanization: "h",    type: "consonant", exampleWord: "দুঃখ",   exampleMeaning: "sorrow" },
          { symbol: "ঁ",  romanization: "~n",   type: "consonant", exampleWord: "চাঁদ",   exampleMeaning: "moon" },
        ],
        grammar: [
          {
            title: "Bengali Script",
            explanation: "Bengali is written left-to-right using the Bengali alphabet (বাংলা বর্ণমালা). It has 11 vowels and 39 consonants. Words are joined by a horizontal headline called মাত্রা (matra).",
            examples: [
              { bangla: "আমি বাংলা শিখছি", romanization: "Ami Bangla shikhchi", english: "I am learning Bengali" },
              { bangla: "এটি সহজ", romanization: "Eti sohoj", english: "This is easy" },
            ],
          },
          {
            title: "Sentence Structure: Subject + Object + Verb",
            explanation: "Unlike English (Subject + Verb + Object), Bengali puts the verb at the END of the sentence. This is called SOV order.",
            examples: [
              { bangla: "আমি ভাত খাই", romanization: "Ami bhat khai", english: "I rice eat → I eat rice" },
              { bangla: "সে বাংলা বলে", romanization: "She Bangla bole", english: "He/She Bengali speaks → He speaks Bengali" },
            ],
          },
          {
            title: "Personal Pronouns",
            explanation: "Bengali has formal and informal versions of 'you'. Use আপনি (apni) with elders/strangers, তুমি (tumi) with friends, and তুই (tui) with very close friends or children.",
            examples: [
              { bangla: "আমি", romanization: "Ami", english: "I / Me" },
              { bangla: "তুমি / আপনি", romanization: "Tumi / Apni", english: "You (informal / formal)" },
              { bangla: "সে", romanization: "She", english: "He / She / They" },
            ],
          },
        ],
        flashcards: [
          // Greetings
          { id: "fc-std-1-1",  bangla: "নমস্কার",       romanization: "Nomoshkar",        english: "Hello",              emoji: "👋", category: "greetings" },
          { id: "fc-std-1-2",  bangla: "সুপ্রভাত",      romanization: "Shuprobhat",        english: "Good morning",       emoji: "☀️", category: "greetings" },
          { id: "fc-std-1-3",  bangla: "শুভ রাত্রি",    romanization: "Shubho ratri",      english: "Good night",         emoji: "🌙", category: "greetings" },
          { id: "fc-std-1-4",  bangla: "আল্লাহ হাফেজ", romanization: "Allah Hafez",       english: "Goodbye",            emoji: "🙏", category: "greetings" },
          { id: "fc-std-1-5",  bangla: "ধন্যবাদ",       romanization: "Dhonnobad",         english: "Thank you",          emoji: "🤝", category: "greetings" },
          { id: "fc-std-1-6",  bangla: "মাফ করবেন",     romanization: "Maf korben",        english: "Excuse me / Sorry",  emoji: "😅", category: "greetings" },
          // Core phrases
          { id: "fc-std-1-7",  bangla: "কেমন আছেন?",   romanization: "Kemon achen?",      english: "How are you?",       emoji: "😊", category: "phrases" },
          { id: "fc-std-1-8",  bangla: "আমি ভালো আছি", romanization: "Ami bhalo achi",    english: "I am fine",          emoji: "😄", category: "phrases" },
          { id: "fc-std-1-9",  bangla: "হ্যাঁ",          romanization: "Hya",               english: "Yes",                emoji: "✅", category: "phrases" },
          { id: "fc-std-1-10", bangla: "না",             romanization: "Na",                english: "No",                 emoji: "❌", category: "phrases" },
          { id: "fc-std-1-11", bangla: "বুঝেছি",         romanization: "Bujhechi",          english: "I understand",       emoji: "💡", category: "phrases" },
          { id: "fc-std-1-12", bangla: "বুঝি না",        romanization: "Bujhi na",          english: "I don't understand", emoji: "🤷", category: "phrases" },
          { id: "fc-std-1-13", bangla: "আবার বলুন",     romanization: "Abar bolun",        english: "Please say again",   emoji: "🔁", category: "phrases" },
          { id: "fc-std-1-14", bangla: "দাম কত?",       romanization: "Dam koto?",         english: "How much?",          emoji: "💰", category: "phrases" },
          // Pronouns
          { id: "fc-std-1-15", bangla: "আমি",           romanization: "Ami",               english: "I / Me",             emoji: "🙋", category: "pronouns" },
          { id: "fc-std-1-16", bangla: "তুমি",           romanization: "Tumi",              english: "You (informal)",     emoji: "👉", category: "pronouns" },
          { id: "fc-std-1-17", bangla: "আপনি",          romanization: "Apni",              english: "You (formal)",       emoji: "🤵", category: "pronouns" },
          { id: "fc-std-1-18", bangla: "সে",             romanization: "She",               english: "He / She",           emoji: "👤", category: "pronouns" },
          { id: "fc-std-1-19", bangla: "আমরা",          romanization: "Amra",              english: "We",                 emoji: "👥", category: "pronouns" },
          { id: "fc-std-1-20", bangla: "তারা",           romanization: "Tara",              english: "They",               emoji: "👫", category: "pronouns" },
          // Family
          { id: "fc-std-1-21", bangla: "মা",             romanization: "Ma",                english: "Mother",             emoji: "👩", category: "family" },
          { id: "fc-std-1-22", bangla: "বাবা",           romanization: "Baba",              english: "Father",             emoji: "👨", category: "family" },
          { id: "fc-std-1-23", bangla: "ভাই",            romanization: "Bhai",              english: "Brother",            emoji: "👦", category: "family" },
          { id: "fc-std-1-24", bangla: "বোন",            romanization: "Bon",               english: "Sister",             emoji: "👧", category: "family" },
          { id: "fc-std-1-25", bangla: "দাদা",           romanization: "Dada",              english: "Grandfather",        emoji: "👴", category: "family" },
          { id: "fc-std-1-26", bangla: "দাদি",           romanization: "Dadi",              english: "Grandmother",        emoji: "👵", category: "family" },
          { id: "fc-std-1-27", bangla: "ছেলে",           romanization: "Chhele",            english: "Son / Boy",          emoji: "👦", category: "family" },
          { id: "fc-std-1-28", bangla: "মেয়ে",           romanization: "Meye",              english: "Daughter / Girl",    emoji: "👧", category: "family" },
          // Numbers
          { id: "fc-std-1-29", bangla: "এক",             romanization: "Ek",                english: "One",                emoji: "1️⃣", category: "numbers" },
          { id: "fc-std-1-30", bangla: "দুই",            romanization: "Dui",               english: "Two",                emoji: "2️⃣", category: "numbers" },
          { id: "fc-std-1-31", bangla: "তিন",            romanization: "Tin",               english: "Three",              emoji: "3️⃣", category: "numbers" },
          { id: "fc-std-1-32", bangla: "চার",            romanization: "Char",              english: "Four",               emoji: "4️⃣", category: "numbers" },
          { id: "fc-std-1-33", bangla: "পাঁচ",           romanization: "Pach",              english: "Five",               emoji: "5️⃣", category: "numbers" },
          { id: "fc-std-1-34", bangla: "দশ",             romanization: "Dosh",              english: "Ten",                emoji: "🔟", category: "numbers" },
          { id: "fc-std-1-35", bangla: "একশো",          romanization: "Ekshho",            english: "One hundred",        emoji: "💯", category: "numbers" },
          // Food
          { id: "fc-std-1-36", bangla: "ভাত",            romanization: "Bhat",              english: "Rice",               emoji: "🍚", category: "food" },
          { id: "fc-std-1-37", bangla: "ডাল",            romanization: "Dal",               english: "Lentils",            emoji: "🫘", category: "food" },
          { id: "fc-std-1-38", bangla: "মাছ",            romanization: "Mach",              english: "Fish",               emoji: "🐟", category: "food" },
          { id: "fc-std-1-39", bangla: "মাংস",           romanization: "Mangso",            english: "Meat",               emoji: "🍖", category: "food" },
          { id: "fc-std-1-40", bangla: "রুটি",           romanization: "Ruti",              english: "Bread",              emoji: "🫓", category: "food" },
          { id: "fc-std-1-41", bangla: "চা",             romanization: "Cha",               english: "Tea",                emoji: "🍵", category: "food" },
          { id: "fc-std-1-42", bangla: "পানি",           romanization: "Pani",              english: "Water",              emoji: "💧", category: "food" },
          { id: "fc-std-1-43", bangla: "আম",             romanization: "Am",                english: "Mango",              emoji: "🥭", category: "food" },
          { id: "fc-std-1-44", bangla: "কলা",            romanization: "Kola",              english: "Banana",             emoji: "🍌", category: "food" },
          // Animals
          { id: "fc-std-1-45", bangla: "বাঘ",            romanization: "Bagh",              english: "Tiger",              emoji: "🐯", category: "animals" },
          { id: "fc-std-1-46", bangla: "কুকুর",          romanization: "Kukur",             english: "Dog",                emoji: "🐶", category: "animals" },
          { id: "fc-std-1-47", bangla: "বিড়াল",         romanization: "Biral",             english: "Cat",                emoji: "🐱", category: "animals" },
          { id: "fc-std-1-48", bangla: "পাখি",           romanization: "Pakhi",             english: "Bird",               emoji: "🐦", category: "animals" },
          { id: "fc-std-1-49", bangla: "গরু",            romanization: "Goru",              english: "Cow",                emoji: "🐄", category: "animals" },
          // Adjectives
          { id: "fc-std-1-50", bangla: "ভালো",           romanization: "Bhalo",             english: "Good",               emoji: "👍", category: "adjectives" },
          { id: "fc-std-1-51", bangla: "খারাপ",          romanization: "Kharap",            english: "Bad",                emoji: "👎", category: "adjectives" },
          { id: "fc-std-1-52", bangla: "বড়",             romanization: "Boro",              english: "Big",                emoji: "🔵", category: "adjectives" },
          { id: "fc-std-1-53", bangla: "ছোট",            romanization: "Chhoto",            english: "Small",              emoji: "🔹", category: "adjectives" },
          { id: "fc-std-1-54", bangla: "গরম",            romanization: "Gorom",             english: "Hot",                emoji: "🌡️", category: "adjectives" },
          { id: "fc-std-1-55", bangla: "ঠান্ডা",         romanization: "Thanda",            english: "Cold",               emoji: "❄️", category: "adjectives" },
          { id: "fc-std-1-56", bangla: "সুন্দর",         romanization: "Shundor",           english: "Beautiful",          emoji: "✨", category: "adjectives" },
          // Verbs
          { id: "fc-std-1-57", bangla: "আসা",            romanization: "Asha",              english: "To come",            emoji: "➡️", category: "verbs" },
          { id: "fc-std-1-58", bangla: "যাওয়া",         romanization: "Jaowa",             english: "To go",              emoji: "🚶", category: "verbs" },
          { id: "fc-std-1-59", bangla: "খাওয়া",         romanization: "Khaowa",            english: "To eat",             emoji: "🍽️", category: "verbs" },
          { id: "fc-std-1-60", bangla: "পড়া",            romanization: "Pora",              english: "To read / study",    emoji: "📖", category: "verbs" },
          { id: "fc-std-1-61", bangla: "লেখা",           romanization: "Lekha",             english: "To write",           emoji: "✍️", category: "verbs" },
          { id: "fc-std-1-62", bangla: "বলা",            romanization: "Bola",              english: "To speak",           emoji: "💬", category: "verbs" },
          // Bangladesh
          { id: "fc-std-1-63", bangla: "রিকশা",          romanization: "Ricksha",           english: "Rickshaw",           emoji: "🛺", category: "bangladesh" },
          { id: "fc-std-1-64", bangla: "ইলিশ",           romanization: "Ilish",             english: "Hilsa fish",         emoji: "🐠", category: "bangladesh" },
          { id: "fc-std-1-65", bangla: "ঢাকা",           romanization: "Dhaka",             english: "Dhaka (capital)",    emoji: "🏙️", category: "bangladesh" },
          { id: "fc-std-1-66", bangla: "বাংলাদেশ",      romanization: "Bangladesh",        english: "Bangladesh",         emoji: "🇧🇩", category: "bangladesh" },
          { id: "fc-std-1-67", bangla: "পদ্মা",          romanization: "Padma",             english: "Padma river",        emoji: "🌊", category: "bangladesh" },
          { id: "fc-std-1-68", bangla: "সুন্দরবন",      romanization: "Shundorbon",        english: "Sundarbans forest",  emoji: "🌿", category: "bangladesh" },
        ],
      },
      lessons: [
        // ── Lesson 0a: Vowels (স্বরবর্ণ) ─────────────────────────────────────
        {
          id: "std-1-0",
          title: "Trace the Vowels",
          description: "Trace all 11 Bengali vowels with your finger",
          unit: 1,
          order: 0,
          xpReward: 44,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "std-1-0-tr-1",  character: "অ", romanization: "o/a",  exampleWord: "অনেক — many",       strokeHint: "Matra right→left, curve down, inner loop, tail", xp: 4 },
            { type: "letter_trace", id: "std-1-0-tr-2",  character: "আ", romanization: "aa",   exampleWord: "আম — mango",        strokeHint: "Matra across, অ-like body, right vertical", xp: 4 },
            { type: "letter_trace", id: "std-1-0-tr-3",  character: "ই", romanization: "i",    exampleWord: "ইলিশ — hilsa fish", strokeHint: "Matra left→right, S-curve to lower-left hook", xp: 4 },
            { type: "letter_trace", id: "std-1-0-tr-4",  character: "ঈ", romanization: "ii",   exampleWord: "ঈদ — Eid",         strokeHint: "Like ই but bottom loops back right", xp: 4 },
            { type: "letter_trace", id: "std-1-0-tr-5",  character: "উ", romanization: "u",    exampleWord: "উট — camel",        strokeHint: "Matra, open oval: right down, bottom, back up", xp: 4 },
            { type: "letter_trace", id: "std-1-0-tr-6",  character: "ঊ", romanization: "uu",   exampleWord: "ঊনত্রিশ — twenty-nine", strokeHint: "Like উ with inner reverse loop", xp: 4 },
            { type: "letter_trace", id: "std-1-0-tr-7",  character: "ঋ", romanization: "ri",   exampleWord: "ঋতু — season",      strokeHint: "Matra, diagonal body with ri-curve", xp: 4 },
            { type: "letter_trace", id: "std-1-0-tr-8",  character: "এ", romanization: "e",    exampleWord: "এক — one",          strokeHint: "Matra right→left, curve down, mid-bar, base", xp: 4 },
            { type: "letter_trace", id: "std-1-0-tr-9",  character: "ঐ", romanization: "oi",   exampleWord: "ঐক্য — unity",     strokeHint: "Matra, center stem down, fork at base", xp: 4 },
            { type: "letter_trace", id: "std-1-0-tr-10", character: "ও", romanization: "o",    exampleWord: "ওষুধ — medicine",   strokeHint: "Left C-curve, matra right, right vertical", xp: 4 },
            { type: "letter_trace", id: "std-1-0-tr-11", character: "ঔ", romanization: "ou",   exampleWord: "ঔষধ — medicine",   strokeHint: "ও left part, right element top hook → arc", xp: 4 },
          ],
        },

        // ── Lesson 0b: Consonants ক–ণ ────────────────────────────────────────
        {
          id: "std-1-0b",
          title: "Consonants: ক to ণ",
          description: "Trace the first 15 Bengali consonants",
          unit: 1,
          order: 1,
          xpReward: 60,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "std-1-0b-tr-1",  character: "ক", romanization: "k",   exampleWord: "কলা — banana",    strokeHint: "Matra, left vertical, upper & lower right arms", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-2",  character: "খ", romanization: "kh",  exampleWord: "খাবার — food",    strokeHint: "Matra, left vertical, right arms", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-3",  character: "গ", romanization: "g",   exampleWord: "গরু — cow",       strokeHint: "Matra right→left, down left, across, up right", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-4",  character: "ঘ", romanization: "gh",  exampleWord: "ঘর — house",      strokeHint: "Matra, left vertical, right hooks, bottom tail", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-5",  character: "ঙ", romanization: "ng",  exampleWord: "বাংলা — Bangla",  strokeHint: "Matra, backward-9 body, descending tail", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-6",  character: "চ", romanization: "ch",  exampleWord: "চাঁদ — moon",     strokeHint: "Matra right→left, body curves down, bottom right", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-7",  character: "ছ", romanization: "chh", exampleWord: "ছাতা — umbrella", strokeHint: "Like চ with extra foot at bottom-right", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-8",  character: "জ", romanization: "j",   exampleWord: "জল — water",      strokeHint: "Matra, center stem, curves left at bottom", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-9",  character: "ঝ", romanization: "jh",  exampleWord: "ঝড় — storm",      strokeHint: "Matra, center stem, bottom fork left and right", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-10", character: "ঞ", romanization: "ny",  exampleWord: "জ্ঞান — knowledge", strokeHint: "Two connected oval loops", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-11", character: "ট", romanization: "T",   exampleWord: "টাকা — money",    strokeHint: "Matra, center vertical, T-base left and right", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-12", character: "ঠ", romanization: "Th",  exampleWord: "ঠান্ডা — cold",  strokeHint: "Matra, V-spread arms meeting at bottom", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-13", character: "ড", romanization: "D",   exampleWord: "ডাল — lentils",   strokeHint: "Full oval clockwise: top→right→bottom→left", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-14", character: "ঢ", romanization: "Dh",  exampleWord: "ঢাকা — Dhaka",   strokeHint: "Like ড oval + inner stroke + right arm", xp: 4 },
            { type: "letter_trace", id: "std-1-0b-tr-15", character: "ণ", romanization: "N",   exampleWord: "বর্ণ — letter",   strokeHint: "Matra, right side down, bottom arc left, close up", xp: 4 },
          ],
        },

        // ── Lesson 0c: Consonants ত–ম ────────────────────────────────────────
        {
          id: "std-1-0c",
          title: "Consonants: ত to ম",
          description: "Trace the next 10 Bengali consonants",
          unit: 1,
          order: 2,
          xpReward: 40,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "std-1-0c-tr-1",  character: "ত", romanization: "t",   exampleWord: "তারা — star",       strokeHint: "Matra, center stem, two legs spreading at base", xp: 4 },
            { type: "letter_trace", id: "std-1-0c-tr-2",  character: "থ", romanization: "th",  exampleWord: "থালা — plate",      strokeHint: "Matra, center vertical, complex right extension", xp: 4 },
            { type: "letter_trace", id: "std-1-0c-tr-3",  character: "দ", romanization: "d",   exampleWord: "দুধ — milk",        strokeHint: "Curved top-right sweep, body curves left", xp: 4 },
            { type: "letter_trace", id: "std-1-0c-tr-4",  character: "ধ", romanization: "dh",  exampleWord: "ধান — paddy rice",  strokeHint: "Matra, center stem, complex fork at bottom", xp: 4 },
            { type: "letter_trace", id: "std-1-0c-tr-5",  character: "ন", romanization: "n",   exampleWord: "নাম — name",        strokeHint: "Matra, right side down, bottom arc, close up left", xp: 4 },
            { type: "letter_trace", id: "std-1-0c-tr-6",  character: "প", romanization: "p",   exampleWord: "পাখি — bird",       strokeHint: "Matra, left & right verticals, crossbar at mid", xp: 4 },
            { type: "letter_trace", id: "std-1-0c-tr-7",  character: "ফ", romanization: "ph",  exampleWord: "ফুল — flower",      strokeHint: "Matra, left & right verticals to bottom", xp: 4 },
            { type: "letter_trace", id: "std-1-0c-tr-8",  character: "ব", romanization: "b",   exampleWord: "বই — book",         strokeHint: "Matra, left vertical, right curve closing at mid", xp: 4 },
            { type: "letter_trace", id: "std-1-0c-tr-9",  character: "ভ", romanization: "bh",  exampleWord: "ভালো — good",       strokeHint: "Matra, left vertical, right vertical with hook", xp: 4 },
            { type: "letter_trace", id: "std-1-0c-tr-10", character: "ম", romanization: "m",   exampleWord: "মা — mother",       strokeHint: "Matra, large oval body clockwise", xp: 4 },
          ],
        },

        // ── Lesson 0d: Consonants য–হ + Special ─────────────────────────────
        {
          id: "std-1-0d",
          title: "Consonants: য to হ",
          description: "Trace the remaining consonants and special marks",
          unit: 1,
          order: 3,
          xpReward: 56,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "std-1-0d-tr-1",  character: "য", romanization: "y/j", exampleWord: "যাও — go",          strokeHint: "Matra, center stem, curves left, hooks right at base", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-2",  character: "র", romanization: "r",   exampleWord: "রাত — night",        strokeHint: "Matra, then diagonal stroke descending right", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-3",  character: "ল", romanization: "l",   exampleWord: "লাল — red",          strokeHint: "Center vertical top→bottom, T-spread at base", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-4",  character: "শ", romanization: "sh",  exampleWord: "শুভ — auspicious",   strokeHint: "Matra, two short verticals, center drop to base", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-5",  character: "ষ", romanization: "Sh",  exampleWord: "ষোল — sixteen",      strokeHint: "Matra, diagonal body curving to lower-right", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-6",  character: "স", romanization: "s",   exampleWord: "সব — all",           strokeHint: "Top bar right→left, left side, mid-bar, right down, base", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-7",  character: "হ", romanization: "h",   exampleWord: "হাত — hand",         strokeHint: "Left vertical, right arm curves up-right then down", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-8",  character: "ড়", romanization: "r",   exampleWord: "গাড়ি — car",        strokeHint: "Oval like ড with descending tail", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-9",  character: "ঢ়", romanization: "rh",  exampleWord: "ঢেঁড়স — okra",     strokeHint: "Like ঢ with tail below", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-10", character: "য়", romanization: "y",   exampleWord: "দায় — responsibility", strokeHint: "Like য with descending tail", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-11", character: "ৎ", romanization: "t",   exampleWord: "বিদ্যুৎ — electricity", strokeHint: "Matra, short center stem, small left foot", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-12", character: "ং", romanization: "ng",  exampleWord: "রং — color",         strokeHint: "Crescent arc opening downward", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-13", character: "ঃ", romanization: "h",   exampleWord: "দুঃখ — sorrow",      strokeHint: "Two small circles, top then bottom", xp: 4 },
            { type: "letter_trace", id: "std-1-0d-tr-14", character: "ঁ", romanization: "~n",  exampleWord: "চাঁদ — moon",        strokeHint: "Crescent arc with dot above", xp: 4 },
          ],
        },

        // ── Lesson 1: Hello & Phrases ─────────────────────────────────────────
        {
          id: "std-1-1",
          title: "Hello & Phrases",
          description: "Your very first Bengali words — say hello, good morning, and more!",
          unit: 1,
          order: 4,
          xpReward: 14,
          exercises: [
            {
              type: "multiple_choice",
              id: "std-1-1-mc-1",
              prompt: "What does this mean?",
              promptBangla: "নমস্কার",
              romanization: "Nomoshkar",
              imageKey: "greeting",
              options: ["Hello", "Goodbye", "Thank you", "Good night"],
              correct: 0,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-1-mc-2",
              prompt: "What does this mean?",
              promptBangla: "সুপ্রভাত",
              romanization: "Shuprobhat",
              imageKey: "morning",
              options: ["Good night", "Good morning", "Goodbye", "How are you?"],
              correct: 1,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-1-mc-3",
              prompt: "What does this mean?",
              promptBangla: "ধন্যবাদ",
              romanization: "Dhonnobad",
              imageKey: "thankyou",
              options: ["Hello", "Goodbye", "Thank you", "Please"],
              correct: 2,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-1-mc-4",
              prompt: "What does this mean?",
              promptBangla: "আল্লাহ হাফেজ",
              romanization: "Allah Hafez",
              imageKey: "goodbye",
              options: ["Good morning", "Thank you", "Hello", "Goodbye"],
              correct: 3,
              xp: 2,
            },
            {
              type: "match_pairs",
              id: "std-1-1-mp-1",
              pairs: [
                { bangla: "নমস্কার", english: "Hello", romanization: "Nomoshkar" },
                { bangla: "সুপ্রভাত", english: "Good morning", romanization: "Shuprobhat" },
                { bangla: "ধন্যবাদ", english: "Thank you", romanization: "Dhonnobad" },
                { bangla: "আল্লাহ হাফেজ", english: "Goodbye", romanization: "Allah Hafez" },
              ],
              xp: 6,
            },
          ],
        },

        // ── Lesson 2: How Are You? ────────────────────────────────────────────
        {
          id: "std-1-2",
          title: "How Are You?",
          description: "Ask how someone is — and answer back in Bengali",
          unit: 1,
          order: 5,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "std-1-2-mc-1",
              prompt: "What does this mean?",
              promptBangla: "আমি",
              romanization: "Ami",
              imageKey: "self",
              options: ["You", "I / Me", "He / She", "We"],
              correct: 1,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-2-mc-2",
              prompt: "What does this mean?",
              promptBangla: "কেমন আছেন?",
              romanization: "Kemon achen?",
              imageKey: "howareyou",
              options: ["What is your name?", "Where are you from?", "How are you?", "I am fine"],
              correct: 2,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-2-mc-3",
              prompt: "What does this mean?",
              promptBangla: "আমি ভালো আছি",
              romanization: "Ami bhalo achi",
              imageKey: "imfine",
              options: ["I am tired", "I am hungry", "I am sad", "I am fine"],
              correct: 3,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-2-mc-4",
              prompt: "What does this mean?",
              promptBangla: "ভালো",
              romanization: "Bhalo",
              imageKey: "good",
              options: ["Bad", "Good", "Hello", "Name"],
              correct: 1,
              xp: 2,
            },
            {
              type: "match_pairs",
              id: "std-1-2-mp-1",
              pairs: [
                { bangla: "আমি", english: "I / Me", romanization: "Ami" },
                { bangla: "তুমি", english: "You", romanization: "Tumi" },
                { bangla: "ভালো", english: "Good", romanization: "Bhalo" },
                { bangla: "সে", english: "He / She", romanization: "She" },
              ],
              xp: 4,
            },
          ],
        },

        // ── Lesson 3: Numbers 1–5 ─────────────────────────────────────────────
        {
          id: "std-1-3",
          title: "Numbers 1–5",
          description: "Count to five in Bengali — one at a time",
          unit: 1,
          order: 6,
          xpReward: 15,
          exercises: [
            {
              type: "multiple_choice",
              id: "std-1-3-mc-1",
              prompt: "What number is this?",
              promptBangla: "এক",
              romanization: "Ek",
              options: ["Two", "Three", "One", "Four"],
              correct: 2,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-3-mc-2",
              prompt: "What number is this?",
              promptBangla: "দুই",
              romanization: "Dui",
              options: ["One", "Two", "Three", "Five"],
              correct: 1,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-3-mc-3",
              prompt: "Which word means THREE?",
              options: ["এক (Ek)", "দুই (Dui)", "তিন (Tin)", "চার (Char)"],
              correct: 2,
              xp: 2,
            },
            {
              type: "match_pairs",
              id: "std-1-3-mp-1",
              pairs: [
                { bangla: "এক", english: "One", romanization: "Ek" },
                { bangla: "দুই", english: "Two", romanization: "Dui" },
                { bangla: "তিন", english: "Three", romanization: "Tin" },
                { bangla: "চার", english: "Four", romanization: "Char" },
                { bangla: "পাঁচ", english: "Five", romanization: "Panch" },
              ],
              xp: 5,
            },
          ],
        },

        // ── Lesson 4: Numbers 6–10 ────────────────────────────────────────────
        {
          id: "std-1-4",
          title: "Numbers 6–10",
          description: "Keep counting — six to ten!",
          unit: 1,
          order: 7,
          xpReward: 15,
          exercises: [
            {
              type: "multiple_choice",
              id: "std-1-4-mc-1",
              prompt: "What number is this?",
              promptBangla: "ছয়",
              romanization: "Chhoy",
              options: ["Seven", "Eight", "Six", "Nine"],
              correct: 2,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-4-mc-2",
              prompt: "What number is this?",
              promptBangla: "সাত",
              romanization: "Shaat",
              options: ["Six", "Eight", "Nine", "Seven"],
              correct: 3,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-4-mc-3",
              prompt: "Which word means TEN?",
              options: ["আট (Aat)", "নয় (Noy)", "দশ (Dosh)", "ছয় (Chhoy)"],
              correct: 2,
              xp: 2,
            },
            {
              type: "match_pairs",
              id: "std-1-4-mp-1",
              pairs: [
                { bangla: "ছয়", english: "Six", romanization: "Chhoy" },
                { bangla: "সাত", english: "Seven", romanization: "Shaat" },
                { bangla: "আট", english: "Eight", romanization: "Aat" },
                { bangla: "নয়", english: "Nine", romanization: "Noy" },
                { bangla: "দশ", english: "Ten", romanization: "Dosh" },
              ],
              xp: 5,
            },
          ],
        },

        // ── Lesson 5: Family ──────────────────────────────────────────────────
        {
          id: "std-1-5",
          title: "Family",
          description: "Mum, Dad, brother, sister — in Bengali!",
          unit: 1,
          order: 8,
          xpReward: 15,
          exercises: [
            {
              type: "multiple_choice",
              id: "std-1-5-mc-1",
              prompt: "What does this mean?",
              promptBangla: "মা",
              romanization: "Ma",
              imageKey: "mother",
              options: ["Father", "Sister", "Mother", "Brother"],
              correct: 2,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-5-mc-2",
              prompt: "What does this mean?",
              promptBangla: "বাবা",
              romanization: "Baba",
              imageKey: "father",
              options: ["Mother", "Father", "Brother", "Sister"],
              correct: 1,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-5-mc-3",
              prompt: "Which word means SISTER?",
              options: ["মা (Ma)", "বাবা (Baba)", "ভাই (Bhai)", "বোন (Bon)"],
              correct: 3,
              xp: 2,
            },
            {
              type: "match_pairs",
              id: "std-1-5-mp-1",
              pairs: [
                { bangla: "মা", english: "Mother", romanization: "Ma" },
                { bangla: "বাবা", english: "Father", romanization: "Baba" },
                { bangla: "ভাই", english: "Brother", romanization: "Bhai" },
                { bangla: "বোন", english: "Sister", romanization: "Bon" },
              ],
              xp: 5,
            },
          ],
        },

        // ── Lesson 6: Bangladesh Life ─────────────────────────────────────────
        {
          id: "std-1-6",
          title: "Bangladesh Life",
          description: "Rickshaws, fish, tigers and more — iconic Bangladeshi words!",
          unit: 1,
          order: 9,
          isQuiz: true,
          xpReward: 14,
          exercises: [
            {
              type: "multiple_choice",
              id: "std-1-6-mc-1",
              prompt: "What does this mean?",
              promptBangla: "রিকশা",
              romanization: "Ricksha",
              imageKey: "rickshaw",
              options: ["Tiger", "Rickshaw", "Fish", "Boat"],
              correct: 1,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-6-mc-2",
              prompt: "What does this mean?",
              promptBangla: "ইলিশ",
              romanization: "Ilish",
              imageKey: "fish",
              options: ["Tiger", "Banana", "Hilsa Fish", "Rice"],
              correct: 2,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-6-mc-3",
              prompt: "What does this mean?",
              promptBangla: "গরু",
              romanization: "Goru",
              imageKey: "cow",
              options: ["Fish", "Tiger", "Cow", "Banana"],
              correct: 2,
              xp: 2,
            },
            {
              type: "multiple_choice",
              id: "std-1-6-mc-4",
              prompt: "What does this mean?",
              promptBangla: "কলা",
              romanization: "Kola",
              imageKey: "banana",
              options: ["Rice", "Fish", "Cow", "Banana"],
              correct: 3,
              xp: 2,
            },
            {
              type: "match_pairs",
              id: "std-1-6-mp-1",
              pairs: [
                { bangla: "রিকশা", english: "Rickshaw", romanization: "Ricksha" },
                { bangla: "ইলিশ", english: "Hilsa Fish", romanization: "Ilish" },
                { bangla: "বাঘ", english: "Tiger", romanization: "Bagh" },
                { bangla: "ভাত", english: "Rice", romanization: "Bhat" },
              ],
              xp: 6,
            },
          ],
        },
      ],
    },
    {
      id: "std-unit-2",
      title: "Colors & Objects",
      description: "Describe the world around you",
      order: 2,
      color: "#1CB0F6",
      prep: {
        characters: [
          { symbol: "র", romanization: "r", type: "consonant", exampleWord: "রং", exampleMeaning: "color" },
          { symbol: "ল", romanization: "l", type: "consonant", exampleWord: "লাল", exampleMeaning: "red" },
          { symbol: "প", romanization: "p", type: "consonant", exampleWord: "পাখি", exampleMeaning: "bird" },
          { symbol: "ব", romanization: "b", type: "consonant", exampleWord: "বই", exampleMeaning: "book" },
          { symbol: "দ", romanization: "d", type: "consonant", exampleWord: "দরজা", exampleMeaning: "door" },
          { symbol: "ত", romanization: "t", type: "consonant", exampleWord: "তারা", exampleMeaning: "star" },
          { symbol: "চ", romanization: "ch", type: "consonant", exampleWord: "চাঁদ", exampleMeaning: "moon" },
          { symbol: "জ", romanization: "j", type: "consonant", exampleWord: "জল", exampleMeaning: "water" },
          { symbol: "ো", romanization: "-o", type: "vowel", exampleWord: "লালো", exampleMeaning: "reddish" },
          { symbol: "া", romanization: "-a", type: "vowel", exampleWord: "মালা", exampleMeaning: "garland" },
        ],
        grammar: [
          {
            title: "Colors as Adjectives",
            explanation: "In Bengali, adjectives come BEFORE the noun, just like in English. Colors don't change form based on gender (unlike many European languages).",
            examples: [
              { bangla: "লাল ফুল", romanization: "lal phul", english: "red flower" },
              { bangla: "নীল আকাশ", romanization: "nil akash", english: "blue sky" },
              { bangla: "সবুজ গাছ", romanization: "shobuj gach", english: "green tree" },
            ],
          },
          {
            title: "This / That: এটা and ওটা",
            explanation: "Use এটা (eta) for things close to you (this) and ওটা (ota) for things far away (that). Add -র (-r) to make it possessive.",
            examples: [
              { bangla: "এটা কী?", romanization: "Eta ki?", english: "What is this?" },
              { bangla: "ওটা একটি বই", romanization: "Ota ekti boi", english: "That is a book" },
              { bangla: "এটার রং কী?", romanization: "Etar rong ki?", english: "What color is this?" },
            ],
          },
        ],
        flashcards: [
          { id: "fc-std-2-1", bangla: "লাল", romanization: "Lal", english: "Red", emoji: "🔴", category: "colors" },
          { id: "fc-std-2-2", bangla: "নীল", romanization: "Nil", english: "Blue", emoji: "🔵", category: "colors" },
          { id: "fc-std-2-3", bangla: "সবুজ", romanization: "Shobuj", english: "Green", emoji: "🟢", category: "colors" },
          { id: "fc-std-2-4", bangla: "হলুদ", romanization: "Holud", english: "Yellow", emoji: "🟡", category: "colors" },
          { id: "fc-std-2-5", bangla: "সাদা", romanization: "Shada", english: "White", emoji: "⬜", category: "colors" },
          { id: "fc-std-2-6", bangla: "কালো", romanization: "Kalo", english: "Black", emoji: "⬛", category: "colors" },
          { id: "fc-std-2-7", bangla: "বই", romanization: "Boi", english: "Book", emoji: "📚", category: "objects" },
          { id: "fc-std-2-8", bangla: "বাড়ি", romanization: "Bari", english: "House", emoji: "🏠", category: "objects" },
          { id: "fc-std-2-9", bangla: "গাছ", romanization: "Gach", english: "Tree", emoji: "🌳", category: "objects" },
          { id: "fc-std-2-10", bangla: "পানি", romanization: "Pani", english: "Water", emoji: "💧", category: "objects" },
        ],
      },
      lessons: [
        {
          id: "std-2-1",
          title: "Basic Colors",
          description: "Learn colors in Bengali",
          unit: 2,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "std-2-1-mp-1",
              pairs: [
                { bangla: "লাল", english: "Red", romanization: "Laal" },
                { bangla: "নীল", english: "Blue", romanization: "Neel" },
                { bangla: "সবুজ", english: "Green", romanization: "Shobuj" },
                { bangla: "হলুদ", english: "Yellow", romanization: "Holud" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "std-2-1-mc-1",
              prompt: "What color is 'কালো'?",
              options: ["White", "Black", "Orange", "Purple"],
              correct: 1,
              xp: 2,
            },
            {
              type: "translate_to_bangla",
              id: "std-2-1-ttb-1",
              english: "Green",
              answer: "সবুজ",
              romanization: "Shobuj",
              xp: 3,
            },
          ],
        },
      ],
    },
  ],
};
