import type { DialectCurriculum } from "@bangla-learn/types";

export const sylhetiCurriculum: DialectCurriculum = {
  dialect: "sylheti",
  units: [
    {
      id: "syl-unit-1",
      title: "Sylheti Greetings",
      description: "Learn how to greet in Sylheti — spoken in Sylhet and the UK Bangladeshi community",
      order: 1,
      color: "#FF9600",
      prep: {
        characters: [
          // Vowels
          { symbol: "অ", romanization: "o/a", type: "vowel" as const, exampleWord: "অনেক (many)" },
          { symbol: "আ", romanization: "aa",  type: "vowel" as const, exampleWord: "আফা (sister)" },
          { symbol: "ই", romanization: "i",   type: "vowel" as const, exampleWord: "ইলিশ (hilsa)" },
          { symbol: "উ", romanization: "u",   type: "vowel" as const, exampleWord: "উঠা (to rise)" },
          { symbol: "এ", romanization: "e",   type: "vowel" as const, exampleWord: "এক (one)" },
          { symbol: "ও", romanization: "o",   type: "vowel" as const, exampleWord: "ওখানে (there)" },
          // Key consonants
          { symbol: "ক", romanization: "k",   type: "consonant" as const, exampleWord: "কিতা (what)" },
          { symbol: "খ", romanization: "kh",  type: "consonant" as const, exampleWord: "খাওয়া (eating)" },
          { symbol: "গ", romanization: "g",   type: "consonant" as const, exampleWord: "গেলাম (I went)" },
          { symbol: "ন", romanization: "n",   type: "consonant" as const, exampleWord: "নাম (name)" },
          { symbol: "প", romanization: "p",   type: "consonant" as const, exampleWord: "পানি (water)" },
          { symbol: "ব", romanization: "b",   type: "consonant" as const, exampleWord: "বাড়ি (home)" },
          { symbol: "ভ", romanization: "bh",  type: "consonant" as const, exampleWord: "ভালা (good)" },
          { symbol: "ম", romanization: "m",   type: "consonant" as const, exampleWord: "মা (mother)" },
          { symbol: "র", romanization: "r",   type: "consonant" as const, exampleWord: "রাত (night)" },
          { symbol: "ল", romanization: "l",   type: "consonant" as const, exampleWord: "লগে (with)" },
          { symbol: "স", romanization: "s",   type: "consonant" as const, exampleWord: "সকাল (morning)" },
          { symbol: "হ", romanization: "h",   type: "consonant" as const, exampleWord: "হে (he/she)" },
          { symbol: "চ", romanization: "ch",  type: "consonant" as const, exampleWord: "চাইর (four)" },
          { symbol: "ত", romanization: "t",   type: "consonant" as const, exampleWord: "তুই (you)" },
        ],
        flashcards: [
          // Sylheti-specific pronouns & key words
          { id: "fc-syl-1", bangla: "হে",          romanization: "He",         english: "He / She (Sylheti)",        category: "pronouns"  },
          { id: "fc-syl-2", bangla: "তুই",          romanization: "Tui",        english: "You (informal)",            category: "pronouns"  },
          { id: "fc-syl-3", bangla: "হেরা",         romanization: "Hera",       english: "They (Sylheti)",            category: "pronouns"  },
          { id: "fc-syl-4", bangla: "আফা",          romanization: "Apha",       english: "Sister (Sylheti)",          category: "family"    },
          { id: "fc-syl-5", bangla: "আব্বা",        romanization: "Abba",       english: "Father",                    category: "family"    },
          { id: "fc-syl-6", bangla: "ভালা",         romanization: "Bhala",      english: "Good / Well",               category: "adjectives"},
          { id: "fc-syl-7", bangla: "হই",           romanization: "Hoi",        english: "Yes (Sylheti)",             category: "phrases"   },
          { id: "fc-syl-8", bangla: "কিতা",         romanization: "Kita",       english: "What (Sylheti)",            category: "phrases"   },
          { id: "fc-syl-9", bangla: "কিতাই",        romanization: "Kitai",      english: "Why (Sylheti)",             category: "phrases"   },
          { id: "fc-syl-10", bangla: "লগে",         romanization: "Loge",       english: "With / Together",           category: "phrases"   },
          { id: "fc-syl-11", bangla: "ভালা আসেন?", romanization: "Bhala assen?", english: "Are you well? (formal)",  category: "greetings" },
          { id: "fc-syl-12", bangla: "ভালা আসি",   romanization: "Bhala ashi", english: "I am well",                 category: "greetings" },
          { id: "fc-syl-13", bangla: "কিতা খাইলা?",romanization: "Kita khaila?", english: "What did you eat?",      category: "phrases"   },
          { id: "fc-syl-14", bangla: "গেলাম",       romanization: "Gelam",      english: "I went / Goodbye (casual)",category: "phrases"   },
          { id: "fc-syl-15", bangla: "চাইর",        romanization: "Chair",      english: "Four (Sylheti for চার)",   category: "numbers"   },
          { id: "fc-syl-16", bangla: "ফুরা",        romanization: "Fura",       english: "All / Finished",            category: "adjectives"},
        ],
        grammar: [
          {
            title: "Sylheti Pronouns — হে, তুই",
            explanation: "Sylheti uses 'হে' (He) for he/she instead of Standard Bengali's 'সে'. For 'you' (informal), it uses 'তুই' (Tui). 'হেরা' is the plural 'they'.",
            examples: [
              { bangla: "হে আসে।",        romanization: "He ashe.",        english: "He/she is coming." },
              { bangla: "তুই কি খাইলা?", romanization: "Tui ki khaila?",  english: "Did you eat?" },
            ],
          },
          {
            title: "What & Where — কিতা, কেলে",
            explanation: "In Sylheti, 'কিতা' (kita) means 'what' — replacing Standard Bengali's 'কি'. Similarly 'কেলে' means 'where' instead of 'কোথায়'.",
            examples: [
              { bangla: "কিতা করছ?",  romanization: "Kita korcho?",  english: "What are you doing?" },
              { bangla: "কেলে গেলা?", romanization: "Kele gela?",   english: "Where did you go?" },
            ],
          },
          {
            title: "Sylheti Greeting — ভালা আসেন?",
            explanation: "The standard Sylheti greeting is 'ভালা আসেন?' (Are you well?), unlike Standard Bengali's 'কেমন আছেন?'. The response is 'ভালা আসি' (I am well).",
            examples: [
              { bangla: "ভালা আসেন?", romanization: "Bhala assen?", english: "Are you well? (formal)" },
              { bangla: "ভালা আসি।",  romanization: "Bhala ashi.",  english: "I am well." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "syl-1-0",
          title: "Write the Letters",
          description: "Trace Bengali vowels and consonants used in Sylheti",
          unit: 1,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "syl-1-0-tr-1", character: "অ", romanization: "o/a", exampleWord: "অনেক — many", xp: 4 },
            { type: "letter_trace", id: "syl-1-0-tr-2", character: "আ", romanization: "aa",  exampleWord: "আম — mango",  xp: 4 },
            { type: "letter_trace", id: "syl-1-0-tr-3", character: "ক", romanization: "k",   exampleWord: "কলা — banana", xp: 4 },
            { type: "letter_trace", id: "syl-1-0-tr-4", character: "ন", romanization: "n",   exampleWord: "নাম — name",   xp: 4 },
            { type: "letter_trace", id: "syl-1-0-tr-5", character: "ম", romanization: "m",   exampleWord: "মা — mother",  xp: 4 },
          ],
        },
        {
          id: "syl-1-1",
          title: "Greetings",
          description: "Greet someone in Sylheti-style speech and learn key spoken forms",
          unit: 1,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-1-1-mp-1",
              pairs: [
                { bangla: "আসসালামু আলাইকুম", english: "Hello (Islamic greeting)",       romanization: "assalamu alaikum" },
                { bangla: "ভালো / বালা",       english: "Good / Fine (Sylheti: বালা)",    romanization: "bala / bhalo"     },
                { bangla: "নাম",               english: "Name",                           romanization: "nam"              },
                { bangla: "আমার নাম ___।",     english: "My name is ___.",                romanization: "amar nam ___."    },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-1-1-tte-1",
              bangla: "তুমি কেমন আসো?",
              romanization: "tumi kemon aso?",
              answer: "How are you? (Sylheti form)",

              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "syl-1-1-ttb-1",
              english: "I am fine. (Sylheti)",
              answer: "আমি বালা আছি।",
              romanization: "ami bala asi.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "syl-1-1-mc-1",
              prompt: "In Sylheti, 'বালা' or 'ভালো' means:",
              options: ["name", "good/fine", "hello", "thank you"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "syl-1-2",
          title: "Introductions",
          description: "Say your name and where you are from in Sylheti-style speech",
          unit: 1,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "syl-1-2-tte-1",
              bangla: "আমার নাম ___।",
              romanization: "amar nam ___.",
              answer: "My name is ___.",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-1-2-tte-2",
              bangla: "আমি বাংলা শিখতাছি।",
              romanization: "ami bangla shikhtasi.",
              answer: "I am learning Bangla. (Sylheti form)",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "syl-1-2-mc-1",
              prompt: "In Sylheti, 'থেইকা' means:",
              options: ["name", "from", "going", "learning"],
              correct: 1,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "syl-1-2-fb-1",
              sentence: "তুমার নাম কী?",
              blank: "তুমার",
              romanization: "tumar nam ki?",
              options: ["তুমার", "আমার", "নাম", "কী"],
              xp: 3,
            },
          ],
        },
        {
          id: "syl-1-3",
          title: "Polite Words",
          description: "Use polite expressions in Sylheti-style spoken Bangla",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-1-3-mp-1",
              pairs: [
                { bangla: "ধন্যবাদ",        english: "Thank you",         romanization: "dhonnobad"     },
                { bangla: "মাফ কইরেন",      english: "Excuse me (Sylheti)", romanization: "maf koiren"   },
                { bangla: "ঠিক আছে / আসে", english: "Okay",               romanization: "thik ase"      },
                { bangla: "প্লিজ",           english: "Please",             romanization: "plij"          },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-1-3-tte-1",
              bangla: "মাফ কইরেন।",
              romanization: "maf koiren.",
              answer: "Excuse me / Forgive me. (Sylheti)",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "syl-1-3-mc-1",
              prompt: "The Sylheti polite request uses which ending?",
              options: ["-করুন", "-কইরেন", "-করবেন", "-করো"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "syl-1-4",
          title: "Yes / No / Basic Replies",
          description: "Give short replies in Sylheti-style speech",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-1-4-mp-1",
              pairs: [
                { bangla: "হ",         english: "Yes (Sylheti spoken)", romanization: "ho / hã" },
                { bangla: "না",        english: "No",                    romanization: "na"      },
                { bangla: "অয়তো",    english: "Maybe",                 romanization: "oyto"    },
                { bangla: "জানি না", english: "I don't know",          romanization: "jani na" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "syl-1-4-ttb-1",
              english: "Yes, I can. (Sylheti)",
              answer: "হ, পারি।",
              romanization: "ho, pari.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "syl-1-4-mc-1",
              prompt: "In Sylheti, 'অয়তো' means:",
              options: ["yes", "no", "maybe", "okay"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "syl-1-5",
          title: "Pronouns",
          description: "Use Sylheti pronouns — including আপনে and the unique আইতাছি form",
          unit: 1,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-1-5-mp-1",
              pairs: [
                { bangla: "আমি",   english: "I",                       romanization: "ami"  },
                { bangla: "তুমি",  english: "You (familiar)",           romanization: "tumi" },
                { bangla: "আপনে", english: "You (polite, Sylheti form)", romanization: "apne" },
                { bangla: "ইনি",  english: "This person / He/She",      romanization: "ini"  },
                { bangla: "আমরা", english: "We",                        romanization: "amra" },
                { bangla: "ওরা",  english: "They",                      romanization: "ora"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-1-5-tte-1",
              bangla: "আপনে কেমন আসেন?",
              romanization: "apne kemon asen?",
              answer: "How are you? (polite Sylheti form)",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-1-5-tte-2",
              bangla: "আমি আইতাছি।",
              romanization: "ami aitasi.",
              answer: "I am coming. (Sylheti progressive)",

              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "syl-1-5-mc-1",
              prompt: "In Sylheti, 'আপনে' is the polite form of 'you'. Standard Bangla uses:",
              options: ["তুমি", "তুই", "আপনি", "হে"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "syl-1-6",
          title: "Family",
          description: "Name close family members in Sylheti-style speech",
          unit: 1,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-1-6-mp-1",
              pairs: [
                { bangla: "মা",      english: "Mother",             romanization: "ma"     },
                { bangla: "বাবা",    english: "Father",             romanization: "baba"   },
                { bangla: "ভাই",     english: "Brother",            romanization: "bhai"   },
                { bangla: "বইন",     english: "Sister (Sylheti)",   romanization: "boin"   },
                { bangla: "মাইয়া", english: "Daughter / Girl",    romanization: "maiya"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-1-6-tte-1",
              bangla: "এইডা আমার মা।",
              romanization: "eida amar ma.",
              answer: "This is my mother. (Sylheti)",

              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-1-6-tte-2",
              bangla: "আমার এক বইন আছে।",
              romanization: "amar ek boin ase.",
              answer: "I have one sister. (Sylheti: বইন for বোন)",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "syl-1-6-mc-1",
              prompt: "The Sylheti word for sister is 'বইন'. In Standard Bangla it is:",
              options: ["ভাই", "বোন", "মেয়ে", "আফা"],
              correct: 1,
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "syl-1-6-mc-2",
              prompt: "'পোলা' in Sylheti means:",
              options: ["daughter", "son/boy", "brother", "father"],
              correct: 1,
              xp: 3,
            },
          ],
        },
      ],
    },

    // ── Unit 2: Partner Conversations (Volume 2 — Lessons 7–12) ──────────────
    {
      id: "syl-unit-2",
      title: "Partner Conversations",
      description: "Warm, respectful speech — personal questions, numbers, time words, and plans in Sylheti",
      order: 2,
      color: "#FF9600",
      prep: {
        characters: [
          { symbol: "ভ", romanization: "bh", type: "consonant" as const, exampleWord: "ভালোবাসি (love)" },
          { symbol: "প", romanization: "p",  type: "consonant" as const, exampleWord: "প্রিয় (dear)" },
          { symbol: "স", romanization: "s",  type: "consonant" as const, exampleWord: "সকাল (morning)" },
          { symbol: "ম", romanization: "m",  type: "consonant" as const, exampleWord: "মায়া (affection)" },
          { symbol: "র", romanization: "r",  type: "consonant" as const, exampleWord: "রাইত (night)" },
          { symbol: "দ", romanization: "d",  type: "consonant" as const, exampleWord: "দশ (ten)" },
          { symbol: "এ", romanization: "e",  type: "vowel"    as const, exampleWord: "এক (one)" },
          { symbol: "আ", romanization: "aa", type: "vowel"    as const, exampleWord: "আইজ (today)" },
        ],
        flashcards: [
          { id: "fc-syl2-1",  bangla: "প্রিয়",        romanization: "priyo",     english: "Dear / Beloved",            category: "affection" },
          { id: "fc-syl2-2",  bangla: "মায়া",         romanization: "maya",      english: "Affection / Tenderness",    category: "affection" },
          { id: "fc-syl2-3",  bangla: "ভালোবাসি",    romanization: "bhalobasi", english: "I love (you)",              category: "affection" },
          { id: "fc-syl2-4",  bangla: "মান দেই",      romanization: "man dei",   english: "Show respect",              category: "phrases"   },
          { id: "fc-syl2-5",  bangla: "কিতা",         romanization: "kita",      english: "What (Sylheti)",            category: "questions" },
          { id: "fc-syl2-6",  bangla: "কই",           romanization: "koi",       english: "Where (Sylheti)",           category: "questions" },
          { id: "fc-syl2-7",  bangla: "পসন্দ",        romanization: "posond",    english: "Preference / Liking",       category: "questions" },
          { id: "fc-syl2-8",  bangla: "স্বপ্ন",       romanization: "shopno",    english: "Dream",                     category: "questions" },
          { id: "fc-syl2-9",  bangla: "লাই / লাগি",  romanization: "lai/lagi",  english: "For (benefactive)",         category: "phrases"   },
          { id: "fc-syl2-10", bangla: "সকাল",         romanization: "shokal",    english: "Morning",                   category: "time"      },
          { id: "fc-syl2-11", bangla: "রাইত",         romanization: "rait",      english: "Night (Sylheti: রাত)",     category: "time"      },
          { id: "fc-syl2-12", bangla: "সন্ধা",        romanization: "shondha",   english: "Evening",                   category: "time"      },
          { id: "fc-syl2-13", bangla: "আইজ",          romanization: "aij",       english: "Today (Sylheti)",           category: "calendar"  },
          { id: "fc-syl2-14", bangla: "গইকাল",        romanization: "goikal",    english: "Yesterday (Sylheti)",       category: "calendar"  },
          { id: "fc-syl2-15", bangla: "আগাইলকাল",    romanization: "agailkal",  english: "Tomorrow (Sylheti)",        category: "calendar"  },
          { id: "fc-syl2-16", bangla: "-মু",          romanization: "-mu",       english: "Will (future suffix: আইমু = will come)", category: "grammar" },
        ],
        grammar: [
          {
            title: "Object marking with -রে",
            explanation: "Sylheti (like other eastern dialects) marks the direct object with -রে instead of standard -কে: তোমারে (you), পরিবাররে (family). This is a key spoken feature.",
            examples: [
              { bangla: "আমি তোমারে ভালোবাসি।", romanization: "ami tomare bhalobasi.", english: "I love you." },
              { bangla: "আমি আপনের পরিবাররে মান দেই।", romanization: "ami apner poribarre man dei.", english: "I respect your family." },
            ],
          },
          {
            title: "Future with -মু",
            explanation: "Many Sylheti communities use -মু as a future suffix: আইমু (will come), যামু (will go), দিমু (will give/send). These are useful as fixed planning chunks.",
            examples: [
              { bangla: "আমি উনিশ তারিখে আইমু।", romanization: "ami unish tarikhe aimu.", english: "I will come on the nineteenth." },
              { bangla: "সকালে তুমারে মেসেজ দিমু।", romanization: "shokale tumare message dimu.", english: "I will message you in the morning." },
            ],
          },
          {
            title: "Sylheti calendar words",
            explanation: "Sylheti uses আইজ (today), গইকাল (yesterday), and আগাইলকাল (tomorrow). These differ from Standard Bengali's আজ, গতকাল, আগামীকাল — learn them as set spoken chunks.",
            examples: [
              { bangla: "আইজ তুমারে খুব মিস করতাছি।", romanization: "aij tumare khub miss kortasi.", english: "I miss you a lot today." },
              { bangla: "আগাইলকাল আমারা দেখা করুম।", romanization: "agailkal amara dekha korum.", english: "We will meet tomorrow." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "syl-2-0",
          title: "Write the Letters",
          description: "Trace new letters featured in Unit 2 vocabulary",
          unit: 2,
          order: 0,
          xpReward: 20,
          isTrace: true,
          exercises: [
            { type: "letter_trace", id: "syl-2-0-tr-1", character: "ভ", romanization: "bh",  exampleWord: "ভালোবাসি — love",    xp: 4 },
            { type: "letter_trace", id: "syl-2-0-tr-2", character: "প", romanization: "p",   exampleWord: "প্রিয় — dear",       xp: 4 },
            { type: "letter_trace", id: "syl-2-0-tr-3", character: "স", romanization: "s",   exampleWord: "সকাল — morning",      xp: 4 },
            { type: "letter_trace", id: "syl-2-0-tr-4", character: "ম", romanization: "m",   exampleWord: "মায়া — affection",    xp: 4 },
            { type: "letter_trace", id: "syl-2-0-tr-5", character: "র", romanization: "r",   exampleWord: "রাইত — night",        xp: 4 },
          ],
        },
        {
          id: "syl-2-1",
          title: "Respect & Affection",
          description: "Speak warmly and respectfully to a partner and their family in Sylheti",
          unit: 2,
          order: 1,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-2-1-mp-1",
              pairs: [
                { bangla: "আপনে",       english: "You (polite)",       romanization: "apne"      },
                { bangla: "প্রিয়",     english: "Dear / Beloved",     romanization: "priyo"     },
                { bangla: "মায়া করি", english: "I care (Sylheti)",   romanization: "maya kori" },
                { bangla: "মান দেই",   english: "Show respect",       romanization: "man dei"   },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-2-1-tte-1",
              bangla: "আমি তোমারে ভালোবাসি।",
              romanization: "ami tomare bhalobasi.",
              answer: "I love you. (Sylheti: -রে object marker)",

              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "syl-2-1-ttb-1",
              english: "You are very dear to me.",
              answer: "তুমি আমার খুব প্রিয়।",
              romanization: "tumi amar khub priyo.",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "syl-2-1-mc-1",
              prompt: "In Sylheti, the object marker -রে changes 'তোমাকে' (you-object) to:",
              options: ["তোমার", "তোমারে", "তোমাকে", "তোমাদের"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "syl-2-2",
          title: "Sweet Personal Questions",
          description: "Ask caring questions to know your partner better — in Sylheti-style speech",
          unit: 2,
          order: 2,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-2-2-mp-1",
              pairs: [
                { bangla: "কিতা",    english: "What (Sylheti)",  romanization: "kita"   },
                { bangla: "কই",      english: "Where (Sylheti)", romanization: "koi"    },
                { bangla: "পসন্দ",  english: "Preference",      romanization: "posond" },
                { bangla: "স্বপ্ন", english: "Dream",            romanization: "shopno" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-2-2-tte-1",
              bangla: "তুমার পসন্দের গান কিতা?",
              romanization: "tumar posonder gan kita?",
              answer: "What is your favorite song? (Sylheti)",

              xp: 4,
            },
            {
              type: "fill_blank",
              id: "syl-2-2-fb-1",
              sentence: "তুমি ___ যাইতে ভালা পাও?",
              blank: "কই",
              romanization: "tumi ___ jaite bala pao?",
              options: ["কই", "কিতা", "ক্যান", "পসন্দ"],
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "syl-2-2-mc-1",
              prompt: "The Sylheti word for 'what' (replacing standard কী) is:",
              options: ["কোথায়", "কিতা", "কেন", "কেলে"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "syl-2-3",
          title: "Numbers 1–10",
          description: "Count to ten and use numbers in everyday partner phrases",
          unit: 2,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-2-3-mp-1",
              pairs: [
                { bangla: "এক",  english: "One",  romanization: "ek"   },
                { bangla: "তিন", english: "Three", romanization: "tin"  },
                { bangla: "পাঁচ", english: "Five", romanization: "pach" },
                { bangla: "আট",  english: "Eight", romanization: "at"   },
                { bangla: "দশ",  english: "Ten",  romanization: "dosh" },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-2-3-tte-1",
              bangla: "আমি তুমার লাই এক ফুল আনছি।",
              romanization: "ami tumar lai ek phul ansi.",
              answer: "I brought one flower for you. (Sylheti: লাই = for)",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "syl-2-3-mc-1",
              prompt: "In Sylheti, 'লাই / লাগি' is a benefactive meaning:",
              options: ["from", "for / to (someone)", "with", "about"],
              correct: 1,
              xp: 3,
            },
            {
              type: "fill_blank",
              id: "syl-2-3-fb-1",
              sentence: "আমি পাঁচ মিনিটে ___।",
              blank: "আইতাছি",
              romanization: "ami pach minite ___.",
              options: ["আইতাছি", "আসছি", "যাইতাছি", "বসছি"],
              xp: 3,
            },
          ],
        },
        {
          id: "syl-2-4",
          title: "Numbers 11–20",
          description: "Count from eleven to twenty and use teen numbers for dates and plans",
          unit: 2,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-2-4-mp-1",
              pairs: [
                { bangla: "এগার",  english: "Eleven",   romanization: "egar"  },
                { bangla: "বার",   english: "Twelve",   romanization: "bar"   },
                { bangla: "পনের", english: "Fifteen",  romanization: "poner" },
                { bangla: "উনিশ", english: "Nineteen", romanization: "unish" },
                { bangla: "বিশ",  english: "Twenty",   romanization: "bish"  },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-2-4-tte-1",
              bangla: "আমি উনিশ তারিখে আইমু।",
              romanization: "ami unish tarikhe aimu.",
              answer: "I will come on the nineteenth. (Sylheti future: আইমু)",

              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "syl-2-4-ttb-1",
              english: "Are you free on the fifteenth? (Sylheti)",
              answer: "পনের তারিখে তুমি ফ্রি?",
              romanization: "poner tarikhe tumi free?",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "syl-2-4-mc-1",
              prompt: "The Sylheti future suffix -মু in 'আইমু' means:",
              options: ["I came", "I will come", "I am coming", "I have come"],
              correct: 1,
              xp: 3,
            },
          ],
        },
        {
          id: "syl-2-5",
          title: "Time Words",
          description: "Talk about morning, afternoon, evening, and night in Sylheti-style speech",
          unit: 2,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-2-5-mp-1",
              pairs: [
                { bangla: "সকাল", english: "Morning",   romanization: "shokal"  },
                { bangla: "বিকাল", english: "Afternoon", romanization: "bikal"   },
                { bangla: "সন্ধা", english: "Evening",   romanization: "shondha" },
                { bangla: "রাইত", english: "Night",      romanization: "rait"    },
                { bangla: "এখন",  english: "Now",        romanization: "ekhon"   },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-2-5-tte-1",
              bangla: "আজ রাইতে কথা হইব।",
              romanization: "aj raite kotha hoib.",
              answer: "We will talk tonight. (Sylheti: রাইত = night)",

              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "syl-2-5-mc-1",
              prompt: "The Sylheti word for 'night' is 'রাইত'. Standard Bengali uses:",
              options: ["রাইত", "রাত", "রাতি", "নিশি"],
              correct: 1,
              xp: 3,
            },
            {
              type: "fill_blank",
              id: "syl-2-5-fb-1",
              sentence: "সকালে তুমারে মেসেজ ___।",
              blank: "দিমু",
              romanization: "shokale tumare message ___.",
              options: ["দিমু", "দিব", "দেব", "দিছি"],
              xp: 3,
            },
          ],
        },
        {
          id: "syl-2-6",
          title: "Plans & Dates",
          description: "Talk about today, yesterday, and tomorrow — Unit 2 quiz",
          unit: 2,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-2-6-mp-1",
              pairs: [
                { bangla: "আইজ",        english: "Today (Sylheti)",     romanization: "aij"      },
                { bangla: "গইকাল",      english: "Yesterday (Sylheti)", romanization: "goikal"   },
                { bangla: "আগাইলকাল", english: "Tomorrow (Sylheti)",  romanization: "agailkal" },
                { bangla: "পরে",        english: "Later",               romanization: "pore"     },
              ],
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-2-6-tte-1",
              bangla: "আইজ তুমারে খুব মিস করতাছি।",
              romanization: "aij tumare khub miss kortasi.",
              answer: "I miss you a lot today. (Sylheti)",

              xp: 4,
            },
            {
              type: "translate_to_bangla",
              id: "syl-2-6-ttb-1",
              english: "I had a lovely time with you yesterday. (Sylheti)",
              answer: "গইকাল তুমার লগে ভালা লাগছে।",
              romanization: "goikal tumar loge bala lagse.",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "syl-2-6-mc-1",
              prompt: "Sylheti for 'yesterday' (instead of standard 'গতকাল') is:",
              options: ["আইজ", "গতকাল", "গইকাল", "আগামীকাল"],
              correct: 2,
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "syl-2-6-mc-2",
              prompt: "Sylheti for 'tomorrow' is:",
              options: ["আইজ", "গইকাল", "পরে", "আগাইলকাল"],
              correct: 3,
              xp: 3,
            },
          ],
        },
      ],
    },
    // ─── Unit 3 ───────────────────────────────────────────────────────────────
    {
      id: "syl-unit-3",
      title: "Food & Daily Life",
      description: "Sylheti kitchen talk — আঁই খাই, market trips, and home life.",
      color: "#7c3aed",
      order: 3,
      prep: {
        flashcards: [
          { id: "fc-syl-3-1",  bangla: "ভাত",        romanization: "vhat",      english: "cooked rice",       emoji: "🍚", category: "food" },
          { id: "fc-syl-3-2",  bangla: "মাছ",         romanization: "mach",      english: "fish",              emoji: "🐟", category: "food" },
          { id: "fc-syl-3-3",  bangla: "ডাইল",        romanization: "dail",      english: "lentils (Sylheti)", emoji: "🫘", category: "food" },
          { id: "fc-syl-3-4",  bangla: "তরকারি",      romanization: "torkari",   english: "curry/vegetables",  emoji: "🥘", category: "food" },
          { id: "fc-syl-3-5",  bangla: "পানি",        romanization: "pani",      english: "water",             emoji: "💧", category: "food" },
          { id: "fc-syl-3-6",  bangla: "চা",          romanization: "cha",       english: "tea",               emoji: "🍵", category: "food" },
          { id: "fc-syl-3-7",  bangla: "দুধ",         romanization: "dudh",      english: "milk",              emoji: "🥛", category: "food" },
          { id: "fc-syl-3-8",  bangla: "রুটি",        romanization: "ruti",      english: "bread / roti",      emoji: "🫓", category: "food" },
          { id: "fc-syl-3-9",  bangla: "গোশত",        romanization: "gosht",     english: "meat (Sylheti)",    emoji: "🍖", category: "food" },
          { id: "fc-syl-3-10", bangla: "ফল",          romanization: "fol",       english: "fruit",             emoji: "🍎", category: "food" },
          { id: "fc-syl-3-11", bangla: "আঁই খাই",    romanization: "ai khai",   english: "I eat",             emoji: "😋", category: "verb" },
          { id: "fc-syl-3-12", bangla: "আঁই রান্ধি",  romanization: "ai randhi", english: "I cook",            emoji: "👨‍🍳", category: "verb" },
          { id: "fc-syl-3-13", bangla: "বাজার",       romanization: "bajar",     english: "market",            emoji: "🛒", category: "place" },
          { id: "fc-syl-3-14", bangla: "দোকান",       romanization: "dokan",     english: "shop",              emoji: "🏪", category: "place" },
          { id: "fc-syl-3-15", bangla: "বাড়ি",        romanization: "bari",      english: "home",              emoji: "🏠", category: "place" },
          { id: "fc-syl-3-16", bangla: "ঘর",          romanization: "ghor",      english: "room",              emoji: "🚪", category: "place" },
          { id: "fc-syl-3-17", bangla: "রান্নাঘর",    romanization: "rannaghor", english: "kitchen",           emoji: "🍳", category: "place" },
          { id: "fc-syl-3-18", bangla: "বিছানা",      romanization: "bishana",   english: "bed",               emoji: "🛏️", category: "home" },
          { id: "fc-syl-3-19", bangla: "খিদা",        romanization: "khida",     english: "hunger",            emoji: "😩", category: "feeling" },
          { id: "fc-syl-3-20", bangla: "পেট ভরা",     romanization: "pet vhora", english: "stomach full",      emoji: "😌", category: "feeling" },
          { id: "fc-syl-3-21", bangla: "কিনুম",       romanization: "kinum",     english: "I will buy (Syl.)", emoji: "🛍️", category: "verb" },
          { id: "fc-syl-3-22", bangla: "দাম",         romanization: "dam",       english: "price",             emoji: "💰", category: "market" },
          { id: "fc-syl-3-23", bangla: "সস্তা",       romanization: "shoshta",   english: "cheap",             emoji: "🏷️", category: "market" },
          { id: "fc-syl-3-24", bangla: "দামি",        romanization: "dami",      english: "expensive",         emoji: "💎", category: "market" },
          { id: "fc-syl-3-25", bangla: "আঁই ঘুমাই",  romanization: "ai ghumai", english: "I sleep",           emoji: "😴", category: "routine" },
          { id: "fc-syl-3-26", bangla: "আঁই উডি",    romanization: "ai udi",    english: "I get up (Syl.)",   emoji: "🌅", category: "routine" },
          { id: "fc-syl-3-27", bangla: "গোসল",        romanization: "ghoshol",   english: "bath",              emoji: "🚿", category: "routine" },
          { id: "fc-syl-3-28", bangla: "কামে যাই",   romanization: "kame jai",  english: "I go to work",      emoji: "💼", category: "routine" },
        ],
        characters: [],
        grammar: [
          {
            title: "আঁই/তুই verbs in daily activity",
            explanation: "Sylheti keeps its pronoun system: আঁই (I) + রান্ধি (cook), তুই (you, informal) + খাস (eat).",
            examples: [
              { bangla: "আঁই ভাত রান্ধি।", romanization: "ai vhat randhi.", english: "I cook rice." },
              { bangla: "তুই কিতা খাস?",   romanization: "tui kita khas?",  english: "What do you eat?" },
            ],
          },
          {
            title: "কিনুম — Sylheti future",
            explanation: "Sylheti future 1st person: কিনুম (I will buy), যামু (I will go), দিমু (I will give).",
            examples: [
              { bangla: "আঁই বাজার থাকি মাছ কিনুম।", romanization: "ai bajar thaki mach kinum.", english: "I will buy fish from the market." },
              { bangla: "আঁই তোরে চা দিমু।",         romanization: "ai tore cha dimu.",           english: "I will give you tea." },
            ],
          },
          {
            title: "তোরে — object marker in Sylheti",
            explanation: "Sylheti informal object: তোরে (to you), আমারে (to me) — not standard তোমাকে/আমাকে.",
            examples: [
              { bangla: "তোরে মাছ দিমু।",  romanization: "tore mach dimu.",   english: "I will give you fish." },
              { bangla: "আমারে চা দে।",    romanization: "amare cha de.",     english: "Give me tea." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "syl-3-1",
          title: "Rice & Fish",
          description: "Food staples: rice, fish, and meat in Sylheti",
          unit: 3,
          order: 1,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-3-1-mc-1",
              prompt: "Sylheti 'I eat' is:",
              options: ["আমি খাই", "আঁই খাই", "আমি খাচ্ছি", "আঁই খাইতাছি"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-3-1-tte-1",
              bangla: "আঁই ভাত আর মাছ খাই।",
              romanization: "ai vhat ar mach khai.",
              answer: "I eat rice and fish.",

              xp: 5,
            },
            {
              type: "match_pairs",
              id: "syl-3-1-mp-1",
              pairs: [
                { bangla: "ভাত",   english: "rice", romanization: "bhat" },
                { bangla: "মাছ",   english: "fish", romanization: "mach" },
                { bangla: "ডাইল", english: "lentils", romanization: "dail" },
                { bangla: "গোশত", english: "meat", romanization: "gosht" },
              ],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "syl-3-1-ttb-1",
              english: "I will buy fish.",
              answer: "আঁই মাছ কিনুম।",
              romanization: "ai mach kinum.",
              xp: 5,
            },
          ],
        },
        {
          id: "syl-3-2",
          title: "At the Market",
          description: "Shopping at the market in Sylheti dialect",
          unit: 3,
          order: 2,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-3-2-mc-1",
              prompt: "Sylheti 'I will buy' is:",
              options: ["কিনব", "কিনমু", "কিনুম", "কিনছি"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-3-2-tte-1",
              bangla: "বাজার থাকি তরকারি কিনুম।",
              romanization: "bajar thaki torkari kinum.",
              answer: "I will buy vegetables from the market.",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "syl-3-2-fb-1",
              sentence: "গোশত অনেক ___।",
              romanization: "gosht onek ___.",
              blank: "দামি",

              options: ["দামি"],

              xp: 5,
            },
            {
              type: "match_pairs",
              id: "syl-3-2-mp-1",
              pairs: [
                { bangla: "বাজার",  english: "market", romanization: "bajar" },
                { bangla: "দোকান",  english: "shop", romanization: "dokan" },
                { bangla: "সস্তা",  english: "cheap", romanization: "shoshta" },
                { bangla: "দামি",   english: "expensive", romanization: "dami" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "syl-3-3",
          title: "In the Kitchen",
          description: "Kitchen vocabulary and cooking in Sylheti",
          unit: 3,
          order: 3,
          xpReward: 20,
          exercises: [
            {
              type: "translate_to_english",
              id: "syl-3-3-tte-1",
              bangla: "আঁর মা রান্নাঘরে রান্ধে।",
              romanization: "ar ma rannaghor-e randhe.",
              answer: "My mother cooks in the kitchen.",

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-3-3-mc-1",
              prompt: "Sylheti 'I cook' is:",
              options: ["আঁই রান্নি", "আঁই রান্ধি", "আঁই রানতাছি", "আঁই রানছি"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "syl-3-3-mp-1",
              pairs: [
                { bangla: "রান্নাঘর", english: "kitchen", romanization: "rannaghor" },
                { bangla: "বিছানা",   english: "bed", romanization: "bishana" },
                { bangla: "ঘর",       english: "room", romanization: "ghor" },
                { bangla: "বাড়ি",    english: "home", romanization: "bari" },
              ],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "syl-3-3-ttb-1",
              english: "I cook rice at home.",
              answer: "আঁই বাড়িত ভাত রান্ধি।",
              romanization: "ai barit vhat randhi.",
              xp: 5,
            },
          ],
        },
        {
          id: "syl-3-4",
          title: "Daily Routine",
          description: "Daily routine and meal times in Sylheti",
          unit: 3,
          order: 4,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-3-4-mc-1",
              prompt: "Sylheti 'I get up' is:",
              options: ["আঁই উঠি", "আঁই উডি", "আঁই উইঠা", "আঁই উঠলাম"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-3-4-tte-1",
              bangla: "আঁই ভোরে উডি গোসল করি।",
              romanization: "ai vhore udi ghoshol kori.",
              answer: "I wake up early and bathe.",

              xp: 5,
            },
            {
              type: "fill_blank",
              id: "syl-3-4-fb-1",
              sentence: "সকালে উডি ___ করি।",
              romanization: "shokale udi ___ kori.",
              blank: "গোসল",

              options: ["গোসল"],

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "syl-3-4-ttb-1",
              english: "I go to work every day.",
              answer: "আঁই রোজ কামে যাই।",
              romanization: "ai roj kame jai.",
              xp: 5,
            },
          ],
        },
        {
          id: "syl-3-5",
          title: "Hunger & Fullness",
          description: "Expressing hunger and fullness in Sylheti",
          unit: 3,
          order: 5,
          xpReward: 20,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-3-5-mc-1",
              prompt: "Sylheti 'I am hungry' uses:",
              options: ["আমার ক্ষুধা", "আঁর খিদা লাগছে", "আমার ক্ষুধা পেয়েছে", "আঁই ক্ষুধার্ত"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-3-5-tte-1",
              bangla: "আঁর অনেক খিদা লাগছে।",
              romanization: "ar onek khida lagse.",
              answer: "I am very hungry.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "syl-3-5-ttb-1",
              english: "Give me tea.",
              answer: "আমারে চা দে।",
              romanization: "amare cha de.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "syl-3-5-mp-1",
              pairs: [
                { bangla: "খিদা",    english: "hunger", romanization: "khida" },
                { bangla: "পেট ভরা", english: "stomach full", romanization: "pet vhora" },
                { bangla: "পানি",    english: "water", romanization: "pani" },
                { bangla: "চা",      english: "tea", romanization: "cha" },
              ],
              xp: 6,
            },
          ],
        },
        {
          id: "syl-3-6",
          title: "Food Quiz",
          description: "Food & Daily Life quiz — Sylheti Unit 3",
          unit: 3,
          order: 6,
          xpReward: 20,
          isQuiz: true,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-3-6-mc-1",
              prompt: "Sylheti 'I will buy' is:",
              options: ["কিনব", "কিনমু", "কিনুম", "কিনতেছি"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-3-6-tte-1",
              bangla: "আঁই বাজার থাকি মাছ আর তরকারি কিনুম।",
              romanization: "ai bajar thaki mach ar torkari kinum.",
              answer: "I will buy fish and vegetables from the market.",

              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "syl-3-6-ttb-1",
              english: "My mother cooks in the kitchen.",
              answer: "আঁর মা রান্নাঘরে রান্ধে।",
              romanization: "ar ma rannaghor-e randhe.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "syl-3-6-fb-1",
              sentence: "আঁর অনেক ___ লাগছে।",
              romanization: "ar onek ___ lagse.",
              blank: "খিদা",

              options: ["খিদা"],

              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-3-6-mc-2",
              prompt: "Sylheti word for 'meat' (not মাংস) is:",
              options: ["ডাইল", "তরকারি", "গোশত", "ভাত"],
              correct: 2,
              xp: 4,
            },
          ],
        },
      ],
    },
    {
      id: "syl-unit-4",
      title: "Numbers & Counting",
      description: "Count in Sylheti — with the unique -খান classifier",
      order: 4,
      color: "#0369a1",
      prep: {
        characters: [],
        grammar: [
          {
            title: "Sylheti classifier -খান",
            explanation: "Sylheti uses -খান as a general-purpose classifier where standard Bengali uses -টা. It attaches directly to the number: একখান = one (of something). -টা also exists but -খান is the distinctly Sylheti form you'll hear everywhere.",
            examples: [
              { bangla: "একখান আম", romanization: "ekkhan am", english: "one mango" },
              { bangla: "দুইখান মাছ", romanization: "duikhan mach", english: "two fish" },
              { bangla: "তিনখান রুটি", romanization: "tinkhan ruti", english: "three rotis" },
            ],
          },
          {
            title: "Sylheti pronunciation shifts",
            explanation: "Several numbers sound different in Sylheti. পাঁচ becomes হাঞ্চ (hanch), সাত becomes হাত (haat), and ছয় becomes শয় (shoy). Once you know the pattern, the rest follows naturally.",
            examples: [
              { bangla: "হাঞ্চ", romanization: "hanch", english: "five (Sylheti পাঁচ)" },
              { bangla: "হাত", romanization: "haat", english: "seven (Sylheti সাত)" },
              { bangla: "শয়", romanization: "shoy", english: "six (Sylheti ছয়)" },
            ],
          },
          {
            title: "Asking price at the market",
            explanation: "At a Sylheti market you'll ask কতো দাম? (koto dam?) — 'how much does it cost?' The seller replies with a number + টাকা (taka). Knowing your numbers is essential for daily life.",
            examples: [
              { bangla: "কতো দাম?", romanization: "koto dam?", english: "How much is it?" },
              { bangla: "দশ টাকা।", romanization: "dosh taka.", english: "Ten taka." },
              { bangla: "কয়খান?", romanization: "koykhan?", english: "How many? (Sylheti)" },
            ],
          },
        ],
        flashcards: [
          { id: "fc-syl-4-1",  bangla: "এক",       romanization: "ek",      english: "one",          emoji: "1️⃣", category: "numbers" },
          { id: "fc-syl-4-2",  bangla: "দুই",       romanization: "dui",     english: "two",          emoji: "2️⃣", category: "numbers" },
          { id: "fc-syl-4-3",  bangla: "তিন",       romanization: "tin",     english: "three",        emoji: "3️⃣", category: "numbers" },
          { id: "fc-syl-4-4",  bangla: "চার",       romanization: "char",    english: "four",         emoji: "4️⃣", category: "numbers" },
          { id: "fc-syl-4-5",  bangla: "হাঞ্চ",     romanization: "hanch",   english: "five (Sylheti)",emoji: "5️⃣", category: "numbers" },
          { id: "fc-syl-4-6",  bangla: "শয়",        romanization: "shoy",    english: "six (Sylheti)", emoji: "6️⃣", category: "numbers" },
          { id: "fc-syl-4-7",  bangla: "হাত",       romanization: "haat",    english: "seven (Sylheti)",emoji: "7️⃣", category: "numbers" },
          { id: "fc-syl-4-8",  bangla: "আট",        romanization: "aat",     english: "eight",        emoji: "8️⃣", category: "numbers" },
          { id: "fc-syl-4-9",  bangla: "নয়",        romanization: "noy",     english: "nine",         emoji: "9️⃣", category: "numbers" },
          { id: "fc-syl-4-10", bangla: "দশ",        romanization: "dosh",    english: "ten",          emoji: "🔟", category: "numbers" },
          { id: "fc-syl-4-11", bangla: "এগারো",     romanization: "egaro",   english: "eleven",       emoji: "1️⃣1️⃣", category: "numbers" },
          { id: "fc-syl-4-12", bangla: "বারো",      romanization: "baro",    english: "twelve",       emoji: "1️⃣2️⃣", category: "numbers" },
          { id: "fc-syl-4-13", bangla: "বিশ",       romanization: "bish",    english: "twenty",       emoji: "2️⃣0️⃣", category: "numbers" },
          { id: "fc-syl-4-14", bangla: "ত্রিশ",     romanization: "trish",   english: "thirty",       emoji: "3️⃣0️⃣", category: "numbers" },
          { id: "fc-syl-4-15", bangla: "একশো",      romanization: "ekshо",   english: "one hundred",  emoji: "💯",  category: "numbers" },
          { id: "fc-syl-4-16", bangla: "এক হাজার",  romanization: "ek hajar",english: "one thousand", emoji: "🔢", category: "numbers" },
          { id: "fc-syl-4-17", bangla: "কয়খান?",   romanization: "koykhan?",english: "how many? (Sylheti)", emoji: "❓", category: "question" },
          { id: "fc-syl-4-18", bangla: "কতো দাম?",  romanization: "koto dam?",english: "how much?",   emoji: "🏷️", category: "money" },
          { id: "fc-syl-4-19", bangla: "টাকা",      romanization: "taka",    english: "taka (money)", emoji: "💵", category: "money" },
          { id: "fc-syl-4-20", bangla: "-খান",      romanization: "-khan",   english: "classifier (Sylheti)", emoji: "🔢", category: "grammar" },
        ],
      },
      lessons: [
        {
          id: "syl-4-1",
          title: "Numbers 1–10",
          description: "Count from one to ten in authentic Sylheti",
          unit: 4,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-4-1-mc-1",
              prompt: "What is the Sylheti word for 'five'?",
              options: ["পাঁচ", "হাঞ্চ", "হাত", "শয়"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "syl-4-1-mp-1",
              pairs: [
                { bangla: "এক",   english: "one",   romanization: "ek" },
                { bangla: "দুই",  english: "two",   romanization: "dui" },
                { bangla: "তিন",  english: "three", romanization: "tin" },
                { bangla: "চার",  english: "four",  romanization: "char" },
                { bangla: "হাঞ্চ", english: "five",  romanization: "hanch" },
              ],
              xp: 8,
            },
            {
              type: "translate_to_english",
              id: "syl-4-1-tte-1",
              bangla: "হাত",
              romanization: "haat",
              answer: "seven",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-4-1-mc-2",
              prompt: "Which number is 'শয়' in Sylheti?",
              options: ["five", "six", "seven", "eight"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-4-1-tte-2",
              bangla: "নয়",
              romanization: "noy",
              answer: "nine",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "syl-4-1-mp-2",
              pairs: [
                { bangla: "শয়",  english: "six",   romanization: "shoy" },
                { bangla: "হাত",  english: "seven", romanization: "haat" },
                { bangla: "আট",   english: "eight", romanization: "aat" },
                { bangla: "নয়",  english: "nine",  romanization: "noy" },
                { bangla: "দশ",  english: "ten",   romanization: "dosh" },
              ],
              xp: 8,
            },
          ],
        },
        {
          id: "syl-4-2",
          title: "The -খান Classifier",
          description: "Master the distinctly Sylheti way to count objects",
          unit: 4,
          order: 2,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-4-2-mc-1",
              prompt: "How do you say 'one mango' using the Sylheti classifier?",
              options: ["একটা আম", "একখান আম", "এক আম", "একজন আম"],
              correct: 1,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-4-2-tte-1",
              bangla: "দুইখান মাছ",
              romanization: "duikhan mach",
              answer: "two fish",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "syl-4-2-fb-1",
              sentence: "তিন___ রুটি দেও।",
              romanization: "tin___ ruti deo.",
              blank: "খান",
              options: ["টা", "খান", "জন", "টি"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "syl-4-2-ttb-1",
              english: "How many? (Sylheti)",
              answer: "কয়খান?",
              romanization: "koykhan?",
              xp: 6,
            },
            {
              type: "multiple_choice",
              id: "syl-4-2-mc-2",
              prompt: "Which classifier is distinctly Sylheti (not used in standard Bengali)?",
              options: ["-টা", "-টি", "-খান", "-জন"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-4-2-tte-2",
              bangla: "হাঞ্চখান আম",
              romanization: "hanch khan am",
              answer: "five mangoes",
              xp: 5,
            },
          ],
        },
        {
          id: "syl-4-3",
          title: "Teens & Tens",
          description: "Count past ten — egaro, baro, bish and beyond",
          unit: 4,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-4-3-mp-1",
              pairs: [
                { bangla: "এগারো", english: "eleven",  romanization: "egaro"  },
                { bangla: "বারো",  english: "twelve",  romanization: "baro"   },
                { bangla: "বিশ",   english: "twenty",  romanization: "bish"   },
                { bangla: "ত্রিশ", english: "thirty",  romanization: "trish"  },
                { bangla: "একশো", english: "hundred",  romanization: "ekshо"  },
              ],
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "syl-4-3-mc-1",
              prompt: "What does 'বিশ' mean?",
              options: ["twelve", "fifteen", "twenty", "thirty"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-4-3-tte-1",
              bangla: "ত্রিশ টাকা",
              romanization: "trish taka",
              answer: "thirty taka",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "syl-4-3-fb-1",
              sentence: "এক ___ টাকা।",
              romanization: "ek ___ taka.",
              blank: "শো",
              options: ["হাজার", "শো", "দশ", "বিশ"],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-4-3-mc-2",
              prompt: "How do you say 'one thousand' in Sylheti?",
              options: ["একশো", "এক লাখ", "এক হাজার", "দশ হাজার"],
              correct: 2,
              xp: 4,
            },
          ],
        },
        {
          id: "syl-4-4",
          title: "At the Market",
          description: "Use numbers to buy and sell at a Sylheti bazaar",
          unit: 4,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "syl-4-4-tte-1",
              bangla: "কতো দাম?",
              romanization: "koto dam?",
              answer: "how much is it?",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-4-4-mc-1",
              prompt: "A seller says 'বিশ টাকা'. How much are they asking?",
              options: ["10 taka", "12 taka", "20 taka", "30 taka"],
              correct: 2,
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "syl-4-4-mp-1",
              pairs: [
                { bangla: "কতো দাম?",    english: "how much?",        romanization: "koto dam?"      },
                { bangla: "কয়খান?",      english: "how many?",        romanization: "koykhan?"       },
                { bangla: "দশ টাকা",     english: "ten taka",         romanization: "dosh taka"      },
                { bangla: "একশো টাকা",   english: "one hundred taka", romanization: "ekshо taka"     },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "syl-4-4-fb-1",
              sentence: "আঁই দুইখান আম কিনলাম ___ টাকায়।",
              romanization: "ai duikhan am kinlam ___ takay.",
              blank: "বিশ",
              options: ["দশ", "বিশ", "তিন", "এক"],
              xp: 6,
            },
            {
              type: "translate_to_bangla",
              id: "syl-4-4-ttb-1",
              english: "I bought five mangoes.",
              answer: "আঁই হাঞ্চখান আম কিনলাম।",
              romanization: "ai hanch khan am kinlam.",
              xp: 7,
            },
            {
              type: "multiple_choice",
              id: "syl-4-4-mc-2",
              prompt: "Complete the market sentence: 'দুইখান মাছ ___ টাকা।'",
              options: ["এগারো", "তিরিশ", "একশো", "হাজার"],
              correct: 1,
              xp: 4,
            },
          ],
        },
        {
          id: "syl-4-5",
          title: "Telling the Time",
          description: "Ask and answer 'what time is it?' in Sylheti",
          unit: 4,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-4-5-mc-1",
              prompt: "How do you ask 'What time is it?' in Sylheti/Bengali?",
              options: ["কত বাজে?", "কটা বাজে?", "কতো দাম?", "কয়খান?"],
              correct: 1,
              xp: 5,
            },
            {
              type: "translate_to_english",
              id: "syl-4-5-tte-1",
              bangla: "দশটা বাজে।",
              romanization: "doshta baje.",
              answer: "it is ten o'clock",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "syl-4-5-fb-1",
              sentence: "___ টা বাজে। (It is five o'clock — Sylheti)",
              romanization: "___ ta baje.",
              blank: "হাঞ্চ",
              options: ["পাঁচ", "হাঞ্চ", "হাত", "শয়"],
              xp: 6,
            },
            {
              type: "match_pairs",
              id: "syl-4-5-mp-1",
              pairs: [
                { bangla: "একটা বাজে",    english: "it is one o'clock",   romanization: "ekta baje"    },
                { bangla: "তিনটা বাজে",   english: "it is three o'clock", romanization: "tinta baje"   },
                { bangla: "হাঞ্চটা বাজে", english: "it is five o'clock",  romanization: "hanch ta baje" },
                { bangla: "দশটা বাজে",    english: "it is ten o'clock",   romanization: "doshta baje"  },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "syl-4-5-ttb-1",
              english: "It is seven o'clock.",
              answer: "হাতটা বাজে।",
              romanization: "hatta baje.",
              xp: 7,
            },
            {
              type: "multiple_choice",
              id: "syl-4-5-mc-2",
              prompt: "A Sylheti speaker says 'শয়টা বাজে' — what time is it?",
              options: ["5 o'clock", "6 o'clock", "7 o'clock", "8 o'clock"],
              correct: 1,
              xp: 5,
            },
          ],
        },
      ],
    },
    {
      id: "syl-unit-5",
      title: "Getting Around",
      description: "Transport, directions, and travel vocabulary in Sylheti",
      order: 5,
      prep: {
        characters: [],
        grammar: [
          {
            title: "Direction words in Sylheti",
            rule: "Sylheti uses উফরে (upstairs/up), নিচে (down/below), আগে (ahead), পিছে (behind) — the same roots as standard Bengali but with distinct pronunciation.",
            examples: [
              { bangla: "বাম দিকে যাও।", romanization: "bam dike jao.", english: "Go left." },
              { bangla: "ডান দিকে যাও।", romanization: "dan dike jao.", english: "Go right." },
            ],
          },
          {
            title: "Asking 'how far?' — কতদূর?",
            rule: "কতদূর? means 'how far?' — used the same way in Sylheti. হাঁটা দূরত্ব means 'walking distance'.",
            examples: [
              { bangla: "বাজার কতদূর?", romanization: "bazar kotodur?", english: "How far is the market?" },
              { bangla: "হাঁটা দূরত্বে।", romanization: "hata durotte.", english: "It's within walking distance." },
            ],
          },
          {
            title: "Transport verbs — যাওয়া, আসা",
            rule: "যাওয়া (to go) and আসা (to come) are used with transport: রিকশায় যাই (I go by rickshaw), বাসে আসি (I come by bus).",
            examples: [
              { bangla: "আঁই রিকশায় যাই।", romanization: "ai rikshay jai.", english: "I go by rickshaw." },
              { bangla: "বাসে আসি।", romanization: "base asi.", english: "I come by bus." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "syl-5-1",
          title: "Transport Vocab",
          description: "Rickshaw, bus, boat — the vehicles of Sylheti life",
          unit: 5,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-5-1-mc-1",
              prompt: "What is 'rickshaw' in Bengali/Sylheti?",
              options: ["নৌকা", "রিকশা", "বাস", "ট্রেন"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-5-1-tte-1",
              bangla: "নৌকায় যাই।",
              romanization: "noukay jai.",
              answer: "I go by boat.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "syl-5-1-mp-1",
              pairs: [
                { bangla: "রিকশা",  english: "rickshaw", romanization: "riksha"  },
                { bangla: "বাস",    english: "bus",       romanization: "bas"     },
                { bangla: "নৌকা",   english: "boat",      romanization: "nouka"   },
                { bangla: "ট্রেন",  english: "train",     romanization: "tren"    },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "syl-5-1-ttb-1",
              english: "I go by bus.",
              answer: "আঁই বাসে যাই।",
              romanization: "ai base jai.",
              xp: 6,
            },
            {
              type: "multiple_choice",
              id: "syl-5-1-mc-2",
              prompt: "Which vehicle is most associated with Sylhet's waterways?",
              options: ["ট্রেন", "রিকশা", "নৌকা", "বাস"],
              correct: 2,
              xp: 4,
            },
          ],
        },
        {
          id: "syl-5-2",
          title: "Asking Directions",
          description: "Left, right, straight ahead — find your way in Sylheti",
          unit: 5,
          order: 2,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "syl-5-2-tte-1",
              bangla: "বাম দিকে যাও।",
              romanization: "bam dike jao.",
              answer: "Go left.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-5-2-mc-1",
              prompt: "How do you say 'go straight' in Bengali?",
              options: ["বাম দিকে", "ডান দিকে", "সোজা যাও", "পিছনে যাও"],
              correct: 2,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "syl-5-2-mp-1",
              pairs: [
                { bangla: "বাম দিকে",  english: "to the left",  romanization: "bam dike"  },
                { bangla: "ডান দিকে",  english: "to the right", romanization: "dan dike"  },
                { bangla: "সোজা",      english: "straight",     romanization: "shoja"     },
                { bangla: "পিছনে",     english: "behind",       romanization: "pichone"   },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "syl-5-2-fb-1",
              sentence: "মসজিদ ___ দিকে।",
              romanization: "mosjid ___ dike.",
              blank: "ডান",
              options: ["বাম", "ডান", "সোজা", "পিছনে"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "syl-5-2-ttb-1",
              english: "The market is to the right.",
              answer: "বাজার ডান দিকে।",
              romanization: "bazar dan dike.",
              xp: 6,
            },
          ],
        },
        {
          id: "syl-5-3",
          title: "How Far?",
          description: "Ask about distance and travel time in Sylheti",
          unit: 5,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-5-3-mc-1",
              prompt: "How do you ask 'how far?' in Bengali/Sylheti?",
              options: ["কতদূর?", "কতক্ষণ?", "কতো দাম?", "কয়খান?"],
              correct: 0,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-5-3-tte-1",
              bangla: "বাজার কতদূর?",
              romanization: "bazar kotodur?",
              answer: "How far is the market?",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "syl-5-3-fb-1",
              sentence: "স্টেশন ___ দূরত্বে।",
              romanization: "steshan ___ durotte.",
              blank: "হাঁটা",
              options: ["হাঁটা", "নৌকা", "বাস", "ট্রেন"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "syl-5-3-ttb-1",
              english: "The station is far.",
              answer: "স্টেশন অনেক দূরে।",
              romanization: "steshan onek dure.",
              xp: 6,
            },
            {
              type: "multiple_choice",
              id: "syl-5-3-mc-2",
              prompt: "What does 'হাঁটা দূরত্ব' mean?",
              options: ["By rickshaw", "Walking distance", "Very far", "How long?"],
              correct: 1,
              xp: 4,
            },
          ],
        },
        {
          id: "syl-5-4",
          title: "At the Station",
          description: "Buy tickets and navigate transport hubs",
          unit: 5,
          order: 4,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "syl-5-4-tte-1",
              bangla: "একটা টিকেট দেন।",
              romanization: "ekta tiket den.",
              answer: "Give me one ticket.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-5-4-mc-1",
              prompt: "How do you ask 'when does the bus leave?'",
              options: ["বাস কতদূর?", "বাস কখন ছাড়ে?", "বাস কয়খান?", "বাস কোথায়?"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "syl-5-4-mp-1",
              pairs: [
                { bangla: "টিকেট",    english: "ticket",    romanization: "tiket"   },
                { bangla: "স্টেশন",   english: "station",   romanization: "steshan" },
                { bangla: "ছাড়া",    english: "to leave",  romanization: "chara"   },
                { bangla: "পৌঁছানো", english: "to arrive", romanization: "pouchano"},
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "syl-5-4-ttb-1",
              english: "When does the train arrive?",
              answer: "ট্রেন কখন পৌঁছাবে?",
              romanization: "tren kokhon pouchabe?",
              xp: 7,
            },
            {
              type: "multiple_choice",
              id: "syl-5-4-mc-2",
              prompt: "A sign says 'সিলেট→ঢাকা' — what route does it indicate?",
              options: ["Dhaka to Sylhet", "Sylhet to Dhaka", "Chittagong to Sylhet", "Sylhet to Rajshahi"],
              correct: 1,
              xp: 4,
            },
          ],
        },
        {
          id: "syl-5-5",
          title: "Travel Review",
          description: "Test your transport and direction vocabulary",
          unit: 5,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-5-5-mc-1",
              prompt: "You want to go right. What do you say?",
              options: ["বাম দিকে যাই।", "সোজা যাই।", "ডান দিকে যাই।", "পিছনে যাই।"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-5-5-tte-1",
              bangla: "আঁই রিকশায় বাজারে যাই।",
              romanization: "ai rikshay bazare jai.",
              answer: "I go to the market by rickshaw.",
              xp: 6,
            },
            {
              type: "fill_blank",
              id: "syl-5-5-fb-1",
              sentence: "দুইটা ___ দেন।",
              romanization: "duita ___ den.",
              blank: "টিকেট",
              options: ["নৌকা", "বাস", "টিকেট", "রিকশা"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "syl-5-5-mp-1",
              pairs: [
                { bangla: "কতদূর?",     english: "how far?",          romanization: "kotodur?"    },
                { bangla: "সোজা যাও",   english: "go straight",       romanization: "shoja jao"   },
                { bangla: "বাসে যাই",   english: "I go by bus",       romanization: "base jai"    },
                { bangla: "টিকেট দেন",  english: "give me a ticket",  romanization: "tiket den"   },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "syl-5-5-ttb-1",
              english: "The station is to the left.",
              answer: "স্টেশন বাম দিকে।",
              romanization: "steshan bam dike.",
              xp: 7,
            },
          ],
        },
      ],
    },
    {
      id: "syl-unit-6",
      title: "Health & Body",
      description: "Body parts, ailments, and visiting the doctor in Sylheti",
      order: 6,
      prep: {
        characters: [],
        grammar: [
          {
            title: "Expressing pain — ব্যথা করছে",
            rule: "To say something hurts: [body part] + ব্যথা করছে ('is hurting'). Example: মাথা ব্যথা করছে = My head hurts.",
            examples: [
              { bangla: "পেট ব্যথা করছে।", romanization: "pet betha korche.", english: "My stomach hurts." },
              { bangla: "হাত ব্যথা করছে।", romanization: "hat betha korche.", english: "My hand hurts." },
            ],
          },
          {
            title: "Feeling unwell — অসুস্থ",
            rule: "আঁই অসুস্থ (I am unwell). জ্বর আসছে = I have a fever. ঠান্ডা লাগছে = I feel cold / have a cold.",
            examples: [
              { bangla: "আঁই অসুস্থ।", romanization: "ai oshustho.", english: "I am unwell." },
              { bangla: "জ্বর আসছে।", romanization: "jor asche.", english: "I have a fever." },
            ],
          },
          {
            title: "Visiting the doctor — ডাক্তার",
            rule: "ডাক্তার দেখানো = to see a doctor. ওষুধ খাওয়া = to take medicine. হাসপাতাল = hospital.",
            examples: [
              { bangla: "ডাক্তার দেখাতে হবে।", romanization: "daktar dekhate hobe.", english: "I need to see a doctor." },
              { bangla: "ওষুধ খাও।", romanization: "oshud khao.", english: "Take the medicine." },
            ],
          },
        ],
      },
      lessons: [
        {
          id: "syl-6-1",
          title: "Body Parts",
          description: "Head to toe — essential body vocabulary in Sylheti",
          unit: 6,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-6-1-mp-1",
              pairs: [
                { bangla: "মাথা",  english: "head",  romanization: "matha" },
                { bangla: "হাত",   english: "hand",  romanization: "hat"   },
                { bangla: "পা",    english: "foot",  romanization: "pa"    },
                { bangla: "চোখ",   english: "eye",   romanization: "chokh" },
                { bangla: "পেট",   english: "stomach", romanization: "pet" },
              ],
              xp: 8,
            },
            {
              type: "multiple_choice",
              id: "syl-6-1-mc-1",
              prompt: "What does 'কান' mean?",
              options: ["eye", "ear", "nose", "mouth"],
              correct: 1,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-6-1-tte-1",
              bangla: "নাক আর মুখ।",
              romanization: "nak ar mukh.",
              answer: "Nose and mouth.",
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "syl-6-1-fb-1",
              sentence: "___ দিয়ে শুনি।",
              romanization: "___ diye shuni.",
              blank: "কান",
              options: ["মাথা", "কান", "চোখ", "নাক"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "syl-6-1-ttb-1",
              english: "My back hurts.",
              answer: "পিঠ ব্যথা করছে।",
              romanization: "pith betha korche.",
              xp: 6,
            },
          ],
        },
        {
          id: "syl-6-2",
          title: "Feeling Unwell",
          description: "Say what's wrong and describe symptoms",
          unit: 6,
          order: 2,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "syl-6-2-tte-1",
              bangla: "আঁই অসুস্থ।",
              romanization: "ai oshustho.",
              answer: "I am unwell.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-6-2-mc-1",
              prompt: "How do you say 'I have a fever'?",
              options: ["পেট ব্যথা করছে।", "জ্বর আসছে।", "ঠান্ডা লাগছে।", "মাথা ঘুরছে।"],
              correct: 1,
              xp: 4,
            },
            {
              type: "match_pairs",
              id: "syl-6-2-mp-1",
              pairs: [
                { bangla: "জ্বর",       english: "fever",      romanization: "jor"      },
                { bangla: "ঠান্ডা",     english: "cold",       romanization: "thanda"   },
                { bangla: "ব্যথা",      english: "pain",       romanization: "betha"    },
                { bangla: "অসুস্থ",    english: "unwell",     romanization: "oshustho" },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "syl-6-2-fb-1",
              sentence: "মাথা ___ করছে।",
              romanization: "matha ___ korche.",
              blank: "ব্যথা",
              options: ["জ্বর", "ব্যথা", "ঠান্ডা", "ভালো"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "syl-6-2-ttb-1",
              english: "I feel cold.",
              answer: "ঠান্ডা লাগছে।",
              romanization: "thanda lagche.",
              xp: 6,
            },
          ],
        },
        {
          id: "syl-6-3",
          title: "At the Doctor",
          description: "Navigate a medical visit — symptoms, medicine, and advice",
          unit: 6,
          order: 3,
          xpReward: 12,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-6-3-mc-1",
              prompt: "What does 'ডাক্তার' mean?",
              options: ["hospital", "medicine", "doctor", "nurse"],
              correct: 2,
              xp: 4,
            },
            {
              type: "translate_to_english",
              id: "syl-6-3-tte-1",
              bangla: "ওষুধ খাও।",
              romanization: "oshud khao.",
              answer: "Take the medicine.",
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "syl-6-3-mp-1",
              pairs: [
                { bangla: "ডাক্তার",    english: "doctor",    romanization: "daktar"    },
                { bangla: "হাসপাতাল",  english: "hospital",  romanization: "hashpatal" },
                { bangla: "ওষুধ",      english: "medicine",  romanization: "oshud"     },
                { bangla: "নার্স",     english: "nurse",     romanization: "nars"      },
              ],
              xp: 8,
            },
            {
              type: "fill_blank",
              id: "syl-6-3-fb-1",
              sentence: "ডাক্তার ___ যেতে হবে।",
              romanization: "daktar ___ jete hobe.",
              blank: "কাছে",
              options: ["কাছে", "দূরে", "বাম", "ডান"],
              xp: 5,
            },
            {
              type: "translate_to_bangla",
              id: "syl-6-3-ttb-1",
              english: "I need to go to the hospital.",
              answer: "আঁই হাসপাতালে যেতে হবে।",
              romanization: "ai hashpataley jete hobe.",
              xp: 7,
            },
          ],
        },
        {
          id: "syl-6-4",
          title: "Pharmacy & Medicine",
          description: "Ask for medicine and understand dosage instructions",
          unit: 6,
          order: 4,
          xpReward: 12,
          exercises: [
            {
              type: "translate_to_english",
              id: "syl-6-4-tte-1",
              bangla: "একটা ওষুধ দেন।",
              romanization: "ekta oshud den.",
              answer: "Give me a medicine.",
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-6-4-mc-1",
              prompt: "A pharmacist says 'দিনে তিনবার খান' — how often should you take it?",
              options: ["Once a day", "Twice a day", "Three times a day", "Once a week"],
              correct: 2,
              xp: 5,
            },
            {
              type: "fill_blank",
              id: "syl-6-4-fb-1",
              sentence: "খাওয়ার ___ ওষুধ খাও।",
              romanization: "khawar ___ oshud khao.",
              blank: "পরে",
              options: ["আগে", "পরে", "সাথে", "ছাড়া"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "syl-6-4-mp-1",
              pairs: [
                { bangla: "ফার্মেসি",   english: "pharmacy",    romanization: "pharmeshi"  },
                { bangla: "ট্যাবলেট",  english: "tablet",      romanization: "tablet"     },
                { bangla: "দিনে",      english: "per day",     romanization: "dine"       },
                { bangla: "খাওয়ার পরে", english: "after eating", romanization: "khawar pore" },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "syl-6-4-ttb-1",
              english: "Take two tablets after eating.",
              answer: "খাওয়ার পরে দুটো ট্যাবলেট খাও।",
              romanization: "khawar pore duto tablet khao.",
              xp: 7,
            },
          ],
        },
        {
          id: "syl-6-5",
          title: "Health Review",
          description: "Review all health and body vocabulary",
          unit: 6,
          order: 5,
          xpReward: 15,
          exercises: [
            {
              type: "translate_to_english",
              id: "syl-6-5-tte-1",
              bangla: "পেট ব্যথা করছে, ডাক্তারের কাছে যাব।",
              romanization: "pet betha korche, daktarer kache jabo.",
              answer: "My stomach hurts, I will go to the doctor.",
              xp: 7,
            },
            {
              type: "multiple_choice",
              id: "syl-6-5-mc-1",
              prompt: "Which symptom means 'I have a headache'?",
              options: ["জ্বর আসছে।", "পেট ব্যথা।", "মাথা ব্যথা।", "হাত ব্যথা।"],
              correct: 2,
              xp: 4,
            },
            {
              type: "fill_blank",
              id: "syl-6-5-fb-1",
              sentence: "আঁই ___ আছি।",
              romanization: "ai ___ achi.",
              blank: "অসুস্থ",
              options: ["ভালো", "অসুস্থ", "সুস্থ", "খুশি"],
              xp: 5,
            },
            {
              type: "match_pairs",
              id: "syl-6-5-mp-1",
              pairs: [
                { bangla: "মাথা ব্যথা",   english: "headache",    romanization: "matha betha"  },
                { bangla: "জ্বর",         english: "fever",       romanization: "jor"          },
                { bangla: "ওষুধ",         english: "medicine",    romanization: "oshud"        },
                { bangla: "হাসপাতাল",    english: "hospital",    romanization: "hashpatal"    },
              ],
              xp: 8,
            },
            {
              type: "translate_to_bangla",
              id: "syl-6-5-ttb-1",
              english: "Take medicine three times a day.",
              answer: "দিনে তিনবার ওষুধ খাও।",
              romanization: "dine tinbar oshud khao.",
              xp: 7,
            },
          ],
        },
      ],
    },
  ],
};
