import type { DialectCurriculum } from "@bangla-learn/types";

export const sylhetiCurriculum: DialectCurriculum = {
  dialect: "sylheti",
  units: [
    {
      id: "syl-unit-1",
      title: "Sylheti Greetings",
      description: "Learn how to greet in Sylheti — spoken in Sylhet and the UK Bangladeshi community",
      order: 1,
      color: "#FF9600",
      lessons: [
        {
          id: "syl-1-1",
          title: "Hello in Sylheti",
          description: "Sylheti has its own greetings different from Standard Bengali",
          unit: 1,
          order: 1,
          xpReward: 10,
          exercises: [
            {
              type: "multiple_choice",
              id: "syl-1-1-mc-1",
              prompt: "In Sylheti, how do you say 'Are you well?'",
              options: [
                "ভালা আসেন? (Bhala assen?)",
                "আপনি কেমন আছেন?",
                "কি খবর? (Ki khabor?)",
                "নমস্কার (Nomoshkar)",
              ],
              correct: 0,
              xp: 3,
            },
            {
              type: "translate_to_english",
              id: "syl-1-1-tte-1",
              bangla: "ভালা আসি",
              romanization: "Bhala ashi",
              answer: "I am well (Sylheti)",
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "syl-1-1-mc-2",
              prompt: "Sylheti word for 'Yes' is:",
              options: ["হ্যাঁ (Hæ)", "হই (Hoi)", "না (Na)", "ঠিক আছে (Thik ache)"],
              correct: 1,
              xp: 2,
            },
            {
              type: "translate_to_bangla",
              id: "syl-1-1-ttb-1",
              english: "I am well (Sylheti)",
              answer: "ভালা আসি",
              romanization: "Bhala ashi",
              xp: 2,
            },
          ],
        },
        {
          id: "syl-1-2",
          title: "Sylheti Pronouns",
          description: "How Sylheti pronouns differ from Standard Bengali",
          unit: 1,
          order: 2,
          xpReward: 10,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-1-2-mp-1",
              pairs: [
                { bangla: "আমি (Ami)", english: "I (same as Standard)", romanization: "Ami" },
                { bangla: "তুই (Tui)", english: "You (informal)", romanization: "Tui" },
                { bangla: "হে (He)", english: "He/She (Sylheti)", romanization: "He" },
                { bangla: "আমরা (Amra)", english: "We", romanization: "Amra" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-1-2-mc-1",
              prompt: "In Sylheti, 'হে' refers to:",
              options: ["I", "You", "He or She", "They"],
              correct: 2,
              xp: 3,
            },
          ],
        },
        {
          id: "syl-1-3",
          title: "Numbers in Sylheti",
          description: "Counting in Sylheti — some numbers sound different!",
          unit: 1,
          order: 3,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-1-3-mp-1",
              pairs: [
                { bangla: "এক", english: "One", romanization: "Ek" },
                { bangla: "দুই", english: "Two", romanization: "Dui" },
                { bangla: "তিন", english: "Three", romanization: "Tin" },
                { bangla: "চাইর", english: "Four (Sylheti)", romanization: "Chair" },
                { bangla: "পাঁচ", english: "Five", romanization: "Panch" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-1-3-mc-1",
              prompt: "In Sylheti, 'চাইর' means:",
              options: ["Three", "Four", "Five", "Six"],
              correct: 1,
              xp: 3,
            },
            {
              type: "translate_to_english",
              id: "syl-1-3-tte-1",
              bangla: "চাইর",
              romanization: "Chair",
              answer: "Four (Sylheti pronunciation of চার)",
              xp: 2,
            },
          ],
        },
        {
          id: "syl-1-4",
          title: "Sylheti Family Words",
          description: "Family terms unique to Sylheti culture",
          unit: 1,
          order: 4,
          xpReward: 15,
          exercises: [
            {
              type: "match_pairs",
              id: "syl-1-4-mp-1",
              pairs: [
                { bangla: "মা", english: "Mother", romanization: "Ma" },
                { bangla: "আব্বা", english: "Father (Sylheti preferred)", romanization: "Abba" },
                { bangla: "ভাই", english: "Brother", romanization: "Bhai" },
                { bangla: "আফা", english: "Sister (Sylheti)", romanization: "Apha" },
              ],
              xp: 5,
            },
            {
              type: "multiple_choice",
              id: "syl-1-4-mc-1",
              prompt: "In Sylheti communities, 'আব্বা' means:",
              options: ["Mother", "Father", "Grandmother", "Uncle"],
              correct: 1,
              xp: 3,
            },
            {
              type: "multiple_choice",
              id: "syl-1-4-mc-2",
              prompt: "The Sylheti word for Sister is:",
              options: ["বোন", "আফা", "ভাই", "মা"],
              correct: 1,
              xp: 2,
            },
          ],
        },
        {
          id: "syl-1-5",
          title: "Common Sylheti Phrases",
          description: "Everyday phrases you will hear in Sylheti",
          unit: 1,
          order: 5,
          xpReward: 20,
          exercises: [
            {
              type: "translate_to_english",
              id: "syl-1-5-tte-1",
              bangla: "কিতা খাইলা?",
              romanization: "Kita khaila?",
              answer: "What did you eat?",
              xp: 4,
            },
            {
              type: "multiple_choice",
              id: "syl-1-5-mc-1",
              prompt: "'কিতা' in Sylheti means:",
              options: ["Who", "When", "What", "Where"],
              correct: 2,
              xp: 3,
            },
            {
              type: "translate_to_english",
              id: "syl-1-5-tte-2",
              bangla: "গেলাম",
              romanization: "Gelam",
              answer: "I went / Let's go (casual farewell in Sylheti)",
              xp: 3,
            },
          ],
        },
      ],
    },
  ],
};
