#!/usr/bin/env bash
# BanglaLearn — auto-updates:
#   1. macOS Notes app widget ("BanglaLearn Dev")
#   2. HANDOFF.md at repo root (for non-Claude devs / tools)
# LaunchAgent runs this every 30 min. Manual: bash .claude/update-notes.sh

REPO="/Users/marwaanswar/bangla-learn"
NOTE_NAME="BanglaLearn Dev"
TMP_BODY="/tmp/banglalearn-note-body.html"
HANDOFF="$REPO/HANDOFF.md"

# --- Gather live data ---
BRANCH=$(git -C "$REPO" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
LAST_COMMIT=$(git -C "$REPO" log -1 --format="%h — %s (%ar)" 2>/dev/null || echo "none")
RECENT_COMMITS=$(git -C "$REPO" log -5 --format="- %h %s (%ar)" 2>/dev/null || echo "none")
MODIFIED=$(git -C "$REPO" diff --name-only HEAD 2>/dev/null | wc -l | tr -d ' ')
MODIFIED_FILES=$(git -C "$REPO" diff --name-only HEAD 2>/dev/null | sed 's/^/  - /' || echo "  none")
UNTRACKED=$(git -C "$REPO" ls-files --others --exclude-standard 2>/dev/null | wc -l | tr -d ' ')
UNTRACKED_FILES=$(git -C "$REPO" ls-files --others --exclude-standard 2>/dev/null | sed 's/^/  - /' || echo "  none")
NOW=$(date "+%Y-%m-%d %H:%M")
NOW_PRETTY=$(date "+%b %d, %Y at %H:%M")

# ─────────────────────────────────────────────────────────────────────────────
# 1. Write HANDOFF.md to repo root
# ─────────────────────────────────────────────────────────────────────────────
cat > "$HANDOFF" <<HANDOFF_EOF
# BanglaLearn — Live Handoff Brief

> Auto-generated by \`.claude/update-notes.sh\` every 30 min. Do not edit manually.
> For architectural context and decisions, see the Claude memory file.

**Last updated:** $NOW

---

## Git Status

| | |
|---|---|
| Branch | \`$BRANCH\` |
| Last commit | $LAST_COMMIT |
| Modified files | $MODIFIED |
| Untracked files | $UNTRACKED |

### Recent commits
$RECENT_COMMITS

### Modified files
$MODIFIED_FILES

### Untracked files
$UNTRACKED_FILES

---

## Current Sprint — what to build next

### Phase 1 (immediate — fast wins)
- [x] \`useFocusEffect\` in HomeScreen — stats now refresh after every lesson
- [x] Streak pill in home header — 🔥 flame + count beside hearts + XP
- [x] Hearts bar in lesson quiz UI — live heart icons greying out per wrong answer
- [x] Game-over screen when all hearts lost — shows retry + back to map
- [ ] AppState foreground listener for sync
  - File: \`apps/mobile/lib/AuthContext.tsx\`
  - Add \`AppState.addEventListener('change', ...)\` to pull on foreground

### Phase 2 (short term)
- [ ] Streak-broken modal — show overlay if \`lastActive\` was >1 day ago
  - New file: \`apps/mobile/components/StreakBrokenModal.tsx\`
- [ ] Heart regeneration — 1 heart per 30 min up to max 5
  - File: \`apps/mobile/lib/storage.ts\`
  - Add \`loseHeartWithTimestamp()\` + \`regenerateHearts()\` helpers

### Phase 3 (content)
- [ ] Expand Sylheti/Barisali/Chittagonian dialect content (~1 unit each → need 3+)
  - Files: \`packages/content/src/dialects/sylheti.ts\`, \`barisali.ts\`, \`chittagonian.ts\`
- [ ] "Coming soon" trailing card in lesson list for limited-content dialects

---

## What is complete

- Monorepo (Expo SDK 51 + Next.js 14 + shared packages)
- Firebase init — anon + email auth
- Social auth — Google + Facebook (expo-auth-session v5.5.2)
- AsyncStorage layer (\`storage.ts\`) — XP, streak, hearts, daily XP, completed lessons, resume, history
- Firestore sync — push on lesson finish, pull on sign-in, realtime listener for non-anon
- Custom analytics — 11 event types, fire-and-forget Firestore writes
- Home screen — SVG Bangladesh map, dialect switcher, lesson list, daily goal, hearts + XP header
- Lesson engine (1,291 lines) — study phase (flip cards) + all 6 exercise types + quiz loop + results + resume
- Auth screens — login + register with social buttons
- Standard Bengali curriculum — multiple units, 1,386 lines of structured content

---

## Key files quick reference

\`\`\`
apps/mobile/
├── app/(tabs)/index.tsx      ← Home: map, lessons, stats
├── app/lesson/[id].tsx       ← Lesson engine (1,291 lines)
├── lib/storage.ts            ← AsyncStorage source of truth
├── lib/sync.ts               ← Firestore push/pull/realtime
├── lib/AuthContext.tsx       ← Auth provider, pulls sync on sign-in
├── lib/analytics.ts          ← Custom event tracking
└── lib/useSocialAuth.ts      ← Google + Facebook OAuth hooks

packages/content/src/dialects/
├── standard.ts               ← 1,386 lines — full curriculum
├── sylheti.ts                ← ~289 lines — 1 unit
├── barisali.ts               ← ~257 lines — 1 unit
└── chittagonian.ts           ← ~273 lines — 1 unit
\`\`\`

---

## Architecture rules

1. **Never read Firestore directly in UI.** Always read AsyncStorage via \`storage.ts\`.
2. **Offline-first.** All writes go to AsyncStorage first, then Firestore async.
3. **Don't eject.** Expo managed workflow only — no bare/custom native.
4. **Anon auth from launch.** Every session has a UID. Social sign-in upgrades via \`linkWithCredential\`.
5. **Web and mobile are separate systems.** Web uses NextAuth + Prisma. Do not cross-wire.

---

## Open decisions (block certain features)

1. Heart regen: 30 min timer vs. ad-watch vs. Bazaar coins?
2. Streak freeze: sell in Bazaar or skip?
3. Non-standard dialect content: manual authoring vs. AI-generated?
4. Web app long-term: separate admin tool or unify with Firebase?

---

## Env vars needed

\`\`\`
EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID
EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID
EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID
EXPO_PUBLIC_FACEBOOK_APP_ID
\`\`\`

## Run commands

\`\`\`bash
cd apps/mobile && npx expo start
\`\`\`
HANDOFF_EOF

echo "[$NOW] HANDOFF.md updated"

# ─────────────────────────────────────────────────────────────────────────────
# 2. Write Notes app HTML body
# ─────────────────────────────────────────────────────────────────────────────
cat > "$TMP_BODY" <<HTML
<h1>🇧🇩 BanglaLearn Dev</h1>
<p><i>Last refreshed: $NOW_PRETTY</i></p>

<h2>📦 Repo Status</h2>
<ul>
  <li><b>Branch:</b> $BRANCH</li>
  <li><b>Last commit:</b> $LAST_COMMIT</li>
  <li><b>Uncommitted:</b> $MODIFIED modified &bull; $UNTRACKED untracked</li>
</ul>

<h2>✅ Done</h2>
<ul>
  <li>Monorepo — Expo SDK 51 + Next.js 14 + shared packages</li>
  <li>Firebase — anon + email + Google + Facebook auth</li>
  <li>AsyncStorage layer (offline-first source of truth)</li>
  <li>Firestore sync — push, pull, realtime listener</li>
  <li>Custom analytics — 11 event types, fire-and-forget</li>
  <li>Home screen — SVG Bangladesh map, dialect switcher, lesson list</li>
  <li>Lesson engine — all 6 exercise types, quiz loop, results, resume</li>
  <li>Standard Bengali curriculum — 1,386 lines, multiple units</li>
  <li>Auth screens with social buttons (Google + Facebook)</li>
  <li>Streak pill in home header (🔥 flame + count)</li>
  <li>useFocusEffect — home screen stats refresh after each lesson</li>
  <li>Hearts bar in lesson quiz UI (live heart icons greying out)</li>
  <li>Game-over screen when all hearts lost (with retry)</li>
</ul>

<h2>🔲 Phase 1 — Up Next</h2>
<ul>
  <li>AppState foreground sync listener (AuthContext.tsx)</li>
</ul>

<h2>🔲 Phase 2 — Soon</h2>
<ul>
  <li>Streak-broken modal on app open</li>
  <li>Heart regeneration timer (1 per 30 min)</li>
</ul>

<h2>🔲 Phase 3 — Content</h2>
<ul>
  <li>Expand Sylheti / Barisali / Chittagonian (1 unit → 3+ each)</li>
  <li>"Coming soon" card for limited-content dialects</li>
</ul>

<h2>⏳ Later</h2>
<ul>
  <li>Leaderboard — real Firestore data</li>
  <li>Bazaar — coins / in-app purchases</li>
  <li>Push notifications — streak reminders</li>
  <li>App Store &amp; Play Store prep</li>
</ul>

<h2>🔑 Env Vars Needed</h2>
<ul>
  <li>EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID</li>
  <li>EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID</li>
  <li>EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID</li>
  <li>EXPO_PUBLIC_FACEBOOK_APP_ID</li>
</ul>
HTML

# ─────────────────────────────────────────────────────────────────────────────
# 3. Push to Notes app
# ─────────────────────────────────────────────────────────────────────────────
osascript <<'EOF'
set noteName to "BanglaLearn Dev"
set tmpFile to POSIX file "/tmp/banglalearn-note-body.html"
set noteBody to read tmpFile as «class utf8»

tell application "Notes"
  set matched to (notes whose name is noteName)
  repeat with n in matched
    delete n
  end repeat
  make new note with properties {name:noteName, body:noteBody}
end tell
EOF

echo "[$NOW] Notes updated — $MODIFIED modified, $UNTRACKED untracked"
